### ISSUE TITLE
Android (5.0 Lollipop & 6.0 Marshmallow) Notification.builder.setColor() is not working

### ISSUE THREAD

**Issue by drayan85** [OneSignal/OneSignal-Android-SDK#101]
# Suppose to be a pink colour background for the notification icon, It is working on Android 7.0 

![14274282_10209949479436032_476535195_o](https://cloud.githubusercontent.com/assets/4456232/18238891/c08bc25e-7373-11e6-8aa5-11f66d7c91e0.jpg)

```
public class OneSignalNotificationService extends NotificationExtenderService {

    private static final String TAG = OneSignalNotificationService.class.getSimpleName();


    @Override
    protected boolean onNotificationProcessing(OSNotificationReceivedResult notification) {
        OverrideSettings overrideSettings = new OverrideSettings();
        overrideSettings.extender = new NotificationCompat.Extender() {
            @Override
            public NotificationCompat.Builder extend(NotificationCompat.Builder builder) {
                // Sets the background notification color to Accent on Android 5.0+ devices.
                return builder.setColor(new BigInteger("FFD4145A", 16).intValue());
            }
        };

        OSNotificationDisplayedResult displayedResult = displayNotification(overrideSettings);
        Log.d(TAG, "Notification displayed with id: " + displayedResult.androidNotificationId);
        return true;
    }
}
```
AndroidManifest.xml
```
<!--One Signal SDK Extended Service Class-->
        <service
            android:name=".notification.OneSignalNotificationService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.onesignal.NotificationExtender" />
            </intent-filter>
        </service>
```

OneSignal SDK version
```
compile 'com.onesignal:OneSignal:3.+@aar'
```

**Comment by jkasten2** [comment]
@drayan85 Your code looks correct, it is working for you on Android 7.0 but not 5 and 6?

You see `Notification displayed with id: ` in your logcat? Can you check for any errors around this in the log?

Thanks.

**Comment by drayan85** [comment]
Since display notification is different on Android 7.0 compare to lower versions. There will be no background colour instead App icon will be tint to the background colour.

![push ntification screen shot crop](https://cloud.githubusercontent.com/assets/4456232/18298400/ed985d3e-74ea-11e6-8727-2be24a215e92.png)



We don't see any error (from OneSignal SDK or Our Application) in the Logcat when Push Receive on the Device

**Comment by jkasten2** [comment]
@drayan85 What about the following entry?
```
Notification displayed with id:
```

This debug line should be printing in the logcat if `onNotificationProcessing` is being called.

**Comment by drayan85** [comment]
@jkasten2 It is printing the Notification ID.

This will be called once Mobile Receive the Notification and before display on the Notification bar on the Device Screen.

**Comment by jkasten2** [comment]
@drayan85 I am not able to reproduce the issue on a Nexus 6 running Android 6.0.1. The exact same code in the SDK is run to set the color no matter the Android version 5, 6, or 7.

Note that if you set a Android group key overriding properties does not work as it creates a different kind of summary notification that isn't supported yet. (even if it is the 1st i the group.)

Please contact OneSignal support with a link to this thread if the above wasn't the issue.
