### ISSUE TITLE
Fatal exception: android.app.RemoteServiceException

### ISSUE THREAD

**Issue by pedrofurtado** [OneSignal/OneSignal-Android-SDK#1020]
When our application installed the OneSignal Cordova SDK + OneSignal android sdk, these errors started to appears in Google Play ANR/Crashes dashboard (i prefer to show the printscreen, to provide more information 👍 ):

![screencapture-play-google-apps-publish-2020-05-18-09_34_00](https://user-images.githubusercontent.com/10530520/82214137-b46cff00-98eb-11ea-92a2-ab2b526675a9.png)

I don't know how to simulate the error, because we don't have too much information about it beyond the printscreen of Google Play for a while. But that is probably related to OneSignal sdk or our configuration of onesignal inside app, because it will started with a version that contains, exclusively, the addition of onesignal in app.
Any help will be really appreciated 🤝 

I found some issues that may be related to it, such as:

https://github.com/OneSignal/OneSignal-Android-SDK/issues/364
https://github.com/OneSignal/OneSignal-Android-SDK/issues/750
https://github.com/OneSignal/OneSignal-Android-SDK/issues/776
https://github.com/OneSignal/OneSignal-Android-SDK/issues/712
https://github.com/OneSignal/OneSignal-Android-SDK/issues/415
https://github.com/OneSignal/OneSignal-Android-SDK/issues/263
https://github.com/OneSignal/OneSignal-Android-SDK/issues/255
https://github.com/OneSignal/OneSignal-Android-SDK/issues/254

**Environment**
- Cordova SDK version 2.9.1 -> https://github.com/OneSignal/OneSignal-Cordova-SDK
- Android SDK version 3.13.2 -> https://github.com/OneSignal/OneSignal-Android-SDK

Anyway, thanks for your hard work on it! 👍 🥇

**Comment by pedrofurtado** [comment]
The majority occurs in Android 6, not exclusively, but majority. Maybe this can help us 🔍

**Comment by pedrofurtado** [comment]
@diegozurita 👍

**Comment by jkasten2** [comment]
@pedrofurtado Thanks for providing the details you have. I don't see OneSignal in the stacktrace so it doesn't seem the crash is related.

**You noted that you didn't see these crashes until adding OneSignal.**
1. Could you provide a stacktrace of **all** threads in the crash report?
     - This will provide some extra detail to help if anything could be related OneSignal
2. Can you confirm no other plugins / SDKs in your app were upgraded or added in the same app release?
3. OneSignal has dependencies on Google Play Services, Firebase, and the Android Support Library. 
   - Unlikely, but possible that one of these versions was updated in your app which is causing an issue.

**Comment by rgomezp** [comment]
Closing due to no response
