### ISSUE TITLE
androidX problem

### ISSUE THREAD

**Issue by AKBIROCK3** [OneSignal/OneSignal-Android-SDK#1036]
**Description:**

hi im developing app inventor platform source i want to add onesignal to it
i've already migrate to androidX but the problem is that onesignal doesn't support androidX and appinventor source can't support jetifier i found no way to make it work 
(your description here)

**Environment**
im using the last version on app inventor

**Comment by mikechoch** [comment]
@AKBIROCK3 Have you tried enabling `AndroidX` and `Jetifier` inside of your `gradle.properties` file?

```
android.useAndroidX=true
android.enableJetifier=true
```

**Comment by AKBIROCK3** [comment]
@mikechoch well app inventor doesn't even have gradle.properties or jetifier
everything should be done manually

**Comment by mikechoch** [comment]
@AKBIROCK3 We are in the midst of an Android X migration with our major release for iOS and Android native SDKs (iOS 3.0.0 & Android 4.0.0). Once we release these your problem should be fixed then, I apologize for the inconvenience here. 

In the meantime, have you tried digging through the app inventor issues or opening an issue with them related to this?

**Comment by AKBIROCK3** [comment]
hi so i've modified onesignal sdk and migrate it to androidX
i want to share it here maybe someone need it in the future
source
https://github.com/AKBIROCK3/onesignal-androidX-version

download it from here
https://github.com/AKBIROCK3/onesignal-androidX-version/releases

**Comment by jkasten2** [comment]
@AKBIROCK3 If you are not using Gradle for app inventor Google also provides a standalone Jetifier tool:
https://developer.android.com/studio/command-line/jetifier
