### ISSUE TITLE
Could not resolve com.google.android.gms:play-services-location:[15.0.0, 16.0.0).      Required by:          project :app > com.onesignal:OneSignal:3.14.0

### ISSUE THREAD

**Issue by massusant** [OneSignal/OneSignal-Android-SDK#1041]
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve com.google.android.gms:play-services-location:[15.0.0, 16.0.0).
     Required by:
         project :app > com.onesignal:OneSignal:3.14.0
      > Failed to list versions for com.google.android.gms:play-services-location.
         > Unable to load Maven meta-data from https://s3-ap-southeast-1.amazonaws.com/godel-release/godel/com/google/android/gms/play-services-location/maven-metadata.xml.
            > Could not get resource 'https://s3-ap-southeast-1.amazonaws.com/godel-release/godel/com/google/android/gms/play-services-location/maven-metadata.xml'.
               > Could not GET 'https://s3-ap-southeast-1.amazonaws.com/godel-release/godel/com/google/android/gms/play-services-location/maven-metadata.xml'. Received status code 403 from server: Forbidden
   > Could not resolve com.google.android.gms:play-services-ads-identifier:[15.0.0, 16.0.99].
     Required by:
         project :app > com.onesignal:OneSignal:3.14.0
      > Failed to list versions for com.google.android.gms:play-services-ads-identifier.
         > Unable to load Maven meta-data from https://s3-ap-southeast-1.amazonaws.com/godel-release/godel/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml.
            > Could not get resource 'https://s3-ap-southeast-1.amazonaws.com/godel-release/godel/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml'.
               > Could not GET 'https://s3-ap-southeast-1.amazonaws.com/godel-release/godel/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml'. Received status code 403 from server: Forbidden

**Comment by jkasten2** [comment]
@massusant The error is pointing to trying to get Google library `com.google.android.gms:play-services-location`  from `https://s3-ap-southeast-1.amazonaws.com/` which most likely isn't available there.

I recommend making sure you have `googe()` at the top of your `repositories` sections in your root `build.gradle`.

https://github.com/OneSignal/OneSignal-Android-SDK/blob/3.14.1/Examples/AndroidStudio/build.gradle#L3-L7

https://github.com/OneSignal/OneSignal-Android-SDK/blob/3.14.1/Examples/AndroidStudio/build.gradle#L16-L21
https://stackoverflow.com/a/35272475/1244574

If you are still seeing an issue I recommend upgrading to Gradle 6.0+ as has better handling of finding libraries when multiple repositories are setup in your project. To upgrade follow this guide.
https://stackoverflow.com/a/35272475/1244574
