### ISSUE TITLE
Unable to sync gradle with OneSignal

### ISSUE THREAD

**Issue by ahmaducg** [OneSignal/OneSignal-Android-SDK#1068]
I keep getting the error

```
Failed to resolve: lifecycle-viewmodel-savedstate-2.2.0
Affected Modules: app
```

When I try to sync the gradle

`implementation('com.onesignal:OneSignal:3.14.1')`

I'm sure it's OneSignal, cause when I remove that implementation, syncing finishes

**Android Studio :** 4.0
**Gradle :** 4.0.0
**Gradle Wrapper :** 6.5

**Comment by jkasten2** [comment]
@ahmaducg 
1. What output do you get if you run `./gradlew app:dependencies --info`?
2. What output do you get if you run `./gradlew app:build`
3. Can you share you root `build.gradle` and `app/build.gradle`?

**Comment by rgomezp** [comment]
Closing due to no response
