### ISSUE TITLE
'ledColor' and 'groupKey' null

### ISSUE THREAD

**Issue by xsorifc28** [OneSignal/OneSignal-Android-SDK#107]
Putting `ledColor` and `groupKey` into the notificaton payload seem to be null (debugging inside `OneSignal.NotificationOpenedHandler`

Before this used to be `led_color` and `group_key` payloads I believe ?

**Comment by jkasten2** [comment]
@xsorifc28 Are you setting these values from the OneSignal dashboard or the [REST API](https://documentation.onesignal.com/docs/notifications-create-notification)?  The REST API fields are `android_group` and `android_led_color`.

Can you send this link to OneSignal support along with the notification id having the issue?

**Comment by xsorifc28** [comment]
I'm setting `ledColor` and `groupKey` when generating the notification in the Android app, as described [here](https://documentation.onesignal.com/docs/android-sdk-api#section-osnotificationpayload).

**Comment by jkasten2** [comment]
`OSNotificationPayload` is designed to be read-only, an instance is created and set when a notification is received.

Can you share how you are using it in your code?

**Comment by xsorifc28** [comment]
``` java    
private static final String ANDROID_GROUP = "groupKey";
private static final String LED_COLOR = "ledColor";

payload.put(ANDROID_GROUP, "myGroup");
payload.put(LED_COLOR, "FF00FF00");

```
This does not work.


``` java    
private static final String ANDROID_GROUP = "android_group";
private static final String LED_COLOR = "android_led_color";

payload.put(ANDROID_GROUP, "myGroup");
payload.put(LED_COLOR, "FF00FF00");
```
Grouping works, led color does not.

**Comment by jkasten2** [comment]
Can you try the following code on your test deivce? If this doesn't make the led blink red then your device doesn't support a cust color.
```Java
      NotificationCompat.Builder notifBuilder = new NotificationCompat.Builder(this)
          .setAutoCancel(true)
          .setSmallIcon(android.R.drawable.ic_popup_reminder)
          .setLights(new BigInteger("FFFF0000", 16).intValue(), 2000, 5000)
          .setDefaults(Notification.DEFAULT_LIGHTS);
      NotificationManagerCompat.from(this).notify(0, notifBuilder.build());
```

You may need to unlock then turn your screen off for it to show on some devices.

**Comment by xsorifc28** [comment]
My device for sure supports custom LED, I've used the `NotificationExtenderService` to build custom notifications with LED colors, it seems like they're not working directly without extending the notification?

**Comment by jkasten2** [comment]
@xsorifc28 I tried to reproduce an issue on a few devices and everything is working correctly. I have reviewed the SDK code an not able to see any possible issues either.

The only way the LED color would not work is if you are omitting `contents` from your payload which means a notification would not be displayed.

**Comment by xsorifc28** [comment]
Thanks, I will check again. Should the payloads be `android_group` and `android_led_color` ?

**Comment by jkasten2** [comment]
@xsorifc28 Correct, the full list of fields supported by the REST API can be found below. https://documentation.onesignal.com/docs/notifications-create-notification

**Comment by jkasten2** [comment]
@xsorifc28 Any updates?

**Comment by xsorifc28** [comment]
Grouping is working fine, LED color is not. I've tested on 3 different phones (API 18, 23, 24).

**Comment by jkasten2** [comment]
@xsorifc28 We haven't had any other reports of the LED color not working. If you are still seeing an issue it is most likely related to the revision of the Android Support Library v4 built with your app.

Please link a Android Studio project reproducing the issue and I can take a look. Also please link this issue to support with your notification ids and we can take a look.
