### ISSUE TITLE
Custom sound not playing with channel set Android 8+

### ISSUE THREAD

**Issue by wellbranding** [OneSignal/OneSignal-Android-SDK#1072]
I have been integrating OneSignal and can't fix this issue, that my custom sound is not playing.
**I have created a category and channel to support Android 8+**. Also I don't use minifyEnabled or any resources shrinking. My file is indeed located in res/raw. 
Here is my JSON:

  

     {
        "app_id": "APP_ID",
        "include_player_ids": ["PLAYER_ID"],
        "data": {"foo": "bar"},
        "priority": 10,
        "contents": {"en": "English Message"},
        "android_group": "GROUP_NAME",
        "android_sound": "sound_2",
        "android_channel_id": "CHANNEL_ID"
       }

I also set my custom sound_2 in Settings...

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/RpGJV.png

File is not too big (160 KB), because I previously used AlarmManager to display notification and I used following code for setting sound and channel. It worked well for all cases.

       val sound = configureCustomSound(context.applicationContext, soundOfNotification)
       val audioAttributes = configureAudioAttributes()
       channel.setSound(sound, audioAttributes)
    
       private fun configureCustomSound(context: Context, soundOfNotification: NotificationSoundEnum): Uri {

        return Uri.parse(
                "android.resource://" +
                        context.packageName +
                        "/" +
                        NotificationSoundsHelper.getCustomSound(soundOfNotification))
    }
    
       private fun configureAudioAttributes(): AudioAttributes? {
        return AudioAttributes.Builder()
                .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
                .setUsage(AudioAttributes.USAGE_ALARM)
                .build()
    }

I have tested on 10+ devices. They all produce same behaviour.

The OneSignal console displays that sound should was set, but no sound is received on device. Perhaps sound plying code is broken, can you reference it? I would take a look, because on my project it worked correctly :)

<img width="634" alt="Screenshot 2020-06-24 at 20 57 57" src="https://user-images.githubusercontent.com/31806066/85608327-9ec2c600-b65d-11ea-82fb-37d50f49c723.png">

**Comment by wellbranding** [comment]
Any suggestions? I have looked at cordova, ionic samples. All of them face exact issue and many issues are created. I have tested on Firebase and no issues there found there, so it has something to do with OneSignal then :(

**Comment by wellbranding** [comment]
Any news?

**Comment by jkasten2** [comment]
@wellbranding If you change this sound setting on an existing Android Category on the OneSignal dashboard make sure to uninstall the app on the device and reinstall it. Android itself does not allow Notification channels / categories to be programmatically updated after created since the user can change these at anytime.

I also recommend extracting your APK to make sure the sound_2 file is there. However since you said this works outside of OneSignal this file is mostly part of your app.

**Comment by mikechoch** [comment]
I can also confirm after just testing `API24` up to `API30` that custom sounds do work and it is important to note that uninstalling and reinstalling the app after updating a category is required

**Comment by wellbranding** [comment]
@mikechoch I do uninstall the app. Can you perhaps add screenshot of the settings in the developer console, or are my settings correct?

**Comment by jkasten2** [comment]
@wellbranding You can attempt to remove `"android_group": "GROUP_NAME",` from your JSON. Sounds and channels / categories should work with a group but this will rule out this as a variable.

I also recommend double checking your sound file is still being put in your APK, incase you made any configuration changes since you last tested your sound directly. You can also try disabling both `shrinkResources` and `minifyEnabled` in your `build.gradle` incase this is remove the sound file from your APK.

**Comment by wellbranding** [comment]
@jkasten2 I removed it still same. I decompiled an application and sound is indeed present. Can you provide some kind of example project, which would use sound and it will work? Also will sounds work on emulator also?

**Comment by dameunbite** [comment]
For anyone that is trying to play a custom notification sound in a react native app. I spent a lot of time figuring this, when is a documentation error.

The documentation says that you have to add the sound resource in: <project-root>/android/app/res/raw when is actually in: res/raw

<img width="898" alt="Screen Shot 2020-07-20 at 11 34 08 PM" src="https://user-images.githubusercontent.com/48269003/88009910-a2712d80-cae1-11ea-958e-dfd5ca83eea3.png">

I think the react native onesingal custom sound notification is out dated

**Comment by jaswinder97** [comment]
> Thanks I solved it! Issue was that all devices have **do not disturbed turn on**. This is why they I could not hear sound. Thank

Could you please share the last params used to make it work? I am trying to implement it in the same way it doesn't sound on my devices (all message notifications sound and app notification sounds settings are enabled and working).

![Screenshot - 2020-07-28T085441 164](https://user-images.githubusercontent.com/17950241/88615914-79880400-d0b0-11ea-9318-04b7ace36390.png)

@wellbranding is there anything I missed? 
I shall be grateful to you. Thanks

**Comment by ribeshbasnet** [comment]
i was facing same problem. my config was all right but i forget to add android channel id in the body.
now it worked just fine.
Thank you all.
