### ISSUE TITLE
OneSignal.setSubscription(true) not working

### ISSUE THREAD

**Issue by heloisasim** [OneSignal/OneSignal-Android-SDK#108]
When an user uninstall the app, onesignal **Subscribed** status is changed to **No(Not Subscribed)**. When the user re-install the app, I can add and remove tags and change other infos but I can't change the **Subscribed** status to **Yes**. It seems that this call is not working **OneSignal.setSubscription(true)**. Am I doing something wrong?

```
public class MyApplication extends Application {

   public void onCreate(){
       OneSignal.startInit(this).init();
       OneSignal.sendTag("tag", "change_tag"); // this is working
       OneSignal.setSubscription(true); // this is not working
   }
...
}
```

**Comment by jkasten2** [comment]
Are you calling `setSubscription` with `false` at any point? I recommend contacting OneSignal support with your device's player / user id so they can check the status on their end.

Also let us know the OneSignal SDK version you are using.

**Comment by heloisasim** [comment]
I was actually configuring wrong the **google project number** in gradle file. So it seems that OneSignal can add/remove tags without the google project number, but it can't subscribe the user (which makes sense). 

```
manifestPlaceholders = [manifestApplicationId: "${applicationId}",
                                onesignal_app_id: "88888888-88888-8888-8888-888888888888",
                                onesignal_google_project_number: "888888888888"]
```
