### ISSUE TITLE
Extender Service and opened handler - override settings setContentIntent

### ISSUE THREAD

**Issue by welcome14** [OneSignal/OneSignal-Android-SDK#1081]
Hi,

How do I go about opening a different activity at the touch on the notification?

If I create a new notification from "onNotificationProcessing (return true - not show original notification)", the onesignal dashboard is not marked as "Clicked" and this is not good, **how can I mark the notification as clicked** ?

I have already created the extension of "NotificationOpenedHandler", but this only works if the app is active. If the notification is received by NotificationExtenderService, **the launcher activity opens when the notification is touched**

I have use "overrideSettings.extender", but it not working with setContentIntent.

Thanks!

**Comment by jkasten2** [comment]
@welcome14 Changing `setContentIntent` will prevent the OneSignal SDK from knowing the notification was tapped on / opened. As you noted doing this means the OneSignal dashboard won't count the click nor will the `NotificationOpenedHandler` fire when you do this.

Instead add `<meta-data android:name="com.onesignal.NotificationOpened.DEFAULT" android:value="DISABLE" />` to your `AndroidManifest.xml`. This will prevent the OneSignal SDK from starting the main `Activity` in your app. You can then decide what you want the notification action to do when you tap on it from the `NotificationOpenedHandler`.
https://documentation.onesignal.com/docs/android-customizations#changing-the-open-action-of-a-notification
