### ISSUE TITLE
Huawei NotificationExtenderService

### ISSUE THREAD

**Issue by niktses** [OneSignal/OneSignal-Android-SDK#1087]
I am using this method to handle notifications.

```Java
public class NotificationExtenderBareBonesExample extends NotificationExtenderService {
   @Override
   protected boolean onNotificationProcessing(OSNotificationReceivedResult receivedResult) {
      // Read properties from result.
     
      // Return true to stop the notification from displaying.
      return false;
   }
}
```

It is working fine on normal android but i have a huawei with only huawei services (android 10) that the method is not called at all. Is shows a notification but it bypasses my custom handle. I have tried it on an emulator with android 10 but it works as intended. I have tried it in several phones with different android versions (not huawei) and it is working fine.

**Comment by jkasten2** [comment]
@niktses The for HMS Huawei devices the OneSignal `NotificationExtenderService` will only fire if you use the Data Message type on the dashboard. Or if sending via the OneSignal REST API use `"huawei_msg_type": "data"`.

Note that HMS pushes sent as data are not as reliable on Huawei devices as if your app is swiped away your app won't be started to get the data message. Unless however your app is put on the Huawei Optimizer safelist under the App launch section.
