### ISSUE TITLE
@Nullable annotations are missing

### ISSUE THREAD

**Issue by danielgomezrico** [OneSignal/OneSignal-Android-SDK#1093]
Hi

This is more a feature requests on the SDK itself, it will be cool to have `@Nullable` annotations all over the models so we can know when something can be null or not, it is specially useful when you are using Kotlin.

This can help developers into running on NullPointerException in some places, like on `OSNotificationPayload.additionalData` which can be null but the object itself does not document it.

**Comment by rgomezp** [comment]
Thank you for the request. Even though I will close it here, we will continue tracking internally. Cheers
