### ISSUE TITLE
manifest merger failed.can someone help me?

### ISSUE THREAD

**Issue by Wasay-Tahir** [OneSignal/OneSignal-Android-SDK#1095]
`Executing tasks: [:app:assembleDebug] in project C:\Users\Quality computer\Downloads\Compressed\WhatsAppClone-master

> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :app:compileDebugAidl NO-SOURCE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:javaPreCompileDebug UP-TO-DATE
> Task :app:generateDebugResValues UP-TO-DATE
> Task :app:generateDebugResources UP-TO-DATE
> Task :app:processDebugGoogleServices UP-TO-DATE
> Task :app:mergeDebugResources UP-TO-DATE
> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :app:extractDeepLinksDebug UP-TO-DATE

> Task :app:processDebugManifest FAILED
C:\Users\Quality computer\Downloads\Compressed\WhatsAppClone-master\app\src\main\AndroidManifest.xml Error:
	Attribute meta-data#onesignal_app_id@value at AndroidManifest.xml requires a placeholder substitution but no value for <onesignal_app_id> is provided.
C:\Users\Quality computer\Downloads\Compressed\WhatsAppClone-master\app\src\main\AndroidManifest.xml Error:
	Attribute meta-data#onesignal_google_project_number@value at AndroidManifest.xml requires a placeholder substitution but no value for <onesignal_google_project_number> is provided.

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 865ms
8 actionable tasks: 1 executed, 7 up-to-date
`

**Comment by jkasten2** [comment]
@Wasay-Tahir The error notes you're missing `onesignal_app_id` and `onesignal_google_project_number`. Please set them in your `app/build.gradle` per step 2.3 in the OneSignal Android SDK Setup guide.
https://documentation.onesignal.com/docs/android-sdk-setup#step-2---add-onesignal-dependencies
```gradle
android {
   defaultConfig {
      manifestPlaceholders = [
          onesignal_app_id: 'PUT_YOUR_ONESIGNAL_APP_ID_HERE',
          // Project number pulled from dashboard, local value is ignored.
          onesignal_google_project_number: 'REMOTE'
      ]
    }
```
