### ISSUE TITLE
NotificationExtenderService not working on Android version 6 and 7.

### ISSUE THREAD

**Issue by mirtizakh** [OneSignal/OneSignal-Android-SDK#1097]
NotificationExtenderService not working on Android version 6 and Android version 7 , but working perfectly fine on Android version 8 and plus.

I am not able to set silent notification by using NotificationExtenderService on Android version 6 and 7 , notifications are not even receiving when I am using NotificationExtenderService in Android version 6 and 7 , but if I remove NotificationExtenderService from Android 6 and 7 notifications are working perfectly fine , but its not silent notification. On Android version 8 and Android version 8+ plus NotificationExtenderService  working perfectly fine.

**Comment by rgomezp** [comment]
Howdy,
Please follow our issue templates so that we can properly assist you.
