### ISSUE TITLE
Unknown error getting FCM Token

### ISSUE THREAD

**Issue by shero1111** [OneSignal/OneSignal-Android-SDK#1107]
**Description:**

When initializing OneSignal on app clients side, I get:
```
Unknown error getting FCM Token 
    java.lang.IllegalArgumentException: Please set your project ID. A valid Firebase project ID is required to communicate with Firebase server APIs: It identifies your project with Google.

```
My dependencies:
    implementation 'com.google.firebase:firebase-auth:19.3.2' //OneSignal didn´t work when this was activated
    implementation 'com.google.firebase:firebase-messaging:20.2.4' //for FCM

Crashing curently

**Comment by rgomezp** [comment]
Howdy,
We need a bit more information to assist you. Please follow our issue template.

Also, please make sure you followed our Android setup docs fully: https://documentation.onesignal.com/docs/generate-a-google-server-api-key

**Comment by jkasten2** [comment]
@shero1111 Please update to OneSignal 3.13.0 or newer when using Firebase Messaging (FCM) or IID 20.1.1 or newer. See this pinned warning issue for more details:
https://github.com/OneSignal/OneSignal-Android-SDK/issues/1018

We also recommend adding and make sure you have the following in your project and is up to date to avoid compatibility issues like this one.
https://github.com/OneSignal/OneSignal-Gradle-Plugin
