### ISSUE TITLE
Custom sound not playing on Flutter in release APK

### ISSUE THREAD

**Issue by JacquesMarques** [OneSignal/OneSignal-Android-SDK#1122]
Hi,

If I run my app with the **flutter run** command and send a notification with a category for the custom sound the sound is played, but when I generate the APK with the **flutter build apk** and send the same notification, no sound is played.
I create a file keep.xml as it is said to do in the documentation:
`<resources 
    xmlns:tools="http://schemas.android.com/tools" 
    tools:keep="@raw/tf003"/>`

but it still doesn't work, does anyone know how I set it up to work?

Thanks

**Comment by rgomezp** [comment]
Howdy, 
Please follow our issue template as we need more information that this to be able to assist you. Furthermore, this is a Flutter specific issue it sounds like so please open the issue in the [Flutter repository](https://github.com/OneSignal/OneSignal-Flutter-SDK). Thank you.
