### ISSUE TITLE
Works with Android TV?

### ISSUE THREAD

**Issue by rcpinheiro** [OneSignal/OneSignal-Android-SDK#1125]
Hi!
I'm not sure if this the correct place to ask this but can OneSignal send notifications to Android TV devices?
I know there are limitations at the OS-level but there are a couple of apps that show notifications, although I don't know if they're really push or keep polling a server for news.
Thanks in advance!

_Note:_ I'm not interested in any user-interface activity, I'm only interested in received notifications.

**Comment by rgomezp** [comment]
Howdy,
Thanks for your question. Push Notifications are a native feature of Android, iOS and Web. OneSignal doesn't create them like we do for In App Messages.

If android supports push on Android TV, then our system should work for it, but IAM we have not designed them specifically for ATV. Hope that helps.

Enjoy!
