### ISSUE TITLE
Security Penetration Test Results

### ISSUE THREAD

**Issue by djnafe** [OneSignal/OneSignal-Android-SDK#1135]
Recently we have submitted our App for a security audit and this is report about OneSignal:

“"com.onesignal.NotificationOpenedReceiver">” & “com.onesignal.UpgradeReceiver" which are being used for push notifications using one signal SDK. these needs to be protected with relevant permission as advised on attached link.

proper permissions needs to be set in android manifest file. Kindly visit this link for more information; https://oldbam.github.io/android/security/android-vulnerabilities-insecurebank-broadcast-receivers

The mobile application contains an exported receiver enabling other applications, including malicious ones, to send intents
without restrictions.
By default, Broadcast Receivers is exported in Android, as the result any application will be able to send an intent to the
Broadcast Receiver of the application.
Recommendation 
Define which applications can send intents to mobile applications Broadcast
Receiver set relevant permissions in the Android Manifest file.

**Comment by Jeasmine** [comment]
Hey, @djnafe thanks for pointing this out! this is for sure something to improve in our end. We will discuss the steps to follow on improving this. In the meantime check our [Beta major release](https://github.com/OneSignal/OneSignal-Android-SDK/tree/major_release_4.0.0)

**Comment by jkasten2** [comment]
@djnafe In researching this the following is only true if `intent-filters` are defined with it.
> By default, Broadcast Receivers is exported in Android, as the result any application will be able to send an intent to the
Broadcast Receiver of the application.

See Android documentation on this:
https://developer.android.com/guide/topics/manifest/receiver-element#exported

[`com.onesignal.NotificationOpenedReceiver` in the 3.15.6 SDK](https://github.com/OneSignal/OneSignal-Android-SDK/blob/3.15.6/OneSignalSDK/onesignal/src/main/AndroidManifest.xml#L64) does NOT have any `intent-filters` so by default it is NOT exported so there isn't a security issue here.

In the [OneSignal 4.0.0 SDK this was changed to an Activity](https://github.com/OneSignal/OneSignal-Android-SDK/blob/4.0.0/OneSignalSDK/onesignal/src/main/AndroidManifest.xml#L119-L122) but again, no `intent-filters` so this isn't exported.
See Android's documentation on Activity exported:
https://developer.android.com/guide/topics/manifest/activity-element#exported



`com.onesignal.UpgradeReceiver` is exported but nothing is read from the `Intent` so there is no security issue here either . It is simply used as a way to trigger notifications to be read internally and put back into the notification shade after the app is upgraded.
https://github.com/OneSignal/OneSignal-Android-SDK/blob/master/OneSignalSDK/onesignal/src/main/java/com/onesignal/UpgradeReceiver.java#L38-L47

**Comment by ahpaleus** [comment]
Hello @jkasten2,

You mentioned that the `NotificationOpenedReceiver` becomes an activity and is unexported, but it became “silently” exported in the [560203a](https://github.com/OneSignal/OneSignal-Android-SDK/commit/560203ac0c834d1e1c2e21c10b9e2680c7dd2cee) commit. Are you sure it should stay unexported?
