### ISSUE TITLE
Request: Android 11 Bubbles support

### ISSUE THREAD

**Issue by rcpinheiro** [OneSignal/OneSignal-Android-SDK#1141]
I hope OneSignal implements the new Bubbles API from Android 11. It's very useful and I think it will be very easy to do since the only new thing is to attach metadata to a notification. It's useful  for chat apps and doesn't impact apps without Bubbles support.
Thanks in advance!

**Comment by Jeasmine** [comment]
Hey, @rcpinheiro thanks for pointing this out! We will evaluate it for the next quarters!

**Comment by emawby** [comment]
Closing this enhancement request here
