### ISSUE TITLE
applicationIdSuffix respected in v3.3.0?

### ISSUE THREAD

**Issue by stkent** [OneSignal/OneSignal-Android-SDK#116]
In https://github.com/OneSignal/OneSignal-Android-SDK/commit/c48ffd148b291fc09517592e38e0265930fb6f6e, the need/ability to supply the application id to the SDK was removed. I use an application id suffix for my debug builds to allow side-by-side installs:

```groovy
buildTypes {
    debug {
        applicationIdSuffix ".debug"
        // ...
    }
}
```

so previously I was doing this:

```groovy
manifestPlaceholders["manifestApplicationId"] = "${android.defaultConfig.applicationId}${applicationIdSuffix}"
```

Will the suffix be included automatically in v3.3.0 of the library? If not, what are the consequences of upgrading to this version of the library likely to be if I have a debug and a release build of my app installed on a device simultaneously? Are both going to receive all notifications? Is the debug version never going to receive any notifications?

Thanks in advance for your help :)

**Comment by gerbiljames** [comment]
I actually submitted issue #110, which was resolved by the removal of `${manifestApplicationId}`. It's been replaced by the standard `${applicationId}` in OneSignals manifest which includes any `applicationIdSuffix` you define automatically. I've tested this myself and the `applicationIdSuffix` is definitely respected in 3.3.0.

**Comment by stkent** [comment]
Ah, thanks for confirming - my testing with the merged manifests suggested the behavior you describe, which surprised me (pleasantly!).

**Comment by jkasten2** [comment]
@stkent Let me know if is all working for you or if you need me to look into the `applicationIdSuffix`.

**Comment by stkent** [comment]
@jkasten2 thanks for checking in! Everything I'm observing matches what @gerbiljames described, so I think we're good :)

**Comment by jkasten2** [comment]
@stkent Good to hear, glad I was able to remove this complexity!
