### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException Cannot perform this operation because there is no current transaction. com.onesignal.OneSignalDbHelper.delete

### ISSUE THREAD

**Issue by Deepakkast** [OneSignal/OneSignal-Android-SDK#1166]
Fatal Exception: java.lang.IllegalStateException
Cannot perform this operation because there is no current transaction.
android.database.sqlite.SQLiteSession.throwIfNoTransaction (SQLiteSession.java:915)
android.database.sqlite.SQLiteDatabase.endTransaction (SQLiteDatabase.java:524)
com.onesignal.OneSignalDbHelper.delete (OneSignalDbHelper.java:279)
com.onesignal.OneSignalCacheCleaner.cleanCachedNotifications (OneSignalCacheCleaner.java:82)
com.onesignal.OneSignalCacheCleaner.access$000 (OneSignalCacheCleaner.java:11)
com.onesignal.OneSignalCacheCleaner$1.run (OneSignalCacheCleaner.java:40)

**Comment by Deepakkast** [comment]
Onesignal version 3.15.3

**Comment by Jeasmine** [comment]
Thanks for reporting this @Deepakkast, we are already working on a PR for fixing it.

**Comment by Jeasmine** [comment]
The fix will be available on the next release!

**Comment by Deepakkast** [comment]
@Jeasmine Thank you

**Comment by Deepakkast** [comment]
it is still coming please check it's so irritating
