### ISSUE TITLE
Action Buttons Set of OneSignal in Elicpse

### ISSUE THREAD

**Issue by lineahosting** [OneSignal/OneSignal-Android-SDK#117]
Hello, I need help on OneSignal.

I do not know very well how to make the user when it receives the notification push, press the button and click this action go to a specific tabs.

As I set up my app done in Eclipse and I enter ID Action Buttons?

I hope you can help me.

I leave an example of what I try to do
https://cloud.githubusercontent.com/assets/2101405/15735954/24976650-28a5-11e6-9764-6d3b6bd06a46.png

----- Spanish ------

Titulo Español: Configurar Action Buttons de OneSignal en Elicpse

Hola, necesito ayuda acerca de OneSignal.

No sé muy bien como hacer para que el usuario cuando recibe la notificación push, pulse click en el boton y esta acción ir a un tabs especifico.

Como debo configurar mi app hecho en Eclipse y que debo ingresar en ID de Action Buttons?

Espero puedan ayudarme.

Dejo un ejemplo de lo que trato de hacer
https://cloud.githubusercontent.com/assets/2101405/15735954/24976650-28a5-11e6-9764-6d3b6bd06a46.png

**Comment by jkasten2** [comment]
@lineahosting To can get the button press event from [setNotificationOpenedHandler](https://documentation.onesignal.com/docs/android-native-sdk#section--setnotificationopenedhandler-). To get the id of the button press read `result.action.actionID` See [OSNotificationOpenResult](https://documentation.onesignal.com/docs/android-native-sdk#section--osnotificationopenresult-) for a full list of properites on the result object.
