### ISSUE TITLE
Could not resolve com.google.firebase:firebase-messaging:[10.2.1, 12.1.0)

### ISSUE THREAD

**Issue by ArunkumarChandraSekar** [OneSignal/OneSignal-Android-SDK#1179]
Hi.,
I have implemented One Signal SDK in my project for the PUSH notification. This one working fine in the project Android SDK 28 version. But its not working in Android SDK 29. 

https://github.com/OneSignal/OneSignal-Android-SDK In this link you already mentioned This OneSingal SDK will supports from Android 4.0.3 (API level 15) to Android 9.0 (28). 

Can you give me the solution for this? Either OneSignal SDK will supports to ApI Level 29 or not.

**_My Current working Code is.,_** 
compileSdkVersion 28
 buildToolsVersion '28.0.3'
 minSdkVersion 19
 targetSdkVersion 28
// OneSignal SDK
    implementation ('com.onesignal:OneSignal:3.10.9'){
        exclude group: 'com.google.android.gms'
    }
 implementation 'com.google.firebase:firebase-appindexing:12.0.1'

In SDK 29... 
compileSdkVersion 29
buildToolsVersion '29.0.3' 
minSdkVersion 19
targetSdkVersion 29
// OneSignal SDK
    implementation ('com.onesignal:OneSignal:3.10.9'){
        exclude group: 'com.google.android.gms'
    }
implementation 'com.google.firebase:firebase-appindexing:19.1.0'

* Firebase appindexing used to work with GoogleApiClient.

**issue is.,**
 Could not resolve com.google.firebase:firebase-messaging:[10.2.1, 12.1.0).

If removed firebase related dependences, cannot get registration id.

  **OneSignal.idsAvailable((userId, registrationId) -> {
            Log.d("debug", "User:" + userId+" , "+registrationId);
        });

* Here registrationId getting NULL.**

* Give me the solution to work with Android SDK 29..

Thanks in Advance...

**Comment by Jeasmine** [comment]
Hey @ArunkumarChandraSekar, can you complete the issue template in order to help you? Thanks!

**Comment by Jeasmine** [comment]
Hey, @ArunkumarChandraSekar thanks for giving more details. Did you try using the [OneSignal Gradle Plugin](https://github.com/OneSignal/OneSignal-Gradle-Plugin)?

**Comment by pynkvalerian** [comment]
hey @Jeasmine, i'm having the same issues as well, I'm using OneSignal Gradle Plugin, and it downgrades `com.android.support` to 28. 

<img width="1217" alt="Screenshot 2020-11-18 at 3 38 53 PM" src="https://user-images.githubusercontent.com/13617451/99499643-2b2aa800-29b4-11eb-9748-845254629667.png">

Could you share more about whether OneSignal is supported on Android 10 (SDK 29)? According to [Google Playstore, we have to upgrade to Android 10 to push out any app updates](https://developer.android.com/distribute/best-practices/develop/target-sdk).

**Comment by ankerbachryhl** [comment]
I get the same warning like above about downgrading. 

I have just successfully pushed an update though, by changing my targetSdk to 29. 

I'm curious to know if the warning will make it break for Android 10 devices in production then or is it fine since the play store approved my submission?

**Comment by jkasten2** [comment]
@ArunkumarChandraSekar The "Could not resolve com.google.firebase:firebase-messaging:[10.2.1, 12.1.0)." error is most likely due to a Gradle bug where some dependencies can not be found when some repositories are added. I recommend updating to Gradle 6.0 or newer noted here https://github.com/OneSignal/OneSignal-Gradle-Plugin/issues/94#issuecomment-626399384

I also recommend updating to [OneSignal-Android-SDK 4.0.0](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.0.0) and follow the migration guide as the 3.10.9 version you are using is quite old. If you can't go to 4.x.x yet I recommend that latest 3.x.x version (3.15.6).

**Comment by jkasten2** [comment]
@pynkvalerian @ankerbachryhl The warning you are seeing is unrelated to the firebase issue this was originally opened with. I have updated the title of this issue to reflect that.

The OneSignalPlugin warning actually comes from the [OneSignal-Gradle-Plugin](https://github.com/OneSignal/OneSignal-Gradle-Plugin) so please open a new issue there will your full `build.gradle` as the issue template instructs so we can reproduce it.
As a quick note though it is recommended you [upgrade to AndroidX](https://developer.android.com/jetpack/androidx/migrate) if you are using targetSdk 29. However in most cases still using com.andorid.support 28 with this shouldn't be an issue but depends on what other Android APIs your app uses.
