### ISSUE TITLE
exclude user from filter notification

### ISSUE THREAD

**Issue by FunnyDevs** [OneSignal/OneSignal-Android-SDK#118]
Is possibile to exclude userId from a filter notification (without adding additional tag)???

**Comment by jkasten2** [comment]
@FunnyDevs Unfortunately there isn't an option for this. Is your use case for this a chat app?

**Comment by FunnyDevs** [comment]
Yes. In particular i want to exclude the sender from a geolocation notification

**Comment by jkasten2** [comment]
@FunnyDevs We will consider it, since this is server API feature request that does not related to the Android SDK I am going to close this issue.
