### ISSUE TITLE
Unable to instantiate service com.onesignal.HmsMessageServiceOneSignal.

### ISSUE THREAD

**Issue by mirtizakh** [OneSignal/OneSignal-Android-SDK#1180]
Appear on Android 6.0.1

Its created on a user device, I am not able to reproduce the steps.

![Capture](https://user-images.githubusercontent.com/25367409/95290687-47043f80-0887-11eb-9eed-8a7be188e4e6.PNG)

**Comment by jkasten2** [comment]
@mirtizakh Thanks for reporting. This error seems quite odd as `HmsMessageServiceOneSignal` would only attempt to be started if it just received an HMS push. However a Nexus 4 is a Google device and doesn't comes with any Huawei services to register for an HMS push token in the first place.

1. How many devices and crash have you seen with this error?

2. Do you have a different build your app on the Huawei AppGallery vs the Google Play store?

3. Are you able to reproduce this crash?

**Comment by jkasten2** [comment]
Closing this issue due to no response

**Comment by fi8er1** [comment]
Fatal Exception: java.lang.RuntimeException
Unable to instantiate service com.onesignal.HmsMessageServiceOneSignal: java.lang.ClassNotFoundException: Didn't find class "com.onesignal.HmsMessageServiceOneSignal" on path: DexPathList[[zip file "/data/app/com.smartsco.recaru-J1nEFZZm0VlePHn7aJlLhg==/base.apk"],nativeLibraryDirectories=[/data/app/com.smartsco.recaru-J1nEFZZm0VlePHn7aJlLhg==/lib/arm64, /data/app/com.smartsco.recaru-J1nEFZZm0VlePHn7aJlLhg==/base.apk!/lib/arm64-v8a, /system/lib64, /hw_product/lib64, /system/product/lib64]]

Brand:HUAWEI
Model:LIO-AL00
Orientation: Portrait
RAM free: 5.95 GB
Disk free: 43.2 GB

Operating System
Version:10
Orientation: Portrait
Rooted:No

classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.12.8'
implementation 'com.onesignal:OneSignal:[4.0.0, 4.99.99]'
