### ISSUE TITLE
In App Messaging keeps showing whenever an activity showed then dismiss automatically in a short time

### ISSUE THREAD

**Issue by buidothanhvinh** [OneSignal/OneSignal-Android-SDK#1183]
**Description:**
I had integrated InAppMessaging in my app and it worked perfectly for the normal case (user presses the action button then the dialog will be dismissed) but when the user uses the hard-back button to dismiss the dialog then the In-App Messaging keeps showing whenever an activity showed then dismiss automatically in short time

**Environment**

1. OneSignal SDK 3.15.2

**Steps to Reproduce Issue:**

1. Start Activity A
1. From Activity A starts Activity B
1. From Onesignal Dashboard sends an InAppMessage (With showing the message only once mode)
1. From Activity B, In-App-Message will be shown
1. Use the hard-back button to dismiss In-App-Message then the app back to Activity A
1. Start Activity B again
Actual result: In-App-Message will be shown then dismiss automatically in a short time. And it will happen repeatedly until the user restarted the app.
Expected result: 

* 1/A configuration to disallow dismissing the popup by the hard-back button pressed 
* 2/Whenever the message dismissed, it should not be shown again (With showing the message only once mode)

**Comment by buidothanhvinh** [comment]
I found that there is a new version named 3.15.4 noted to fix this issue. I tried but It still happening. Please help to double-check. Thank you

**Comment by buidothanhvinh** [comment]
@Jeasmine Could you help to double-check?

**Comment by Jeasmine** [comment]
Hey, @buidothanhvinh, we worked on this fix https://github.com/OneSignal/OneSignal-Android-SDK/pull/1247. This will be included in our next release. Thanks for your patience!

**Comment by Jeasmine** [comment]
This fix is included on https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.1.0 let me know if this fixed your problem, thxs!

**Comment by buidothanhvinh** [comment]
Hi @Jeasmine . Could you help to include this fix for 3.15.7 release? 
Because from our app still using 3.15.x version

**Comment by myounis97** [comment]
Hello please reopen this isssue as this issue is happening on version 4.8.5

**Comment by nan-li** [comment]
Hi @myounis97, can you share exactly what is happening for you on 4.8.5?
