### ISSUE TITLE
Notification click not deleted - amazon Kindle

### ISSUE THREAD

**Issue by kumsook** [OneSignal/OneSignal-Android-SDK#120]
Notification click not deleted.
Power on/off affer deleted.
Is there any other way?

NotificationExtender.java
public class NotificationExtender extends NotificationExtenderService {
    @Override
    protected boolean onNotificationProcessing (OSNotificationReceivedResult receivedResult) {
        OverrideSettings overrideSettings OverrideSettings = new ();
        overrideSettings.extender NotificationCompat.Extender = new () {
            @Override
            public NotificationCompat.Builder extend (NotificationCompat.Builder builder) {
                // Sets the background notification color to Green on Android 5.0+ devices.
                Log.d ( "onNotificationProcessing", "extend");
                return builder
                        .setOnlyAlertOnce (true)
                        .setAutoCancel (true);
            }
        };
        OSNotificationDisplayedResult displayedResult = displayNotification (overrideSettings);
        return true;
    }

androidManifest.xml

```
    <amazon:enable-feature android:name="com.amazon.device.messaging" android:required="false"/>
    <activity android:name="com.onesignal.NotificationOpenedActivity" android:theme="@android:style/Theme.NoDisplay"/>
    <service android:name="com.onesignal.ADMMessageHandler" android:exported="false" />
    <receiver android:name="com.onesignal.ADMMessageHandler$Receiver"
              android:permission="com.amazon.device.messaging.permission.SEND" >
        <intent-filter>
            <action android:name="com.amazon.device.messaging.intent.REGISTRATION" />
            <action android:name="com.amazon.device.messaging.intent.RECEIVE" />
            <category android:name="xxxx" />
        </intent-filter>
    </receiver>
    <receiver android:name="com.onesignal.NotificationOpenedReceiver" />
    <service android:name="com.onesignal.GcmIntentService" />
    <service android:name="com.onesignal.SyncService"/>
    <activity android:name="com.onesignal.PermissionsActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar" />

    <service android:name="com.onesignal.NotificationRestoreService" />
    <receiver android:name="com.onesignal.BootUpReceiver">
        <intent-filter>
            <action android:name="android.intent.action.BOOT_COMPLETED" />
            <action android:name="android.intent.action.QUICKBOOT_POWERON" />
        </intent-filter>
    </receiver>
    <receiver android:name="com.onesignal.UpgradeReceiver" >
        <intent-filter>
            <action android:name="android.intent.action.MY_PACKAGE_REPLACED" />
        </intent-filter>
    </receiver>
    <service android:name=".NotificationExtender"
             android:exported="false">
        <intent-filter>
            <action android:name="com.onesignal.NotificationExtender" />
        </intent-filter>
    </service>
    <!-- onesignal -->
```

**Comment by jkasten2** [comment]
@kumsook Do you mean the notification is not removed from the notification shade when you tap on the notification?

I am not sure I understand how restarting the device is related to your issue.

`setAutoCancel(true)` is already set by our SDK so this isn't required in your code.

**Comment by kumsook** [comment]
@jkasten2 Thank you answer. 
Do you mean the notification is not removed from the notification shade when you tap on the notification? -> yes.

I am not sure I understand how restarting the device is related to your issue.
-> restarting removed from the notification shade.

setAutoCancel(true) is already set by our SDK so this isn't required in your code. 
-> oh, ok. 
I proceeded this part with removing the source and it happened 2 out of 10 times when I ran it.

Could you also add the model and FireOS version you are testing on?
model : Amazon Fire HD 7	
FireOS : KFASWI (5.1.1)

**Comment by jkasten2** [comment]
@kumsook We haven't had any other reports of an issue like this. Can you let us know the version of the Google Play services library and / or the Android Support Library v4 you are using? Since `setAutoCancel` is called through `NotificationCompat.Builder` there could be a bug in the revision that is being built into your app.

Also can you check for any error or warnings in the logcat when you tap on the notification?
