### ISSUE TITLE
Unable to instantiate receiver GcmBroadcastReceiver

### ISSUE THREAD

**Issue by janbolat** [OneSignal/OneSignal-Android-SDK#1200]
Hello,
after sending a push message to users we are having a lot of crashes, and it keeps growing:
![image](https://user-images.githubusercontent.com/6511056/97469077-3029a800-1970-11eb-941c-c0533050a537.png)

It is happening only on the latest version of our app (which we released few months ago), which has `OneSignal v3.15.2`.

```
Fatal Exception: java.lang.RuntimeException: Unable to instantiate receiver packageName.GcmBroadcastReceiver: java.lang.ClassNotFoundException: Didn't find class "packageName.GcmBroadcastReceiver" on path: DexPathList[[zip file "/data/app/packageName-npc468_zyumoyXzrr1GAPQ==/base.apk"],nativeLibraryDirectories=[/data/app/packageName-npc468_zyumoyXzrr1GAPQ==/lib/arm, /system/lib, /system/vendor/lib]]
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3376)
       at android.app.ActivityThread.-wrap18(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1780)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

Caused by java.lang.ClassNotFoundException: Didn't find class "packageName.GcmBroadcastReceiver" on path: DexPathList[[zip file "/data/app/packageName-npc468_zyumoyXzrr1GAPQ==/base.apk"],nativeLibraryDirectories=[/data/app/packageName-npc468_zyumoyXzrr1GAPQ==/lib/arm, /system/lib, /system/vendor/lib]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
```

I found a similar bug which which leads to the following page about Unity https://documentation.onesignal.com/docs/troubleshooting-unity#section-androidx-compatibility
but we don't use Unity at all.

The only major thing we did is implemented Huawei Mobile Services and updated to OneSignal with HMS support.

I understand that it is missing `packageName.GcmBroadcastReceiver` class, but in previous versions we didn't configure anything at all (I mean Proguard if it is the case).

What can be the cause of the problem?
Thank you

**Comment by jkasten2** [comment]
@janbolat This should be `com.onesignal.GcmBroadcastReceiver` as noted here
https://github.com/OneSignal/OneSignal-Android-SDK/blob/3.15.2/OneSignalSDK/onesignal/src/main/java/com/onesignal/GcmIntentService.java

They only way "packageName.GcmBroadcastReceiver" could be attempt to be instantiated is if it was defined in your `AndroidManifest.xml` like this. You don't need to add `GcmBroadcastReceiver` at all to your `AndroidManifest.xml` manually as this SDK will automatically add it at build time in your app bundle / APK.

**Comment by jkasten2** [comment]
@janbolat Thanks for checking.

Can you search through it if you have any other occurrences of the `com.google.android.c2dm.intent.RECEIVE` or "`GcmBroadcastReceiver`"?

Could you also check the `AndroidManifest.xml` in your APK? I don't believe Proguard or R8 / D8 would rename anything in your `AndroidManifest.xml` but may with aggressive settings.

**Comment by janbolat** [comment]
Sorry @jkasten2, I figured it out. I mixed up the app version, it is my mistake. It is happening on the previous version of our app where we removed OneSignal for that period of time. Now I get it why it occurred (because we sent to all users through OneSignal dashboard).

I am closing the issue. Sorry for disturbing.
