### ISSUE TITLE
the sdk documentation for android studio 4.1 is deprecated

### ISSUE THREAD

**Issue by ghost** [OneSignal/OneSignal-Android-SDK#1201]
**Description:**
The sdk documentation for android studio version 4.1 is obsolete.

## In the new version you can no longer add :
buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/'}
    }
    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.8, 0.99.99]'
    }
}
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

repositories {
    maven { url 'https://maven.google.com' }

## }
An error appears that you cannot add dependencies before the plugins

## New buildgradle structure of android studio:
plugins {
    id 'com.android.application'
}

android {
    compileSdkVersion 30
    buildToolsVersion "30.0.2"

```
defaultConfig {
    applicationId "com.app.example"
    minSdkVersion 16
    targetSdkVersion 30
    versionCode 1
    versionName "1.0"
```

```
    testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
}
```

```
buildTypes {
    release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
    }
}
compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
}
```

}

dependencies {

```
implementation 'androidx.appcompat:appcompat:1.2.0'
implementation 'com.google.android.material:material:1.2.1'
implementation 'androidx.constraintlayout:constraintlayout:2.0.2'
testImplementation 'junit:junit:4.+'
```

**Comment by jadayash** [comment]
Hello

Did you find any solution for that?
Onesignal isn't working on api 30+

**Comment by spacehowen** [comment]
> Hola
> 
> ¿Encontraste alguna solución para eso?
> Onesignal no funciona en api 30+

**Comment by spacehowen** [comment]
> Hola
> 
> ¿Encontraste alguna solución para eso?
> Onesignal no funciona en api 30+

if i manage to fix it i leave you a link to a temporary solution until oneignal fixes that error 
https://stackoverflow.com/questions/48610901/only-build-script-and-other-plugins-script-blocks-are-allowed-before-plugins

**Comment by Jeasmine** [comment]
Thanks for reporting this! We will work on this.

**Comment by jkasten2** [comment]
@jadayash We have updated our documentation to account for the change.
https://documentation.onesignal.com/docs/android-sdk-setup#step-2---add-onesignal-gradle-plugin-and-sdk
