### ISSUE TITLE
[4.0.0-beta2] Attempt to read from field 'org.json.JSONObject com.onesignal.UserState.syncValues' on a null object reference

### ISSUE THREAD

**Issue by starchey** [OneSignal/OneSignal-Android-SDK#1212]
**Description:**
We've received a crash report from Crashlytics on our latest release which is using OneSignal `4.0.0-beta2`.

**Environment**

1. OneSignal SDK version: 4.0.0-beta2.
1. Compile SDK 29
1. Target SDK 29
1. Installed via Gradle.
1. Crash report observed on Android 11 device while the app was in the background.
1. User Device: Google Pixel 3.

**Steps to Reproduce Issue:**

Have not reproduced.

```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'org.json.JSONObject com.onesignal.UserState.syncValues' on a null object reference
       at com.onesignal.UserStatePushSynchronizer$1.onSuccess(UserStatePushSynchronizer.java:54)
       at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:269)
       at java.lang.Thread.run(Thread.java:923)
```

**Comment by Jeasmine** [comment]
Hey @starchey, thanks in advance for using the beta version, and for your feedback, we will take a look.

**Comment by Jeasmine** [comment]
Hey @starchey  sorry for the delayed answer! but we will release a fix for this on the next beta cut release

**Comment by jkasten2** [comment]
[4.0.0-beta3](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.0.0-beta3) is now released with fix noted above.
