### ISSUE TITLE
Android SDK Major Release 4.0.0 - Beta! 

### ISSUE THREAD

**Issue by Jeasmine** [OneSignal/OneSignal-Android-SDK#1215]
Hello!

The Android Native major release version 4 is now in Beta!

This version includes many exciting changes including an overall simplification of the API as well as many of the underlying native improvements and bug fixes.

Some key changes already in Beta:

Better notification control while app is in foreground
Better notification control while app is in background, no need for services
Simplified Initialization

### Why you should start migrating now
Most importantly, we want to give you the opportunity to voice your opinion and provide feedback so that we can make changes as needed to better suit your implementation.

Furthermore, it is always beneficial to get a head start on migrating your implementation to ensure a smooth transition. As we continue improving OneSignal, being fully migrated to the latest version of the SDK will help minimize potential issues and ensure you can focus on providing value to your customers, improving your business, and creating a delightful messaging experience.

To begin migrating your app to version 4, read our migration guide [here](https://documentation.onesignal.com/docs/step-by-step-android-native-3x-to-400-upgrade-guide). Regarding this guide, please let us know if anything could be clarified or communicated better.

[Releases Page
](https://github.com/OneSignal/OneSignal-Android-SDK/releases)
We are looking forward to hearing from you.

Enjoy!

**Comment by Kieninger** [comment]
Hey,

do you already have a rough plan, when you will release 4.0.0 officially?

We are currently integrating the latest OneSignal version and are questioning, if we might skip that and immediately start with 4.0.0.
If it takes months to consider 4.0.0 as stable, then we most probably stay with the current version and migrate later since we don't want to go in production with a beta version.

BR,
Florian

**Comment by jkasten2** [comment]
@keithnoguchi I don't have an exact timeline but what I can say is things are looking to be on the order of weeks (not months) before a fail cut of 4.0.0 made as the stable release.

**Comment by jkasten2** [comment]
OneSignal-Android-SDK 4.0.0 Beta 3 is now available!
https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.0.0-beta3

**Comment by alexthekid07** [comment]
Do you have any ETA on when this will trickle down to Xamarin.Android? A lot of us are stuck choosing between broken push notifications on AndroidX or keeping our apps out of date by targeting lower versions of Android.

**Comment by rgomezp** [comment]
Out of Beta
---

Version 4 of the SDK is no longer in Beta. Please see the [migration guide](https://documentation.onesignal.com/docs/mobile-2020-api-migration-guide) regarding how to upgrade.

Enjoy!
