### ISSUE TITLE
In App popup auto hides

### ISSUE THREAD

**Issue by mwaked** [OneSignal/OneSignal-Android-SDK#1219]
Hello Mr/Mrs,
We have In App active but in android devices somehow it shows for .5 sec and it auto hides , it makes our app annoying,
Please help us to fix this issue?

* The version of OneSignal which we are using is "3.15.4"
* In App Settings:
![](https://user-images.githubusercontent.com/33099498/99901534-f5413880-2cbf-11eb-8eab-cf3239a3915d.png)

Thanks

**Comment by jkasten2** [comment]
@mwaked Thanks for the reporting. Could you [update to the latest 4.0.0 release](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.0.0) to see if this fixes this issue? Please provide exact steps on reproducing the issue if you are still seeing this problem after updating.

**Comment by jkasten2** [comment]
Closing due to no response.
