### ISSUE TITLE
Some OneSignal methods not working

### ISSUE THREAD

**Issue by ekdnam** [OneSignal/OneSignal-Android-SDK#1242]
**Description:**

I am trying to add OneSignal to my app. To initialize, it I have added to my MainPageActivity.java

```
OneSignal.initWithContext(this);
OneSignal.setAppId(ONESIGNAL_APP_ID);
```

Initially I had added

```
OneSignal.startInit(this).init();
```

and Android Studio showed an error 

`Cannot resolve method 'startInit' in 'OneSignal'`

Similarly,

```
OneSignal.setSubscription(true);
```

showed the error 

`Cannot resolve method 'setSubscription' in 'OneSignal'`

**Environment**

* minSdkVersion: 16
* targetSdkVersion: 30
* Have added the SDK to my project with gradle.

**Steps to Reproduce Issue:**

1. (your steps here)
1. 
1. 

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by Jeasmine** [comment]
Hey @ekdnam, thanks for reporting this issue. We had changed the API recently, this part of the documentation is not up to date. In the meantime, check the comment on https://documentation.onesignal.com/docs/sdk-reference#setsubscription-method while we work on making the docs better

**Comment by Jeasmine** [comment]
@ekdnam https://documentation.onesignal.com/docs/android-native-sdk#disablepush updated!

**Comment by ekdnam** [comment]
@Jeasmine Okay, thanks a lot! 

I would like to mention one point. When any APIs are deprecated and replaced with some other API, can you mention that in the docs? Like this API was deprecated in this version, and got replaced with this API? This will make things amazingly easy for the end-user. Help us keep track of what changed.

Thanks!

**Comment by Jeasmine** [comment]
@ekdnam Yeah actually you can see that here https://documentation.onesignal.com/docs/40-api-android-native#removed-methods, in there you see that the setSubscription is deprecated by disablePush

**Comment by ekdnam** [comment]
Oh, I had no idea about these links. Thanks!
