### ISSUE TITLE
Clear notifications when app resumes 

### ISSUE THREAD

**Issue by raysango** [OneSignal/OneSignal-Android-SDK#125]
Hi, can we clear notifications from status bar and badge number when app is in the background and then  resumes. testing on Android cordova app

**Comment by raysango** [comment]
nvm, I found a way.

**Comment by rwillett** [comment]
Do you mind sharing how you did this please?

Thanks

Rob

**Comment by raysango** [comment]
@rwillett sure, what I did is override the CordovaActivity onResume function in MainActivity and added  OneSignal.clearOneSignalNotifications() to clear notifications and badge count, hope this helps

**Comment by rwillett** [comment]
Ok, thats what we aredoing, we're actually using Cordova and clearOneSignalNotifications() isn't in the SDK  (yet!).

If anybody from OneSignal is reading this, can you officially expose clearOneSignalNotifications() in OneSignal.js. We've added this in ourselves but it would be good to have this in proper :)

Rob
