### ISSUE TITLE
Latest Notification in Grouped Notification Comes Back After Clear All

### ISSUE THREAD

**Issue by salami** [OneSignal/OneSignal-Android-SDK#1250]
**Description:**

When clicking Clear All from the notifications list on an Android phone, if there are notifications grouped together, then after clear, the most recent one will come back as a silent notification.

Note that the Clear All is the system function that clears notifications for all apps.

**Environment**

Using the latest:
implementation 'com.onesignal:OneSignal:[4.0.0, 4.99.99]'

But it was happening on 3.15.3 as well.

**Steps to Reproduce Issue:**

1. Set up OneSignal on Android using latest SDK
1. Send a few messages (I always test with 3) with the same android_group
1. Pull down system notifications and tap "Clear All" -- to clear notifications from all apps
1. The most recent notification from that group will reappear as a silent notification.

**Anything else:**

The OneSignal troubleshooting says this:

_Why do I see previous notifications again?_

_The OneSignal Android Native SDK will reshow notifications that did not get interacted with. The user must click or dismiss the notification to not show it again._

https://documentation.onesignal.com/docs/troubleshooting-android

I don't know if this is related. It only happens with grouped notifications. In any case, there should be a way to avoid this.

I will continue investigating and update as I find more.

**Comment by jkasten2** [comment]
@salami Thanks for reporting could you provide a few more details?
1. What device models have you reproduce the issue on?
   - Please include the Android version as well.
2. Does the issue still happen if you don't set an Android group?
3. Does the issue happen with a different number of notifications instead of 3? Does it happen with 1,2, or 4?

**Comment by salami** [comment]
1. Reproduced for sure on --  Pixel 3a / Android 10 , Pixel 3a / Android 11, Samsung Galaxy Note 8 / Android 11
2. No, it only seems to happen when the group is set
3. It happens with 2 or more notifications. Doesn't happen when only 1 is sent.

**Comment by salami** [comment]
This seems to no longer be an issue. I don't know if that's because of an Android update or OneSignal update or something else.
