### ISSUE TITLE
the BASEURL does not change 4.1.0

### ISSUE THREAD

**Issue by mehdisamavat** [OneSignal/OneSignal-Android-SDK#1255]
**Description:**

I will change the BASEURL from https://api.onesignal.com/ to MYDOMAIN (Because of sanctions)
But requests are still being sent to https://api.onesignal.com/

please guide me how to change BASEURL

**Environment**

all device

**Comment by jkasten2** [comment]
@mehdisamavat Sorry we can't provide support if this is do sanctions.

**Comment by mehdisamavat** [comment]
Hi OneSignal/OneSignal-Android-SDK
I only ask about change URLBASE
Open source is a joke, humanity is a joke, we define conditions or they
define us?
Do not be sorry I'm sorry
