### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method setInitialDelay

### ISSUE THREAD

**Issue by yiann0s** [OneSignal/OneSignal-Android-SDK#1259]
**Description:**
While trying to migrate from 3.X to 4 version of OneSignal library, after performing the steps of the Migration Guide, the app fails to load, with the Message shown in screenshot below

![device-2021-01-18-150640](https://user-images.githubusercontent.com/16455421/104919391-d8af3d00-599e-11eb-862e-4ea5e8745ccd.png)

**Environment**

1. Using as minSdkVersion 16 and targetSdkVersion 30, buildToolsVersion '30.0.3'

**Steps to Reproduce Issue:**
Project gradle build
`buildscript {
    repositories {
        google()
        jcenter()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.1'
        classpath 'com.google.gms:google-services:4.3.3'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.2.0'
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.9, 0.99.99]'
    }
}

ext {
    supportlib_version = '28.0.0'
}

allprojects {

```
repositories {
    google()
    maven {
        url 'http://dl.bintray.com/esri/arcgis'
        }
    maven { url "https://jitpack.io" }
    jcenter()
    maven{
        url "https://maven.google.com"
    }
    mavenCentral()
```

```
}
```

}`

module app build gradle
`buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/'}
    }
    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.8, 0.99.99]'
    }
}

buildscript {
    repositories {
        mavenCentral()
    }

}

apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'

configurations {
    all*.exclude group: 'com.android.support', module: 'support-v13'
    all*.exclude group: 'com.google.guava', module: 'listenablefuture'
}

// Apply the Crashlytics Gradle plugin
apply plugin: 'com.google.firebase.crashlytics'

repositories {
    maven { url 'https://maven.google.com' }
    jcenter() {}

}

android {

```
aaptOptions {
    additionalParameters "--no-version-vectors"
}
compileSdkVersion 30
buildToolsVersion '30.0.3'
useLibrary 'org.apache.http.legacy'
// Other stuffs
dexOptions {
    javaMaxHeapSize "4g"
}
```

```
packagingOptions {
    exclude 'META-INF/LGPL2.1'
    exclude 'META-INF/LICENSE'
    exclude 'META-INF/NOTICE'
}
```

```
defaultConfig {
    applicationId "com.app.driversnetwork"
    minSdkVersion 16
    targetSdkVersion 30
    versionCode 226
    versionName "174.0.26"
    multiDexEnabled true
```

```
    manifestPlaceholders = [ maps_key                       : "****" ]
}
packagingOptions {
    exclude 'META-INF/proguard/androidx-annotations.pro'
    exclude 'META-INF/androidx.exifinterface_exifinterface.version'
}
buildTypes {
    release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
}
```

```
flavorDimensions "white"
```

```
productFlavors{
    aegean{
        applicationId = "com.rcflavorproba"
        versionCode 44
        versionName "1.0.17"
        dimension "white"
        manifestPlaceholders = [maps_key: "****"]
    }
}
```

```
lintOptions {
    checkReleaseBuilds false
    abortOnError false
}
```

```
compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
}
```

}

ext {
    supportlib_version = '28.0.0'
    enableCrashlytics = true
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation fileTree(include: ['*.jar'], dir: 'libs')

```
implementation 'io.branch.sdk.android:library:5.0.3'
```

```
implementation 'com.google.firebase:firebase-ml-vision:24.0.3'
implementation 'com.google.firebase:firebase-messaging:20.2.4'
```

```
implementation('com.weiwangcn.betterspinner:library-material:1.1.0') {
    exclude group: 'com.android.support', module: 'appcompat-v7'
    exclude group: 'com.rengwuxian.materialedittext', module: 'library'
}
```

```
implementation 'gun0912.ted:tedpermission:2.2.3'
//replace with older versions if ANR bugs do still appear
//implementation 'com.onesignal:OneSignal:3.10.9'
implementation 'com.onesignal:OneSignal:[4.0.0, 4.99.99]'
implementation 'androidx.appcompat:appcompat:1.2.0'
implementation 'androidx.media:media:1.1.0'  
implementation 'androidx.mediarouter:mediarouter:1.1.0' 
implementation 'androidx.exifinterface:exifinterface:1.2.0' 
implementation 'com.google.android.material:material:1.2.0'
implementation 'androidx.browser:browser:1.2.0' 
implementation 'androidx.legacy:legacy-support-v4:1.0.0' 
implementation 'androidx.cardview:cardview:1.0.0'
implementation 'com.google.android.gms:play-services-location:[17.0.0, 17.99.99]'
implementation 'com.google.android.gms:play-services-maps:17.0.0'
implementation 'com.google.android.gms:play-services-places:17.0.0'
```

   (.....)
}`

**Stack Trace**

`2021-01-18 14:40:10.148 11715-11809/com.rcflavorproba E/AndroidRuntime: FATAL EXCEPTION: OS_REST_SUCCESS_CALLBACK
    Process: com.rcflavorproba, PID: 11715
    java.lang.NoSuchMethodError: No virtual method setInitialDelay(JLjava/util/concurrent/TimeUnit;)Landroidx/work/WorkRequest$Builder; in class Landroidx/work/OneTimeWorkRequest$Builder; or its super classes (declaration of 'androidx.work.OneTimeWorkRequest$Builder' appears in /data/app/com.rcflavorproba-yaC0eeMZVq602PYxRKb6Fw==/base.apk)
        at com.onesignal.OSNotificationRestoreWorkManager.beginEnqueueingWork(OSNotificationRestoreWorkManager.java:46)
        at com.onesignal.OneSignal.handleActivityLifecycleHandler(OneSignal.java:831)
        at com.onesignal.OneSignal.init(OneSignal.java:721)
        at com.onesignal.OneSignal.setAppId(OneSignal.java:624)
        at com.onesignal.OneSignal.reassignDelayedInitParams(OneSignal.java:1027)
        at com.onesignal.OneSignal.onRemoteParamSet(OneSignal.java:758)
        at com.onesignal.OneSignal$5.complete(OneSignal.java:968)
        at com.onesignal.OneSignalRemoteParams.processJson(OneSignalRemoteParams.java:205)
        at com.onesignal.OneSignalRemoteParams.access$100(OneSignalRemoteParams.java:12)
        at com.onesignal.OneSignalRemoteParams$1.onSuccess(OneSignalRemoteParams.java:150)
        at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:269)
        at java.lang.Thread.run(Thread.java:764)`

Thank you for your time and effort. For any further details needed, I would be happy to provide them

**Comment by CarlesGameHouse** [comment]
Hi, had the exact same issue and it was fixed upgrading:
implementation "androidx.work:work-runtime:2.0.0" to implementation "androidx.work:work-runtime:2.2.0"

**Comment by yiann0s** [comment]
> Hi, had the exact same issue and it was fixed upgrading:
> `implementation "androidx.work:work-runtime:2.0.0"` to `implementation "androidx.work:work-runtime:2.2.0"`

Thanks for the recommendation! Now the code seems to produce error 
`java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/work/impl/utils/futures/AbstractFuture;`
Very similar results with issue #1254

**Comment by yiann0s** [comment]
Implementing the suggestion of deleting the below line, taken from [here](https://github.com/fluttercommunity/flutter_downloader/issues/223), made the problem disappear 

`configurations.all {
 all*.exclude group: 'com.google.guava', module: 'listenablefuture'
}`
