### ISSUE TITLE
Crash com.google.firebase:firebase-iid@@20.2.2:9

### ISSUE THREAD

**Issue by goodibunakov** [OneSignal/OneSignal-Android-SDK#1267]
Only I get this crash?
I use sdk 4.1.0 
I found that https://stackoverflow.com/questions/62794147/java-lang-abstractmethoderror-abstract-method-com-google-android-gms-tasks-tas

When you will up firebase version?

**Comment by semihozkoroglu** [comment]
@goodibunakov did you find any solution? i faced same problem.

**Comment by goodibunakov** [comment]
@semihozkoroglu I think there is only one possible solution - update dependency in onesignal sdk. I found that there is pull request https://github.com/OneSignal/OneSignal-Android-SDK/pull/1264

**Comment by jkasten2** [comment]
This is now fixed in the 4.2.0 release:
https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.2.0
