### ISSUE TITLE
project keys

### ISSUE THREAD

**Issue by OlegTarashkevich** [OneSignal/OneSignal-Android-SDK#127]
Please add ability to set onesignal_app_id and onesignal_google_project_number directly from code. I want to store my keys with encryption, then decrypt them and set when I want to init onesignal library. 

In other case any developer can decompile project and retrieve onesignal_app_id and onesignal_google_project_number

Example:

```
OneSignal.startInit(context)
                .autoPromptLocation(true)
                .setKeys(onesignal_app_id, onesignal_google_project_number)
                .init();
```

```
manifestPlaceholders = [onesignal_app_id: "${onesignal_app_id}",
                                onesignal_google_project_number: "${onesignal_google_project_number}"]
```

**Comment by jkasten2** [comment]
@OlegTarashkevich You can use the following syntax instead to set this at runtime..
```Java
OneSignal.init(Context, googleProjectNumber, oneSignalAppId, NotificationOpenedHandler , NotificationReceivedHandler);
```

We still recommend calling this from the `onCreate` for your `Application` class for OneSignal to work correctly.

**Comment by OlegTarashkevich** [comment]
@jkasten2 Awesome! I will try it! 
Thank you!

**Comment by soshial** [comment]
There are also handy `init()` methods without Notification handlers.
