### ISSUE TITLE
On using OneSignal within a library, if one app uninstalls which leads to unsubscribe there is no way to subscribe through remaining apps.

### ISSUE THREAD

**Issue by NamanJindal03** [OneSignal/OneSignal-Android-SDK#1271]
Description: On using OneSignal within a library, if one app uninstalls which leads to unsubscribe there is no way to subscribe again to OneSignal through remaining apps.

Environment
OneSignal SDK 4.0.0

Steps to Reproduce Issue:
Steps:
•	Create an android library where you have initialized OneSignal
•	Put push notification function (which is setNotificationOpenedHandler
•	 ) in the library itself 
•	Create 2 apps where you are using this this library
•	Run both these apps on a single device (now we have 1 subscribed device in OneSignal)
•	Uninstall the latest among the above 2 apps. (now we have 0 subscribed as on uninstall OneSignal unsubscribes device)
•	Now even when we open the first app we aren’t subscribed again to oneSignal

Actual result: Lost subscribe to oneSignal all together
Help needed: need a way to subscribe again to oneSignal

**Comment by Jeasmine** [comment]
Hey @NamanJindal03, thanks for reporting the issue. We will keep track of this.

Same issue as https://github.com/OneSignal/OneSignal-Android-SDK/issues/1272

**Comment by jkasten2** [comment]
@NamanJindal03 Incase you are not subscribed to the issue linked here I just replied with an update. https://github.com/OneSignal/OneSignal-Android-SDK/issues/1272#issuecomment-844578494
