### ISSUE TITLE
Attempt to invoke virtual method 'org.json.JSONObject com.onesignal.UserState.generateJsonDiff(com.onesignal.UserState, boolean)' on a null object reference

### ISSUE THREAD

**Issue by bobbyirawan09** [OneSignal/OneSignal-Android-SDK#1279]
**Description:**

> Disclaimer, the real title is `Attempt to invoke virtual method 'org.json.JSONObject f.i.f4.a(f.i.f4, boolean)' on a null object reference`, I just make it more readable as the title.

Hi, recently I get an error in my crashlytics that could be the issue from OneSignal, I already asked the support and she tells me to open the issue in Github. I'll explain in **Anything Else** section. The information and research are purely on my observation, so please tell me if there's something wrong.

After reading the **Anything Else** section, my further question is, how can the `currentUserState` null? Is there's anything I can do to avoid or catch this crash issue? Another question is, as the docs mentioned, that I don’t need to add any proguard rule to whitelist OneSignal class, but why `UserState` class got obfuscated?

Thank you

**Environment**

1. Using OneSignal SDK 4.0.0
1. I add the SDK through the
1. Affected device mostly Xiaomi and Samsung
1. Affected device OS mostly android 10
1. 54% crash happens in background

**Steps to Reproduce Issue:**

Currently, I don't know how to reproduce it, here are some step that I had already try to reproduce the issue, using Android 11 on Note10+ device:

1. Open the notification
1. Open the application normally
1. Play with the notification permission in the application setting

**Anything else:**

Here is the stack trace, as the guideline:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONObject f.i.f4.a(f.i.f4, boolean)' on a null object reference
       at com.onesignal.UserStateSynchronizer.persist(UserStateSynchronizer.java:197)
       at com.onesignal.OneSignalStateSynchronizer.persist(OneSignalStateSynchronizer.java:80)
       at com.onesignal.OneSignal.scheduleSyncService(OneSignal.java:1214)
       at com.onesignal.OneSignal.backgroundSyncLogic(OneSignal.java:1209)
       at com.onesignal.OneSignal.onAppLostFocus(OneSignal.java:1197)
       at com.onesignal.ActivityLifecycleHandler$AppFocusRunnable.run(ActivityLifecycleHandler.java:282)
       at java.lang.Thread.run(Thread.java:919)
```

* at `com.onesignal.OneSignal.onAppLostFocus(OneSignal.java:1197)
` It’s indicate that the app is in background
* at `com.onesignal.OneSignal.backgroundSyncLogic(OneSignal.java:1209)` 
in this line, it calls the scheduleSyncService function, this function will be called if there are any unsynced changes
* `com.onesignal.OneSignal.scheduleSyncService(OneSignal.java:1214)` 
this line contain code below
boolean unsyncedChanges = OneSignalStateSynchronizer.persist();
the function persist is called
* `com.onesignal.OneSignalStateSynchronizer.persist(OneSignalStateSynchronizer.java:80)` 
this contain code to check the email and push state if it’s persist or not
* `com.onesignal.UserStateSynchronizer.persist(UserStateSynchronizer.java:197)
` this function is called when getting persist value for email state in previous function, the code trigger this is below
boolean emailPersisted = getEmailStateSynchronizer().persist();
* `org.json.JSONObject f.i.f4.a(f.i.f4, boolean)' on a null object reference` 
the problem lies here, the `f.i.f4` is the `UserState` class that obfuscated and for the `a`, it’s belong to `generateJsonDiff()` function. in this function call, the code is `
boolean unSynced = currentUserState.generateJsonDiff(toSyncUserState, isSessionCall()) != null;` 
from the code, what could be the problem is that the `currentUserState` property is null, but the `toSyncUserState` is not null (there’s checker for it). The `currentUserState` property is the problem that stack trace inform.

The question is in **Description** section

**Comment by rborn** [comment]
We also have this error in the ReactNative module. 
I managed to reproduce it this way: 

- exit the app on the android device ( swipe up, not force kill)
-  send a push
- tap on the push notification
- 💥

 I suspect the code that triggers it is `getTags`

**Comment by rborn** [comment]
I can confirm that in RN case it was `getTags` that created the issue. I removed it from our codebase ( js side) and the crash is not there anymore.

**Comment by bobbyirawan09** [comment]
I had tried your step to reproduce it, but the crash didn't happen on my device. Pixel 3A runs on Android 11.

I assumed `getTags` that you mentioned is like in this [docs](https://documentation.onesignal.com/docs/sdk-reference#gettags-method). If what I assumed correct, then I don't think it's related to my problem, since I don't implement and have that code in my project. Thanks for the response @rborn

**Comment by bobbyirawan09** [comment]
Is there any info about this issue already fixed in the new release or not? It's affecting almost 100 users right now since I can't do anything about this, thanks

Sorry for mentioning you guys, thanks @jkasten2 @Jeasmine

**Comment by namdp** [comment]
any update?

**Comment by bobbyirawan09** [comment]
apparently no, the developer also not give any information about this

**Comment by Jeasmine** [comment]
Hey, sorry for the delay on this issue. Thanks for the information! We are working on this for the next release.

**Comment by Jeasmine** [comment]
The fix has been included under https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.3.3
