### ISSUE TITLE
Allow consumers to inject their own SharedPreferences implementation

### ISSUE THREAD

**Issue by stkent** [OneSignal/OneSignal-Android-SDK#128]
Currently, the SDK uses the following `SharedPreferences` implementation:

``` java
context.getSharedPreferences(OneSignal.class.getSimpleName(), Context.MODE_PRIVATE);
```

For added security, it would be nice to be able to inject an instance of e.g. `https://github.com/scottyab/secure-preferences` instead.

**Comment by jkasten2** [comment]
@stkent Sorry but I don't believe I'll be able to look into this in the near future. However if this is a feature you would like interrogated I'll gladly look over and merge in a pull request.

**Comment by stkent** [comment]
I also don't have time to address this imminently, just wanted to open the issue as a nice-to-have!

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration
