### ISSUE TITLE
⚠️ Upgrade your project from JCenter to Maven Central ⚠️ 

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-Android-SDK#1293]
>[OneSignal is hosted on Maven Central](https://search.maven.org/artifact/com.onesignal/OneSignal) with the latest version as well as all previous versions today!

## JCenter is deprecated
Android Studio defaults to the JCenter repository for non-Google artifacts (Java / Kotlin packages, libraries, SDKs ect) 
however [JFrog is sunsetting JCenter](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/).

This means:

* March 31st 2021 - No new versions of packages
* February 1, 2022 - Servers will be completely taken offline

[Google acknowledges this issue](https://developer.android.com/studio/build/jcenter-migration) but unfortunately does not provide a migration instructions today(3/18/21) for app developers. However we have created a guide below on how to do so today.

## 1. Add Maven Central to your project
1. Open your root `build.gradle`
1. Find `jcenter()` and add `mavenCentral()` before it.
  * _Make sure to add this in both spots where `jcenter()` is found._

Your `build.gradle` should look something like this:

```gradle
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        google()
        mavenCentral()
        jcenter()
       // NOTE: Keep any other entries you may have had here
    }
    dependencies {
        classpath "com.android.tools.build:gradle:4.1.3"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        jcenter()
       // NOTE: Keep any other entries you may have had here
    }
}
```

3. Sync Gradle by pressing "Sync Now" in Android Studio

## 2. How to fully migrate off JCenter
If you attempt to remove `jcenter()` completely today from your Android project you will get the following error.

### Error if you remove JCenter today (3/18/21)
```
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find org.jetbrains.trove4j:trove4j:20160824.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/trove4j/trove4j/20160824/trove4j-20160824.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/trove4j/trove4j/20160824/trove4j-20160824.pom
     Required by:
         project : > com.android.tools.build:gradle:4.1.3 > com.android.tools.build:builder:4.1.3 > com.android.tools:sdk-common:27.1.3
```

### Why - Android core dependency still requires JCenter (3/18/21)
Android Studio 4.1.3 and AGP (Android Gradle Plugin) still have a version of a dependency (trove4j) that is only on JCenter.
* _[This is solved in AGP 4.2.0](https://issuetracker.google.com/issues/109894262#comment7) but this is still in beta and requires Android Studio 4.2 beta as well._

### Work around for trove4j missing
To fix the `trove4j` missing error noted above we can force upgrade to a newer version that is available on Maven Ceternal.
Add the following to the bottom of your root `build.gradle`.

```gradle
// Temporary workaround for missing trove4j when removing jcenter() until you can upgrade to "com.android.tools.build:gradle:4.2.0"
buildscript {
    configurations.all {
        resolutionStrategy {
            eachDependency {
                // https://issuetracker.google.com/issues/109894262#comment9
                if (requested.group == "org.jetbrains.trove4j" && requested.name == "trove4j" && requested.version == "20160824") {
                    useTarget("org.jetbrains.intellij.deps:trove4j:1.0.20181211")
                }
            }
        }
    }
}
```

_[Source](https://issuetracker.google.com/issues/109894262#comment11)_

### OneSignal is already on Maven Central
[OneSignal is hosted on Maven Central](https://search.maven.org/artifact/com.onesignal/OneSignal) with the latest version as well as all previous versions today!

### Other could not resolve errors
You may find that not all libraries / SDKs in your project are on Maven Central, or even available outside of JCenter. You will need to view the build error log and contact the vendor of those dependencies on what their migration strategy is.

**Comment by jkasten2** [comment]
OneSignal has made [an announcement of this issue](https://onesignal.com/blog/android-migrate-jcenter-to-maven-central/) and the [OneSignal Android setup guide](https://documentation.onesignal.com/docs/android-sdk-setup#step-2-add-onesignal-gradle-plugin-and-sdk) has been updated so closing this to indicate this is resolved.

It will still be pinned here few a number of months to bring attention to this required upgrade.

**Comment by jkasten2** [comment]
Even though this is closed it is still open for discussion so please feel free to comment and ask any questions on this topic here still.

**Comment by mathiasmadsen** [comment]
We have an old project, that seems impossible to upgrade. 2 months ago we discovered that notifications wasn't sent to Android users, and I was sure it had something to do with the JCenter issue.

While we are looking into a complete rebuilding of the app, our client decided to send out a new notification a few days ago. And now it works for Android.

Going to the core of the [JFrog announcement](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), I found this message at the top:

> UPDATE 4/27/2021: We listened to the community and will keep JCenter as a read-only repository indefinitely. Our customers and the community can continue to rely on JCenter as a reliable mirror for Java packages.

So now I am wondering if I can expect the issue to be resolved for now?

**Comment by jkasten2** [comment]
@mathiasmadsen Thanks for reporting, what solved the notification sent issue for you?

On the Jcenter update note, as they noted their repo will remain read-only but this means you will not get any updates either. The most compatible way to upgrade is to keep `jcenter()` but  make sure you have `mavenCentral()` and `google()` before it if you can't fully remove jcenter.

**Comment by mathiasmadsen** [comment]
> @mathiasmadsen Thanks for reporting, what solved the notification sent issue for you?
> 
> On the Jcenter update note, as they noted their repo will remain read-only but this means you will not get any updates either. The most compatible way to upgrade is to keep `jcenter()` but make sure you have `mavenCentral()` and `google()` before it if you can't fully remove jcenter.

Well, that is the strange thing. We did nothing. The app hasn't been updated for a while, so it is definitely not using `mavenCentral()`. But I will contact the OneSignal support team and see if they can figure it out.

**The results from 28/2-2022:**
<img width="919" alt="2022-02-28" src="https://user-images.githubusercontent.com/3418529/161832049-bee6f785-a6d2-4f57-9c46-0c05f5532429.png">


**The results from 31/3-2022:**
<img width="918" alt="2022-03-31" src="https://user-images.githubusercontent.com/3418529/161832062-29e98e68-4718-4223-a4ce-f913a36465c6.png">

**Comment by jkasten2** [comment]
@mathiasmadsen The "Failed (Errored)" status for all your Android notifications was most likely due to an authentication issue with Firebase. It could be a number of things such as someone on your team revoked the FCM key on your Firebase Console account or some other one-off auth issue. You can normally find warnings under Setting > Platforms if you get a failure like this.

To keep this on topic with this issue however please create a new issue if you have any follow up. But as you noted, OneSignal support would be best for this kind of situation with send issues.
