### ISSUE TITLE
Tests with Appium - Popup's element are not accessible 

### ISSUE THREAD

**Issue by shbadawy** [OneSignal/OneSignal-Android-SDK#1294]
**Description:**
I am using Appium for UI testing, when a popup window is triggered and shown on the device, the XML code of the popup's elements are not accessible (cannot access any elements' id inside the popup, for example the X button). Hence, cannot dismiss this popup using Appium and continue the automated tests. I only can dismiss the popup manually by clicking on the X button on the emulator.

**Environment**
OS: MacOS Big Sur
SDK version: 3.0
Java: 14.0.2
Appium: 1.20.2

**Attachments**

* I have attached an image with a sample popup used in the app, and the XML of the code isn't being detected (Using Appium)

![Sample](https://user-images.githubusercontent.com/22125302/111283865-9b8ac280-8650-11eb-8643-006f1d0a6d26.png)

**Comment by jkasten2** [comment]
@shbadawy Thanks for reporting. I don't have enough experience with Appium provide a known solution on how to resolve this issue. However you noted that you are trying to grab the XML element for the "X" button so this sound like Appium can grab elements from an Android view. OneSignal's In-App Messages are HTML and the only Android view is a WebView here. So if Appium has a way to interact with WebViews the would most likely be the way to go.

**Comment by shbadawy** [comment]
@jkasten2 Thank you for the quick response. I will check if there is a way to access HTML elements using Appium Android.

**Comment by shbadawy** [comment]
@jkasten2 While writing Appium test today, I encountered a Webview elements in the app I am testing, and the Webview elements are shown and accessed normally using Appium inspector. Is there a way to access the elements' XML in the popups that are generated using OneSignal ?

**Comment by jkasten2** [comment]
@shbadawy You 2nd screenshot here looks like a Android native view to me. As I see `android.widget` on the right side, a webview would have HTML elements. Please provide more details if I am mistaken.

**Comment by shbadawy** [comment]
@jkasten2 Thank you for your response. 
I have searched about this issue but unfortunately, did not found a solution from Appium side.
But I have found a **workaround** that to dismiss OneSignal's popups when they are expected to appear by applying `swiping down gesture`.

**Comment by jkasten2** [comment]
Thanks for proving those details, could help others who run into this issue in the future.
Going to close this for now as it isn't a OneSignal specific issue, but feel free to add more details or questions related to issue.
