### ISSUE TITLE
ClassCastException crash on OneSignal.handleActivityLifecycleHandler()

### ISSUE THREAD

**Issue by cgsbanno** [OneSignal/OneSignal-Android-SDK#1297]
**Description:**

This appears to be happening in an internal OneSignal code path (`OneSignal.makeAndroidParamsRequest()`) as opposed to our `Application.onCreate()` (`OneSignal.initWithContext()`, `OneSignal.setAppId()`, etc.)

Following code execution from `OneSignal.makeAndroidParamsRequest()`, `OneSignal.init(appContext)` is called in `OneSignal.setAppId()`, therefore the validation on `L622` is `false`:

```
if (appActivity != null && appActivity.get() != null)
```

At this point, the passed `Context` is recognized as an `Application` `Context`

In `init()`, `handleActivityLifecycleHandler()` is then called with the same `Context`. On `L829`, the passed `Application` `Context` is cast to `Activity` which causes the crash:

```
if (inForeground) {
    if (OneSignal.getCurrentActivity() == null && activityLifecycleHandler != null) {
        activityLifecycleHandler.setCurActivity((Activity) context);
```

Maybe some issue with the validations in `OneSignal.setAppId()` `L622` and/or `OneSignal.handleActivityLifecycleHandler()` `L827-828`, or a race condition since this is affecting a small percentage of our user base (~270 users)

**Environment:**

SDK Version: 4.2.0 but crash was also reported on 4.1.0
Maven
Android target: 30
Affected Android versions: Android 7-11

**Steps to Reproduce Issue:**

Cannot reproduce locally, crashes are being reported in production via our crash reporting tool.

**Anything else:**

```
java.lang.ClassCastException: com.banno.grip.GripApplication cannot be cast to android.app.Activity
    at com.onesignal.OneSignal.handleActivityLifecycleHandler(OneSignal.java:829)
    at com.onesignal.OneSignal.init(OneSignal.java:722)
    at com.onesignal.OneSignal.setAppId(OneSignal.java:625)
    at com.onesignal.OneSignal.reassignDelayedInitParams(OneSignal.java:1028)
    at com.onesignal.OneSignal.onRemoteParamSet(OneSignal.java:759)
    at com.onesignal.OneSignal$5.complete(OneSignal.java:969)
    at com.onesignal.OneSignalRemoteParams.processJson(OneSignalRemoteParams.java:205)
    at com.onesignal.OneSignalRemoteParams.access$100(OneSignalRemoteParams.java:12)
    at com.onesignal.OneSignalRemoteParams$1.onSuccess(OneSignalRemoteParams.java:150)
    at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:269)
    at java.lang.Thread.run(Thread.java:919)
```

Our tool is reporting the crash as occurring in thread `OS_REST_SUCCESS_CALLBACK`

Crashes began after updating from OneSignal 3.x -> 4.x

**Comment by zsliu** [comment]
I run into the same issue. Any update about the issue?

**Comment by Sahara150** [comment]
Same issue here. Really should get some fix.

**Comment by Jeasmine** [comment]
Thanks for pointing this up. We will take a look over it

**Comment by angelolloqui** [comment]
Same here... please keep us informed when this is fixed... it is showing up in our crash reports

**Comment by Jeasmine** [comment]
This has been released under https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.4.1
