### ISSUE TITLE
OneSignal Push notifications for TWA apps.

### ISSUE THREAD

**Issue by Vegas10128** [OneSignal/OneSignal-Android-SDK#1298]
Its the year 2021, and have yet to see any decent / clear documentation or implementation instructions for TWA apps to have OneSignal capabilities. 

I have seen this thread here. 
https://github.com/OneSignal/OneSignal-Android-SDK/issues/868

Which was marked closed by rgomezp
and only response from this user was. 

"Thanks for your recommendation. We will consider adding this in the future" and
"We will continue tracking this request internally"

Further more, little more investigating to find 2 solutions in same & separate thread.

` implementation ('com.onesignal:OneSignal:3.12.7') {
        exclude group: "com.android.support", module: "customtabs"
    }
`
and 

`implementation ('com.onesignal:OneSignal:3.12.7') {
      //  exclude group: "com.android.support", module: "support-v4"
        exclude group: "com.android.support", module: "customtabs"
    }
`

But both solutions do NOT work, instead it causes errors after building application. 

`Manifest merger failed with multiple errors, see logs`

I have also tried updating to recommended version by android studio, 
I have also attempted with migrate to android x,

Can we expect documentation or instructions on implementing onesignal to TWA anytime soon?
If not, i will drop TWA's like a bag of bricks and consider improving more towards PWA apps.

**Comment by jkasten2** [comment]
@Vegas10128 Thanks for resurfacing, I was able to reproduce the issue. I have some options I have verified fix the build errors on the original issue.
https://github.com/OneSignal/OneSignal-Android-SDK/issues/868#issuecomment-812253272
