### ISSUE TITLE
OSExternalUserIdUpdateCompletionHandler OnSuccess But External User ID Not Subcribed Yet

### ISSUE THREAD

**Issue by kweiser** [OneSignal/OneSignal-Android-SDK#1300]
**Description:**

In our system we want to use the OneSignal External User ID. Therefore we use method OneSignal::setExternalUserId(...)
Once OSExternalUserIdUpdateCompletionHandler.OnSuccess is called, we expect that the new ID can be used.
But if right afterwards, our Server wants to send a push notification suing this ID, the following error is returned from OneSignal:

* All included players are not subscribed - 

Doing the same request some time later with the same ID, no issue occurs and the push is received.

We have now a workaround that we wait 1 second after we received the onSuccess callback. Then everything works as expected.

Our question is now, why the onSuccess callback is called even the system seems not to be ready yet. 

Thanks a lot.

**Environment**
Android:
oneSignalPluginVersion=[0.12.9, 0.99.99]
Server:
https://onesignal.com/api/v1/notifications

**Steps to Reproduce Issue:**

1. Create new external user ID
1. Apply to OneSignal::setExternalUserId
1. OSExternalUserIdUpdateCompletionHandler.OnSuccess -> use external User ID 
1. Server requests push notification for new user id using https://onesignal.com/api/v1/notifications

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by jkasten2** [comment]
@kweiser Thanks for reporting, I checked how the setExternalUserId fires on the latest OneSignal-Android-SDK 4.3.0 and does only fire after the network call has gone through and a 2xx response is received from onesignal.com. OneSignal's backend will normally take just a few seconds before the updated is committed before it becomes available.

I am not sure I understand the use case targeting with an external Id right after it added. Or was this just a test?

Also `include_external_user_ids` requires your OneSignal App REST API key  to authenticate. Make sure you only make a REST API request using it from your server, never client side (from your app)!

**Comment by kweiser** [comment]
@jkasten2 , thanks a lot for your quick reply. 

Yes, we make the REST API requests only from our server.
Yes, it is a automated test execution to verify our system. In the test sceanrio we set a new external user ID in OneSignal, submit the ID to our Server and the server immediately want to send a notification. 

As an additional information: The failure occur mainly on fast devices. On slower ones the tests always passes.

**Comment by jkasten2** [comment]
@kweiser If it is an automated test (not production code) I recommend reading the player record by doing a GET REST API call on the player_id to ensure `external_user_id` is available. OneSignal uses a sort of cached write to provide good uptime so this write takes a few seconds in most cases to be committed.

Another options is to use `included_player_ids` to send a notification, but that probably isn't an option for you as that is not what you automated test is trying to verify.

**Comment by kweiser** [comment]
@jkasten2 
Thanks a lot for your suggestions. For now, we are fine with the provided answers.

Thanks a lot for the great support.
