### ISSUE TITLE
Notification data received in background but not appear custom notification

### ISSUE THREAD

**Issue by hafiz013** [OneSignal/OneSignal-Android-SDK#1327]
**Description:**
Hi when i do log the data notification appear but custom notification not appear. I don't know what wrong with my code.

Sample code:
1) Inside manifest
```xml
<application
        android:name=".AppControll"
        android:allowBackup="false"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/Theme.MuslimahPro"
        tools:replace="android:allowBackup">
        
        <service android:name=".fcm.NotificationBackground"
            android:permission="android.permission.BIND_JOB_SERVICE"
            android:exported="false"
            tools:ignore="Instantiatable">
            <intent-filter>
                <action android:name="com.onesignal.NotificationExtender" />
            </intent-filter>
        </service>

        <meta-data android:name="com.onesignal.NotificationServiceExtension"
            android:value="packagename.NotificationBackground" />

        <!-- Example: Sets all OneSignal notification's accent color to Green by default.  -->
        <!-- Color format is in ARGB. -->
        <meta-data android:name="com.onesignal.NotificationAccentColor.DEFAULT" android:value="FF00FF00" />
    </application>
```

2) in class notificationbackground
```Kotlin
@SuppressWarnings("unused")
class NotificationBackground : OSRemoteNotificationReceivedHandler {

    override fun remoteNotificationReceived(
            context: Context,
            notificationReceivedEvent: OSNotificationReceivedEvent
    ) {
        val notification = notificationReceivedEvent.notification
        val mutableNotification = notification.mutableCopy()

        // Example of modifying the notification's accent color
        val channelId = context.resources.getString(R.string.default_notification_channel_id)
        val defaultSoundUri = RingtoneManager.getDefaultUri(RingtoneManager.TYPE_NOTIFICATION)

        val data = notification.additionalData
        Log.e("NotificationBackground", "Received Notification Data: " + data)

        val notificationLayoutExpanded = RemoteViews(
                context.packageName,
                R.layout.notification_large
        )

        if (data.has("notify_id") && data.has("title") && data.has("img") &&
                data.has("msg")){
            Log.e("NotificationBackground", "data has"). // <-- this log appear data but
            val intent = Intent(context, MainActivity::class.java).apply {
                addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP)
                putExtra("idPost", data.optInt("notify_id"))
            }
            val pendingIntent = PendingIntent.getActivity(context, 0 /* Request code */, intent,
                    PendingIntent.FLAG_ONE_SHOT)
            notificationLayoutExpanded.setTextViewText(R.id.titleNotify, data.optString("title"))
            notificationLayoutExpanded.setTextViewText(R.id.msg, data.optString("msg"))
            notificationLayoutExpanded.setImageViewBitmap(R.id.profileUser, getBitmapFromURL(data.optString("img")))
          // this custom notification not appear. why?
            mutableNotification.setExtender { builder: NotificationCompat.Builder ->
                builder.setChannelId(channelId)
                builder.setSmallIcon(R.mipmap.ic_launcher_round)
                builder.setStyle(NotificationCompat.BigTextStyle().bigText(data.optString("msg")))  //recommended for full background and app title
                builder.setContentIntent(pendingIntent)
                //builder.setContent(notificationLayoutExpanded)
                builder.setCustomBigContentView(notificationLayoutExpanded)
                builder.setAutoCancel(true)
                builder.setVibrate(longArrayOf(1000, 1000, 1000, 1000, 1000))
                builder.setLights(Color.RED, 3000, 3000)
                builder.setSound(defaultSoundUri)
                builder.setVisibility(NotificationCompat.VISIBILITY_PUBLIC)
                builder.setColor(ContextCompat.getColor(context, R.color.white))
            }
            notificationReceivedEvent.complete(mutableNotification)
        }else{
            Log.e("NotificationBackground", "data no has")
            notificationReceivedEvent.complete(null)
        }
    }
    private fun getBitmapFromURL(location: String): Bitmap? {
        try {
            return BitmapFactory.decodeStream(URL(location).openConnection().getInputStream())
        } catch (t: Throwable) {
            Log.i("OneSignalExample", "COULD NOT DOWNLOAD IMAGE")
        }
        return null
    }
}
```

**Environment**
1) implementation 'com.onesignal:OneSignal:4.3.1' in app build
2)apply plugin id 
```gradle
plugins {
    id 'com.onesignal.androidsdk.onesignal-gradle-plugin'
}
```
3)under dependecies
`classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.12.10'`
4)extend application 
```Kotlin
       // Logging set to help debug issues, remove before releasing your app.
        OneSignal.setLogLevel(OneSignal.LOG_LEVEL.VERBOSE, OneSignal.LOG_LEVEL.NONE)

        // OneSignal Initialization
        OneSignal.initWithContext(this)
        OneSignal.setAppId(ONESIGNAL_APP_ID)
```

**Comment by jkasten2** [comment]
@hafiz013 I tool a look and if you are seeing `"data has"` as you noted in the comment in your code it should be displaying. I have seen issue where a wrongly formatted small notification icon could cause it not to display however. To start try commenting out this line.
```kotlin
  builder.setSmallIcon(R.mipmap.ic_launcher_round)
```

If that doesn't help I recommend removing code until the notification displays. Narrow down the issue to as minimum amount of code as possible so we can find the root of the issue.

**Comment by hafiz013** [comment]
nope working either @jkasten2 .. ermh why this library not working

**Comment by hafiz013** [comment]
@jkasten2 finally i found bugs on this library one signal. 
1) when   builder.setStyle(NotificationCompat.BigTextStyle().bigText(data.optString("msg"))). <-- working if without this code builder.setCustomBigContentView(notificationLayoutExpanded) and builder.setCustomContentView(notificationLayoutExpanded) and builder.setChannelId(channelId).

**Comment by hafiz013** [comment]
please fix u code/library @jkasten2

**Comment by jkasten2** [comment]
@hafiz013 The [`NotificationCompat.Builder`](https://developer.android.com/reference/androidx/core/app/NotificationCompat.Builder) is part of the AndroidX / Jetpack library. If you calling the `CustomContent` method with your own custom view then you don't need call `setStyle`. It's possible instead of Google's library ignore one it is omitting the displaying.

OneSignal already takes care of using the correct styles, message body, message title, channel, etc so I am not sure what you need from a custom view to recommend any other settings.

**Comment by hafiz013** [comment]
@jkasten2  i do customview without setstyle but still not appear notifications. i think onesignal got bugs. my custom view i need for display largeicon appear on left side instead of right side.

**Comment by jkasten2** [comment]
> 1) when   builder.setStyle(NotificationCompat.BigTextStyle().bigText(data.optString("msg"))). <-- working if without this code builder.setCustomBigContentView(notificationLayoutExpanded) and builder.setCustomContentView(notificationLayoutExpanded) andchannelId).

Maybe I misunderstood the part above. Did you mean you had to remove `builder.setStyle`, `builder.setCustomBigContentView`, `builder.setCustomContentView`, and `builder.setChannelId` for the notification to display? Including any of them causes your notification not to display?

> . i think onesignal got bugs ...

[`NotificationCompat.Builder`](https://developer.android.com/reference/androidx/core/app/NotificationCompat.Builder) is part of the AndroidX library which you are setting your properties on. Follow [Android's documentation](https://developer.android.com/reference/androidx/core/app/NotificationCompat.Builder) on this to make sure you are setting these correctly.
However if you can narrow down the issue to the exact field and value that is causing the issue we can try to help.

 > ... my custom view i need for display largeicon appear on left side instead of right side.

Different versions of Android, manufacturers, and devices languages settings (such as RTL) could mean your custom view might not display correctly or would not fit with the styling of the device so I would encourage thorough testing if you use this. Also fully read through[ Android Create a Custom Notification Layout](https://developer.android.com/training/notify-user/custom-notification) guide.

**Comment by jkasten2** [comment]
Closing due to missing details and inactivity
