### ISSUE TITLE
NotificationAccentColor for night mode

### ISSUE THREAD

**Issue by mukhatov** [OneSignal/OneSignal-Android-SDK#1329]
**Description:**

NotificationAccentColor is not applied for night mode. Following the documentation, you need to set the value through the manifest.
The value is a string, color format is in ARGB

Example:
`
<meta-data android:name="com.onesignal.NotificationAccentColor.DEFAULT" android:value="FF00FF00" />
`

**Environment**
OneSignal sdk version 4.3.3

**Steps to Reproduce Issue:**

**manifest**
`        <meta-data
            android:name="com.onesignal.NotificationAccentColor.DEFAULT"
            android:value="@string/notification_accent_color" />`

**values**
`
    <string name="notification_accent_color">FF000000</string>`
**values-night**
`
    <string name="notification_accent_color">FFFFFFFF</string>`

Color value for dark theme is ignored. What could be the reason?

**Comment by nan-li** [comment]
Hi @mukhatov, it seems the methods provided by android to get meta-data may not be updated for dark mode. A workaround is being developed. Thanks for your patience!

**Comment by Jeasmine** [comment]
The fix has been released under https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.4.1
