### ISSUE TITLE
Server key restriction

### ISSUE THREAD

**Issue by xsorifc28** [OneSignal/OneSignal-Android-SDK#133]
What kind of restriction should be set on the firebase/google project console server API key (configured on https://onesignal.com) ?

**Comment by jkasten2** [comment]
@xsorifc28 You should no longer user the "Google Project Console" to create keys / project numbers as it no longer creates valid ones for GCM messages.

Instead follow one of our guides below.
* Creating a new key - https://documentation.onesignal.com/docs/generate-a-google-server-api-key
* Use existing FCM - https://documentation.onesignal.com/docs/firebase-cloud-messaging-fcm

**Comment by xsorifc28** [comment]
I'm using the FCM guide. The key in this guide also shows up in the Google project console with a security warning as it is "auto generated by Google service".

Are there any restrictions to set on this server key?

For example, for Android keys, I've set my SHA1 fingerprint and package name as restrictions.
