### ISSUE TITLE
Crash Run App Ofuscated

### ISSUE THREAD

**Issue by mariofelesdossantosjunior** [OneSignal/OneSignal-Android-SDK#1336]
No class found, not setting up OSRemoteNotificationReceivedHandler
                         D  OneSignal handleActivityLifecycleHandler inForeground: true
         AndroidRuntime  E  FATAL EXCEPTION: OS_REST_SUCCESS_CALLBACK
                         E  Process: com.useblu, PID: 10345
                         E  java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implem
                            ent Configuration.Provider.
                         E      at androidx.work.impl.WorkManagerImpl.androidx.work.impl.WorkManagerImpl getInstance(android.content.Context)(WorkManagerImpl.java:158)
                         E      at androidx.work.WorkManager.androidx.work.WorkManager getInstance(android.content.Context)(WorkManager.java:184)
                         E      at com.onesignal.OSNotificationRestoreWorkManager.void beginEnqueueingWork(android.content.Context,boolean)(OSNotificationRestoreWorkManager.java:48)
                         E      at com.onesignal.OneSignal.void handleActivityLifecycleHandler(android.content.Context)(OneSignal.java:893)
                         E      at com.onesignal.OneSignal.void init(android.content.Context)(OneSignal.java:778)
                         E      at com.onesignal.OneSignal.void setAppId(java.lang.String)(OneSignal.java:681)
                         E      at com.onesignal.OneSignal.boolean reassignDelayedInitParams()(OneSignal.java:1089)
                         E      at com.onesignal.OneSignal.void onRemoteParamSet()(OneSignal.java:815)
                         E      at com.onesignal.OneSignal$5.void complete(com.onesignal.OneSignalRemoteParams$Params)(OneSignal.java:1030)
                         E      at com.onesignal.OneSignalRemoteParams.void processJson(java.lang.String,com.onesignal.OneSignalRemoteParams$Callback)(OneSignalRemoteParams.java:206)
                         E      at com.onesignal.OneSignalRemoteParams.void access$100(java.lang.String,com.onesignal.OneSignalRemoteParams$Callback)(OneSignalRemoteParams.java:12)
                         E      at com.onesignal.OneSignalRemoteParams$1.void onSuccess(java.lang.String)(OneSignalRemoteParams.java:151)
                         E      at com.onesignal.OneSignalRestClient$5.void run()(OneSignalRestClient.java:269)
                         E      at java.lang.Thread.null run(null)(Thread.java:919)
      OOMEventManagerFK  D  checkEventAndDumpForJE: 0
    MixpanelAPI.SysInfo  W  Permission READ_PHONE_STATE not granted. Property $radio will not be available.
               BpBinder  W  Slow Binder: BpBinder transact took 219 ms, interface=com.google.android.gms.measurement.internal.IMeasurementService, code=11 oneway=false
             com.useblu  I  ProcessProfilingInfo new_methods=8281 is saved saved_to_disk=1 resolve_classes_delay=8000
               BpBinder  W  Slow Binder: BpBinder transact took 417 ms, interface=android.os.storage.IStorageManager, code=35 oneway=false
             com.useblu  W  Long monitor contention with owner OS_REST_SUCCESS_CALLBACK (10623) at boolean libcore.io.Linux.access(java.lang.String, int)(Linux.java:-2) waiters=0 in java.io.File android.app.ContextImpl.getFilesDir() for 730ms
                         W  Long monitor contention with owner OS_REST_SUCCESS_CALLBACK (10623) at boolean libcore.io.Linux.access(java.lang.String, int)(Linux.java:-2) waiters=1 in java.io.File android.app.ContextImpl.getDatabasesDir() for 729ms
                         W  Long monitor contention with owner OS_REST_SUCCESS_CALLBACK (10623) at boolean libcore.io.Linux.access(java.lang.String, int)(Linux.java:-2) waiters=2 in java.io.File android.app.ContextImpl.getFilesDir() for 651ms
                         W  Long monitor contention with owner firebase-installations-executor-1 (10537) at java.io.File android.app.ContextImpl.getFilesDir()(ContextImpl.java:687) waiters=0 in void com.google.firebase.installations.FirebaseInstallations.insertOrUpdatePre
                            fs(com.google.firebase.installations.local.PersistedInstallationEntry) for 457ms

OneSignal Plugin Version [0.12.10, 0.99.99]
OneSingal dependence version [4.0.0, 4.99.99]

**Comment by jfishman1** [comment]
Thank you for following up with our Support team sharing you resolved the issue with this guide: https://developer.android.com/topic/libraries/architecture/workmanager/advanced/custom-configuration#on-demand

**Comment by jkasten2** [comment]
For others who run into this issue make sure you don't forget the 2nd part of Android customization guide if you are disabling the default `WorkManagerInitializer`.

**Kotlin:**
```Kotlin
class MyApplication() : Application(), Configuration.Provider {
     override fun getWorkManagerConfiguration() =
           Configuration.Builder()
                .setMinimumLoggingLevel(android.util.Log.INFO)
                .build()
}
```

**Java:**
```Java
class MyApplication extends Application implements Configuration.Provider {
    @Override
    public Configuration getWorkManagerConfiguration() {
        return new Configuration.Builder()
                .setMinimumLoggingLevel(android.util.Log.INFO)
                .build();
    }
}
```


Google also notes:
> Note: If you call the deprecated no-parameter WorkManager.getInstance() method before WorkManager has been initialized, the method throws an exception. You should always use the WorkManager.getInstance(Context) method, even if you're not customizing WorkManager.

I confirmed OneSignal is correctly always using `WorkManager.getInstance(Context)` so this isn't an issue:
https://github.com/OneSignal/OneSignal-Android-SDK/search?q=WorkManager&type=code
