### ISSUE TITLE
Setting onesignal_app_id at runtime?

### ISSUE THREAD

**Issue by ssaxena01** [OneSignal/OneSignal-Android-SDK#134]
I have separate onesignal apps configured for different servers - qa/dev/staging/prod. Is it possible to instantiate onesignal app id at runtime vs placing it in the build.gradle? How do I accomplish this as different servers does not translate into different build flavors. I have only 2 build flavors - release and debug.

**Comment by jkasten2** [comment]
@ssaxena01 You can use the following syntax instead to set this at runtime..
```Java
OneSignal.init(Context, googleProjectNumber, oneSignalAppId, NotificationOpenedHandler , NotificationReceivedHandler);
```

We still recommend calling this from the `onCreate` for your `Application` class for OneSignal to work correctly.
