### ISSUE TITLE
Build fails when targeting Android 12 - Explicitly declare android:exported

### ISSUE THREAD

**Issue by islam-assi** [OneSignal/OneSignal-Android-SDK#1349]
**Description:**

I'm trying to test targeting Android 12 for an app I'm working on. I just want to see what things may fail doing so. The build is failing because of not declaring the android:exported in the manifest. When I checked the merged manifest file, I found that OneSignal doesn't declare android:exported.

https://developer.android.com/about/versions/12/behavior-changes-12#exported

This is the error:

>Manifest merger failed with multiple errors, see logs 
Error:
	Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

Here are the OneSignal components that appears in the merged manifest file and seems that it needs to declare android:exported.

<img width="683" alt="Screenshot 2021-05-27 at 12 53 37" src="https://user-images.githubusercontent.com/76941763/119816925-9c13c500-beed-11eb-9255-8594214fcb52.png">

<img width="669" alt="Screenshot 2021-05-27 at 12 53 06" src="https://user-images.githubusercontent.com/76941763/119816944-a209a600-beed-11eb-8254-bc0191e2f142.png">

**Comment by jkasten2** [comment]
@islam-assi Thanks for reporting, this is fixed in PR #1362 and will be part of the next release.
