### ISSUE TITLE
Get notification's title and content as a string in android? 

### ISSUE THREAD

**Issue by EgyptianM** [OneSignal/OneSignal-Android-SDK#135]
Hi, how can I get notification's title and content as a string to store in DB in android?

**Comment by jkasten2** [comment]
@EgyptianM If you want to store the notification on the open event you can do so by calling [`setNotificationOpenedHandler`](https://documentation.onesignal.com/docs/android-native-sdk#section--setnotificationopenedhandler-). You can then get the content and title from [`OSNotificationOpenResult`](https://documentation.onesignal.com/docs/android-native-sdk#section--osnotificationopenresult-).

Or if you need to store these everytime a notification is received you can do so with a [`NotificationExtenderService`](https://documentation.onesignal.com/docs/android-native-sdk#section--notificationextenderservice-)

You can get the title and message body with the below code from either.
`result.notification.payload.title`
`result.notification.payload.body`

Thanks.

**Comment by jkasten2** [comment]
@EgyptianM Feel free to reopen this issue if you need more information on our getting these values out of OneSignal.

For help on storing values into a DB on Android I recommend posting on stackoverflow.com
