### ISSUE TITLE
IllegalArgumentException: Comparison method violates its general contract!

### ISSUE THREAD

**Issue by bobbyirawan09** [OneSignal/OneSignal-Android-SDK#1360]
**Description:**

Hi there, recently I got velocity alert of an error that the source could be from OneSignal. The information and research are purely on my observation, so please tell me if there's something wrong.

The error is as the title, `IllegalArgumentException`. After looking the stacktrace, the problem could happen because the usage of `WorkManager`, which I didn't use at all in my application and any other third party library I used except OneSignal. It could be happen because of `sort` method in `Array` or because compare in `if` method.

I also looking class that using `WorkManager` in OneSignal lib. I found two class:

1. OSNotificationRestoreWorkManager. I presume this could be the source problem.
2. OSNotificationWorkManager.

I don't exactly know if this error really because of OneSignal or not, please let me know if it's not. 

Thank you.

**Environment**

1. Using OneSignal SDK 4.4.0
2. 99% of affected device are Samsung, you can see the specific device in the attached image
3. 100% affected device OS is Android 11
4. 97% crash happens in background
5. Affecting only 15 user, and its quite consistent, from the first time error appear until now

**Steps to Reproduce Issue:**

Currently, I don't know how to reproduce it, here are some step that I had already try to reproduce the issue, using Android 11 on Note10+ device:

- App in background, send notification, there is no error in Android Studio logcat
- App had been killed, send notification, there is no error in Android Studio logcat

I think there could be some condition to met to reproduce this issue. Either after restarting the application or bluetooth on maybe.

**Anything else:**

```
Fatal Exception: java.lang.IllegalArgumentException: Comparison method violates its general contract!
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2389)
       at android.os.Parcel.createException(Parcel.java:2369)
       at android.os.Parcel.readException(Parcel.java:2352)
       at android.os.Parcel.readException(Parcel.java:2294)
       at android.app.IActivityManager$Stub$Proxy.getHistoricalProcessExitReasons(IActivityManager.java:11243)
       at android.app.ActivityManager.getHistoricalProcessExitReasons(ActivityManager.java:4231)
       at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:171)
       at androidx.work.impl.utils.ForceStopRunnable.forceStopRunnable(ForceStopRunnable.java:210)
       at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:108)
       at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

And also stack trace below, which not always happen

```
Caused by android.os.RemoteException: Remote stack trace:
	at java.util.TimSort.mergeLo(TimSort.java:777)
	at java.util.TimSort.mergeAt(TimSort.java:514)
	at java.util.TimSort.mergeCollapse(TimSort.java:441)
	at java.util.TimSort.sort(TimSort.java:245)
	at java.util.Arrays.sort(Arrays.java:1492)
```

Device, OS, and Device state info is in image below

![Screen Shot 2021-06-16 at 12 35 52](https://user-images.githubusercontent.com/21231279/122158531-6ab06880-ce9f-11eb-97f5-063efcc2ae0c.png)

**Comment by jkasten2** [comment]
@bobbyirawan09 Thanks for reporting. This looks to be an issue with the Jetpack / AndroidX WorkManager as I do not see OneSignal in the stacktrace.

Could you provide which version of WorkManager is used in your app? Run the following and look for `androidx.work:work-runtime:`
`gradlew app:dependencies --configuration releaseCompileClasspath`

From there you may want to upgrade or downgrade depending on the version shown.

**Comment by bobbyirawan09** [comment]
Hi @jkasten2,

I already check the WorkManager version, and the version is `2.7.0-alpha04`, which is not a stable version. The stable version is `2.5.0`.

Also I found in your code that the WorkManager version you guys using is in range, not in certain version, the code I mentioned is [here](https://github.com/OneSignal/OneSignal-Android-SDK/blob/260097d2eb60695be462b350e7e6251d2d6b5c17/OneSignalSDK/onesignal/build.gradle#L7). This could be a problem to in my opinion.

You mentioned that I cant upgrade or downgrade the version. I'm little bit confused on how to do it because it's not my project that using the WorkManager library, but OneSignal library that using it. Do you mind to share how to do it or an article maybe? 

Thanks.

**Comment by bobbyirawan09** [comment]
Hi @jkasten2,

I already check the WorkManager version, and the version is 2.7.0-alpha04, which is not a stable version. The stable version is 2.5.0.

Also I found in your code that the WorkManager version you guys using is in range, not in certain version, the code I mentioned is here. This could be a problem to in my opinion.

You mentioned that I cant upgrade or downgrade the version. I'm little bit confused on how to do it because it's not my project that using the WorkManager library, but OneSignal library that using it. Do you mind to share how to do it or an article maybe?

Thanks.

WorkManager version<br>
![Screen Shot 2021-06-17 at 13 51 29](https://user-images.githubusercontent.com/21231279/122339827-1d51fb00-cf74-11eb-86a5-0b77fd0d553f.png)

**Comment by jkasten2** [comment]
@bobbyirawan09 There are a few ways this version can be changed.

### Option 1 - Add androidx.work:work-runtime to your build.gradle
Adding an exact version to `app/build.gradle`.
```gradle
implementation "androidx.work:work-runtime:2.5.0"
```
This works as OneSignal depends on a version range and Gradle will resolve to this exact version since it is in the range, even if your app's code doesn't directly use it.

### Option 2 - Use Dependency Locking
This will create a `.lockfile` you can check in to source control to give you consistent builds.
Follow Gradle documenation here on setting it up:
   - https://docs.gradle.org/7.0/userguide/dependency_locking.html

Normally you don't edit the `.lockfile` but in your case you will want to edit it to lower `work-runtime` to a stable version such as [2.5.0](https://maven.google.com/web/index.html?q=work-runtim#androidx.work:work-runtime:2.5.0) .


### Future change
In order to prevent this in the future OneSignal can use version ranges that only include known minor stable versions. Example with `androidx.work:work-runtime:[2.0.0, 2.5.99]`. Allowing up to `99` as a patch version means any bug fix versions will automatically be used.

**Comment by bobbyirawan09** [comment]
Okay, I will try the first option, since its the most efficient to me.

I will let you know if the error still happen or not

Thank you for your support.

**Comment by bobbyirawan09** [comment]
Hi @jkasten2 

So I had followed your step to add work manager dependency in my project, current stable version is 2.5.0. After that I tried release app to Closed Testing and got rejected. The reason is because using implicit Pending Intent, you can see the detail in email attached.

I don't know if it's related to OneSignal or not, because in my project I'm not using PendingIntent at all, and after some searching I found that OneSignal used PendingIntent. Can you do a favor for me to check if it's related or not with OneSignal. I really appreciate it.

Thank you,
Bobby

![Screen Shot 2021-06-23 at 16 20 09](https://user-images.githubusercontent.com/21231279/123062703-59d39a00-d43f-11eb-8c0a-4a5cacf11cdd.png)

**Comment by jkasten2** [comment]
@bobbyirawan09 I did a review of all `PendingIntent` references in this repo's code base and I don't see any implicit ones. We also haven't made any recent changes to these nor have we received any other reports of this.

If you don't have any code in your app using `PendingIntent` then I recommend checking if you updated any other libraries / SDK in your app since you latest summitted successfully.

**Comment by bobbyirawan09** [comment]
thanks for the information @jkasten2, really appreciate it, I will check other libraries / SDK too
