### ISSUE TITLE
How to listen when an in-app message dismiss?

### ISSUE THREAD

**Issue by vantangst** [OneSignal/OneSignal-Android-SDK#1371]
In-app message question
How to listen when an in-app message dismiss?
I want to do some action after the user closed the in-app message. DO we have any way to reach this?

**Comment by Jeasmine** [comment]
Hey @vantangst, unfortunately, there is not a specific listener for IAM dismissal. You could implement `setInAppMessageClickHandler` and check if `doesCloseMessage` is true; If so, it will dismiss the IAM. For `doesCloseMessage` to return true, you need to add a clickable option inside your IAM and enable the `Dismiss on click ` option, which is the closest behavior to what you are trying to do.

**Comment by vantangst** [comment]
Thanks @Jeasmine for your help.
But i mean the close button from the sdk form
<img width="478" alt="image" src="https://user-images.githubusercontent.com/13620155/124060072-6d41bf00-da56-11eb-8b3e-94aefe95962e.png">
