### ISSUE TITLE
com.onesignal.GcmBroadcastReceiver ANR

### ISSUE THREAD

**Issue by allenhsu-17live** [OneSignal/OneSignal-Android-SDK#1398]
**Description:**

I got onesignal ANR Issue form google play, I can reproduce this issue on my device

```
Broadcast of Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x1000010 pkg=com.machipopo.media17 cmp=com.machipopo.media17/com.onesignal.GcmBroadcastReceiver (has extras) }
```

**Environment**

1. 3.10.x
2. maven

**Steps to Reproduce Issue:**

1. (your steps here)
2.
3.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by nan-li** [comment]
Hi @allenhsu-17live, 

Please give more information as you are able to reproduce this issue, by filling out **Steps to Reproduce Issue** and stacktraces leading up to the ANR.

**Comment by nan-li** [comment]
Closing due to no response.
