### ISSUE TITLE
 After updating to Gradle 7.0.0 unable to apply plugin 'com.onesignal.androidsdk.onesignal-gradle-plugin'

### ISSUE THREAD

**Issue by m-asadullah** [OneSignal/OneSignal-Android-SDK#1399]
**Description:**

After updating to Gradle ** 'com.android.tools.build:gradle:7.0.0'**
This below is caused, the stack trace  is here
An exception occurred applying plugin request [id: 'com.onesignal.androidsdk.onesignal-gradle-plugin']
> Failed to apply plugin 'com.onesignal.androidsdk.onesignal-gradle-plugin'.
   > Could not create plugin of type 'GradleProjectPlugin'.
      > java.lang.ExceptionInInitializerError (no error message)
(your description here)

**Environment**

Android Studio Arctic Fox | 2020.3.1
Build #AI-203.7717.56.2031.7583922, built on July 26, 2021
Runtime version: 11.0.10+0-b96-7249189 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 4
Registry: external.system.auto.import.disabled=true

**Comment by AndreasBoehm** [comment]
Hi @m-asadullah,

this issue has been fixed with version `0.13.0` of the onesignal-gradle-plugin: https://github.com/OneSignal/OneSignal-Gradle-Plugin/releases/tag/0.13.0

You can use the latest version of the plugin as well: https://github.com/OneSignal/OneSignal-Gradle-Plugin/releases/tag/0.13.4

**Comment by m-asadullah** [comment]
Thanks 💝 Sir @AndreasBoehm for suggestions to overcome that issue.
Here is screenshot of success achieved from your advice. ❣
<img src="https://i.imgur.com/ZA6vvy1.png"/>
