### ISSUE TITLE
PendingIntent error when targeting Android S (31)

### ISSUE THREAD

**Issue by axiel7** [OneSignal/OneSignal-Android-SDK#1408]
**Description:**

I'm getting the following error while integrating the OneSignal SDK on a Android project with targetSdk set to 31:
`java.lang.IllegalArgumentException: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.`

**Environment**

1. targetSdk and compileSdk set to 31
2. OneSignal SDK added using the official docs (mavenCentral)

**Steps to Reproduce Issue:**

1. Add the OneSignal SDK to a project with targetSdkVersion 31
2. Initialize OneSignal on the Application class
3. Compile and launch the app

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by AndreasBoehm** [comment]
I created a PR to fix that issue, but unfortunately we also need to wait until google releases a new version of the androidx workmanager: https://github.com/OneSignal/OneSignal-Android-SDK/pull/1400

**Comment by jkasten2** [comment]
@axiel7 Thanks for reporting, this in now fixed in the OneSignal-Android-SDK 4.5.0 release.
