### ISSUE TITLE
Control over Android Task and the Back Stack

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-Android-SDK#141]
### Current Limitations
Currently app developers limited to the following behaviors when a notification is opened.
1. Create or resume the Launcher `Activity`.
2. Only fire [NotificationOpenedHandler](https://documentation.onesignal.com/docs/android-native-sdk#section--notificationopenedhandler-) ([details](https://documentation.onesignal.com/docs/android-customizations#section-changing-the-open-action-of-a-notification)).
   - However this requires the app developer the manage the [Tasks and Back Stacks](https://developer.android.com/guide/components/tasks-and-back-stack.html) themselves.
3. [Or close the launcher `Activity`](https://documentation.onesignal.com/docs/android-customizations#section-resume-last-activity-when-opening-a-notification
) if another is started.
   - Not ideal, as it allocates extra memory and requires modification to app logic.

What is missing is a built in solution to resume the app where the user left off. Basically option 3. should be default and shouldn't require any additional changes to the app's code.

### Current Implementation
Currently OneSignal's default action when opening a notification is to open the launcher `Activity` with the following.
```Java
launchIntent.setFlags(Intent.FLAG_ACTIVITY_REORDER_TO_FRONT | Intent.FLAG_ACTIVITY_NEW_TASK);
context.startActivity(launchIntent);
```

This is done as `context` is an `Application` instance instead of an `Activity`. Android requires `startActivity` to include the `FLAG_ACTIVITY_NEW_TASK` flag if your context isn't an `Activity` type. The `Context` is not an `Activity` instance as the `GenerateNotification` class in the SDK uses `PendingIntent.getBroadcast` to create a `NotificationOpenedReceiver` instance.

### Implementation option
Due to limitations of non-Activity type Contexts in Android an invisible `Activity` should be created by using `PendingIntent.getActivity` for the notification's `setContentIntent`. The class `NotificationOpenedActivity` should be used as the `PendingIntent`. If the app's process is started from this `Intent` then the launcher will most likely need to be started before finishing the `NotificationOpenedActivity` Activity.

**Comment by samarth220194** [comment]
I think the intent which I am creating in the app to go to my 'DesiredActivity' is creating the problem.

` Intent intent = new Intent(getApplicationContext(),
                       DesiredActivity);`

This intent is being called from the Application class ,hence it is using 'getApplicationContext()' so when i backpress on the 'DesiredActivity' then my app closes ,but i want that it should go to my 'MainActivity'.

Please provide a solution for this .

**Comment by samarth220194** [comment]
I think the intent which I am creating in the app to go to my 'DesiredActivity' is creating the problem.

` Intent intent = new Intent(getApplicationContext(),
                       DesiredActivity);`

This intent is being called from the Application class ,hence it is using 'getApplicationContext()' so when i backpress on the 'DesiredActivity' then my app closes ,but i want that it should go to my 'MainActivity'.

Please provide a solution for this .

**Comment by jkasten2** [comment]
@samarth220194 I recommend using [`registerActivityLifecycleCallbacks`](https://developer.android.com/reference/android/app/Application.html#registerActivityLifecycleCallbacks(android.app.Application.ActivityLifecycleCallbacks)) so you can store the last `Activity` your app was on. *Use a [`WeakReference`](https://docs.oracle.com/javase/7/docs/api/java/lang/ref/WeakReference.html) so this doesn't create a leak though.* You can then use your last `Activity` instead of `getApplicationContext()` so you can omit the `FLAG_ACTIVITY_NEW_TASK` flag. This should put your new `DesiredActivity` at the top of the last Task the user was on when using your app.

**Comment by samarth220194** [comment]
I will try sir and get back back to you !

**Comment by samarth220194** [comment]
Sir please give some more  reference about how to do it.I am not able to get the exact logic on how to use it .

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration
