### ISSUE TITLE
Mass crashes after migration to v4.5.0: android.content.pm.PackageManager android.content.Context.getPackageManager()

### ISSUE THREAD

**Issue by AndrewTerekhine** [OneSignal/OneSignal-Android-SDK#1414]
**Description:**
We cannot reproduce it, but we have mass crash reports after migrating to v4.5.0 from v4.4.2. We also upgraded google-services and crashlytics. See the versions below.

**Environment**
Google services were upgraded too, maybe it the root cause:
dependencies classpath { com.google.gms:google-services:4.3.10 }
implementation 'com.google.firebase:firebase-crashlytics:18.2.1'
implementation 'com.onesignal:OneSignal:4.5.0'

**Stack trace:**
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'android.content.pm.PackageManager android.content.Context.getPackageManager()' on a null object reference
com.onesignal.OSUtils.packageInstalledAndEnabled (OSUtils.java:270)
com.onesignal.OSUtils.isGMSInstalledAndEnabled (OSUtils.java:283)
com.onesignal.OSUtils.supportsGooglePush (OSUtils.java:325)
com.onesignal.OSUtils.getDeviceType (OSUtils.java:344)
com.onesignal.OSReceiveReceiptController.sendReceiveReceipt (OSReceiveReceiptController.java:57)
com.onesignal.NotificationBundleProcessor.processNotification (NotificationBundleProcessor.java:202)
com.onesignal.NotificationBundleProcessor.processJobForDisplay (NotificationBundleProcessor.java:161)
com.onesignal.NotificationBundleProcessor.processJobForDisplay (NotificationBundleProcessor.java:133)
com.onesignal.OSNotificationController.processNotification (OSNotificationController.java:97)
com.onesignal.OSNotificationReceivedEvent.processNotification (OSNotificationReceivedEvent.java:95)
com.onesignal.OSNotificationReceivedEvent.access$000 (OSNotificationReceivedEvent.java:35)
com.onesignal.OSNotificationReceivedEvent$2.run (OSNotificationReceivedEvent.java:84)
java.lang.Thread.run (Thread.java:919)

**Workaround:**
As a workaround, we are trying to roll back to v4.4.2 and google-services to 4.3.8 and crashlytics to 18.2.0. That combination used to work fine. We hope you can fix v4.5.0 soon.

**Comment by emawby** [comment]
@AndrewTerekhine Thank you for reporting we are investigating.

**Comment by emawby** [comment]
@AndrewTerekhine Do you have any additional information about the crashes for example:

- Device types (in particular are Huawei devices crashing?)
- Android Versions
- device state when crashing

**Comment by AndrewTerekhine** [comment]
@emawby Yes I have, here you are (it seems to be all the OS/devices and in background state):
OS:

Android versions affected by this crash
Android 10 (SDK 29)
38.6%
Android 9 (SDK 28)
34.7%
Android 11 (SDK 30)
8.2%
Android 8.1 (SDK 27)
8.0%
Android 7.0 (SDK 24)
4.9%
Android 6.0 (SDK 23)
2.4%
Android 8.0 (SDK 26)
1.9%
Android 7.1 (SDK 25)
1.1%
Android 5.1 (SDK 22)
0.2%
Android 5.0 (SDK 21)
0.01%
Android 4.4 (SDK 19)
0.01%

Devices:

Acer Liquid S1
7.9%
1,024 MB (965 MB)
Mediatek MT6589

Samsung Galaxy A10s
4.4%
1,792 MB (1,785 MB)
Mediatek MT6762

Motorola moto e6 play
3.7%
2,048 MB (1,862 MB)
Mediatek MT6739WW

Samsung Galaxy A10e
3.6%
1,792 MB (1,676 MB)
Samsung Exynos 7884B

Samsung Galaxy J4+
3.0%
2,048 MB (1,819 MB)
Qualcomm MSM8917

Motorola moto e5 play
2.4%
1,024 MB (863 MB)
Qualcomm MSM8917

LGE K22
2.3%
2,048 MB (1,883 MB)
Qualcomm QM215

Motorola Moto G Turbo Edition
2.1%
2,048 MB (1,914 MB)
Qualcomm MSM8939

Samsung Galaxy A50
2.0%
5,632 MB (1,536 MB)
Samsung Exynos 9610

Samsung Galaxy A51
1.9%
3,584 MB (3,570 MB)
Samsung Exynos 9611

Samsung Galaxy A11
1.9%
2,048 MB (1,810 MB)
Qualcomm SDM450

Samsung Galaxy A01
1.7%
2,048 MB (1,836 MB)
Qualcomm SDM439

Motorola moto e6s
1.6%
3,840 MB (1,805 MB)
Mediatek MT6762

Samsung Galaxy J4
1.2%
2,048 MB (1,836 MB)
Samsung Exynos 7570

Motorola motorola one action
1.2%
3,840 MB (3,727 MB)
Samsung Exynos 9609

Xiaomi Mi A2 Lite
1.2%
3,584 MB (2,826 MB)
Qualcomm MSM8953

Redmi Note 9
1.1%
3,840 MB (2,746 MB)
Mediatek MT6769

Redmi 9
1.1%
3,840 MB (3,735 MB)
Mediatek MT6769T

Samsung Galaxy J6+
1.1%
3,072 MB (2,820 MB)
Qualcomm MSM8917

Motorola motorola one macro
1.1%
3,840 MB (1,803 MB)
Mediatek MT6771

Motorola moto g(7) play
1.0%
2,048 MB (1,831 MB)
Qualcomm SDM632

Samsung Galaxy J4 Core
0.9%
1,024 MB (858 MB)
Qualcomm MSM8917

Motorola motorola one fusion
0.9%
3,840 MB (3,708 MB)
Qualcomm SDM710

Samsung Galaxy J5 Pro
0.9%
2,048 MB (1,816 MB)
Samsung Exynos 7870

Samsung Galaxy A20s
0.9%
3,584 MB (2,790 MB)
Qualcomm SDM450

Motorola moto g(6)
0.9%
3,072 MB (2,855 MB)
Qualcomm SDM450

Samsung Galaxy A31
0.9%
3,840 MB (3,666 MB)
Mediatek MT6768

Samsung Galaxy J6
0.9%
2,816 MB (1,805 MB)
Samsung Exynos 7870

Motorola one
0.8%
3,584 MB (2,821 MB)
Qualcomm MSM8953

LGE LM-X120
0.8%
1,024 MB (887 MB)
Mediatek MT6739WW

===================
And MANY MANY others
===================

Device state when crashing:
99% in background

**Comment by nan-li** [comment]
Hi @AndrewTerekhine, a patch was released in version 4.5.1.
Thanks again for reporting!
~ Nan
