### ISSUE TITLE
Crash app but true setup

### ISSUE THREAD

**Issue by NhatLam** [OneSignal/OneSignal-Android-SDK#1415]
![236600079_2985625915040489_4880063171741113152_n](https://user-images.githubusercontent.com/31428056/129697714-5be58db7-ea57-4cbd-8334-1e692fb07b68.jpg)
I setup in Application. The first time open app. App crash. Please help em

**Comment by jkasten2** [comment]
@NhatLam Could you let us know the version of the `androidx.work:work-runtime` in your project? You can run `./gradlew app:dependencies` from the terminal to find this version.

It looks like from your screenshot this crashes on an Android 10, MI 8 device. Have you tested on any other devices or emulators to see if you still have the issue?

**Comment by NhatLam** [comment]
> @NhatLam Could you let us know the version of the `androidx.work:work-runtime` in your project? You can run `./gradlew app:dependencies` from the terminal to find this version.
> 
> It looks like from your screenshot this crashes on an Android 10, MI 8 device. Have you tested on any other devices or emulators to see if you still have the issue?
i use androidx.work:work-runtime= "2.4.0"
I only have xiaomi mi 8
