### ISSUE TITLE
NPE calling `OneSignal.getDeviceState()?.userId`

### ISSUE THREAD

**Issue by JurajKuliska** [OneSignal/OneSignal-Android-SDK#1428]
**Description:**
Hello,
A crash appeared in my crash reporting system that is happening even for the same user pretty regularly. It's a `NullPointerException` that is thrown after calling `OneSignal.getDeviceState()?.userId` (stacktrace attached below)

I'm sure I'm calling this after OneSignal is fully initialized (`OneSignal.initWithContext()` and `OneSignal.setAppId()` have been called)

The crash appears to be impacting Samsung phones only (listed below) and they all have the functionality of dual SIM (not necessarily related to the crash but might be)

**Environment**
1. Android SDK v4.4.2
2. Added to the project using maven

**Steps to Reproduce Issue:**
I have this crash report from a crash reporting tool and couldn't reproduce it myself as I don't own a Samsung device.
However the crash appears to always happen on the app start while the OneSignal is being initialized (the app never runs more than 1 second before crashing)

Another observation is that all of the crashes are happening on Samsung devices with **Dual SIM**
and given the fact that the crash actually happens after calling the code on line [OneSignalStateSynchronizer#170](https://github.com/OneSignal/OneSignal-Android-SDK/blob/740b39cc506ef8b5cbacbb36ddd987cd5f573978/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignalStateSynchronizer.java#L170) that reads:
```kotlin
getPushStateSynchronizer().setSMSNumber(smsNumber, smsAuthHash);
```
it very well might have something to do with that fact.

The reported devices that the crash appeared on:
- samsung SM-J530F
- samsung SM-G781B
- samsung SM-G973F
- samsung SM-G975F

**Anything else:**

Crash stacktrace (the relevant part of it) after calling `OneSignalManager.getUserId`
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean g.k.ka.e0()' on a null object reference  at 
com.onesignal.OneSignalStateSynchronizer.getUserSubscribePreference(OneSignalStateSynchronizer.java:170)  at 
com.onesignal.OSSubscriptionState.<init>(OSSubscriptionState.java:60)  at 
com.onesignal.OneSignal.getCurrentSubscriptionState(OneSignal.java:499)  at 
com.onesignal.OneSignal.getDeviceState(OneSignal.java:609)  at 
this gets called from OneSignal.getDeviceState()?.userId
```

**Comment by Yerlan1Fit** [comment]
any updates regarding to this issue?

**Comment by santiago-parodi** [comment]
I have the same issue, any updates?

**Comment by jennantilla** [comment]
Hello everyone! This issue will be closed as it has gone stale. 

We have a new major release for Android which has many improvements and enhancements! Among its new features is a new getter for OneSignal and External Ids which should address this issue.

We highly recommend upgrading to 5.x.x. Please refer to our [migration guide](https://github.com/OneSignal/OneSignal-Android-SDK/blob/main/MIGRATION_GUIDE.md) for more details!
