### ISSUE TITLE
NotificationServiceExtension implement OneSignal.OSRemoteNotificationReceivedHandler not working in Huawei

### ISSUE THREAD

**Issue by rizkyalfauji11** [OneSignal/OneSignal-Android-SDK#1434]
NotificationServiceExtension which implement OneSignal.OSRemoteNotificationReceivedHandler not working in Huawei Devices. I have already tested in other devices like Asus, Pixel, Xiaomi, and others but the class is not called in Huawei Devices. Please help!

**Comment by nan-li** [comment]
Hi @rizkyalfauji11,

I apologize for not getting you a reply earlier. Unfortunately the `NotificationServiceExtension` implementing `OSRemoteNotificationReceivedHandler` for OneSignal-Android-SDK v4.x.x does not work on Huawei.

For Huawei, follow [this Service Extension Guide](https://documentation.onesignal.com/v7.0/docs/service-extensions#android-notification-service-extension).
