### ISSUE TITLE
Huawei pushes without icons

### ISSUE THREAD

**Issue by d-aleksandrov** [OneSignal/OneSignal-Android-SDK#1439]
**Description:**
HMS core pushes did not any reacts for push icons.
Push icons always show app icon in description (not default push icon)
I do not have any reaction with interceptor and push description

**Environment**
- Android SDK 31
- HMS Push 6.1.0.300
- AGConnect 1.6.0.300
- Onesignal 4.6.0

**Steps to Reproduce Issue:**
  1. Add the OneSignal SDK to your project
  2. Integrade HMS Push kit with onesignal
  3. Send any push
  4. Push show with app logo, not default or custom push icon
  5. All works correct in google service integration

**Anything else:**
New HMS version is required, because it supported android target sdk31. I can't downgrade libraries version yo previous target sdk.

**Comment by jkasten2** [comment]
@d-aleksandrov Could you let us know the exact device model and Android version it is running that is not showing your icon correctly? Please also include a screenshot of the notification as well.

> New HMS version is required, because it supported android target sdk31.

Could you let us know if this is causing a build error? If so could you provide the full error message or more details on the this issue.

**Comment by jkasten2** [comment]
@d-aleksandrov Thanks for the details, we haven't confirmed that this version of Magic UI / EMUI works with the icon your are describing. Can you please include a screenshot if the notification highlight the icon issue so we can ensure we are looking the same issue?

Do these two devices have Google Services on them or only HMS on them?

If it is HMS does sending a "data" type notification vs a "message" type make a difference?
This can be set with `huawei_msg_type` on the OneSignal REST API or on the OneSignal dashboard when sending a notification.
https://documentation.onesignal.com/reference/create-notification#attachments

**Comment by d-aleksandrov** [comment]
I just send notification from web form in the onesignal site, and see this result.
Sorry, i cant send the picture of push - NDA.
But, it's very similar push - only title, text and push icon (not large)
All's great in google devices, but on huawei i jus see app logo instead icon

**Comment by jkasten2** [comment]
@d-aleksandrov If you could still provide a screenshot blacking out the information you can't share this would be helpful to us. We will look into getting a device with MagicUI 3 so we can look into reproducing the issue as well. However any other information you can provide will help us find and fix the issue faster.

**Comment by nan-li** [comment]
Hi @d-aleksandrov, I am checking in on this issue to see where you are now. 

Is this still a problem for you on your device?

**Comment by nan-li** [comment]
Closing due to no response. Since this is a visual issue, we would need the images.
