### ISSUE TITLE
sdk shows popup notification in case of timeout

### ISSUE THREAD

**Issue by namdroid** [OneSignal/OneSignal-Android-SDK#144]
how can i prevent that ?
thanks

**Comment by jkasten2** [comment]
@namdroid Make sure you don't have `setLogLevel` any where in your code.

Please attach a screenshot if you are still seeing an issue.

**Comment by jkasten2** [comment]
@namdroid We haven't had any other reports of this. Feel free to reopen this issue if my last comment didn't help.
