### ISSUE TITLE
ANR com.onesignal.OSBackgroundSync.scheduleSyncServiceAsJob

### ISSUE THREAD

**Issue by raghav2945** [OneSignal/OneSignal-Android-SDK#1441]
**Description:**

In our application, we've noticed an increase in ANR for your component. It has recently increased in ANR number. We are presently using version 4.6.0, which has been upgraded.

**Environment**

Android Version: Multiple (7/8/10/11)

**Steps to Reproduce Issue:**
1. Inability to reproduce a certain phase due to a lack of specifics. Information collected via app monitoring tools Embrace.

**Stacktraces**

`android.os.BinderProxy.transactNative
android.os.BinderProxy.transact
android.app.job.IJobScheduler$Stub$Proxy.schedule
android.app.JobSchedulerImpl.schedule
com.onesignal.OSBackgroundSync.scheduleSyncServiceAsJob
com.onesignal.OSBackgroundSync.scheduleBackgroundSyncTask
com.onesignal.OSFocusDelaySync.scheduleSyncTask
com.onesignal.ActivityLifecycleHandler.handleLostFocus
com.onesignal.ActivityLifecycleHandler.onActivityPaused
com.onesignal.ActivityLifecycleListener.onActivityPaused
android.app.Application.dispatchActivityPaused
android.app.Activity.dispatchActivityPaused
android.app.Activity.onPause
androidx.fragment.app.FragmentActivity.onPause
com.audiomack.activities.BaseActivity.onPause
com.audiomack.ui.home.HomeActivity.onPause
android.app.Activity.performPause
android.app.Instrumentation.callActivityOnPause
android.app.ActivityThread.performPauseActivityIfNeeded
android.app.ActivityThread.performPauseActivity
android.app.ActivityThread.handlePauseActivity
android.app.servertransaction.PauseActivityItem.execute
android.app.servertransaction.TransactionExecutor.executeLifecycleState
android.app.servertransaction.TransactionExecutor.execute
android.app.ActivityThread$H.handleMessage
android.os.Handler.dispatchMessage
android.os.Looper.loop
android.app.ActivityThread.main
java.lang.reflect.Method.invoke
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run
com.android.internal.os.ZygoteInit.main
`

**Comment by jkasten2** [comment]
@raghav2945 Thanks for reporting this issue, this is the same stracktrace as issue #1315. Please follow this issue for updates.
