### ISSUE TITLE
Unresolved reference: startInit() After upgrading to SDK 4.+.+

### ISSUE THREAD

**Issue by faisalmohd83** [OneSignal/OneSignal-Android-SDK#1451]
**Description:**
After upgrading to 4.6.0 (event tried with [4.0.0, 4.99.99]) option, init() API is not recognizing.
Shows `Unresolved reference: startInit` as an error and unable to proceed with the build.

**Environment**
1. Android SDK:  [4.0.0, 4.99.99]
2. How did you add the SDK to your project: MavenCentral

**More in detial**

One-signal integrated as below:

In project-level build.gradle:

`        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.10, 0.99.99]'
`

In app/build.gradle:

```
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
  
implementation 'com.onesignal:OneSignal:[4.0.0, 4.99.99]'
```

It seems many APIs changed in the new release, Is there any release/upgrade notes to refer to?

Cheers!

**Comment by nan-li** [comment]
Hi @faisalmohd83,
If you're upgrading from `3.x.x` to `4.x.x`, there are many changes. Start with the [upgrade guide here](https://documentation.onesignal.com/docs/step-by-step-android-native-3x-to-400-upgrade-guide#step-3---update-initialization-code).
