### ISSUE TITLE
oneSignal is not working with android  studio new version

### ISSUE THREAD

**Issue by ruchit1999** [OneSignal/OneSignal-Android-SDK#1458]
**Description:**
oneSignal is not working with android  studio new version
  classpath 'com.android.tools.build:gradle:4.1.3'
 

**Environment**

1. android studio 2020.3.1 patch 2
2. add SDK from documentation

**Comment by jkasten2** [comment]
@ruchit1999 Thanks for reporting but we will need more information to help. Could you let know the following?
1. The OneSignal SDK version
2. The exact error you are getting in Android Studio or on the device
3. Your root `buildle.gradle` and your `app/build.gradle`

**Comment by nan-li** [comment]
@ruchit1999, Closing due to no response, we can re-open when details are provided.
