### ISSUE TITLE
createSummaryNotification crash on Android 11 

### ISSUE THREAD

**Issue by fetra06** [OneSignal/OneSignal-Android-SDK#1460]
I'm using OneSignal:4.6.0 and I have this crash on Android 11:

```java
com.onesignal.GenerateNotification.createSummaryNotification (GenerateNotification.java:532)


Fatal Exception: java.lang.IllegalStateException
Couldn't read row 493, col 2 from CursorWindow. Make sure the Cursor is initialized correctly before accessing data from it
```

**Comment by fetra06** [comment]
unfortunately I can't reproduce it . I just get crashlytics reports that is error on this line :
com.onesignal.GenerateNotification.createSummaryNotification (GenerateNotification.java:532)

devices : motorola, vivo and realme

**Comment by nan-li** [comment]
Hi @fetra06,

Can you provide more details about the number of crashes and percentage of users affected? This will give context to the rarity and reproducibility of the crash. 

Also, confirming that all of the crashing devices are on Android 11?

**Comment by nan-li** [comment]
Closing due to no response, and no other reports of this issue.

We can re-open if we get more information.
