### ISSUE TITLE
The player id always change after uninstall and reinstall the app

### ISSUE THREAD

**Issue by CeccoCQ** [OneSignal/OneSignal-Android-SDK#1466]
For OneSignal 4.x, I've a lot of users into dashboard.
A user for every uninstallation and reinstallation of app, seems that the player id always change. 

I've followed step-by-step the guide, without success.

**Comment by anis-applocum** [comment]
I'm getting opposite output.
Player id doesn't change when I reinstall app.
Version 'com.onesignal:OneSignal:3.13.0'

**Comment by jkasten2** [comment]
@anis-applocum That is indented behavior for the 3.x.x, if the device isn't opted out of the Google Ad Id. In 4.0.0 the OneSignal SDK no longer uses it.

**Comment by manuel-plavsic** [comment]
> I'm getting opposite output. Player id doesn't change when I reinstall app. Version 'com.onesignal:OneSignal:3.13.0'

Some of our users are experiencing this issue with the Flutter SDK v3.2.8, which — according to the release notes — uses the Android SDK v4.7.0. However, we cannot reproduce this output. Is it possible that the advertising ID is still used in certain edge cases?
