### ISSUE TITLE
OneSignal field collapse_id client side handling

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-Android-SDK#147]
Currently OneSignal's `collapse_id` REST API field sets GCM's `collapse_key` which replaces notifications not received by the device yet. However the SDK doesn't handle this yet to replace existing already displayed notifications in the notification shade with the new content.

#### Alternative Feature
You can instead set Group Key on the dashboard or `android_group` on the REST API. This stack notifications together with the same key. See [Notification Stacking](https://documentation.onesignal.com/docs/android-customizations#section-notification-stacking) for an example.

#### Workaround
In the meantime it is possible to set `androidNotificationId` on `OverrideSettings` when following step 3 of the [Background Data and Notification Overriding](https://documentation.onesignal.com/docs/android-customizations#section-background-data-and-notification-overriding) guide.

**Comment by josinaldobarbosa** [comment]
+1

**Comment by nickmarx12345678** [comment]
+1

**Comment by mroushdy** [comment]
+1

**Comment by jkasten2** [comment]
Implementation considerations.
1. Notification stacking / groups.
2. Notification restoring logic.
3. Badge count logic.
4. Add equivalent cancel by tag / collapse_key in addition to current integer version.

**Comment by erikswed** [comment]
Do you mean that if I set the same 
androidNotificationId when setting "overrideSettings.androidNotificationId=someInteger" that that will make the collapsing happen - all Notifications with same androidNotificationId will collaps on each other

**Comment by jkasten2** [comment]
@erikswed Correct, however this won't work with stacking / grouped notifications and may cause badge counts to be higher. We will make sure these aren't issues when we implement this.

**Comment by jkasten2** [comment]
@josinaldobarbosa @nickmarx12345678 @mroushdy @erikswed This has been implemented in commit 4faa7ba5368791e3df0fb608fe4e6ca8fef493ce and will be included in the 3.4.4 release.

**Comment by 78lab** [comment]
Please update cordova SDK for this ASAP.
