### ISSUE TITLE
android.database.sqlite.SQLiteCantOpenDatabaseException

### ISSUE THREAD

**Issue by poojakaluskar** [OneSignal/OneSignal-Android-SDK#1471]
**Description:**

We are getting the crash reports on New Relic. 

**Environment**

1. classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.9, 0.99.99]'
2. implementation 'com.onesignal:OneSignal:[4.0.0, 4.99.99]

**Steps to Reproduce Issue:**

I am not able to reproduce this on my end.

**Anything else:**

![Screen Shot 2021-10-27 at 11 32 13 AM](https://user-images.githubusercontent.com/12078962/139108828-26d6a685-a3b4-451f-bd90-2ac1a36a099e.png)

![Screen Shot 2021-10-27 at 11 32 00 AM](https://user-images.githubusercontent.com/12078962/139108835-6c123d29-bc83-4e4e-8a10-9dc55c5b6052.png)

**Comment by jingmaolin** [comment]
I also have this problem, is there any new progress?

**Comment by nan-li** [comment]
Hi @poojakaluskar and @jingmaolin,
Thanks for reporting the issue. 
1. Could let us know the Android versions and device models you are seeing the crash on? 
2. Also could you let us know the percentage of users affected by this crash.
3. @jingmaolin Can you reproduce this crash?

**Comment by nan-li** [comment]
These two stack traces have been reported in https://github.com/OneSignal/OneSignal-Android-SDK/issues/1432, closing this in favor of that one. Please see the related issue for updates.
