### ISSUE TITLE
Example not working for android 12

### ISSUE THREAD

**Issue by FVivolo** [OneSignal/OneSignal-Android-SDK#1483]
**Description:**
the example is based on an old API that is not accepted anymore in google.

how can you post this is an updated example if this doesn't follow the google policies

https://developer.android.com/distribute/best-practices/develop/target-sdk

Thanks for updating this.

**Comment by justanapp** [comment]
a working update regarding android 12 targeting huawei would be really appreciated! thanks!

**Comment by jkasten2** [comment]
Thanks for reporting, we have updated the example project's `targetSdkVersion` to 31 to follow Google's recommendations to target the latest version. 
We have also confirmed the example is able to received notifications on Huawei devices without Google Services
