### ISSUE TITLE
Unable to start service Intent act=com.google.firebase.MESSAGING_EVENT

### ISSUE THREAD

**Issue by rostopira** [OneSignal/OneSignal-Android-SDK#149]
First of all, quote [from Google Developers](https://developers.google.com/cloud-messaging/)

> Firebase Cloud Messaging (FCM) is the new version of GCM. It inherits the reliable and scalable GCM infrastructure, plus new features! See the FAQ to learn more. If you are integrating messaging in a new app, start with FCM. GCM users are strongly recommended to upgrade to FCM, in order to benefit from new FCM features today and in the future.

Now my issue. Everything works for few hours, and then suddenly stops. Notifications aren't shown and in logcat I see following:

```
11-29 15:51:35.348 16383-16383/? E/FirebaseInstanceId: Failed to resolve target intent service, skipping classname enforcement
11-29 15:51:35.348 3672-5620/? W/ActivityManager: Unable to start service Intent { act=com.google.firebase.MESSAGING_EVENT pkg=com.MY.APP.ID (has extras) } U=0: not found
11-29 15:51:35.353 16383-16383/? E/FirebaseInstanceId: Error while delivering the message: ServiceIntent not found.
```

I've tried to add `compile 'com.google.firebase:firebase-messaging:10.0.1'` to build.gradle, but that doesn't help.

I think issue is in using GCM, migration to FCM should help.

**Comment by rostopira** [comment]
I have experience with both GCM and FCM, and also migration experience. I could update SDK to FCM in few days, is contributing welcome?

**Comment by jkasten2** [comment]
@rostopira Thanks for looking into this. Can you share your project where you are reproducing this issue?

I haven't started work on updating our SDK to use the FCM library yet. We need to ensure that our SDK will work with either library (GCM or FCM) during this transition period. This will give time to for native developers to update their gradle projects. This repo is shared with all our other SDKs, some of which can't use FCM yet so this SDK will need to fallback to GCM if FCM isn't present in the app.

**Comment by rostopira** [comment]
No, I can't, it's private. The only things, that I did, was adding IdsAvailableHandler and extending  NotificationExtenderService.
Anyway, I just extended FirebaseMessagingService instead and it seems to work ok (I need only data payload), so issue can be closed

**Comment by jkasten2** [comment]
@rostopira That is odd, the only cause of something like this I have run into is if you are using 2 different Google Project numbers in your app. When your register a different Google Project number the token created from the old project number will become invalid shortly after.

**Comment by jkasten2** [comment]
@rostopira If you can reproduce this issue on a new project we can try it out on our test devices to dig into the issue further.
