### ISSUE TITLE
Onesignal console issue with HMS

### ISSUE THREAD

**Issue by ToleubekRauan** [OneSignal/OneSignal-Android-SDK#1496]
**Description:**

From Onesignal console message sent to HMS device with type "message", but is not received.
If change type to "data", push message is received, it prints to logcat

**Environment**

Specs:
compileSdkVersion 31
targetSdkVersion 31
'com.onesignal:OneSignal:4.6.3'
'com.huawei.hms:push:6.1.0.300'

**Steps to Reproduce Issue:**

  
I think it's more Onesignal console issue

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by jkasten2** [comment]
@ToleubekRauan Thanks for reporting, by "not received" do you mean it is not displayed on the device or the [`setNotificationWillShowInForegroundHandler`](https://documentation.onesignal.com/docs/sdk-notification-event-handlers#foreground-notification-received-event) or [`
Android Notification Service Extension`](https://documentation.onesignal.com/docs/service-extensions#android-notification-service-extension) is not firing for you?

The HMS message type is directly handle by "HMS Core", it displays it and the app can't get an event for this. Only a "data" type message allows you to handle in your app's code.

**Comment by ToleubekRauan** [comment]
@jkasten2
I listen messages in onMessageReceived provided by HmsMessageService

**Comment by jkasten2** [comment]
@ToleubekRauan I see, that only works for HMS "data" message type.

**Comment by ToleubekRauan** [comment]
@jkasten2 Btw, from Appgallery connect console i able to send message type push notifications

**Comment by jkasten2** [comment]
@ToleubekRauan OneSignal allows you send both types as well. Are you saying the "message" type does trigger `onMessageReceived` when you send from Appgallery connect console?

**Comment by ToleubekRauan** [comment]
@jkasten2 No, but it shows push in notification center

**Comment by jkasten2** [comment]
@ToleubekRauan Are you getting any errors when you check your delivered message on the OneSignal dashboard? Or is it being reported as successful?

**Comment by ToleubekRauan** [comment]
@jkasten2 messages are reported as successful

**Comment by KKChong** [comment]
Hi @jkasten2, I'm having the same issue. Can you check from the logcat, are the values of hms.sent_time and hms.ttl = 0 as below? 

rawPayload='{"custom":"{"i":"a39d821c-19d9-47cf-9269-721975e8739e","a":{"foo":"bar"}}","alert":"English Message","title":"English Title","**hms.sent_time":"0","hms.ttl":"0"**}

I suspect the onesignal library are not handle probably due to the ttl & sent_time are 0, and causing the code run into else case (line 95. OSNotificationController.class)
![image](https://user-images.githubusercontent.com/2024607/145825181-018a1d53-e334-4628-bee8-75b1855fa01d.png)

**Comment by jkasten2** [comment]
@KKChong @ToleubekRauan  Thanks for all the detail here. This is now fixed in version 4.7.0:
https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.7.0
