### ISSUE TITLE
Missing shrinkResources setting

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-Android-SDK#150]
When `shrinkResources` is enabled default notification icons and sounds are removed from the APK. 
* `ic_stat_onesignal_default`
* `ic_onesignal_large_icon_default`
* `onesignal_default_sound`

Look into adding a `res/raw/keep.xml` to this SDK's aar package to see if it will prevent the app's level `shrinkResources` from removing the resources above.
https://developer.android.com/studio/build/shrink-code.html#keep-resources

**Comment by jkasten2** [comment]
Only an issue when strict mode is enabled. Added exception file for OneSignal when this mode is enabled.
be37c4d2502a69986a94de121aabb4cad87cf4f9

**Comment by josinaldobarbosa** [comment]
Please put this in the documentation, I spent days to find out why my notification was crashing into production :(

**Comment by jkasten2** [comment]
@josinaldobarbosa The commit above should force keep those files even when `tools:shrinkMode="strict"` is enabled now. Could you list the full exception you seeing and the project settings that apply to this?

**Comment by josinaldobarbosa** [comment]
My problem was that he did not find the icons via api example:

"small_icon": "ic_arrows",
"large_icon": "ic_notification",

The icon that was crashing is a vector:

```
Fatal Exception: android.app.RemoteServiceException: Bad notification posted from package com.mypackage: Couldn't create icon: StatusBarIcon(icon=Icon(typ=RESOURCE pkg=com.mypackage id=0x7f020077) visible user=0 )
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1686)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:241)
       at android.app.ActivityThread.main(ActivityThread.java:6217)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```
The other that is not a vector it just did not display

Because in production shrinkResources was enabled, I did the same thing you used in the lib for my project and it worked.

**Comment by jkasten2** [comment]
@josinaldobarbosa Are you using `compile 'com.onesignal:OneSignal:[3.5.3,4.0.0)'` to import our SDK or are you using our `.jar` directly?

**Comment by josinaldobarbosa** [comment]
compile 'com.onesignal:OneSignal:3.4.4'

**Comment by jkasten2** [comment]
@josinaldobarbosa I overlooked your previous comment, since your icons aren't one of the default names I listed in the first post they won't be force kept by our SDK. The Google documentation for `shrinkResources` covers it's behavior well for resources not directly used so we don't plan to add this to our docs.

Thanks.
