### ISSUE TITLE
com.onesignal.GcmBroadcastReceiver: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present'

### ISSUE THREAD

**Issue by hamza-ahmed** [OneSignal/OneSignal-Android-SDK#1504]
**Description:**

(your description here)

**Environment**

**Steps to Reproduce Issue:**

1. (your steps here)
2.
3.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by ankitmwebvillee** [comment]
@hamza-ahmed Use Library version(4.6.3) com.onesignal:OneSignal:4.6.3

**Comment by jkasten2** [comment]
@hamza-ahmed You need to use [OneSignal-Android-SDK 4.6.2](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.6.2) or newer if you target Android API 31 (Android 12) to avoid this runtime crash.

**Comment by hamza-ahmed** [comment]
> @hamza-ahmed You need to use [OneSignal-Android-SDK 4.6.2](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.6.2) or newer if you target Android API 31 (Android 12) to avoid this runtime crash.

Thanks its work

**Comment by luis95gr** [comment]
> > @hamza-ahmed You need to use [OneSignal-Android-SDK 4.6.2](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.6.2) or newer if you target Android API 31 (Android 12) to avoid this runtime crash.
> 
> Thanks its work

Hi, how do you update the sdk to 4.6.2 in xamarin?

**Comment by jkasten2** [comment]
@luis95gr You can use the [OneSignal-Xamarin-SDK 4.0.0-beta1 release](https://github.com/OneSignal/OneSignal-Xamarin-SDK/releases/tag/4.0.0-beta1) to get this version of the OneSignal SDK. Or you can continue to target Android API 30 as a fallback for the short term.

**Comment by luis95gr** [comment]
> @luis95gr You can use the [OneSignal-Xamarin-SDK 4.0.0-beta1 release](https://github.com/OneSignal/OneSignal-Xamarin-SDK/releases/tag/4.0.0-beta1) to get this version of the OneSignal SDK. Or you can continue to target Android API 30 as a fallback for the short term.

Thank you, I will continue targeting API 30 until One-Signal 4.0.0 is released

**Comment by EmilAlipiev** [comment]
> @luis95gr You can use the [OneSignal-Xamarin-SDK 4.0.0-beta1 release](https://github.com/OneSignal/OneSignal-Xamarin-SDK/releases/tag/4.0.0-beta1) to get this version of the OneSignal SDK. Or you can continue to target Android API 30 as a fallback for the short term.

or you can remove Onesignal and permanent solution. publishing a beta1 as crashing version is a nogo.

**Comment by Poker26-8** [comment]
Gravedad	Código	Descripción	Proyecto	Archivo	Línea	Estado suprimido
Error		android:exported needs to be explicitly specified for element <receiver#com.onesignal.GcmBroadcastReceiver>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.	TELEMETRIA.Android	C:\6\XAMARIN\Nueva carpeta\TELEMETRIA\TELEMETRIA\TELEMETRIA\TELEMETRIA.Android\obj\Debug\130\AndroidManifest.xml	19	


alguien sabe como solucionar ese problema al compilarlo en un teléfono real
