### ISSUE TITLE
Could not find OneSignal-4.6.4.aar 

### ISSUE THREAD

**Issue by Muhammadwahab** [OneSignal/OneSignal-Android-SDK#1510]
Hi i unable to build the app in android due to to below issue it was working fine before suddenly this issue occurred . Might be you guys working on current SDK please let me know when will this fixed 

i am using these dependencies in gradle

    val one_signal = "com.onesignal:OneSignal:${Versions.oneSignalVersion}"
    val oneSignalRoot = "gradle.plugin.com.onesignal:onesignal-gradle-plugin:${Versions.oneSignalRootVersion}"

    const val oneSignalVersion = "[4.0.0, 4.99.99]"
    const val oneSignalRootVersion = "[0.12.9, 0.99.99]"
    
        implementation (Dependencies.one_signal) {
        exclude group: 'com.google.android.gms', module: 'play-services-location'
        exclude group: 'com.google.android.gms', module: 'play-services-ads-identifier'
        exclude group: 'com.google.guava', module: 'jetified-guava'
    }

> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform OneSignal-4.6.4.aar (com.onesignal:OneSignal:4.6.4) to match attributes {artifactType=android-java-res, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not find OneSignal-4.6.4.aar (com.onesignal:OneSignal:4.6.4).
        Searched in the following locations:
            https://jcenter.bintray.com/com/onesignal/OneSignal/4.6.4/OneSignal-4.6.4.aar

**Comment by shahabrauf18** [comment]
Please check here.

https://github.com/OneSignal/OneSignal-Android-SDK/issues/1509#issuecomment-1010771567

**Comment by jkasten2** [comment]
Same as issue #1509.

The jcenter specific URL error can be solved by following https://github.com/OneSignal/OneSignal-Android-SDK/issues/1509#issuecomment-1010771567 as @shahabrauf18 pointed out.
