### ISSUE TITLE
Old notifications are restored with app launch, no way to detect the restoring state like 3.x.x

### ISSUE THREAD

**Issue by bluemix** [OneSignal/OneSignal-Android-SDK#1518]
**Description:**

I've implemented the background service extension, 
to do some background stuff for notifications.
However, when notifications are received (completed) and displayed to the user, and
everything is OK, but, whenever the user closes the app and run the app 
again, the same notifications are restored!

The OneSignal [Android doc](https://documentation.onesignal.com/docs/service-extensions#getting-a-payload-from-a-notification) says there is a `restoring` flag for the received notifications, 
but it didn't exist!

**Environment**

1. Androiod SDK 31
2. Maven
3. OneSignal v4.6.5

**Steps to Reproduce Issue:**

1. Background process the notification and mark it as completed
2. Wait for 2 minutes and close the app
3. The same notification is restored

**Comment by jkasten2** [comment]
@bluemix Thanks for reporting, we will look into provide a way to detect or preventing the need to filter on this in the future. In the mean time I recommend tracking the notification id in your app so you don't process the data more than once.
