### ISSUE TITLE
Error: Cannot change requiresUserPrivacyConsent() from TRUE to FALSE

### ISSUE THREAD

**Issue by ubuntudroid** [OneSignal/OneSignal-Android-SDK#1520]
**Description:**

I am calling `OneSignal.setRequiresUserPrivacyConsent(true)` right before calling `OneSignal.initWithContext(context)`.

Later, if the user provides/declines consent, I am calling `OneSignal.provideUserConsent(true/false)`.

However, in the log I am getting this error:

```
Cannot change requiresUserPrivacyConsent() from TRUE to FALSE
```

But I am never calling `setRequiresUserPrivacyConsent(false)`. 🤷  

Debugging calls to `setRequiresUserPrivacyConsent()` I found that it is called in a call chain launched by `initWithContext()`, specifically:

https://github.com/OneSignal/OneSignal-Android-SDK/blob/9ae1b92463348f2928312b8fdc5a04922952ee8d/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java#L886

So although this is not documented one needs to set the following in the manifest to enable the privacy consent feature:

<meta-data
            android:name="com.onesignal.PrivacyConsent"
            android:value="ENABLE" />

That way I could also remove my manual call to `setRequiresUserPrivacyConsent()` and everything worked as expected. I guess the documentation needs some updating here - and maybe the function `setRequireUserPrivacyConstent()` should be made private as calling it manually should likely never be needed with that manifest meta data entry in place.

**Environment**

SDK version: 4.6.5 
Android version: checked on Android 12

**Steps to Reproduce Issue:**

1. Call `OneSignal.setRequiresUserPrivacyConsent(true)`
2. Call `OneSignal.initWithContext(app)`

**Anything else:**

no crash, just the error (see description)

**Comment by jkasten2** [comment]
@ubuntudroid Thanks for reporting, this was a logging mistake so you can safely ignore it. It has been fixed in PR #1527 and will be included in the next release to clean up this confusing log message.
