### ISSUE TITLE
Attempt to invoke method on a null object reference

### ISSUE THREAD

**Issue by volvitanium** [OneSignal/OneSignal-Android-SDK#1524]
**Description:**
Actually, I got this exception in a flutter application. But after some research, I realized that the bug is in the OneSignal android library.
So I'm posting the issue here.

**Environment**
flutter doctor:
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 6.1.7601], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 4.2)

pubspec.yaml
onesignal_flutter: ^3.2.7

it depends to: OneSignal-4.6.3.jar

**Steps to Reproduce Issue:**

In my project I got a race-condition and exception happens in one of 20 restarts.
Generally, I think, you can try:
1. addSubscriptionObserver()
2. allow GC to free your object with implementation of  OSSubscriptionObserver
3. call removeSubscriptionObserver() with any other implementation of OSSubscriptionObserver (that does not added yet)

**Anything else:**

As you can see in call stack below, exception happens in OSObservable class.
```
   void removeObserver(Object observer) {
      for(int i = 0; i < this.observers.size(); ++i) {
         Object anObserver = ((WeakReference)this.observers.get(i)).get();
         if (anObserver.equals(observer)) {               /// <--- HERE IS AN EXCEPTION
            this.observers.remove(i);
            break;
         }
      }
   }
```

anObserver can be null only in one case - GC have freed the object. Other possibility to add null to observer list I can't find.
As hot fix I will try to fix removeObserver() function to something like this:

```
   void removeObserver(Object observer) {
      for(int i = 0; i < this.observers.size(); ++i) {
         Object anObserver = ((WeakReference)this.observers.get(i)).get();
         if (anObserver == null){
             this.observers.remove(i);
             continue;
         }
         if (anObserver.equals(observer)) {
            this.observers.remove(i);
            break;
         }
      }
   }
```
/* I think this will be enough. */

Here is flutter call stack:
E/MethodChannel#OneSignal(11966): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Object.equals(java.lang.Object)' on a null object reference
E/MethodChannel#OneSignal(11966): 	at com.onesignal.OSObservable.removeObserver(OSObservable.java:58)
E/MethodChannel#OneSignal(11966): 	at com.onesignal.OneSignal.removeSubscriptionObserver(OneSignal.java:2884)
E/MethodChannel#OneSignal(11966): 	at com.onesignal.flutter.OneSignalPlugin.addObservers(OneSignalPlugin.java:197)
E/MethodChannel#OneSignal(11966): 	at com.onesignal.flutter.OneSignalPlugin.setAppId(OneSignalPlugin.java:190)
E/MethodChannel#OneSignal(11966): 	at com.onesignal.flutter.OneSignalPlugin.onMethodCall(OneSignalPlugin.java:120)
E/MethodChannel#OneSignal(11966): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#OneSignal(11966): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:178)
E/MethodChannel#OneSignal(11966): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0$DartMessenger(DartMessenger.java:206)
E/MethodChannel#OneSignal(11966): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$6ZD.run(Unknown Source:12)
E/MethodChannel#OneSignal(11966): 	at android.os.Handler.handleCallback(Handler.java:883)
E/MethodChannel#OneSignal(11966): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/MethodChannel#OneSignal(11966): 	at android.os.Looper.loop(Looper.java:214)
E/MethodChannel#OneSignal(11966): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#OneSignal(11966): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#OneSignal(11966): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#OneSignal(11966): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by jkasten2** [comment]
@volvitanium Thanks for reporting! This is being addressed in PR https://github.com/OneSignal/OneSignal-Android-SDK/pull/1525 and will be included in the next release.
