### ISSUE TITLE
3.16.2 was never published to Maven Central. (3.16.2 contains a notification background image RTL fix)

### ISSUE THREAD

**Issue by janbolat** [OneSignal/OneSignal-Android-SDK#1529]
Hi,
v3.16.2 couldn't be found during the building. Please take a look at https://repo.maven.apache.org/maven2/com/onesignal/OneSignal/
Not urgent, but fyi.
Thank you

**Comment by jkasten2** [comment]
Thanks for reporting. It looks like the version didn't get published to Maven Central. We will look into correcting this in the future.

Looking at the [OneSignal-Android-SDK 3.16.2 patch notes](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/3.16.2) this release fixes a very specific background image rendering issue which could only happen if you are setting using the background image feature.
