### ISSUE TITLE
java.util.ConcurrentModificationException error

### ISSUE THREAD

**Issue by YoonKyoungTae** [OneSignal/OneSignal-Android-SDK#153]
Hi, 
I was experience this error.
Use Onesignal SDK version is 3.4.2, 

> [compile 'com.onesignal:OneSignal:3.4.2@aar']

```
java.util.LinkedHashMap$LinkedHashIterator.nextEntry (LinkedHashMap.java:346)
java.util.LinkedHashMap$KeyIterator.next (LinkedHashMap.java:366)
com.onesignal.OneSignalStateSynchronizer.generateJsonDiff (OneSignalStateSynchronizer.java:75)
com.onesignal.OneSignalStateSynchronizer.access$200 (OneSignalStateSynchronizer.java:46)
com.onesignal.OneSignalStateSynchronizer$UserState.generateJsonDiff (OneSignalStateSynchronizer.java:267)
com.onesignal.OneSignalStateSynchronizer$UserState.access$000 (OneSignalStateSynchronizer.java:201)
com.onesignal.OneSignalStateSynchronizer.syncUserState (OneSignalStateSynchronizer.java:480)
com.onesignal.OneSignalStateSynchronizer$NetworkHandlerThread$1.run (OneSignalStateSynchronizer.java:444)
android.os.Handler.handleCallback (Handler.java:739)
android.os.HandlerThread.run (HandlerThread.java:61)
```

How can i to resolve?
Thank you.

**Comment by jkasten2** [comment]
@YoonKyoungTae Are you able to reproduce this issue? Can you let us know the OneSignal methods you are calling and the steps to reproduce it? If you are able to reproduce the problem is a new project and link it here it will help us turn around a fix quicker.

**Comment by jkasten2** [comment]
@YoonKyoungTae I reviewed our code and wasn't able to see any conditions where a `ConcurrentModificationException` exception could occur.

If you see an this exception again on our 3.4.X SDK please attach the full new stack trace.
