### ISSUE TITLE
External id callback returns emaıl instead of email

### ISSUE THREAD

**Issue by joerogers** [OneSignal/OneSignal-Android-SDK#1541]
**Description:**

When checking the channel status for setting the external id, I noticed that user's in Turkey the email channel key is being returned as "emaıl" instead "email"  (Note the missing dot over the letter i)

The cause is due to a locale bug in UserStateSynchronizer.

The following method does the wrong thing:

```
String getChannelString() {   return this.channel.name().toLowerCase(); }
```

Because the default locale is used, the wrong glyph is returned for the letter i in countries like Turkey.

Instead the code should be:

```
String getChannelString() {   return this.channel.name().toLowerCase(Locale.ROOT); }
```
It is dangerous to use the "default" locale when converting case when you are testing constants or enums.

**Environment**
1. What version of the Android SDK are you using?   4.6.7
2. How did you add the SDK to your project (eg. maven)   gradle

**Steps to Reproduce Issue:**

1. Set device's locale to be Turkey
2. set the email address
3. set the external id
4. Check the json body in the callback.

**Comment by jkasten2** [comment]
@joerogers Thanks for report!
We will check all code that uses `toLowerCase()` and `toUpperCase()` in the SDK and ensure this case is covered.
