### ISSUE TITLE
[Android 12] Crash when tapping on Notification action button due to use of Intent.ACTION_CLOSE_SYSTEM_DIALOGS

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-Android-SDK#1543]
## Issue
The [`handleDismissFromActionButtonPress`](https://github.com/OneSignal/OneSignal-Android-SDK/blob/4.7.0/OneSignalSDK%2Fonesignal%2Fsrc%2Fmain%2Fjava%2Fcom%2Fonesignal%2FNotificationOpenedProcessor.java#L73) method in this SDK uses [`Intent.ACTION_CLOSE_SYSTEM_DIALOGS`](https://developer.android.com/reference/android/content/Intent#ACTION_CLOSE_SYSTEM_DIALOGS) however in Android API Level 31 (Android 12) this requires a new permission.

## Solution
The logic in `handleDismissFromActionButtonPress` was written in 2016 in PR #18 so it is likely things have changed with Android. We should attempt to remove `handleDismissFromActionButtonPress` to see if it correctly closes the notification shade in Android 12. If it does we can then go back to older versions of Android support by the SDK (Android 4.1 at the time of writing) to see if we still need it as well. If it is still required we can simply omit it if the device is running API level 31 or newer.

## Workaround
Setting your project to use`androidSdkVersion` to `30` would most likely workaround this issue until this is resolved.

**Comment by vincent-paing** [comment]
Will submit a PR to fix this

**Comment by nan-li** [comment]
The crash fix has been released in [version 4.7.1](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.7.1).

For now, I will still leave this issue open in case users cannot upgrade yet and can use the workaround.
