### ISSUE TITLE
OSRemoteNotificationReceivedHandler is not called and the notification is displayed

### ISSUE THREAD

**Issue by aduilio** [OneSignal/OneSignal-Android-SDK#1544]
**Description:**

Android SDK is not calling the OSRemoteNotificationReceivedHandler implementation and displaying the notification.

**Environment**
I'm using the version 4.7.0: implementation 'com.onesignal:OneSignal:[4.7.0, 4.99.99]'

This is the class:

```
package com.aduilio.service

@SuppressWarnings("unused")
class OneSignalNotificationReceiver(private var context: Context) : OneSignal.OSRemoteNotificationReceivedHandler {

    override fun remoteNotificationReceived(p0: Context?, notificationReceivedEvent: OSNotificationReceivedEvent?) {
        val data = notificationReceivedEvent?.notification?.additionalData

        data?.let {
            ......
        }

        notificationReceivedEvent?.complete(null)
    }
}
```

In the manifest:

```
<meta-data
    android:name="com.onesignal.NotificationServiceExtension"
    android:value="com.aduilio.service.OneSignalNotificationReceiver" />
```

I`m sending the notification from the app: 

  ```
  val account = getAccount()
  val deviceId = PreferencesUtil(context).getUUID()

  val body = NotificationBody()
  body.content = NotificationContent()
  body.filters = arrayListOf()
  val notificationFilter = NotificationFilter()
  notificationFilter.value = account.email
  body.filters?.add(notificationFilter)
  body.data = NotificationData(deviceId)

  NotificationRequest().send(body)
```

The app registers using the user e-mail as a tag:

`OneSignal.sendTag("email", email)`

remoteNotificationReceived is not called but a notification with the content "Message" is displayed.

**Comment by aduilio** [comment]
I forgot to mention. I was using the version 3.X with NotificationExtenderService and OneSignal.NotificationReceivedHandler. It was working properly.

**Comment by jkasten2** [comment]
@aduilio Thanks for reporting.

Can you confirm your `<meta-data>` tag is in side your `<application>` tag?
###### AndroidManifest.xml
```xml
<application ...> 
  <!-- 
    Keep name="com.onesignal.NotificationServiceExtension"
    value = your class fully name spaced
   -->
  <meta-data 
      android:name="com.onesignal.NotificationServiceExtension"
      android:value="com.onesignal.example.NotificationServiceExtension" />
</application>
```

If that is correct there some logging the SDK will print which will provide the details to why it didn't call your NSE:
https://github.com/OneSignal/OneSignal-Android-SDK/blob/fd3da865b90bd2e3e2578deb9b9d1a657500308e/OneSignalSDK/onesignal/src/main/java/com/onesignal/OSNotificationController.java#L182-L188

Make sure to enable VERBOSE logging with `OneSignal.setLogLevel` to get these to print.

If the class is not found, I recommend disabling Proguard / R8 to see if that is the issue.

**Comment by aduilio** [comment]
Hi @jkasten2. Thank you very much for helping. The logs helped to find the problem.

My class OneSignalNotificationReceiver was implementing the old OneSignal.NotificationReceivedHandler and it was receiving the context as parameter. I forgot to remove it once the new one has the context in the method. The OneSignal needs an empty constructor for this class.

My mistake not check the logs before.

**Comment by bhaskarraj** [comment]
I am also facing the same problem. I am not able to solve this. I have declared the below inside application tag

`        <meta-data android:name="com.onesignal.NotificationServiceExtension"
            android:value="com.osolutions.otv.common.NotificationServiceExtension" />`
            
 I have created a NotificationServiceExtension class as below:
 
    class NotificationServiceExtension implements OneSignal.OSRemoteNotificationReceivedHandler {

    @Override
    public void remoteNotificationReceived(Context context, OSNotificationReceivedEvent osNotificationReceivedEvent) {
        //to read the custom key value pairs
        Log.e("remoteNotificationReceived", "Called");
        }
    }

I am getting the below exception in the log

```
java.lang.IllegalAccessException: java.lang.Class<com.osolutions.otv.common.NotificationServiceExtension> is not accessible from java.lang.Class<com.onesignal.OSNotificationController>
 at java.lang.Class.newInstance(Native Method)
 at com.onesignal.OSNotificationController.setupNotificationServiceExtension(OSNotificationController.java:191)
at com.onesignal.OneSignal.init(OneSignal.java:795)
at com.onesignal.OneSignal.setAppId(OneSignal.java:713)
 at com.onesignal.OneSignal.reassignDelayedInitParams(OneSignal.java:1158)
 at com.onesignal.OneSignal.onRemoteParamSet(OneSignal.java:865)
 at com.onesignal.OneSignal$6.complete(OneSignal.java:1099)
 at com.onesignal.OneSignalRemoteParams.processJson(OneSignalRemoteParams.java:206)
 at com.onesignal.OneSignalRemoteParams.access$100(OneSignalRemoteParams.java:12)
 at com.onesignal.OneSignalRemoteParams$1.onSuccess(OneSignalRemoteParams.java:151)
 at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:292)
```
 Am I missing something?

**Comment by MingSern** [comment]
@bhaskarraj did you solved it? Am facing same issue as well
