### ISSUE TITLE
com.onesignal.shortcutbadger.ShortcutBadger.initBadger:200 SecurityException

### ISSUE THREAD

**Issue by SuperBuper** [OneSignal/OneSignal-Android-SDK#1546]

**Comment by jkasten2** [comment]
@SuperBuper Where you able to solve this issue or find the root cause?

**Comment by jkasten2** [comment]
I see this was created under the wrong repo at first and another issue was created https://github.com/OneSignal/OneSignal-Android-SDK/issues/1545. Let's continue there instead of here then.
