### ISSUE TITLE
crash on Onesignal-3.4.2

### ISSUE THREAD

**Issue by OlegTarashkevich** [OneSignal/OneSignal-Android-SDK#155]
Onesignal-3.4.2

```
Fatal Exception: java.lang.RuntimeException
Unable to start receiver com.onesignal.NotificationOpenedReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'int org.json.JSONArray.length()' on a null object reference

Caused by java.lang.NullPointerException
com.onesignal.OneSignal.notificationOpenedRESTCall (OneSignal.java:1058)
com.onesignal.OneSignal.handleNotificationOpen (OneSignal.java:1033)
com.onesignal.NotificationOpenedProcessor.processIntent (NotificationOpenedProcessor.java:101)
com.onesignal.NotificationOpenedProcessor.processFromActivity (NotificationOpenedProcessor.java:57)
com.onesignal.NotificationOpenedReceiver.onReceive (NotificationOpenedReceiver.java:11)
android.app.ActivityThread.handleReceiver (ActivityThread.java:2728)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:616)
```

![screen shot 2016-12-14 at 12 38 39](https://cloud.githubusercontent.com/assets/13828110/21177069/936a062a-c1fa-11e6-9beb-9dbf2fa9b33b.png)

**Comment by pmaojo** [comment]
I have the same error. Did you fix it?

**Comment by jkasten2** [comment]
@pmaojo We haven't been able to reproduce this one, you seeing the crash in production or your test devices? Are you seeing the exact same stack-trace as above in your crash?

It might be due to upgrading from an older SDK version and then tapping on an existing notification after the upgrade. If you updated our SDK could you provide the from and to versions?

**Comment by pmaojo** [comment]
somehow the error went away...

**Comment by jkasten2** [comment]
@OlegTarashkevich @pmaojo Android can some times restart Activities or BroadcastReceivers and with a empty Intent under memory pressure. I have fixed this by adding checks for our key before attempting to process it in commit 09b482f029900997eae6777cf5d033a1b7271c09.
