### ISSUE TITLE
Not reading background notifications using OSRemoteNotificationReceivedHandler

### ISSUE THREAD

**Issue by bhaskarraj** [OneSignal/OneSignal-Android-SDK#1559]
I am not able to read the notification in the background.  I have declared the below inside application tag

`        <meta-data android:name="com.onesignal.NotificationServiceExtension"
            android:value="com.osolutions.otv.common.NotificationServiceExtension" />`
            
 I have created a NotificationServiceExtension class as below:
 
    class NotificationServiceExtension implements OneSignal.OSRemoteNotificationReceivedHandler {

    @Override
    public void remoteNotificationReceived(Context context, OSNotificationReceivedEvent osNotificationReceivedEvent) {
        //to read the custom key value pairs
        Log.e("remoteNotificationReceived", "Called");
        }
    }

I am getting the below exception in the log

```
java.lang.IllegalAccessException: java.lang.Class<com.osolutions.otv.common.NotificationServiceExtension> is not accessible from java.lang.Class<com.onesignal.OSNotificationController>
 at java.lang.Class.newInstance(Native Method)
 at com.onesignal.OSNotificationController.setupNotificationServiceExtension(OSNotificationController.java:191)
at com.onesignal.OneSignal.init(OneSignal.java:795)
at com.onesignal.OneSignal.setAppId(OneSignal.java:713)
 at com.onesignal.OneSignal.reassignDelayedInitParams(OneSignal.java:1158)
 at com.onesignal.OneSignal.onRemoteParamSet(OneSignal.java:865)
 at com.onesignal.OneSignal$6.complete(OneSignal.java:1099)
 at com.onesignal.OneSignalRemoteParams.processJson(OneSignalRemoteParams.java:206)
 at com.onesignal.OneSignalRemoteParams.access$100(OneSignalRemoteParams.java:12)
 at com.onesignal.OneSignalRemoteParams$1.onSuccess(OneSignalRemoteParams.java:151)
 at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:292)
```
 Am I missing something?

**Comment by jkasten2** [comment]
@bhaskarraj The issue looks like your class (`com.osolutions.otv.common.NotificationServiceExtension`) doesn't have a default constructor for OneSignal to create an instance of your class. The crash points to this line in the OneSignal SDK:
https://github.com/OneSignal/OneSignal-Android-SDK/blob/4.7.0/OneSignalSDK/onesignal/src/main/java/com/onesignal/OSNotificationController.java#L191

## Solution
To fix you issue make sure you have public constructor with no parameters for your `NotificationServiceExtension` class.
Example:
```java
class NotificationServiceExtension implements OneSignal.OSRemoteNotificationReceivedHandler {

  // NEW: Must have a default public constructor for OneSignal
  public NotificationServiceExtension() {
  }

  @Override
  public void remoteNotificationReceived(Context context, OSNotificationReceivedEvent osNotificationReceivedEvent) {
      //to read the custom key value pairs
      Log.e("remoteNotificationReceived", "Called");
      }
  }
}
```

**Comment by bhaskarraj** [comment]
@jkasten2 I added the default constructor but still, it's not working. Giving me the same exception. I am testing on a Oneplus device.

**Comment by jkasten2** [comment]
@bhaskarraj Could let us know what Android versions and devices models you are seeing this issue on? Are they are any where it is working or do you see the issue on all devices?

Could you also share the rest of your `NotificationServiceExtension` class code so we can confirm you have correctly set up?

**Comment by LateinitTN** [comment]
@bhaskarraj class should set public like that
public class NotificationServiceExtension implements OSRemoteNotificationReceivedHandler {

    public NotificationServiceExtension(){}

    @Override
    public void remoteNotificationReceived(Context context, OSNotificationReceivedEvent osNotificationReceivedEvent) {
        OSNotification notification = osNotificationReceivedEvent.getNotification();
        OSMutableNotification mutableNotification = notification.mutableCopy();
        JSONObject data = notification.getAdditionalData();
        Log.i("OneSignalExample", "Received Notification Data: " + data);
        osNotificationReceivedEvent.complete(mutableNotification);
    }
}

**Comment by jkasten2** [comment]
@bhaskarraj I believe @LateinitTN is correct the important detail I forgot in my original reply about was that your class must also be public.

**Comment by jkasten2** [comment]
@exp24kirill in the Android 5.x.x SDK (v11 is the documentation version) there is no longer a `complete()` method, the notification displays automatically now.
* If you want to prevent the notification from showing you can call `event.preventDefault()` now.

See the full documentation for the OneSignal Android Notification Service Extension:
https://documentation.onesignal.com/docs/service-extensions#android-notification-service-extension
