### ISSUE TITLE
android.os.DeadSystemException

### ISSUE THREAD

**Issue by jinkaiYu** [OneSignal/OneSignal-Android-SDK#1569]
![image](https://user-images.githubusercontent.com/18320608/163950247-11e2833c-dddc-48e6-ba5f-ec66388ec978.png)
![image](https://user-images.githubusercontent.com/18320608/163950523-40f6f1af-9008-4138-bc59-25bba1710ce0.png)

**Environment**
OneSignal SDK 4.7.1

**Comment by nan-li** [comment]
Hi @jinkaiYu,

Thank you for reporting. Please see this linked issue: https://github.com/OneSignal/OneSignal-Android-SDK/issues/1170.
Can you share the stack trace as text instead of as a picture, so it's easier to search and copy?

**Comment by jinkaiYu** [comment]
@nan-li 
Android API: Android 10,level 29
Device : HWJSN-H-JSN-AL00
We currently have more than 300 users reporting this problem through background statistics, and within a week
