### ISSUE TITLE
Waiting for remote params. Moving unsubscribeWhenNotificationsAreDisabled() operation to a pending task queue error in Logcat

### ISSUE THREAD

**Issue by Mathbl** [OneSignal/OneSignal-Android-SDK#1575]
**Description:**
Hi,

I've followed the documentation to initialize and configure OneSignal in my Application class. It works fine, but I'm always seeing errors in Logcat, even though I have the same steps as the sample.

**Environment**
- compileSdk/targetSdk 31
- OneSignal v4.7.2 through Gradle

**Steps to Reproduce Issue:**
In Application class onCreate():
```kotlin
if (BuildConfig.DEBUG) OneSignal.setLogLevel(OneSignal.LOG_LEVEL.WARN, OneSignal.LOG_LEVEL.NONE)
OneSignal.initWithContext(this)
OneSignal.setAppId(BuildConfig.ONESIGNAL_APP_ID)
OneSignal.unsubscribeWhenNotificationsAreDisabled(true)
OneSignal.setLocationShared(false)
```
Logcat will show: 
```logcat
09:42:07.225 OneSignal  E  Waiting for remote params. Moving unsubscribeWhenNotificationsAreDisabled() operation to a pending task queue.
09:42:07.225 OneSignal  E  Waiting for remote params. Moving setLocationShared() operation to a pending task queue.
```
I've checked the source code, but I don't understand why I would get Logcat errors by initializing OneSignal according to the documentation? Shouldn't this be a warning or info if this happens on every app launch?

Thanks!

**Comment by nan-li** [comment]
Hi @Mathbl,

Thanks for reporting, and you're right, these particular logs serve more as information about what is happening in the SDK, and not usually an error when it runs smoothly. 

In some other situations, it could be an error. We will think about modifying these error logs into warnings.

**Comment by jennantilla** [comment]
Closing this issue as logging has been significantly updated in Android SDK 5.x.x, along with many other improvements and enhancements! Please refer to the [migration guide](https://github.com/OneSignal/OneSignal-Android-SDK/blob/user-model/main/MIGRATION_GUIDE.md) for more information on upgrading.

Thanks!

**Comment by muhammad-kumail** [comment]
I'm facing same issue in 4.5.3
