### ISSUE TITLE
Deeplink/NotificationOpenedHandler - Impossible to fallback to default OneSignal redirect

### ISSUE THREAD

**Issue by JulienArzul** [OneSignal/OneSignal-Android-SDK#158]
Hello,

I am currently implementing the opening of a deep link in my application when a specific notification is received. From your documentation, you advise to add custom data in the notification payload and then route the user in a NotificationOpenedHandler.
I like the idea. However, from what I've seen in the docs (and what I've discovered so far in the SDK), it's missing the possibility to let OneSignal handle the routing of the user if we didn't find the custom data we were looking for.

In my case, I have one or two type of notifications that will open a specific Activity of my application. The rest of them should have the default behavior: opening the launcher activity or redirecting to the browser if there was a launchUrl or any other future routing that will be added in OneSignal.

Currently, there is no middle ground : either we handle the activity opened when the notification is clicked or we let OneSignal do it. It would be nice to be able to handle some cases and let OneSignal handle the rest.

I can see two ways of implementing that: 
- by providing a method that does that redirection independently of the com.onesignal.NotificationOpened.DEFAULT manifest entry that we call in the NotificationOpenedHandler
- by returning a boolean in the notificationOpened method to specify if we did handle the notification opening

Thanks

PS : this is obviously an enhancement and not a bug

**Comment by jkasten2** [comment]
Thanks for the suggestion, adding your own code to start the launcher `Activity` when the is no additional data does add extra blot to the application logic. I like the return value from `notificationOpened ` idea, might implement that there are no caveats.

**Comment by lukyanov** [comment]
Thinking about the same behaviour and love the idea of the return value from `notificationOpened`.

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration
