### ISSUE TITLE
R8 Warning - Missing class com.google.firebase.messaging

### ISSUE THREAD

**Issue by 123dma** [OneSignal/OneSignal-Android-SDK#1580]
**Description:**

I'm only using onesignal, but when compiling the release versions, R8 displays the warning:

`Missing class com.google.firebase.messaging.TopicOperation$TopicOperations (referenced from: void com.google.firebase.messaging.TopicOperation.<init>(java.lang.String, java.lang.String))
`

I've tried to add this in the R8 obfuscation rules but without success.

```
-keep public class com.onesignal.ADMMessageHandler {*;}
-keep public class com.onesignal.*
 keep public class com.google.firebase.messaging
-keep public class com.onesignal.ADMMessageHandler {*;}

-keep class com.onesignal.JobIntentService$* {*;}

-keep class com.onesignal.OneSignalUnityProxy {*;}
```

**Environment**

What version of the Android SDK are you using?
  classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.14.0, 0.99.99]'
   implementation 'com.onesignal:OneSignal:[4.0.0, 4.99.99]'

**Steps to Reproduce Issue:**

1. Add the OneSignal SDK ANDROID to your project
2. Run Android Studio ofuscation R8 Release

**Anything else:**

(crash stacktraces, as well as any other information here)
`Missing class com.google.firebase.messaging.TopicOperation$TopicOperations (referenced from: void com.google.firebase.messaging.TopicOperation.<init>(java.lang.String, java.lang.String))
`

**Comment by jkasten2** [comment]
@123dma Thanks for reporting, looks like an issue with Firebase itself. It was also reported on their forums:
https://groups.google.com/g/firebase-talk/c/uQfTiV1vLBE

The `void com.google.firebase.messaging.TopicOperation` reference seems to be located here:
https://github.com/firebase/firebase-android-sdk/blob/ac3276ce7d5f5181b1c419731495eb88a98537af/firebase-messaging/src/main/java/com/google/firebase/messaging/TopicOperation.java#L43
Looking at the git blame it hasn't changed since July 2020, so the issue might be around the version of R8 you are using instead.

**Comment by rynkowsg** [comment]
Do you have any issues other than a warning? If not, why do you want to keep that name? Ignoring it should be ok.

If you check, you probably have the missing_rules.txt file among your proguard outcomes, in which proguard suggest ignoring it:

```
-dontwarn com.google.firebase.messaging.TopicOperation$TopicOperations
```

**Comment by 123dma** [comment]
@jkasten2  thanks for the feedback. The message in the firebase thread was created by myself. I verified that it included the reference to the firebase.message, however after discovering this I removed the reference and the warning is still being displayed. I will create a test project to check the details.

@rynkowsg rynkowsg thanks for the message, I usually don't think like that, I have some persistent ANR's that I can't solve, so I try not to ignore warnings. I don't believe that the reason R8 has informed the option to ignore is because it is irrelevant.

**Comment by jkasten2** [comment]
@123dma Thanks for the update, feel free to report back here with your findings, as it could help others that may run into the same Firebase issue.

Closing this issue as not related to OneSignal however, but let us know if we are mistaken.

**Comment by rynkowsg** [comment]
@123dma 
ANRs are one things, ProGuard warnings are another. If you had a ProGuard issue, you would get a crash not an ANR.

I understand you don't ignore warnings, but with a certain classes of warnings, the right thing to do is to ignore them. This one looks like one, same as other ProGuard warnings shown when your dependencies use SSL libraries, e.g. OkHttp generates ProGuard warnings about `org.conscrypt.*`, `org.bouncycastle.*` that can be only ignored.

I would say, it is fine to ignore this one.

If you have ANRs, I would recommend offloading the UI thread.

**Comment by jkasten2** [comment]
R8 warnings mean it's possible a `NoClassDefFoundError` exception could be thrown at runtime when the class happens to be accessed. It's possible your app may never hit these code paths and may never see the issue, however suppressing a warning like this has some risk. Libraries should provide proguard rules so consumers of the library don't have to understand or dig in to their code.

I would assume Firebase is automatically providing proguard rules so it is really odd that it would get get a "Missing class". So other possibilities is the project has a specific Firebase version that has a bug with this, or the project as some aggressive R8 rules that are obfuscating more classes.
