### ISSUE TITLE
Your app contains content that doesn’t comply with the Device and Network Abuse policy

### ISSUE THREAD

**Issue by mukhatov** [OneSignal/OneSignal-Android-SDK#1582]
**Description:**

After a recent review, we received the following message

> Your app contains content that doesn’t comply with the Device and Network Abuse policy. We found your app is using a non-compliant version of Huawei Mobile Services SDK which contains code to download or install applications from unknown sources outside of Google Play.

>After 120 days, new app releases containing this non-compliant version of this SDK will be rejected. This SDK version violates Device & Network Abuse policy

**Environment**

        classpath("gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.13.4")
        classpath("com.huawei.agconnect:agcp:1.6.0.300")

Flawors

    flavorDimensions.add("version")
    productFlavors {
        create("huawei") {
            dimension = "version"
        }
        create("google-play") {
            dimension = "version"
        }
    }

Dependencies

    val oneSignal = "4.7.2"
    "google-playImplementation"("com.onesignal:OneSignal:$oneSignal") {
        exclude(group = "com.huawei.hms")
    }
    "huaweiImplementation"("com.onesignal:OneSignal:$oneSignal") {
        exclude(group = "com.google.android.gms")
        exclude(group = "com.google.firebase")
    }
    "huaweiImplementation"("com.huawei.hms:push:6.3.0.304")

**Steps to Reproduce Issue:**

Google play review

**Anything else:**

We don't use other libraries from HMS.

**Comment by jkasten2** [comment]
@mukhatov Can you also make sure you are omitting `apply plugin: "com.huawei.agconnect"` from your `google-play` builds?
See this example how to do something like this:
https://github.com/OneSignal/OneSignal-Android-SDK/blob/4.7.2/Examples/OneSignalDemo/app/build.gradle#L45-L52

If you still see the issue I recommend following this to double check the dependencies getting build into the app:
https://stackoverflow.com/a/63137778

**Comment by jkasten2** [comment]
Closing due to no response.
