### ISSUE TITLE
Add Gradle configuration cache support

### ISSUE THREAD

**Issue by fillipeoliveira-hotmart** [OneSignal/OneSignal-Android-SDK#1592]
**Description:**

Gradle configuration cache is not working properly with OneSignal lib on project. After enable the configuration cache, I start getting messages like this (gradle log) on every build
`Calculating task graph as configuration cache cannot be reused because cached version information for androidx.work:work-runtime:{require [2.1.0, 2.7.99]; prefer 2.7.1} has expired.`

`Calculating task graph as configuration cache cannot be reused because cached version information for androidx.cardview:cardview:{require [1.0.0, 1.0.99]; prefer 1.0.0} has expired.`

And when I check my dependencies graph, I found this
```bash
+--- com.onesignal:OneSignal:4.6.5
|    +--- androidx.cardview:cardview:{require [1.0.0, 1.0.99]; prefer 1.0.0} -> 1.0.0 (*)
|    +--- androidx.legacy:legacy-support-v4:{require [1.0.0, 1.0.99]; prefer 1.0.0} -> 1.0.0 (*)
|    +--- androidx.browser:browser:{require [1.0.0, 1.3.99]; prefer 1.3.0} -> 1.4.0 (*)
|    +--- androidx.appcompat:appcompat:{require [1.0.0, 1.3.99]; prefer 1.3.1} -> 1.4.1 (*)
|    +--- androidx.work:work-runtime:{require [2.1.0, 2.7.99]; prefer 2.7.1} -> 2.5.0 (*)
```

The only way I found to get configuration cache working, is removing that libraries from onesignal and add then with the fixed versions on my project, like this

```kotlin
    implementation("com.onesignal:OneSignal:4.6.5") {
        exclude("com.google.firebase")
        exclude("com.google.android.gms")
        exclude("androidx.cardview")
        exclude("androidx.legacy")
        exclude("androidx.browser")
        exclude("androidx.appcompat")
        exclude("androidx.work")
    }
    implementation("androidx.cardview:cardview:1.0.0")
    implementation("androidx.legacy:legacy-support-v4")
    implementation("androidx.browser:browser:1.3.0")
    implementation("androidx.appcompat:appcompa:1.3.1")
    implementation("androidx.work:work-runtime:2.7.1")
    ...
```

After that, I start to get this message on the start of the build.
`Reusing configuration cache.`

**Environment**
1. OneSignal 4.6.5
2. Gradle 7.0.3
3. `org.gradle.unsafe.configuration-cache=true` on gradle.properties

**Steps to Reproduce Issue:**
1. Add the OneSignal SDK to your project
2. add `org.gradle.unsafe.configuration-cache=true` on gradle.properties
3. sync and build (2 times at least. First to try to create an cache and after that to use)

**Anything else:**

**Comment by nan-li** [comment]
Hi @fillipeoliveira-hotmart,

Thank you for reporting and details on this feature. [Gradle documentation](https://docs.gradle.org/current/userguide/configuration_cache.html) currently says:

> The configuration cache is an [incubating](https://docs.gradle.org/current/userguide/feature_lifecycle.html#feature_lifecycle) feature, and the details described here may change.

It may be that version ranges with a preference are not supported as of Gradle `7.0.3`. 

Are you seeing that other dependencies with ranges and a `prefer` version are reused, while the OneSignal dependencies are not? Also, just wondering if you are also using the `onesignal-gradle-plugin`?

You can also try updating your Gradle version to see if there are any changes.

**Comment by fillipeoliveira-hotmart** [comment]
Hi @nan-li 
Yes, I'm using the `onesignal-gradle-plugin` too..

You are right about the support of range versions on Gradle 7.0.3. I create a sample app with Gradle 7.2 and the problem do not occur any more.

On my other app, I can't update the gradle right now, so I still using that "hack". But is good to now that on newer version, every thing os working fine.

Thanks for your support.

**Comment by nan-li** [comment]
Thanks for confirming @fillipeoliveira-hotmart, good to hear!

I will close this issue then.
