### ISSUE TITLE
OneSignal.disablePush is not working

### ISSUE THREAD

**Issue by felipezf** [OneSignal/OneSignal-Android-SDK#1594]
**Description:**
I'm trying to disable the push notifications when the user execute the app logout. I'm calling the method OneSignal.disablePush, but even after called this method the app still receive push notifications.

**Environment**
1. What version of the Android SDK are you using? 4.73

2. How did you add the SDK to your project? 
```java
OneSignal.initWithContext(this)
OneSignal.setAppId(BuildConfig.ONE_SIGNAL_APP_ID)
OneSignal.setLogLevel(OneSignal.LOG_LEVEL.DEBUG, OneSignal.LOG_LEVEL.NONE)
OneSignal.setNotificationOpenedHandler(NotificationHandler())
```

**Steps to Reproduce Issue:**
  1. Add the OneSignal SDK to your project
  2. Place your App ID in the application's gradle file
  3. Attempt to receive a push notification
  4. Call  OneSignal.disablePush(true)
  5.  Attempt to receive a push notification
  6.  You will still receive push notifications

**Comment by jkasten2** [comment]
Closing due to no response.
