### ISSUE TITLE
[question]: How do i integrate into an existing application.

### ISSUE THREAD

**Issue by adoboligh1** [OneSignal/OneSignal-Android-SDK#1617]
### How can we help?

hello onesignal, i am new to android development and i have this code which i noticed is already using the Application Tag inside the androidmanifest.xml i have followed your tutorial and created the class but inside the android manifest.xml the application tag is already in use by the apps main class and it extends MultidexApplication Instead of Application. so how do i go around it?. below is my android manifest.xml code.

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.boxradio.gh">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

    <uses-feature
        android:glEsVersion="0x00020000"
        android:required="false" />

    <application
        android:name="com.boxradio.gh.XRadioApplication"
        android:allowBackup="true"
        android:hardwareAccelerated="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppThemeFull"
        android:usesCleartextTraffic="true"
        tools:ignore="LockedOrientationActivity">

    <activity
            android:name="com.boxradio.gh.XRadioSplashActivity"
            android:configChanges="touchscreen|keyboard|keyboardHidden|navigation|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"
            android:exported="true"
            android:label="@string/app_name"
            android:screenOrientation="portrait">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <activity
            android:name="com.boxradio.gh.XMultiRadioMainActivity"
            android:configChanges="touchscreen|keyboard|keyboardHidden|navigation|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"
            android:label="@string/app_name"
            android:launchMode="singleTop"
            android:screenOrientation="portrait"
            android:windowSoftInputMode="adjustPan|adjustResize" />
        <activity
            android:name="com.boxradio.gh.XSingleRadioMainActivity"
            android:configChanges="touchscreen|keyboard|keyboardHidden|navigation|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"
            android:label="@string/app_name"
            android:launchMode="singleTop"
            android:screenOrientation="portrait"
            android:windowSoftInputMode="adjustPan|adjustResize" />

        <activity
            android:name="com.boxradio.gh.XRadioShowUrlActivity"
            android:configChanges="touchscreen|keyboard|keyboardHidden|navigation|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"
            android:label="@string/app_name"
            android:screenOrientation="portrait" />
        <activity
            android:name="com.boxradio.gh.XRadioGrantActivity"
            android:configChanges="touchscreen|keyboard|keyboardHidden|navigation|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"
            android:label="@string/app_name"
            android:screenOrientation="portrait" />

        <service
            android:name="com.boxradio.gh.stream.service.YPYStreamService"
            android:exported="false" />

        <receiver
            android:name="com.boxradio.gh.stream.service.YPYIntentReceiver"
            android:exported="true">
            <intent-filter>
                <action android:name="android.media.AUDIO_BECOMING_NOISY" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.MEDIA_BUTTON" />
            </intent-filter>
        </receiver>

        <meta-data
            android:name="com.google.firebase.messaging.default_notification_channel_id"
            android:value="${applicationId}.N3" />

        <service
            android:name="com.boxradio.gh.firebasemsg.XRadioFBMessagingService"
            android:exported="true">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>

        
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_icon"
            android:resource="@drawable/ic_notification_24dp" />

        
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_color"
            android:resource="@color/colorPrimary" />

        <meta-data
            android:name="firebase_messaging_auto_init_enabled"
            android:value="true" />
        <meta-data
            android:name="firebase_analytics_collection_enabled"
            android:value="true" />

        <meta-data
            android:name="com.google.android.gms.ads.AD_MANAGER_APP"
            android:value="true" />

        <uses-library
            android:name="org.apache.http.legacy"
            android:required="false" />

        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="@string/admob_app_id" />

    </application>

</manifest>

Main JAVA CLASS below.

package com.boxradio.gh;

import android.util.Log;

import androidx.multidex.MultiDexApplication;

import com.boxradio.gh.constants.IXRadioConstants;
import com.boxradio.gh.stream.ssl.XRadioSSLSocketFactory;
import com.facebook.ads.AudienceNetworkAds;

import javax.net.ssl.HttpsURLConnection;

public class XRadioApplication extends MultiDexApplication implements IXRadioConstants {

    @Override
    public void onCreate() {
        super.onCreate();
        if (!AudienceNetworkAds.isInitialized(this) && ALLOW_FB_ADS) {
            AudienceNetworkAds
                    .buildInitSettings(this)
                    .withInitListener(initResult -> {
                        Log.e(TAG, "=======>isInitialized=" + initResult);
                    })
                    .initialize();
        }
        if (ENABLE_CUSTOMIZE_SSL) {
            setUpHttpsSelfSigned();
        }
    }

    private void setUpHttpsSelfSigned() {
        try {
            HttpsURLConnection.setDefaultSSLSocketFactory(new XRadioSSLSocketFactory());
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }

}

Thank you :)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @adoboligh1! If you already have an Application class then you can just add the [OneSignal initialization code](https://documentation.onesignal.com/docs/android-sdk-setup#step-3-add-required-code) to your existing class's `onCreate` method.

Let us know how that goes!

**Comment by adoboligh1** [comment]
> Hi @adoboligh1! If you already have an Application class then you can just add the [OneSignal initialization code](https://documentation.onesignal.com/docs/android-sdk-setup#step-3-add-required-code) to your existing class's `onCreate` method.
> 
> Let us know how that goes!

That worked! thank you :)
