### ISSUE TITLE
[Bug]: Dasho Class not found: com.amazon.device.messaging.ADMMessageHandlerBase

### ISSUE THREAD

**Issue by adgluzdov** [OneSignal/OneSignal-Android-SDK#1623]
### What happened?

When I compile android project that contains OneSignal and uses DashO, I get an error: Dasho Class not found: com.amazon.device.messaging.ADMMessageHandlerBase

![image](https://user-images.githubusercontent.com/11931849/183887113-79d18835-ac2c-4882-8992-0fa453caec5c.png)

### Steps to reproduce?

```Markdown
1. Create Simple Project
2. Include Onesignal
3. Include DashO
4. Build release
```

### What did you expect to happen?

Successful release.

### OneSignal Android SDK version

Release 4.7.4

### Android version

13, 12, 11, 10, 9, 8, 7.1, 7.0, 6

### Specific Android models

```Markdown
* Android Studio, Emulator/Device, API any
```

### Relevant log output

```Shell
Error: Class not found: com.amazon.device.messaging.ADMMessageHandlerBase; super class of com.onesignal.ADMMessageHandler; called from protected void com.onesignal.ADMMessageHandler.onMessage(android.content.Intent)
Class not found: com.amazon.device.messaging.ADMMessageHandlerBase; super class of com.onesignal.ADMMessageHandler; called from protected void com.onesignal.ADMMessageHandler.onMessage(android.content.Intent)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adgluzdov** [comment]
You can be sure of this even if you try to connect DashO to the implementation of the demo project

**Comment by emawby** [comment]
@adgluzdov Hello thank you for reaching out. We are releasing an update today that changes our Amazon dependency which might fix the issue. I tried to reproduce this with a trial license for dasho, but could not get the issue. Are there any details to your dasho implementation that might be relevant?

**Comment by adgluzdov** [comment]
@emawby Thanks for the answer. I hope the update helps, if so, I will definitely let you know about it. So far I'm trying to solve the problem without updating. We managed to successfully build the application by creating our own implementation of com.amazon... with an empty implementation. The application built, but push notifications are not delivered, and the user is not registered as a subscriber.

**Comment by adgluzdov** [comment]
@emawby Thank you, your update helped me.
https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.8.2

**Comment by adgluzdov** [comment]
@emawby Sorry, the update didn't help.
Here's what helped.
You need to manually add the library to the project. 
https://developer.amazon.com/docs/adm/overview.html#download
And add connect it like this: 
dependencies {
    compileOnly files('libs/amazon-device-messaging-1.1.0.jar')
}
And that's the only way it worked for me.
Check: https://developer.amazon.com/docs/adm/set-up.html

But anyway, thanks for the update, I looked at the changes and just by your example I realized what needs to be changed.
