### ISSUE TITLE
How to pass User Privacy Consents and GDPR values to OneSignal SDK after the user provided the consents?

### ISSUE THREAD

**Issue by SharyRajpoot** [OneSignal/OneSignal-Android-SDK#1626]
### How can we help?

I am currently following your doc. and currently, I am working with Privacy Consents and GDPR stuff. [here](https://documentation.onesignal.com/docs/sdk-reference#privacy)
Oka, I got all but one thing I am not getting here is supposed user has given my app permission or consent then how can I pass those consents to OneSignal SDK?
Like how can I tell OneSignal that the user is agreed or disagree?

Currently, I am doing stuff like this...
```
// On Application class OnCreate method

        val hasGdprConsents = prefsManager.hasKey(PrefsManager.IS_GDPR_APPLIES)
        val isGdprApplies = prefsManager.getPrefsBool(PrefsManager.IS_GDPR_APPLIES)
       
        if(!OneSignal.userProvidedPrivacyConsent() && (isGdprApplies || !hasGdprConsents)) {
            // Delays initialization of the SDK until the user provides privacy consent
            OneSignal.setRequiresUserPrivacyConsent(true) 
        }

        // OneSignal Initialization
        OneSignal.initWithContext(this)
        OneSignal.setAppId(getString(R.string.onesignal_app_id))

```

Now supposed at some point e.g Ads SDKS detects this region is under GDRP so my app asked for user consent and from there...
if the user agrees I set values like this.
```
onAgree => OneSignal.provideUserConsent(true)
onDisagree => OneSignal.provideUserConsent(false)
```
But I have a feeling like these methods are not intended for this purpose. They are just here to let OneSignal knows that oka we have taken the consent and you can do further initialization...etc
But what I want is to tell OneSignal that the user didn't allow to share or sell its data..etc

So how can I pass user consent to OneSignal SDK?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SharyRajpoot** [comment]
Closing due to no response and interest in answering.

**Comment by jmadler** [comment]
Our SDK only collects a small amount of information that would be considered PII under GDPR.  This is documented under [OneSignal's Handling Personal Data](https://documentation.onesignal.com/docs/handling-personal-data) guidance.  The rest of the GDPR exposure comes from developer action; such as setting user tags.

Our GDPR API works as follows:
1. You must enable the optional flag `requiresUserPrivacyConsent` as you initialize the SDK.
2. You may choose to disable location sharing.
3. You must prompt for consent from the user.
3a. If the user explicitly chooses to provide consent, you must call provideConsent(true) to enable SDK behavior.
3b. If the user explicitly chooses to not provide consent, you must choose how to handle SDK behavior.  You can choose to call `provideUserConsent(true)` but avoid setting certain GDPR-sensitive tags, or you can choose to explicitly forego SDK usage altogether.

We can not automatically assume what the appropriate course of action is for a user who has chosen to not provide "consent", as we do not know what data is stored in tags, and what information the user was prompted with to provide consent.  Thus we can not make `provideUserConsent(false)` meaningful.

For GDPR specific information, please see [OneSignal's GDPR guidance](https://documentation.onesignal.com/docs/gdpr-compliance).  For additional support, please reach out to your sales/support contact at OneSignal.
