### ISSUE TITLE
The Android SDK server is currently turned off.

### ISSUE THREAD

**Issue by sieunju** [OneSignal/OneSignal-Android-SDK#1629]
OneSignal SDK Server HTTP Code 530.....?

https://documentation.onesignal.com/docs/android-sdk-setup

what happend ?! 😭😭😭

**Comment by nan-li** [comment]
Hi @sieunju, thanks for reporting. 

It looks like our documentation is back up, but if there are any further issues, please see https://status.onesignal.com/ for updates.
