### ISSUE TITLE
setInFocusDisplaying - handle null and store value

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-Android-SDK#163]
`setInFocusDisplaying` will throw an `null` exception if it is called before initialization.  If `OneSignal.Builder` hasn't been created yet an instance should be created and the value should be set on it.

This improvement will make it easier for wrapping SDKs to handle out of order events.

**Comment by avishayil** [comment]
+1

**Comment by jkasten2** [comment]
@avishayil Fixed in commit 5f670ac5b76f5e661018fe6513de730e43007a2b. Will update the react issue when I create a release with this fix included.
