### ISSUE TITLE
Onesignal.clearOnesignalNotifications() does not work when the notifs are more than 5 

### ISSUE THREAD

**Issue by thekingrenz23** [OneSignal/OneSignal-Android-SDK#1634]
Hello. If the notifs are more than 5 and you clear it via clearOnesignalNotifications()
It does not work it will just collapse into single notif and say 5 new messages

**Comment by emawby** [comment]
@thekingrenz23 Thank you for reaching out we will investigate!

**Comment by nan-li** [comment]
This has been released in[ 4.8.3](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.8.3)

**Comment by raffaelgyr** [comment]
This bug still exists when clearing notifications one at a time using OneSignal.removeNotification()

**Comment by thekingrenz23** [comment]
Yes this issue still exist. My current workaround as of the moment is to make all the notification send on the same channel id
