### ISSUE TITLE
SyncService memory usage

### ISSUE THREAD

**Issue by pushand** [OneSignal/OneSignal-Android-SDK#164]
![screenshot_20170127-151227](https://cloud.githubusercontent.com/assets/12893140/22367781/5605919c-e4a9-11e6-8a04-a36f3bb098a8.jpg)
SyncService memory usage goes upto 245mb on android every time it is being started

**Comment by jkasten2** [comment]
@pushand The SyncService runs to make sure all tags, session, etc are synced with OneSignal. It is only active for a short time after your app is first back grounded.

It shows the memory usage this way as the service is on the same process. The usage is from any resources still loaded in to memory from your app.
