### ISSUE TITLE
[question]: POST for api.onesignal.com/players failing

### ISSUE THREAD

**Issue by juhchamp** [OneSignal/OneSignal-Android-SDK#1649]
### How can we help?

I have been used the OneSignal for a while and now I noticed in the logs that the api endpoint `https://api.onesignal.com/players` are failing with error `Identifier invalid format.` but I don't know the real cause of that.
Anyone can help? Here are the logs:

```
V/OneSignal: OneSignalRestClient: After con.getResponseCode to: https://api.onesignal.com/players
I/OneSignal: Device registered, UserId = adfa.................
V/OneSignal: OSFocusDelaySync scheduleSyncTask:SYNC_AFTER_BG_DELAY_MS: 2000
V/OneSignal: OSBackgroundSync scheduleSyncServiceAsJob:atTime: 2000
I/OneSignal: OSBackgroundSync scheduleSyncServiceAsJob:result: 1
V/OneSignal: Completed request to update external user id for channel: push and success: true
V/OneSignal: OneSignalRestClient: After con.getResponseCode to: https://api.onesignal.com/players
I/OneSignal: Device registered, UserId = 39c..............
V/OneSignal: OneSignalRestClient: After con.getResponseCode to: https://api.onesignal.com/players
W/OneSignal: OneSignalRestClient: POST RECEIVED JSON: {"success":false,"errors":["[\"Identifier invalid format.\"]"]}
W/OneSignal: Failed last request. statusCode: 400 response: {"success":false,"errors":["[\"Identifier invalid format.\"]"]}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @juhchamp, in your log, do you also see the POST SEND JSON data? 

Identifier Invalid may mean:
- the push token is not being generated correctly (push record)
- the email address or phone number is not formatted correctly (email or SMS records)

Thanks for the additional details!

**Comment by juhchamp** [comment]
Hi @jennantilla, thanks for the reply. Yes, I see the POST SEND JSON data and now I can see what was wrong. I was sending the phone number in the `OneSignal.setSMSNumber` function without the "+" in front of the number; after the "+" was put in the front of the number like +55991224477, the error `Identifier invalid format` stopped appearing, however, another error appeared:
`JSON RECEIVED POST: {"errors":["invalid identifier_auth_hash"]}`
I believe the above error is related with the invalid `emailAuthHash`. I'll check with the backend team and see about that.

Thanks.

**Comment by jennantilla** [comment]
Thanks for the update! Your backend team may find our [identify verification doc](https://documentation.onesignal.com/docs/identity-verification) helpful. I'll go ahead and close this issue but please feel free to respond back if you are still having issues.
