### ISSUE TITLE
Sending versionCode as game_version is inconsistent with iOS SDK

### ISSUE THREAD

**Issue by jalada** [OneSignal/OneSignal-Android-SDK#1651]
In this SDK you send the package's `versionCode` as `game_version` (which shows up in the OneSignal interface as App Version). But on iOS you send the Version which (I think?) is more analgous to `versionName` - it doesn't affect builds like `versionCode` does on Android (that'd be a bit more like Build on iOS I guess).

Android:

https://github.com/OneSignal/OneSignal-Android-SDK/blob/e119f4d8074c4f7f42dcb23b473529819dffa25b/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java#L1521

iOS:

https://github.com/OneSignal/OneSignal-iOS-SDK/blob/f55808d7907fd3da97eda0c0b8674806763fdcd1/iOS_SDK/OneSignalSDK/Source/OneSignal.m#L1697

For multi-platform apps, especially React Native, this causes some frustrating inconsistency in the OneSignal UI and means we have to resort to our own custom app version trigger. These apps have the same version string, think you can guess which ones are Android and which are iOS:

![image](https://user-images.githubusercontent.com/126989/191714475-a4cf31fa-f84e-4bc9-9d5d-0e7c519e9b9e.png)

I can't see a way to customise this behaviour on either iOS or Android referenced in the documentation nor obvious in the code. Is there something that could be added to help line these up?

**Comment by jennantilla** [comment]
Hi @jalada, App Version pulls from Android's `versionCode` in your app's build.gradle file whereas iOS uses CFBundleShortVersionString. You can update XCode's Bundle Version String to align app versions:
<img width="460" alt="Screen Shot 2022-10-07 at 2 47 35 PM" src="https://user-images.githubusercontent.com/46546946/194665709-a980a58e-9a58-45b7-a264-25e64eff5412.png">

Let us know if that works for you!

**Comment by jalada** [comment]
Hi @jennantilla. I don't think that really makes sense, but perhaps I'm being a noob? Here's [the description of `CFBundleShortVersionString` from Apple](https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring):

> This key is a user-visible string for the version of the bundle. The required format is three period-separated integers, such as 10.14.1. The string can only contain numeric characters (0-9) and periods.

And here's [the description of `versionCode` from Google](https://developer.android.com/studio/publish/versioning#appversioning):

> A positive integer used as an internal version number. This number is used only to determine whether one version is more recent than another, with higher numbers indicating more recent versions. This is not the version number shown to users; that number is set by the versionName setting.

It seems to me like you are using two different version numbers from the two platforms to mean the same thing in OneSignal.

I'd argue that on Android you should be using `versionName` if you're going to use `CFBundleShortVersionString` from iOS. Here's Google's description of `versionName`:

>  versionName — A string used as the version number shown to users. This setting can be specified as a raw string or as a reference to a string resource. The value is a string so that you can describe the app version as a <major>.<minor>.<point> string, or as any other type of absolute or relative version identifier. The versionName has no purpose other than to be displayed to users.

That sounds much closer to Apple's description of `CFBundleShortVersionString`; both are user visible, both can be in semantic versioning format

**Comment by jennantilla** [comment]
Hi @jalada thanks for sharing this feedback! We do not currently have a setting to switch version numbers between Android/iOS. Updating this would be a breaking change, so would be something to be considered as part of a future major release.

A workaround would be to set the version numbers you need as a [data tag](https://documentation.onesignal.com/docs/add-user-data-tags), or to send separate notifications for each type of version code.

**Comment by jennantilla** [comment]
Closing issue due to no response. Please @ mention me if we need to revisit this issue.

We have an updated major release available for our Android SDK with many improvements and enhancements! Please refer to the [migration guide](https://github.com/OneSignal/OneSignal-Android-SDK/blob/user-model/main/MIGRATION_GUIDE.md) for more information on upgrading.

Thanks!
