### ISSUE TITLE
[question]: Override "fallbackToSettings"-prompt?

### ISSUE THREAD

**Issue by TobiasEdqvist** [OneSignal/OneSignal-Android-SDK#1656]
### How can we help?

Hi,

Quick question. Is it possible to override the fallbackToSettings prompt design? We would like a completely different design for it than a normal "popup".

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @TobiasEdqvist

You can pass `false` into `promptForPushNotifications` to add your own prompt/UI.

Code example [here](https://github.com/OneSignal/OneSignal-Android-SDK/blob/d4002830e54b73e8dfc3213549a58ec4ced5e704/Examples/OneSignalDemo/app/src/main/java/com/onesignal/sdktest/model/MainActivityViewModel.java#L564).

Thanks!
