### ISSUE TITLE
Crash SQLiteDatabaseCorruptException from OneSignalDbHelper  [question]: 

### ISSUE THREAD

**Issue by antrd** [OneSignal/OneSignal-Android-SDK#1659]
### How can we help?

As the issue https://github.com/OneSignal/OneSignal-Android-SDK/issues/1432 is closed, I would like to reopen it in a new question, because the resolved error is a different one: SQLiteCantOpenDatabaseException. What about the **SQLiteDatabaseCorruptException**? 

Description
App crashes with android.database.sqlite.SQLiteDatabaseCorruptException.
It seems only occurs on Samsung devices running Android 10.
Currently this crash is by far the most relevant issue on our app.

Environment
Compile SDK: 30
OneSignal SDK: 4.4.2
OneSignal plugin: 0.13.4
Using Maven: yes

Stacktrace
Fatal Exception: android.database.sqlite.SQLiteDatabaseCorruptException
file is not a database (code 26 SQLITE_NOTADB[26]): , while compiling: PRAGMA journal_mode
android.database.sqlite.SQLiteConnection.nativePrepareStatement (SQLiteConnection.java)
android.database.sqlite.SQLiteConnection.acquirePreparedStatement (SQLiteConnection.java:1372)
android.database.sqlite.SQLiteConnection.executeForString (SQLiteConnection.java:960)
android.database.sqlite.SQLiteConnection.setJournalMode (SQLiteConnection.java:547)
android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration (SQLiteConnection.java:483)
android.database.sqlite.SQLiteConnection.open (SQLiteConnection.java:316)
android.database.sqlite.SQLiteConnection.open (SQLiteConnection.java:218)
android.database.sqlite.SQLiteConnectionPool.openConnectionLocked (SQLiteConnectionPool.java:737)
android.database.sqlite.SQLiteConnectionPool.open (SQLiteConnectionPool.java:284)
android.database.sqlite.SQLiteConnectionPool.open (SQLiteConnectionPool.java:251)
android.database.sqlite.SQLiteDatabase.openInner (SQLiteDatabase.java:1386)
android.database.sqlite.SQLiteDatabase.open (SQLiteDatabase.java:1336)
android.database.sqlite.SQLiteDatabase.openDatabase (SQLiteDatabase.java:967)
android.database.sqlite.SQLiteDatabase.openDatabase (SQLiteDatabase.java:955)
android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked (SQLiteOpenHelper.java:448)
android.database.sqlite.SQLiteOpenHelper.getWritableDatabase (SQLiteOpenHelper.java:391)
com.onesignal.OneSignalDbHelper.getSQLiteDatabase (OneSignalDbHelper.java:150)
com.onesignal.OneSignalDbHelper.getSQLiteDatabaseWithRetries (OneSignalDbHelper.java:174)
com.onesignal.OneSignalDbHelper.delete (OneSignalDbHelper.java:289)
com.onesignal.OSNotificationDataController$1.run (OSNotificationDataController.java:57)
java.lang.Thread.run (Thread.java:919)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@antrd In version 4.7.2 we released a fix for the issue mentioned in #1432. Have you tried updating to at least that version to see if the corruption issue is also fixed?

**Comment by jennantilla** [comment]
Closing this issue due to no response. Please @ mention me if we need to revisit after upgrading to at least 4.7.2.

Also noting that we have an updated major release available for our Android SDK with many improvements and enhancements! Please refer to the [migration guide](https://github.com/OneSignal/OneSignal-Android-SDK/blob/user-model/main/MIGRATION_GUIDE.md) for more information on upgrading.

Thanks!
