### ISSUE TITLE
[question]: Notification Images Not Showing in Battery-Saver mode

### ISSUE THREAD

**Issue by arndtdev** [OneSignal/OneSignal-Android-SDK#1665]
### How can we help?

Hi, 
I was wondering if the OneSignal SDK has any solution to loading images in Battery-Saver mode, other than the one mentioned in troubleshooting (hosting photos on OneSignal/Image size changing)? I am encountering this problem in every library I try to use and am trying to find the one without it. 
Thanks!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@appverkdev Thanks for the question. Battery-Saver mode varies quite a bit between Android versions and device manufactures. Normally the only side effect of enabling this is delayed notifications.

Can you list the **Android versions** and **device models** you have tested and noticed an issue with? Also list the **steps you took to enable the battery mode** to ensure we are comparing the same setting too.

**Comment by jkasten2** [comment]
@appverkdev Thanks for the details, could you capture the full logcat from the device for both these scenarios so it can be compared?
Make sure to also [enable OneSignal VERBOSE logging](https://documentation.onesignal.com/docs/sdk-reference#setloglevel-method).

Send a notification with an image:
1. With "battery saver" off. (ensure image shows
2. With "battery saver" on. (reproducing the issue)

You can share these here as attachments to your Github reply, or if you wish to keep the log private share with OneSignal support and link them to this thread.
