### ISSUE TITLE
[Bug]: Unable to instantiate service com.onesignal.GcmIntentJobService

### ISSUE THREAD

**Issue by Rabtman** [OneSignal/OneSignal-Android-SDK#1668]
### What happened?

Crashs at our app startup on Huawei devices and latest release of onesignal sdk (4.8.2)
![image](https://user-images.githubusercontent.com/25163658/195880337-faca24e4-68fe-49f8-be7b-5e28f32f9a2d.png)

### Steps to reproduce?

```Markdown
When users running Huawei devices with Android 10 launch our app
```

### What did you expect to happen?

 no crash

### OneSignal Android SDK version

Release 4.8.2

### Android version

10

### Specific Android models

```Markdown
Huawei devices
```

### Relevant log output

```Shell
Fatal Exception: java.lang.RuntimeException: Unable to instantiate service com.onesignal.GcmIntentJobService: java.lang.ClassNotFoundException: Didn't find class "com.onesignal.GcmIntentJobService" on path: DexPathList[[zip file "/data/app/-sZLjmgk3-1ARIAHymApY5A==/base.apk", zip file "/data/app/d-sZLjmgk3-1ARIAHymApY5A==/split_config.arm64_v8a.apk", zip file "/data/app/-sZLjmgk3-1ARIAHymApY5A==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/-sZLjmgk3-1ARIAHymApY5A==/lib/arm64, /data/app/-sZLjmgk3-1ARIAHymApY5A==/base.apk!/lib/arm64-v8a, /data/app/-sZLjmgk3-1ARIAHymApY5A==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/-sZLjmgk3-1ARIAHymApY5A==/split_config.xxhdpi.apk!/lib/arm64-v8a, /system/lib64, /hw_product/lib64, /system/product/lib64, /prets/lib64]]
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:4796)
       at android.app.ActivityThread.access$3000(ActivityThread.java:260)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2470)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:219)
       at android.app.ActivityThread.main(ActivityThread.java:8668)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@Rabtman Those devices may not have GMS and require HMS. This should not crash though so we will look into this. In the mean time have you tried setting up[ Huawei Messaging Service](https://documentation.onesignal.com/docs/huawei-sdk-setup)?

**Comment by jennantilla** [comment]
Closing this issue due to no response. Please @ mention me if we need to revisit.

We have an updated major release available for our Android SDK with many improvements and enhancements! Please refer to the [migration guide](https://github.com/OneSignal/OneSignal-Android-SDK/blob/user-model/main/MIGRATION_GUIDE.md) for more information on upgrading.

Thanks!
