### ISSUE TITLE
Invalid Proguard Rule

### ISSUE THREAD

**Issue by forrestbice** [OneSignal/OneSignal-Android-SDK#167]
`-keep public interface android.app.OnActivityPausedListener {*;}` from https://documentation.onesignal.com/docs/android-sdk-setup is invalid

**Comment by jkasten2** [comment]
@forrestbice This is valid and the exact line is in our prograud rules build into our .aar as well.
https://github.com/OneSignal/OneSignal-Android-SDK/blob/3.4.3/OneSignalSDK/onesignal/consumer-proguard-rules.pro#L8

It was however missing the following line which is required to keep Android 2.3 to 3.2 devices from crashing when progaurd is enabled.
```Java
-keep class com.onesignal.ActivityLifecycleListenerCompat** {*;}
```
