### ISSUE TITLE
[question]: Usage of Android Support library

### ISSUE THREAD

**Issue by cpaleop** [OneSignal/OneSignal-Android-SDK#1671]
### How can we help?

Recently we were looking to disable Jetifier on a project which depends on OneSignal SDK (version 4.8.2). We made use of [this third-party Gradle Plugin](https://github.com/dipien/bye-bye-jetifier) which detects and reports if any third party libraries still use the Android Support library and we got reports that OneSignal SDK uses `android.support.customtabs`.

From a quick search in your project I can see that this package is only being used in `ShadowCustomTabsClient`, which in turn is only being used in the unit-tests.

So my question is: Is it safe to ignore this report and remove Jetifier from our project?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@cpaleop Thanks for your question, yes you can remove Jetifier if OneSignal was the last thing in question. In [OneSignal-Android-SDK 4.0.0](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.0.0) we fully moved over to AndroidX (AKA Jetpack)
