### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by cassde** [OneSignal/OneSignal-Android-SDK#1676]
### What happened?

Android receives duplicate notifications when a push notification message includes a title, when the message is sent without a title, android receives just one notification as intended.

### Steps to reproduce?

```Markdown
send push notification to android users and add a title
```

### What did you expect to happen?

I expect to receive 1 notification on android

### OneSignal Android SDK version

react-native-onesignal: ^4.3.7

### Android version

12, 11

### Specific Android models

```Markdown
Android 12
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @cassde, 

You shared this issue at https://github.com/OneSignal/react-native-onesignal/issues/1444 as well. Let's keep the discussion there in one place, so I will close this issue.
