### ISSUE TITLE
Change from import of the OSUtils.java

### ISSUE THREAD

**Issue by ricardonostrum** [OneSignal/OneSignal-Android-SDK#1683]
### What's on your mind?

Good afternoon.

In order to add more value in relation to library security, I suggest changing the import "java.util.Random" to be replaced by "java.security.SecureRandom", in the OSUtils.java class.

No more for the moment, thank you.

Ricardo Magno da Silva

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@ricardonostrum Thanks for reporting, I took a look and I see `java.util.Random` is only used for a random delay currently so we don't see any security issue here.

However, I am sure this comes up as a flag in code analysis tools so we can look in cleaning that up as a lower priority issue.
