### ISSUE TITLE
[Bug]: Safe Areas Return [0,0,0,0] on an Android device with a cutout

### ISSUE THREAD

**Issue by isles1217** [OneSignal/OneSignal-Android-SDK#1696]
### What happened?

When building an in-app message for our landscape-oriented Android Application, we found that we were unable to pad the content based on the provided [Safe Area insets](https://documentation.onesignal.com/docs/design-your-in-app-message-with-html#5-design-for-notches-aka-safe-areas). Our web developers were able to ascertain that the inset returned is just an array of zeroes ([0,0,0,0]), and couldn't be used to correctly pad the content. We were forced to redesign our IAM since the insets weren't reliable. 

### Steps to reproduce?

```Markdown
1. Open an Android device that has a display cut out (notch), ie. Pixel 6
2. Trigger any of the In-App Messages in OneSignal to send to your test device
3. Drop a breakpoint here: https://github.com/OneSignal/OneSignal-Android-SDK/blob/0994a92661ebfa498b5c368f3cd60fb36bd00f48/OneSignalSDK/onesignal/src/main/java/com/onesignal/WebViewManager.java#L139
4. The insets array on the device returns [0,0,0,0], despite having a cutout potentially blocking content). 

Note that this may impact applications running in landscape orientation more than portrait orientations due to the location of the camera cutout.
```

### What did you expect to happen?

I expected the safe areas inset to return values to correctly pad the content, so that the content doesn't collide with the camera cutout. 

### OneSignal Android SDK version

4.8.2

### Android version

13

### Specific Android models

```Markdown
* Google Pixel 6
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@isles1217 Thanks for reporting, and narrowing it down to [com/onesignal/WebViewManager.java#L139](https://github.com/OneSignal/OneSignal-Android-SDK/blob/0994a92661ebfa498b5c368f3cd60fb36bd00f48/OneSignalSDK/onesignal/src/main/java/com/onesignal/WebViewManager.java#L139), that is helpful!

Is there any other devices in your testing that had the same issue or happened to work correctly? This will help narrow things down as Android notch logic varies quite a bit here.

Any screenshots or example In-App Messages you can share will also be helpful.

**Comment by jkasten2** [comment]
@isles1217 Is this issue still happening for you? If so, could you provide some of the details from above?

**Comment by jennantilla** [comment]
Closing issue due to no response. Please @ mention me if we need to revisit this issue.

We have an updated major release available for our Android SDK with many improvements and enhancements! Please refer to the [migration guide](https://github.com/OneSignal/OneSignal-Android-SDK/blob/user-model/main/MIGRATION_GUIDE.md) for more information on upgrading.

Thanks!
