### ISSUE TITLE
[BUG] inFocusDisplaying theme

### ISSUE THREAD

**Issue by Khang-NT** [OneSignal/OneSignal-Android-SDK#170]
When I enable `inFocusDisplaying`, OneSignal SDK show in-app dialog with white text, and white background, just happen in my android N device, with 4.4 device the dialog is fine.

**Comment by jkasten2** [comment]
@Khang-NT Can you check your theme related files (`AndroidManifest.xml`, `colors.xml`, etc) in your project  for background and text color?

The SDK uses `AlertDialog.Builder` without changing any of the color settings.
https://github.com/OneSignal/OneSignal-Android-SDK/blob/3.4.3/OneSignalSDK/onesignal/src/main/java/com/onesignal/GenerateNotification.java#L104

**Comment by Khang-NT** [comment]
Ok, got it. It depends on activity alert dialog theme. Thanks.
