### ISSUE TITLE
How to stop notification shows directly without handling them?

### ISSUE THREAD

**Issue by Dhvl-Golakiya** [OneSignal/OneSignal-Android-SDK#171]
HI,

I'm using this code in extenderService

    protected boolean onNotificationProcessing(OSNotificationReceivedResult receivedResult) {
        return true;
    }

But before going to NotificationReceivedHandler class, one notification with default message title and message content is displaying and another notification is showing from NotificationReceivedHandler. I'm sending additional data into payload and I want to show a notification only with additional data.

Please help.

**Comment by jkasten2** [comment]
@Dhvl-Golakiya If the above is your full `onNotificationProcessing` code then our SDK won't display a notification at all. If you are seeing a notification still then make sure you don't have any other SDKs trying to process GCM / FCM message.

Thanks.

**Comment by jkasten2** [comment]
@Dhvl-Golakiya Feel free to reopen this issue if you need any more help on this.
