### ISSUE TITLE
[Bug]: deeplink with parameters doesn't work 

### ISSUE THREAD

**Issue by ahmedgaber1244** [OneSignal/OneSignal-Android-SDK#1718]
### What happened?

i use latest sdk version and app can't use deep link sent with the notification 

![image](https://user-images.githubusercontent.com/16956573/211142578-58f39656-69d3-476f-99d9-89f089ba8080.png)

![image](https://user-images.githubusercontent.com/16956573/211142600-0bd8cef5-ab79-4b7f-8799-c0781e54caa1.png)

it always open main activity but never start the action suppose to happen

that's what i send 
![WhatsApp Image 2023-01-07 at 11 02 33 AM](https://user-images.githubusercontent.com/16956573/211142703-356ed4d4-9119-470a-b1eb-46d870c7933b.jpeg)

### Steps to reproduce?

```Markdown
1. send notification from one signal dashboard
2. click notification wether app in foreground or background
```

### What did you expect to happen?

use the param sent with notification to open particular screen on my app 
that's what i send 
![WhatsApp Image 2023-01-07 at 11 02 33 AM](https://user-images.githubusercontent.com/16956573/211142703-356ed4d4-9119-470a-b1eb-46d870c7933b.jpeg)

### OneSignal Android SDK version

4.8.4

### Android version

13, 12, 11, 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brismithers** [comment]
Hi @ahmedgaber1244 .  It looks like you are using `androidx.navigation` to control app navigation?  Would you be able to provide the `AndroidManifest.xml` file post-build?  As part of the [navigation component](https://developer.android.com/guide/navigation/navigation-deep-link#implicit), it will replace the `<nav-graph>` element with generated `<intent-filter>` elements to match all of the deep links in the navigation graph.

The resulting `<intent-filter>` is what we will need to see to determine why routing isn't happening successfully.

Note I've found this [issue](https://issuetracker.google.com/issues/154166825) which might be related.

Thanks!

**Comment by ahmedgaber1244** [comment]
Hi @brismithers  i think that's what you need 
`<activity
            android:name="hamza.solutions.audiohat.view.activity.MainActivity"
            android:configChanges="orientation|screenSize|screenLayout"
            android:exported="true"
            android:launchMode="singleTask"
            android:windowSoftInputMode="adjustPan" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data android:scheme="https" />
                <data android:host="audiohatdar.com" />
                <data android:path="/app-sharing" />
            </intent-filter>
            <intent-filter android:autoVerify="true" >
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data android:scheme="audiohatapp" />
                <data android:host="pushToBook" />
                <data android:path="/" />
            </intent-filter>
        </activity>`

**Comment by ahmedgaber1244** [comment]
still waiting for your kind reply

**Comment by m-asadullah** [comment]
@ahmedgaber1244 check your device settings or **Go to App Manager** and check your app settings. Whether your app allows to open links or not?

**Comment by ahmedgaber1244** [comment]
@m-asadullah it's set to be supported 
![Screenshot_2023-01-30-10-03-19-29_fc704e6b13c4fb26bf5e411f75da84f2](https://user-images.githubusercontent.com/16956573/215421020-3e0571ac-eada-4d9d-a167-15a2cb3278d4.jpg)

**Comment by brismithers** [comment]
@ahmedgaber1244 can you try this with "Auto Verify" unchecked?  I've only seen `android:autoVerify="true"` on URLs with an `http` or `https` scheme.  See Android's [documentation on auto verification](https://developer.android.com/training/app-links/verify-android-applinks).   Let me know if this fixes it!

**Comment by brismithers** [comment]
HI @ahmedgaber1244 can you please let us know if the above suggestion fixed your issue? Thanks!

**Comment by jennantilla** [comment]
Closing due to no response. 

@ahmedgaber1244 feel free to reach out if you are still having issues.

We have also release a new major version of OneSignal with many improvements and enhancements. Check it out [here](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.0.2).

Thanks!
