### ISSUE TITLE
A lot of crashes. NPE.

### ISSUE THREAD

**Issue by OlegTarashkevich** [OneSignal/OneSignal-Android-SDK#172]
Hi @jkasten2,
I found strange crash. It's appears only when I add onesignal to my project. I did an experiment - I published my app without onesignal and all works fine.
 I use v.3.4.3.
I need your library, but I don't want to lose my customers. Please look at the attached screenshot.
Seems onesignal has some places where occurs NPE. I can't reproduce it one my devices.
Please help ASAP!

![2017-02-13 1 45 14](https://cloud.githubusercontent.com/assets/13828110/22866907/83c07dee-f18e-11e6-80be-d939aa79c445.png)

**Comment by jkasten2** [comment]
@OlegTarashkevich Could you attach the full log from the Download.txt link on that page? Feel free to send it to OneSignal support if you can't make it public and link in this issue thread.

Thanks.

**Comment by OlegTarashkevich** [comment]
@jkasten2 Thank you for your fast response.

[xxxxxxxxxxx_issue_1034_crash_58A2960A0169000147A2C1D9D1C83EF3_915f9d818f7446c3a6b3cb4c2dc6817c_0_v1.txt](https://github.com/OneSignal/OneSignal-Android-SDK/files/773352/xxxxxxxxxxx_issue_1034_crash_58A2960A0169000147A2C1D9D1C83EF3_915f9d818f7446c3a6b3cb4c2dc6817c_0_v1.txt)
[xxxxxxxxxxx_issue_1351_crash_58A283BD01880001516A0E676B37B735_c97902caddfb43d5be31a920091444d2_0_v1.txt](https://github.com/OneSignal/OneSignal-Android-SDK/files/773353/xxxxxxxxxxx_issue_1351_crash_58A283BD01880001516A0E676B37B735_c97902caddfb43d5be31a920091444d2_0_v1.txt)

I see that it happened on IInAppBillingService.java, in-app billing library. I use it in the project. 
If I disable onesignal - I have no any crashes on that.

**Comment by jkasten2** [comment]
@OlegTarashkevich Thanks for the details the crash is coming from the `isBillingSupported` method in `IInAppBillingService.java`, line 208. It seems Google has a few different versions of this file but they don't document it well. Could you attach your `IInAppBillingService.aidl` and `IInAppBillingService.java`? The `.java` version should be under `app\build\generated\source\aidl\debug\com\android\vending\billing\IInAppBillingService.java` in your project folder.

**Comment by OlegTarashkevich** [comment]
Here they are:

[inApp_files.zip](https://github.com/OneSignal/OneSignal-Android-SDK/files/776893/inApp_files.zip)

Hope it helps

**Comment by jkasten2** [comment]
@OlegTarashkevich The crash seems to be happening from within Google's code however the root of the issue might be their code isn't thread safe.

Are you calling OneSignal init from the main thread or from another thread? How about your IAP code? Where is `IabHelper.startSetup(...)` being called?

**Comment by OlegTarashkevich** [comment]
@jkasten2 I'm calling OneSignal in Application class in onCreate method in the main thread.
All work properly at all my test devices. But I receive crashes... 

```
OneSignal.startInit(this)
                .autoPromptLocation(true)
                .init();
```

Also I'm calling `mIabHelper.startSetup(new IabHelper.OnIabSetupFinishedListener() {...`
in AsyncTask in doInBackground.

I think that is all weird.

**Comment by jkasten2** [comment]
@OlegTarashkevich This problem seems to be a race condition issue between multiple threads and is harder to fix / determine the issue since the crash is happening from inside of the IabHelper / IInAppBillingService classes.

Can you try calling `mIabHelper.startSetup` from the main thread? Google notes that is is process asynchronously and is safe to call from the main thread noted in their comments below.

https://github.com/googlesamples/android-play-billing/blob/4b2e7e21efe23cf72748388d3f591ece0597195e/TrivialDrive/app/src/main/java/com/example/android/trivialdrivesample/util/IabHelper.java#L209-L216

Do you have an kind of integration tests setup? Can you try running it tin a loop to see if you can reproduce this crash?

**Comment by jkasten2** [comment]
@OlegTarashkevich There have been a number of internal changes since our 3.4.3 SDK. Do you still see the issue in our 3.5.4 SDK?

**Comment by OlegTarashkevich** [comment]
Hey @jkasten2 thank you for your response. I've updated app in April and in begin of May, and need some time to get more statistics.

**Comment by jkasten2** [comment]
@OlegTarashkevich We haven't received any other reports of this. Feel free to add more details if you are still getting a crash after the SDK update. Thanks.
