### ISSUE TITLE
[Enhancement] Change playerId method 

### ISSUE THREAD

**Issue by DCKT** [OneSignal/OneSignal-Android-SDK#173]
Hello,

I've already posted something similar for React-Native (https://github.com/geektimecoil/react-native-onesignal/issues/144) about changing playerId after JavaScript events but it seems impossible ATM.

So I've take a look at the API and I would like to know if there is a way to manually change the playerId ?  
Thereby, I could make a PR to the React-Native module for adding the functionality. 

Thanks for your intereset !

**Comment by jkasten2** [comment]
@DCKT Thanks for the suggestion, we don't plan to allow the `player_id` to be changed for the device. I it is assigned by our server then returned to the device.

Instead I recommend using [`sendTag`](https://documentation.onesignal.com/docs/android-native-sdk#section--sendtag-) or [`syncHashedEmail`](https://documentation.onesignal.com/docs/android-native-sdk#section--synchashedemail-) to uniquely identify the device / user. You can then use `filters` on the OneSignal [create notification](https://documentation.onesignal.com/v3.0/reference#create-notification) REST API call to target specific users.

**Comment by casablancaplusplus** [comment]
Hi,

I really need this. I can generate the player id using the rest api. I just need to set it in the Android sdk of yours. Is there a work around ?

thanks in advance

**Comment by jkasten2** [comment]
@casablancaplusplus The OneSignal [player create / add a new device](https://documentation.onesignal.com/reference#add-a-device) REST API is used by this SDK to create a player with an id already. No need to make the REST API call your self in your app's code.
