### ISSUE TITLE
Default notification visibility is PUBLIC instead of Android default PRIVATE.

### ISSUE THREAD

**Issue by kistitan** [OneSignal/OneSignal-Android-SDK#174]
In GenerateNotification.java you have the following snippet:

```java
         int visibility = Notification.VISIBILITY_PUBLIC;
         if (gcmBundle.has("vis"))
            visibility = Integer.parseInt(gcmBundle.optString("vis"));
         notifBuilder.setVisibility(visibility);
```
Can you instead not set the visibilityof the notification if the 'vis' is not set in the Bundle? or rather set it to PRIVATE as that is the Android Default.

It can make difference when the user overrides the lock screen notification settings.

Thanks

**Comment by jkasten2** [comment]
@kistitan Thanks for the suggestion. We will consider changing this in the next major version release.

For those looking to change this setting on the current 3.X version it can be set with one of the following options.
1. [Background Data and Notification Overriding](https://documentation.onesignal.com/docs/android-customizations#section-background-data-and-notification-overriding).

2. Set `android_visibility` to 0 on all notification. Option also available on the dashboard.

**Comment by jkasten2** [comment]
@kistitan Update on this, Android Channels / Categories now default to private visibility.
https://documentation.onesignal.com/docs/android-notification-categories

Note, that if you set a category on your notification the channel setting will be applied even to pre-O devices.

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration

**Comment by rgomezp** [comment]
This has been resolved
