### ISSUE TITLE
[question]: App removed from Play Store, Reported issue on uploading users installed application information via OneSignal

### ISSUE THREAD

**Issue by tid3841** [OneSignal/OneSignal-Android-SDK#1741]
### How can we help?

Our app was removed from Google play, mentioning that our app is uploading users' installed application information via OneSignal SDK

Below is the message from Google Play Console

APK REQUIRES PROMINENT DISCLOSURE​
Your app is uploading users' Installed Application information to https://onesignal.com without a prominent disclosure. Prior to the collection and transmission, it must prominently highlight how the user data will be used, describe the type of data being collected and have the user provide affirmative consent for such use.

Note: 
We are already showing the prominent disclosure for all the datatypes that onesignal SDK is using following the link below
https://documentation.onesignal.com/docs/google-play-data-safety-requirements
our privacy policy has been updated accordingly

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jasminder** [comment]
Any update on this ?

**Comment by emawby** [comment]
@jasminder Updating to the latest OneSignal SDK should resolve this issue. If it does not please feel free to reopen
