### ISSUE TITLE
`onNotificationProcessing` is called many times when app launched.

### ISSUE THREAD

**Issue by Tecco** [OneSignal/OneSignal-Android-SDK#175]
Onesignal is very useful. Thanks :)
However, one problem came out.

```
public class NotificationReceivedService extends NotificationExtenderService {

    @Override
    protected boolean onNotificationProcessing(OSNotificationReceivedResult notification) {
        Log.d("onesignal", notification.payload.body);
        return false;
    }
}
```

When launching the application, the previous pushes are called at once.
```
02-19 12:13:10.707 17656-17733/com.tecc0.hoge D/onesignal: hey
02-19 12:13:11.022 17656-17733/com.tecc0.hoge D/onesignal: yeah
02-19 12:13:11.034 17656-17733/com.tecc0.hoge D/onesignal: wow
02-19 12:13:11.065 17656-17733/com.tecc0.hoge D/onesignal: good
02-19 12:13:11.097 17656-17733/com.tecc0.hoge D/onesignal: bad
...
```

If notification is manually deleted from the notification center, it will not be output to the log.
Is there a solution?

**Comment by jkasten2** [comment]
@Tecco When the app is cold started the SDK regenerates all notifications that haven't been dismissed or opened as you are seeing. This is to bring them back if the app was force closed as Android will remove them in this case.

We have a `notification.restoring` flag you can check in case you only need process the back ground event once. However you should still setup your customer properties and display it like the first time so the user does not miss your notification.

**Comment by Tecco** [comment]
> We have a notification.restoring

I found it! Thanks!

> However you should still setup your customer properties and display it like the first time so the user does not miss your notification.

OK, I'll try it.
