### ISSUE TITLE
[question]: InApp banner doesn't dismiss after button click

### ISSUE THREAD

**Issue by yargeel** [OneSignal/OneSignal-Android-SDK#1751]
### How can we help?

Hello!

Could you, please, help me with this issue: InApp banner doesn't dismiss after button click.

App part:
Android, Kotlin, I'm using com.onesignal:OneSignal:4.8.5
MainActivity/onCreate:
OneSignal.setInAppMessageClickHandler { result ->
            /// My stuff
}

OneSignal dashboard part:
Company: https://dashboard.onesignal.com/apps/a7b94694-44cc-4079-8d4a-548ab4571b1d/in_app_messages/ef549bba-d980-4cec-8ca1-be83cfd68ef6/edit
"Dismiss on click": TRUE
Button URL: app://fox-pizza.ru/?utm_source=mp&utm_medium=baza&utm_campaign=promokod&utm_content=20skidka&utm_term=samovyvoz

After appearing InApp banner and clicking a button my app does needed stuff, but banner blink's for a part of second and doesn't dismiss, unitl I clicked "X" button or swiping it down.

What should I do to correct such behaviour?

iOS app with the same funcionality working well.

Best regards,
Yaroslav

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brismithers** [comment]
Hi @yargeel .  I suspect it's related to the deep link URL you've specified.  If you remove the URL (or change it to something like `https://www.google.com`), does the IAM successfully dismiss?

**Comment by yargeel** [comment]
Hello!
Thank you for your answer.
In case I use http:// or https:// url scheme IAM successfully dismiss, BUT platform (both - iOS and Android) opens external browser (Chrome and Safari) with given url even if I have set OneSignal_suppress_launch_urls = TRUE.

**Comment by yargeel** [comment]
Is there any news?

**Comment by emawby** [comment]
Hello, are you using the `setLaunchURLs` function anywhere?

**Comment by yargeel** [comment]
Hello!
No, we don't.
Also, afair, setLaunchURLsInApp() method belongs to iOS SDK part.

**Comment by jennantilla** [comment]
Hello @yargeel apologies that this issue has gone stale. Are you still facing this issue? If so, can you please send over screenshots from your AndroidManifest.xml where you are suppressing the launch URL?

More general information about linking can be found [here](AndroidManifest.xml).

Thanks!

**Comment by jennantilla** [comment]
Closing due to no response.
