### ISSUE TITLE
Method "enableWebViewRemoteDebugging()" activated in class "WebViewManager.java"

### ISSUE THREAD

**Issue by ricardonostrum** [OneSignal/OneSignal-Android-SDK#1755]
### How can we help?

Goodnight.

After a static test using MobSF in version 3.3.0 of oneSignal, I got a feedback about the "WebViewManager.java" class that is using the "enableWebViewRemoteDebugging()" method and this was not recommended by the tool, as a good development practice safe. I would like your feedback, even so I can classify it as false/positive or not.

If performing the upgrade to version 4.8.5 is also a recommendation, we can arrange this process.

Here is the return of the tool:
CWE - 919: Weaknesses in Mobile Applications.
OWASP TOP 10: M1: Improper Platform Usage
OWASP MASVS:MSTG-RESILIENCE-2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
Hello we are [only using this method](https://github.com/OneSignal/OneSignal-Android-SDK/blob/1fcacef07478264d6a837d9748b6f4890cc11ea4/OneSignalSDK/onesignal/src/main/java/com/onesignal/WebViewManager.java#L504) if the OneSignal Log Level is set to debug. If you do not want to use this method in your release builds then we recommend not setting the OneSignal logging to Debug.

**Comment by manish-chimera** [comment]
> Hello we are [only using this method](https://github.com/OneSignal/OneSignal-Android-SDK/blob/1fcacef07478264d6a837d9748b6f4890cc11ea4/OneSignalSDK/onesignal/src/main/java/com/onesignal/WebViewManager.java#L504) if the OneSignal Log Level is set to debug. If you do not want to use this method in your release builds then we recommend not setting the OneSignal logging to Debug.

@emawby How we can not set the OneSignal logging to  Debug? I need to disable this for my webview app

**Comment by cabrerojas** [comment]
![image (2)](https://github.com/user-attachments/assets/ed55150f-6701-4bb6-85cb-c213caee6565)
setLogLevel(0)
This worked for me
