### ISSUE TITLE
Stacked/Grouped Android notification crashes app on open

### ISSUE THREAD

**Issue by calanti** [OneSignal/OneSignal-Android-SDK#177]
Using the basic/standard Android implementation ( OneSignal.startInit(this).init() in onCreate ) appears to crash my app shortly after opening if it was fully closed when launching from a grouped notification (multiple notifications stacked by same group_key)

Tested on;
Xiaomi Mi Max (Android 6.0.1)
LG Nexus 5X (Android 7.1.1)

I don't get much in terms of logs or errors, but I can see "Activity_launch_request" output for each notification within the stack.

**Comment by calanti** [comment]
This turned out to be a payload and AndroidManifest issue, our website url was in the payload and my AndroidManifest had an intent-filter to launch the app from our url.

**Comment by gaurangpatel** [comment]
I got a similar issue. When trying to open an Activity from NotificationOpenHandler, app is crashing since context is not available. 
Any idea? 
Intent intent = new Intent(MainActivity.getContext() , StartActivity.class);
         intent.putExtra("launchUrl", launchUrl);
        MainActivity.getContext().startActivity(intent);
