### ISSUE TITLE
[Bug]: Excessive wakelocks 

### ISSUE THREAD

**Issue by sureshmaidaragi1** [OneSignal/OneSignal-Android-SDK#1774]
### What happened?

Due to onesignal library our app is consuming a lot of battery. As you can see that battery historian showing almost 39min wake lock is acquired.

<img width="770" alt="Screenshot 2023-05-06 at 11 25 18 PM" src="https://user-images.githubusercontent.com/121005368/236639515-6c92f090-ad3c-40d1-9252-dd8f63840872.png">

### Steps to reproduce?

```Markdown
Just use android onesignal library in your project and generate bug report from android developer settings in phone. Use that bug report in battery historian
```

### What did you expect to happen?

Wake lock should not be more than 2sec for every push notification 

### OneSignal Android SDK version

4.0.0  4.99.99

### Android version

13, 12, 11, 10, 9, 8

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@sureshmaidaragi1 Thank you for reporting we will investigate

**Comment by sureshmaidaragi1** [comment]
We found that because of this wakelock our resulting in huge phone battery consumption, will be waiting to hear your resolution around this

**Comment by sureshmaidaragi1** [comment]
Please check some more details here

<img width="1502" alt="Screenshot 2023-05-09 at 6 44 41 PM" src="https://github.com/OneSignal/OneSignal-Android-SDK/assets/121005368/436f933a-72ae-4690-a79c-7fe145ec391b">
<img width="1120" alt="Screenshot 2023-05-09 at 6 53 10 PM" src="https://github.com/OneSignal/OneSignal-Android-SDK/assets/121005368/7beba43c-b19c-4784-b7f8-16f9615f2232">
<img width="1075" alt="Screenshot 2023-05-09 at 6 53 21 PM" src="https://github.com/OneSignal/OneSignal-Android-SDK/assets/121005368/465a842b-d72b-4464-b726-53da55741e81">

**Comment by sureshmaidaragi1** [comment]
Please check some more details here

<img width="1502" alt="Screenshot 2023-05-09 at 6 44 41 PM" src="https://github.com/OneSignal/OneSignal-Android-SDK/assets/121005368/436f933a-72ae-4690-a79c-7fe145ec391b">
<img width="1120" alt="Screenshot 2023-05-09 at 6 53 10 PM" src="https://github.com/OneSignal/OneSignal-Android-SDK/assets/121005368/7beba43c-b19c-4784-b7f8-16f9615f2232">
<img width="1075" alt="Screenshot 2023-05-09 at 6 53 21 PM" src="https://github.com/OneSignal/OneSignal-Android-SDK/assets/121005368/465a842b-d72b-4464-b726-53da55741e81">

**Comment by jkasten2** [comment]
@sureshmaidaragi1 we have refactored most of the code in our v5 SDK. Can you let us know if upgrading fixes this issue for you?
