### ISSUE TITLE
[question]: OneSignal playerId is null when Android Gradle Plugin is Updated

### ISSUE THREAD

**Issue by AbdullahEjazCheetay** [OneSignal/OneSignal-Android-SDK#1778]
### How can we help?

Recently we have updated the android-gradle-plugin from 7.0.4 to 7.4.2. 

On AGP v7.0.4 OneSignal is working fine and generating the device id
but on AGP v7.4.2 we are getting null whenever we try to fetch the device id.

One Signal initialization code in the application

```
 // OneSignal Initialization
OneSignal.setAppId(ONE_SIGNAl_APP_ID)
OneSignal.initWithContext(applicationContext)
```
And this is how we are getting device id

`val deviceId = OneSignal.getDeviceState()?.userId`

**Environment:**
OneSignal SDK Version: 4.8.5
AGP : 7.4.5
Firebase Boom: 30.5.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by michael-winkler** [comment]
Should the order not be:
```
OneSignal.initWithContext(applicationContext)
OneSignal.setAppId(ONE_SIGNAl_APP_ID)
```

?

**Comment by AbdullahEjazCheetay** [comment]
> Should the order not be:
> 
> ```
> OneSignal.initWithContext(applicationContext)
> OneSignal.setAppId(ONE_SIGNAl_APP_ID)
> ```
> 
> ?

tried it but same result.

**Comment by jennantilla** [comment]
Thank you for the information, @AbdullahEjazCheetay! We will attempt to reproduce/investigate on our end and get back to you as soon as possible.

**Comment by SamedHrmn** [comment]
Hi, any update?

**Comment by jennantilla** [comment]
Hello everyone! Apologies that this issue became stale. Is anyone still experiencing this? If so, would you please send over the [log](https://documentation.onesignal.com/docs/capturing-a-debug-log) from the device where you call `getDeviceState`?

Thanks!

**Comment by jennantilla** [comment]
Closing due to no response. Please let us know if you are still having any trouble with this.
