### ISSUE TITLE
[Bug]: Default message icon when update to AGP 8+

### ISSUE THREAD

**Issue by fillipeoliveira-hotmart** [OneSignal/OneSignal-Android-SDK#1783]
### What happened?

Hi,
After update my Gradle and AGP to 8.x, the notification icon on Onesignal return to be the default (bell icon).
Making some tests, I think the "problem" is that in AGP 8+ some config flags is now enabled by default, like `android.nonTransitiveRClass` and `android.nonFinalResIds`.
https://developer.android.com/build/releases/gradle-plugin#default-changes

If I disable these 2 flag, the custom icon back to work as intended.

### Steps to reproduce?

```Markdown
1. Update Gradle/AGP to 8.+
2. Be sure that `android.nonTransitiveRClass` and `android.nonFinalResIds` are enabled (default value)
3. Build a release version of the app
4. Check the notification icon
```

### What did you expect to happen?

The custom notification icon continue to work as before.

### OneSignal Android SDK version

4.8.5

### Android version

13, 12, 11, 10

### Specific Android models

```Markdown
Pixel 1
Pixel 6a
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @fillipeoliveira-hotmart thanks for flagging! We'll take a look.

**Comment by fillipeoliveira-hotmart** [comment]
Hi @jennantilla ,
Making more tests after, I just discover that besides turning off the `android.nonTransitiveRClass` solve our problem, it's may not be the cause.
I found that version of dexguard that we are using has a bug that are removing our `keep rule` of the notification icon. =/
After updating the dexguard version, the notification icon back to work even with `android.nonTransitiveRClass` enabled.

Thx.
