### ISSUE TITLE
Date & Time get updated on notifications when app is cold started

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-Android-SDK#179]
The date and time will be updated on notifications currently in the shade if the app is closed then started again. This is seems not be an issue on Android 7.0 but is reproducible on Android 5.0.1.

To fix the SDK will need to track the received time and set on the notification if it is being represented.

**Update:**
Tested on Android 7.1.1 and it is an issue as well. Probably an issue for all Android versions and just tested incorrectly on Android 7.0 before.

**Comment by chunghe** [comment]
Also reproducible on Android 6.0.

**Comment by jkasten2** [comment]
@chunghe Fixed in commit 26dd41009078142a528ae4a7ddba4efc92e829fa. It will be part of the 3.4.4 release.

**Comment by chunghe** [comment]
great news! appreciate!
