### ISSUE TITLE
[question]: Will we require any updates because of the upcoming FCM feature deprecation

### ISSUE THREAD

**Issue by GSala** [OneSignal/OneSignal-Android-SDK#1797]
### How can we help?

Firebase [announced some feature deprecation](https://firebase.google.com/support/faq#fcm-23-deprecation) related to legacy protocols being used for push. Will we need to update our clients with a newer version of the SDK or any new configuration, when those features are fully deprecated?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@GSala Good question we have some information in this [post](https://onesignal.com/blog/what-you-should-know-about-the-fcm-depreciation-announcement/), but we are hard at work supporting the newer FCM API and will have more updates in the future

**Comment by gdeglin** [comment]
Hi @GSala . No SDK update is necessary. The change will simply involve uploading your Firebase Service Account credentials file to the OneSignal dashboard. We will be introducing support for the new protocol and instructions on how to upload the Service Account credentials over the next few days.

**Comment by GSala** [comment]
Sounds good  👍

**Comment by gdeglin** [comment]
Update to this: Support for FCM v1 has been released, and you can update your existing apps to use it on the OneSignal dashboard.
