### ISSUE TITLE
Display push notifications as a banner instead of silently showing up on the system tray.

### ISSUE THREAD

**Issue by satyajitvure91** [OneSignal/OneSignal-Android-SDK#1807]
### How can we help?

I tried creating my own notification channel but when I send a push notification from one signal dashboard, it uses the default "Miscellaneous" channel which is of low importance. How do I setup Onesignal on my end to configure this?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @satyajitvure91 thank you for reaching out!

More information on channel configuration can be found [here](https://documentation.onesignal.com/docs/android-notification-categories).

If you create a channel with URGENT importance then the notification should make a sound and pop up on screen.

If you are still having difficulty, please share more about how you configured your channel. There are a few [reasons](https://documentation.onesignal.com/docs/android-notification-categories#why-are-my-android-categories-not-working) why the categories might not be working.

Thanks!

**Comment by jennantilla** [comment]
@satyajitvure91 just checking in--is this still an issue for you?
