### ISSUE TITLE
[Bug]: Cut-off inApp message

### ISSUE THREAD

**Issue by Popda** [OneSignal/OneSignal-Android-SDK#1808]
### What happened?

InApp message with parameter margin: without on web inApp creation form don't fit window size in App
tested with lib version 4.8.6 and 5.0.0
![image](https://github.com/OneSignal/OneSignal-Android-SDK/assets/14309340/67fd6146-e3f3-4cd2-a4cd-d7a1101ecada)
![image](https://github.com/OneSignal/OneSignal-Android-SDK/assets/14309340/0baee094-d87a-4a79-b80a-6cb457f05ce7)

### Steps to reproduce?

```Markdown
create full screen inApp message with margin: without 
send to App
see that dont fit screen size
```

### What did you expect to happen?

InApp fit screen like it shown in preview
![image](https://github.com/OneSignal/OneSignal-Android-SDK/assets/14309340/d645e56a-8df4-418c-8182-93024e9f07af)

### OneSignal Android SDK version

4.8.6, 5.0.0

### Android version

13

### Specific Android models

```Markdown
device: Realme GT Master Edition RMX3363
android: Android 13
Also was detected on other devices with android version 11 and higher
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
@Popda apologies for the delay! I haven't been able to reproduce this, are you still having this issue on the [latest release](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.0.5)? Thank you for the update!

**Comment by jennantilla** [comment]
Closing due to no response. @Popda if you are still experiencing this please feel free to respond!
