### ISSUE TITLE
[question]: Requesting Permission on Android 13

### ISSUE THREAD

**Issue by irinapopova124** [OneSignal/OneSignal-Android-SDK#1817]
### How can we help?

Two days ago, the Android SDK Setup Code for requesting permission was:

```
// optIn will show the native Android notification permission prompt.
// We recommend removing the following code and instead using an In-App Message to prompt for notification permission (See step 7)
OneSignal.getUser().getPushSubscription().optIn();
```

Now it is has become

```
        // requestPermission will show the native iOS notification permission prompt.
        // We recommend removing the following code and instead using an In-App Message to prompt for notification permission

        OneSignal.getNotifications().requestPermission(Continue.with(r -> {
            if (r.isSuccess()) {
                if (r.getData()) {
                    // `requestPermission` completed successfully and the user has accepted permission
                }
                else {
                    // `requestPermission` completed successfully but the user has rejected permission
                }
            }
            else {
                // `requestPermission` completed unsuccessfully, check `r.getThrowable()` for more info on the failure reason
            }
        }));
```

Please advise on what is the proper way to request permission on Android 13. Thanks a lot!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
@irinapopova124 thanks for reaching out!

To receive push notifications on the device, you can use either method.  `optIn` will resume receiving of push notifications or will prompt the user for push notifications permission if they have not yet been prompted. This method can also be used in conjunction with `optOut` if at any point you want the user to stop receiving push notifications on the current device (regardless of system-level permission status).

For greater control over prompting for push notification permission, you can use `requestPermission`.

Let us know if you have any additional questions or concerns!
