### ISSUE TITLE
error

### ISSUE THREAD

**Issue by palashmandokhot** [OneSignal/OneSignal-Android-SDK#182]
how to solve Error: Manifest merger failed with multiple errors in android studio?

**Comment by jkasten2** [comment]
@palashmandokhot Could you attach the full error you are seeing?

**Comment by palashmandokhot** [comment]
in android studio android manifestxml file two times  this code
repeat---------
 <activity android:name=".MainActivity" />
        <activity android:name=".MainActivity" />
 i send you error pic of merged text ---------

**Comment by palashmandokhot** [comment]
in android studio android manifestxml file two times  this code repeat---------
 <activity android:name=".MainActivity" />
        <activity android:name=".MainActivity" />
 i send you error pic of merged text ---------
![20170301_180153_resized b](https://cloud.githubusercontent.com/assets/26090315/23460313/c7c51080-feaa-11e6-9fcb-5ec376aa965b.jpg)

**Comment by jkasten2** [comment]
@palashmandokhot The error isn't related to OneSignal but it looks like you have duplicated entries in the same or multiple `AndroidManifest.xml` files in your project.
```XML
<activity android:name=".MainActivity" />
```

If you continue to see an issue I recommend putting your full `AndroidManifest.xml` on a gist and share it on Stackoverflow.

**Comment by palashmandokhot** [comment]
if i deleted one code then problem solve because this code two times
repeated.

**Comment by palashmandokhot** [comment]
Manifest merger failed with multiple errors is solved.tell me i give you
some codes can you add class,interface and enum in the codes.

On Thu, Mar 2, 2017 at 12:36 PM, Palash Mandokhot <palashmandokhot@gmail.com
