### ISSUE TITLE
[Question] Cannot resolve method 'disablePush' in 'OneSignal' ?

### ISSUE THREAD

**Issue by StevenRogre** [OneSignal/OneSignal-Android-SDK#1822]
### How can we help?

So I've been using the "disablePush" boolean in my app to let users opt in or out of getting notifications but the method is no longer present since I updated to the latest 5.0 version! Is there a new one or something? I cannot find anything in the docs or here!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @StevenRogre, thanks for reaching out!

the `disablePush` method has been deprecated in 5.0.0. However, you can still disable push notifications to the subscription using the [`optOut`](https://documentation.onesignal.com/docs/mobile-sdk#disabling-a-push-subscription) SDK methods.

Let us know if you have any additional questions or concerns!

**Comment by StevenRogre** [comment]
Thanks! I have another issue now lol.

` java.lang.Exception: Service interface com.onesignal.core.internal.application.IApplicationService could not be instantiated`

Seems to be happening after using ProGuard.

**Comment by jennantilla** [comment]
@StevenRogre we are working on updating ProGuard rules for 5.0.0.

You can track the issue and add any additional comments here: https://github.com/OneSignal/OneSignal-Android-SDK/issues/1810

I'll go ahead and close out this issue since the original question has been addressed.

Thanks!
