### ISSUE TITLE
[question]: Android Notification Service Extension in v5.0.0

### ISSUE THREAD

**Issue by ngoni** [OneSignal/OneSignal-Android-SDK#1825]
### How can we help?

The official documentation for v5.0.0 covers use of [Android Notification Service Extension.](https://documentation.onesignal.com/docs/service-extensions#android-notification-service-extension)

I can't find the class `OSRemoteNotificationReceivedHandler`. Has this been removed? 

I want to receive data in the background, as in version v4.x.x

Is there an alternative approach?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ngoni** [comment]
After a bit of searching I found this [implementation](https://github.com/OneSignal/OneSignal-Android-SDK/blob/user-model/main/Examples/OneSignalDemo/app/src/main/java/com/onesignal/sdktest/notification/NotificationServiceExtension.java), which has the updated class to use:  `INotificationServiceExtension`

Your documentation will need updating :-)

**Comment by jennantilla** [comment]
Thanks for pointing this out, @ngoni! We've updated the documentation.
