### ISSUE TITLE
Why new version don't send Ip address to OneSignal Subscriptions dashboard

### ISSUE THREAD

**Issue by IlliaMel** [OneSignal/OneSignal-Android-SDK#1838]
### How can we help?

I am using OneSignal in my project. The previous version worked fine. After initializing values and sending tags from the user, I could check data on OneSignal Subscriptions dashboard. Now, I want to use the new version of OneSignal, 5.0.1. However, when I perform the same operations, the client's IP address doesn't appear. All other data comes but the country and api address do not

https://prnt.sc/pbWKhk47k0Re (print screen)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello @IlliaMel thank you for reaching out! We are currently investigating this and will let you know when resolved.

**Comment by kat0d** [comment]
no ip, country and wrong language tag, it' "en" for all users

**Comment by jennantilla** [comment]
Hi @kat0d--we have fixed the language issue in our latest release,[ 5.0.2](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.0.2).

We are still investigating the IP/country issue; it is being tracked [here](https://github.com/OneSignal/OneSignal-Android-SDK/issues/1833). For consolidation purposes, I'm going to close this issue. Please check the other thread for updates!
