### ISSUE TITLE
how to solve error:class,interface or enum expected in codes in android studio?

### ISSUE THREAD

**Issue by palashmandokhot** [OneSignal/OneSignal-Android-SDK#184]
how to add class,interface and enum in this codes------------------
import com.apptracker.android.listener.AppModuleListener;
import com.apptracker.android.track.AppTracker;

 
public class MainActivity extends Activity {
       
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
 
        if(savedInstanceState == null) {
     
            AppTracker.startSession(getApplicationContext(),"YOUR_APP_API_KEY",AppTracker.ENABLE_AUTO_CACHE);
        }

        AppTracker.loadModuleToCache(getApplicationContext(),"inapp");
    }
 
    public void gameOver() {
      
        if(AppTracker.isAdReady("inapp")) {
                AppTracker.loadModule(getApplicationContext(),"inapp");
        }
    }
}
AppTracker.setAgeRange("18-25"); 
// Allowed values for Age range are: "13-17", "18-25", "26-35", "36-45", "46+"
 
AppTracker.setGender("Female"); 
// Allowed values for Gender are: "Male", "Female"
import com.apptracker.android.listener.AppModuleListener;
import com.apptracker.android.track.AppTracker;

 
public class MainActivity extends Activity {
 
	private AppModuleListener leadboltListener = new AppModuleListener() {
		@Override
		public void onModuleLoaded(String location) {
		
		}
		@Override
		public void onModuleFailed(String location, String error, boolean isCache) {}
		@Override
		public void onModuleClosed(String location) {
			
		}
		@Override
		public void onModuleClicked(String location) {}
		@Override
		public void onModuleCached(String location) {
			// Add code if not auto-recaching for when loadModuleModuleToCache is successful
		}
		@Override
		public void onMediaFinished(boolean viewCompleted) {
			if(viewCompleted) {
				Log.i("AppTracker", "User finished watching rewarded video");
			} else {
				Log.i("AppTracker", "User skipped watching rewarded video");
			}
		}
	};
       
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
 
        if(savedInstanceState == null) {
       
            AppTracker.setModuleListener(leadboltListener);
			AppTracker.startSession(getApplicationContext(),"YOUR_APP_API_KEY",AppTracker.ENABLE_AUTO_CACHE);
        }

        AppTracker.loadModuleToCache(getApplicationContext(),"video");
    }
 
    public void gameOver() {
     
        if(AppTracker.isAdReady("video")) {
                AppTracker.loadModule(getApplicationContext(),"video");
        }      
    }
}

**Comment by jkasten2** [comment]
@palashmandokhot I don't see `OneSignal` in your code. Please make sure to follow each step in our setup guide below.
https://documentation.onesignal.com/docs/android-sdk-setup

**Comment by palashmandokhot** [comment]
what is one signal ?

**Comment by palashmandokhot** [comment]
can you add class,interface and enum in codes

**Comment by palashmandokhot** [comment]
can you add class,interface and enum in codes because i dont know where add
class,interface and enum in the codes and try but in android studio again
and again shows error:class,interface and enum expected.
