### ISSUE TITLE
how to add class,interface and enum in leadbolt codes?

### ISSUE THREAD

**Issue by palashmandokhot** [OneSignal/OneSignal-Android-SDK#185]
import com.apptracker.android.listener.AppModuleListener;
import com.apptracker.android.track.AppTracker;
// Leadbolt SDK imports
 
public class MainActivity extends Activity {
       
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
 
        if(savedInstanceState == null) {
            // Initialize Leadbolt SDK with your api key
            AppTracker.startSession(getApplicationContext(),"YOUR_APP_API_KEY",AppTracker.ENABLE_AUTO_CACHE);
        }
        // cache Leadbolt Ad without showing it
        AppTracker.loadModuleToCache(getApplicationContext(),"inapp");
    }
 
    public void gameOver() {
        // call this when you want to display the Leadbolt Interstitial
        if(AppTracker.isAdReady("inapp")) {
                AppTracker.loadModule(getApplicationContext(),"inapp");
        }
    }
}
AppTracker.setAgeRange("18-25"); 
// Allowed values for Age range are: "13-17", "18-25", "26-35", "36-45", "46+"
 
AppTracker.setGender("Female"); 
// Allowed values for Gender are: "Male", "Female"
import com.apptracker.android.listener.AppModuleListener;
import com.apptracker.android.track.AppTracker;
// Leadbolt SDK imports
 
public class MainActivity extends Activity {
 
	private AppModuleListener leadboltListener = new AppModuleListener() {
		@Override
		public void onModuleLoaded(String location) {
			// Add code here to pause game and/or all media including audio
		}
		@Override
		public void onModuleFailed(String location, String error, boolean isCache) {}
		@Override
		public void onModuleClosed(String location) {
			// Add code here to resume game and/or all media including audio
		}
		@Override
		public void onModuleClicked(String location) {}
		@Override
		public void onModuleCached(String location) {
			// Add code if not auto-recaching for when loadModuleModuleToCache is successful
		}
		@Override
		public void onMediaFinished(boolean viewCompleted) {
			if(viewCompleted) {
				Log.i("AppTracker", "User finished watching rewarded video");
			} else {
				Log.i("AppTracker", "User skipped watching rewarded video");
			}
		}
	};
       
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
 
        if(savedInstanceState == null) {
            // Initialize Leadbolt SDK with your api key
            AppTracker.setModuleListener(leadboltListener);
			AppTracker.startSession(getApplicationContext(),"YOUR_APP_API_KEY",AppTracker.ENABLE_AUTO_CACHE);
        }
        // cache Leadbolt Video Ad without showing it
        AppTracker.loadModuleToCache(getApplicationContext(),"video");
    }
 
    public void gameOver() {
        // call this when you want to display the Leadbolt Video
        if(AppTracker.isAdReady("video")) {
                AppTracker.loadModule(getApplicationContext(),"video");
        }      
    }
}
1
2
3
4
5
AppTracker.setAgeRange("18-25"); 
// Allowed values for Age range are: "13-17", "18-25", "26-35", "36-45", "46+"
 
AppTracker.setGender("Female"); 
// Allowed values for Gender are: "Male", "Female"
private AppModuleListener leadboltListener = new AppModuleListener() {
    @Override
    public void onModuleLoaded(String location) {
        Log.i("AppTracker", "Ad loaded successfully - "+location);
        // Add code here to pause game and/or all media including audio
    }
    @Override
    public void onModuleFailed(String location, String error, boolean isCache) {
        if(isCache) {
            Log.i("AppTracker", "Ad failed to cache - "+location);
        } else {
            Log.i("AppTracker", "Ad failed to display - "+location);
        }
    }
    @Override
    public void onModuleClosed(String location) {
        Log.i("AppTracker", "Ad closed by user - "+location);
        // Add code here to resume game and/or all media including audio
    }
    @Override
    public void onModuleClicked(String location) {
        Log.i("AppTracker", "Ad clicked by user - "+location);
    }
    @Override
    public void onModuleCached(String location) {
        Log.i("AppTracker", "Ad cached successfully - "+location);
        // Add code if not auto-recaching for when loadModuleModuleToCache is successful
    }
    @Override
    public void onMediaFinished(boolean viewCompleted) {
        if(viewCompleted) {
            Log.i("AppTracker", "User finished watching rewarded video");
        } else {
            Log.i("AppTracker", "User skipped watching rewarded video");
        }
    }
};
AppTracker.setModuleListener(leadboltListener);
AppTracker.startSession(getApplicationContext(),"YOUR_APP_API_KEY",AppTracker.ENABLE_AUTO_CACHE);

**Comment by jkasten2** [comment]
@palashmandokhot I don't believe your question relates to OneSignal as you noted in your other issue https://github.com/OneSignal/OneSignal-Android-SDK/issues/184#issuecomment-283932897.
I recommend posting your question on http://stackoverflow.com/.

**Comment by palashmandokhot** [comment]
you not add class,interface and enum in the code.

**Comment by palashmandokhot** [comment]
can you add class,interface and enum in the codes

**Comment by palashmandokhot** [comment]
tell me can you add class,interface and enum in codes.
