### ISSUE TITLE
How to get player ID in one signal 5.0.2 in android java?[question]: 

### ISSUE THREAD

**Issue by FaribaLaiq** [OneSignal/OneSignal-Android-SDK#1855]
### How can we help?

I checked the answers on the internet but those methods does not work for one signal 5.0.2. So how can I get the player ID there?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @FaribaLaiq thanks for reaching out! In 5.x.x, Player ID is now Subscription ID. Code examples for accessing this can be found [here](https://documentation.onesignal.com/docs/mobile-sdk#subscription-id).

Let us know if you have any additional questions or concerns!
