### ISSUE TITLE
[question]: When does the SDK Version in the console get updated?

### ISSUE THREAD

**Issue by Dev-Czle** [OneSignal/OneSignal-Android-SDK#1859]
### How can we help?

I was testing with SDK version 4.8.6, and I recently updated to the newly released 5.0.2 version. However, when I checked the OneSignal console - Audience - Subscriptions, I still see that the SDK Version is listed as 040806. When is this supposed to change? I've also tried restarting the app, but the issue persists.

<img width="447" alt="image" src="https://github.com/OneSignal/OneSignal-Android-SDK/assets/64242983/623fdfd5-3e4c-4701-9b2e-fb5b8cc46212">

Device : Galaxy ZFlip3 5g
OS : Android 13
Notification Permission : X (Denied 4.8.6)
Root : X

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @Dev-Czle thanks for reaching out! We're looking into this and will get back to you as soon as possible.

**Comment by jennantilla** [comment]
Hi @Dev-Czle thank you for your patience on this! This was fixed in our latest release, [5.0.5](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.0.5). Please feel free to update to this version and let us know if you have any additional questions or concerns!
