### ISSUE TITLE
Badge count not displaying on Samsung Android 7.0+ devices

### ISSUE THREAD

**Issue by Buli1212** [OneSignal/OneSignal-Android-SDK#186]
As soon as I updated software the badge count stopped being displayed on my devices. Other applications like Facebook Messengers are still showing it correctly. Badges are not disabled in manifest or any other .xml files.

**Comment by jkasten2** [comment]
@Buli1212 Could you include the exact device model and Android version you are testing on? Also well as confirm you are using our 3.4.3 SDK?

**Comment by Buli1212** [comment]
compile 'com.onesignal:OneSignal:3.+@aar'
Nexus 9 tablet and Samsung Galaxy S7 Edge. Both on Android 7.0

**Comment by jkasten2** [comment]
@Buli1212 We use the [ShortcutBadger](https://github.com/leolin310148/ShortcutBadger) and have updated from version 1.1.11 to 1.1.13 which fixed issues with some Samsung devices.

However we haven't created a new release for this yet. Can try this build to see if it fixes the issue on your Samsung devices?
[onesignal-release.zip](https://github.com/OneSignal/OneSignal-Android-SDK/files/822898/onesignal-release.zip)

Instructions on using a local .aar
https://gist.github.com/jkasten2/4683711807373dabaf5d5833b9574bb1

**Comment by jkasten2** [comment]
@Buli1212 Can you try using the latest version (1.1.14) of [ShortcutBadger](https://github.com/leolin310148/ShortcutBadger) in your app. Try setting a badge value in code and let us know if it works on your device. We can update our library to use this version if so to fix the issue.

**Comment by jkasten2** [comment]
@Buli1212 I have updated the ShortcutBader library to 1.1.16 in commit aad2e82fce2db728b5408e974e2ee654b9fa8591 which includes the fix I noted above. It seems like this should fix issues with Samsung devices with Android 5.0 and newer. It will be included in the 3.4.4 release.
