### ISSUE TITLE
[question]: How do I stop pushing default notifications so I can customize my notifications?

### ISSUE THREAD

**Issue by buivu2108** [OneSignal/OneSignal-Android-SDK#1861]
### How can we help?

In the old version: I can block system notifications with the command:
   notificationReceivedEvent?.complete(null)
in the above command:
class NotificationWillShowInForegroundHandler : OneSignal.OSNotificationWillShowInForegroundHandler {

     override fun notificationWillShowInForeground(notificationReceivedEvent: OSNotificationReceivedEvent?) {
         when (isHideInForeground) {
             true -> {
                 notificationReceivedEvent?.complete(null)
             }
             else -> {
                 notificationReceivedEvent?.complete(notificationReceivedEvent.notification)
             }
         }
     }
}

How can I do the same with the new version v11.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by michael-winkler** [comment]
There exist now a method which is called "preventDefault()".
It's a method from "notificationevent"

**Comment by buivu2108** [comment]
> There exist now a method which is called "preventDefault()". It's a method from "notificationevent"

Please be more specific. Thank you very much

**Comment by jennantilla** [comment]
Thanks for answering, @michael-winkler! Let us know if there are any additional questions or concerns.
