### ISSUE TITLE
How can I obtain the User Onesignal id once the permissions have been accepted?

### ISSUE THREAD

**Issue by iber-fernandez-darkmaster** [OneSignal/OneSignal-Android-SDK#1864]
### How can we help?

I want to recover that value

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @iber-fernandez-darkmaster! Are you looking to access the subscription ID or the onesignal_id?

For the former, you can access it via the [SDK](https://documentation.onesignal.com/docs/mobile-sdk#subscription-id).

You can use our [API View User](https://documentation.onesignal.com/reference/view-user) endpoint to access all IDs for a user.

Please let us know if you have any additional questions or concerns!
