### ISSUE TITLE
Why the process is recreated after killed the application ?

### ISSUE THREAD

**Issue by safety97** [OneSignal/OneSignal-Android-SDK#187]
Hello, i have the last version 3.4.3 of the SDK and each time i kill the app, by android studio or from the device, the process of my application is automatically re-created.
I guess there is a sticky service which re-start itself since the app is killed. It is possible to create the service in another process to avoid this ? 
it's really annoying because i have to do some action if the process is alive or not.  

Thank's you in advance.

**Comment by jkasten2** [comment]
@safety97 Correct, we do use `START_STICKY` on our `SyncService`. It is used to make sure any pending tags, sessions, and other fields are synced to OneSignal in case the app is closed before it had to chance to make a network request.

We will look into seeing if the service can be run on a different process without issues but I believe that our usage of `SharedPreferences` will prevent this. I'll update this issue when we have more information.

**Comment by safety97** [comment]
@jkasten2 Yes, indeed the `SharedPreferences` should be used in the same process.
Thank's for the reply.

**Comment by jkasten2** [comment]
@safety97 I have changed the `SyncService` to only restart the service if there are pending changes that haven't been sent to OneSignal's server's yet in commit cf7b242bf500c64dceb02ced8cd1df566f7b16a6. This will be included in the next 3.4.4 release.

Do note that every time a notification is received your `Application` `onCreate` will start as well which is unavoidable. Additionally any other `BroadcastReceiver` or `Service` will fire this as well so I recommend making sure your code in it isn't to resource heavily.

**Comment by safety97** [comment]
Ok thank you very much !
