### ISSUE TITLE
[Bug]: On Android 14 showing blank page on click the notification (v11.0)

### ISSUE THREAD

**Issue by imrankst1221** [OneSignal/OneSignal-Android-SDK#1870]
### What happened?

Getting blank page on click of notification on android 14 (Pixel 5).

### Steps to reproduce?

```Markdown
1. Update in to version [5.0.0, 5.99.99]
2. Run the app on Android 14 (Pixel 5)
3. Send test notification 
4. When app is open click on the notification 
5. Showing blank screen with a text box and button "TEST"
```

### What did you expect to happen?

When app is open and click on the notification. 

### OneSignal Android SDK version

[5.0.0, 5.99.99]

### Android version

13

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@imrankst1221 Are you using deep linking (launch urls) in your notifications?

**Comment by imrankst1221** [comment]
@emawby Yes I am using the deep link but it's not looks like any webpage. Even I change the deep link URL with very popular website but each time it's showing a popup with Test button and a test editor.

**Comment by jennantilla** [comment]
Closing due to no response.
