### ISSUE TITLE
[question]: How to remove Android Permission Location from Android Manifest?

### ISSUE THREAD

**Issue by herotha** [OneSignal/OneSignal-Android-SDK#1875]
### How can we help?

When I submit to Play Store, I just noticed my app has extra Android android.permission.ACCESS_COARSE_LOCATION.
Is there anyway to omit that permission from my App Manifest?
I just upgraded OneSignal SDK to version 5.0.3. And I don't want my user know I have this permission inside my app.

![Screenshot 2023-10-19 191254](https://github.com/OneSignal/OneSignal-Android-SDK/assets/8534773/5b9c778f-484e-4fe5-8998-9dd95b435e7f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @herotha thanks for reaching out!

Did you previously have [location sharing](https://documentation.onesignal.com/docs/mobile-sdk#location) enabled?

Adding android.permission.ACCESS_COARSE_LOCATION is part of the location sharing setup but this is not required to use the OneSignal SDK. If you don't want to track location, you can remove this, although I am unsure if any other SDKs or libraries in your app may need it.

Thanks for the additional information!

**Comment by brismithers** [comment]
Hi @herotha, one possible solution is, rather than include the entire `com.onesignal:OneSignal` dependency,  you can update your App's build.gradle to only specify the individual modules you want included:

```
dependencies {
  implementation 'com.onesignal:core:[5.0.0, 5.99.99]'
  implementation 'com.onesignal:in-app-messages:[5.0.0, 5.99.99]'
  implementation 'com.onesignal:notifications:[5.0.0, 5.99.99]'
}
```

**Comment by nan-li** [comment]
Users of the native OneSignal Android SDK can remove the location module from dependencies. Closing this issue as resolved.

We are investigating how to address this in OneSignal's cross platform SDKs as brought up in the linked issue on Unity above.
