### ISSUE TITLE
[Bug]: can't set external id by login function

### ISSUE THREAD

**Issue by MohammedShehata** [OneSignal/OneSignal-Android-SDK#1879]
### What happened?

I used the last version of one signal 5.0.3
and tried to login by an external id

```
val externalId = "....."
OneSignal.login(externalId)
```
but it is never been saved!

Any help!
Thanks!

### Steps to reproduce?

```Markdown
1- install one signal 5.0.3
2- login by external id
3- external id is never been set
```

### What did you expect to happen?

I expect the external id is set successfully w.r.t the documentation

### OneSignal Android SDK version

5.0.3

### Android version

12, 11, 10, 9

### Specific Android models

```Markdown
Tried on a lot of devices, it is not related to a specific device
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MohammedShehata** [comment]
I had to downgrade to version **4.8.5** and it is working well now, so if it will be nice to fix it on your last version

**Comment by jennantilla** [comment]
Hi @MohammedShehata thanks for reaching out! I'm not able to reproduce this--logging in by external id is successful for me. Would you be able to include the [log](https://documentation.onesignal.com/docs/capturing-a-debug-log) from your device(s) reproducing this behavior? We'll be happy to take a look!

**Comment by nan-li** [comment]
Hi @MohammedShehata,

Thank you for following up.

I see in your logs that `Operation execution failed without retry` so there should be more information above this about the request that was sent and the error response. Do you still have the complete logs?

In particular, I am looking for any logs that contain `HttpClient: `. These will contain the requests the SDK sends for user creation, logging in, or any other updates, and the responses from the server to these requests. Somewhere in there should be the request that failed and the actual error message.

```
D/OneSignal: [DefaultDispatcher-worker-1] HttpClient: POST apps/<YOUR_APP_ID>/users - <REQUEST_BODY>

D/OneSignal: [DefaultDispatcher-worker-1] HttpClient: POST apps/<YOUR_APP_ID>/users - STATUS: 201 JSON: <RESPONSE_BODY>
```

**Comment by jennantilla** [comment]
@MohammedShehata just checking in to see if you received our previous response?

**Comment by jennantilla** [comment]
Closing due to no response. @MohammedShehata feel free to reach back out if you are still experiencing issues.
