### ISSUE TITLE
Random error dialog shown when GCM connection fails 5 times

### ISSUE THREAD

**Issue by martyglaubitz** [OneSignal/OneSignal-Android-SDK#188]
When having no internet connection - the sdk sometimes just displays this error.
I've already found the code that's responsible for that: https://github.com/OneSignal/OneSignal-Android-SDK/blob/master/OneSignalSDK/onesignal/src/main/java/com/onesignal/PushRegistratorGPS.java#L104

This stuff looks almost like some debug statement which someone forgot to take out.
I can't see any option to make sure this disruptive message isn't going to be shown to our users...

![gcm_error](https://cloud.githubusercontent.com/assets/1542037/23790823/01bc6b30-0581-11e7-86e3-c7f5f2288339.jpeg)

**Comment by jkasten2** [comment]
@martyglaubitz The screenshot is from the code you linked to. This is only showing as you are calling `OneSignal.setLogLevel` somewhere in your code. You should remove `setLogLevel` before releasing your app.

**Comment by DimaKoz** [comment]
@martyglaubitz I hope it will be useful for you :
```
if (BuildConfig.DEBUG) {
    OneSignal.setLogLevel(OneSignal.LOG_LEVEL.DEBUG, OneSignal.LOG_LEVEL.WARN);
} else {
    OneSignal.setLogLevel(OneSignal.LOG_LEVEL.NONE, OneSignal.LOG_LEVEL.NONE);
}
```

**Comment by martyglaubitz** [comment]
@DimaKoz yes we're doing that. the thing is i was looking for the code which decides whether this dialog is shown or not and couldn't really find anything. Turns out https://github.com/OneSignal/OneSignal-Android-SDK/blob/master/OneSignalSDK/onesignal/src/main/java/com/onesignal/PushRegistratorGPS.java#L90 was what i was looking for...

**Comment by jkasten2** [comment]
@martyglaubitz The screenshot you posted is from the following line.
https://github.com/OneSignal/OneSignal-Android-SDK/blob/3.4.3/OneSignalSDK/onesignal/src/main/java/com/onesignal/PushRegistratorGPS.java#L164

The [`ShowUpdateGPSDialog`](https://github.com/OneSignal/OneSignal-Android-SDK/blob/3.4.3/OneSignalSDK/onesignal/src/main/java/com/onesignal/PushRegistratorGPS.java#L104) method is different, it shows a dialog with the following message.
`"To receive push notifications please press 'Update' to enable 'Google Play services'."` with an "Update", "Skip", and "Close" button. This should be extremely rare to see as the Google Play Services app disabled or not installed if the Play Store is which we also check before prompting to update / enable.

**Comment by martyglaubitz** [comment]
@jkasten2 i know, but still - no SDK should throw a random modal dialog at it's user. You either:
1. Crash with an Exception which message says clearly what went wrong
2. You log an error which tells the developer what's wrong and what to do about it.

Think about it - how would a CI build catch this?
