### ISSUE TITLE
[Bug]: Gradle crash when using another dependency that uses latest work-runtime version

### ISSUE THREAD

**Issue by rubenferreira97** [OneSignal/OneSignal-Android-SDK#1889]
### What happened?

The latest version does not compile when using another dependency that uses latest work-runtime version (2.8.1).

OneSignal SDK should update the gradle version to `require ['2.1.0, 2.8.99], prefer '2.8.1`.
```
api('androidx.work:work-runtime') {
        version {
            require '[2.1.0, 2.7.99]'
            prefer '2.7.1'
        }
    }
```

### Steps to reproduce?

```Markdown
1. Compile a project that uses a dependency with the latest work-runtime version (2.8.1). In my case I am using workmanager.
```

### What did you expect to happen?

I expected the app to compile without gradle errors.

### OneSignal Android SDK version

Release 5.0.3

### Android version

12

### Specific Android models

```Markdown
Android 12
Xiaomi Redmi Note 9S
```

### Relevant log output

```Shell
* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class androidx.work.OneTimeWorkRequestKt found in modules work-runtime-2.8.1-runtime (androidx.work:work-runtime:2.8.1) and work-runtime-ktx-2.7.1-runtime (androidx.work:work-runtime-ktx:2.7.1)
     Duplicate class androidx.work.PeriodicWorkRequestKt found in modules work-runtime-2.8.1-runtime (androidx.work:work-runtime:2.8.1) and work-runtime-ktx-2.7.1-runtime (androidx.work:work-runtime-ktx:2.7.1)

     Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Thanks for reaching out @rubenferreira97! We'll work on incorporating this into our next release.

**Comment by jennantilla** [comment]
@rubenferreira97 heads up this has been updated in [5.0.4](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.0.4).

Let us know if you have any additional questions or concerns!
