### ISSUE TITLE
Any callback for auto register

### ISSUE THREAD

**Issue by KingWu** [OneSignal/OneSignal-Android-SDK#189]
Hi,
OneSignal initialize it on Application's onCreate function. When the device without network connection to open an application, OneSignal cannot auto register. Also, there is no callback to know whether Registration is successful or not. 

Any callback forr auto register? Or, can i manually to trigger the registration. 

Based on the current SDK structure, i cannot make sure the users is successful to register the push service.

**Comment by jkasten2** [comment]
@KingWu Our SDK should continue to retry if the device does not have a stable connection or no connection at all. It does increasing back off so it might take a while if the device has been offline for a while before making a connection again. Make sure you are using the latest SDK which is 3.4.3 currently.

You can use [`idsAvailable`](https://documentation.onesignal.com/docs/android-native-sdk#section--idsavailable-) to know when the device becomes registered.

You can also enable [setLogLevel](https://documentation.onesignal.com/docs/android-native-sdk#section--setloglevel-) with `VERBOSE` to print out all network request attempts.

**Comment by KingWu** [comment]
Yes. i am using the version 3.4.3 sdk. i think it is necessary to implement a callback to know about the network request. Otherwise, it is hard to make sure Push service is ready before handling some use cases like user registration.

**Comment by jkasten2** [comment]
@KingWu [`idsAvailable`](https://documentation.onesignal.com/docs/android-native-sdk#section--idsavailable-) will fire when the device is registered with OneSignal. Please send us a logcat noted in my last message if your seeing an issue with this.

**Comment by ndastur** [comment]
Actually this really useful. I have raised a similar issue. Can check therefore that the idsAvailable event will always be called on successful registration. I.e. even if it's not a new id etc

That way we can have a bool flag ```_oneSignal_available = false```

and inside idsAvailable set that to true,

presumably registrations can't be "lost" and if they can then how do we know about that??

Thanks

**Comment by jkasten2** [comment]
@ndastur Correct, the idsAvailable callback will fire immediately if the device has already registered. You can check if the `pushToken` is `null`. If so then they did not accept notification permissions.
