### ISSUE TITLE
How to disable notifications in INotificationServiceExtension

### ISSUE THREAD

**Issue by Zevsus** [OneSignal/OneSignal-Android-SDK#1892]
### How can we help?

Version 5.0.3
Previously, there was such a function of displaying notifications for the user if he had a certain title in the notification.
Example: A message comes with the URL of a file, if the user is subscribed to it through the settings(SharedPreferences), then display it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brismithers** [comment]
Hi @Zevsus !  `INotificationReceivedEvent` has a method  `preventDefault()` which allows you to prevent a notification from being displayed to the user.  If you don't call `preventDefault()` the notification will be displayed to the user. Here's an example in kotlin, assuming you are conditionally display depending on the title of the notification:


```kotlin
class NotificationServiceExtension : INotificationServiceExtension {
    override fun onNotificationReceived(event: INotificationReceivedEvent) {
        if(event.notification.title != "title-that-should-be-shown") {
            // prevent the notification from displaying
            event.preventDefault()
        }
    }
}
```
