### ISSUE TITLE
Notification receive issue

### ISSUE THREAD

**Issue by pchauhan** [OneSignal/OneSignal-Android-SDK#190]
I  am able to registerdevice and able to get app_id.
Sending notification from one signal website getting below error

**03-26 00:05:04.428 13354-13354/? W/GCM-DMM: broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE pkg=com.xxxxx (has extras) }**

Please let me know suggestion.
Thanks
Parag

**Comment by jkasten2** [comment]
@pchauhan This means the Google Play services app couldn't start your app since it was force stopped / closed. Please see the following link for caused of this.
https://documentation.onesignal.com/docs/notifications-show-successful-but-are-not-being-shown#section-the-app-is-force-stopped

**Comment by pchauhan** [comment]
@jkasten2  Thanks for reply.
I am not killing/force stop an app .
My issue resolved after implementing own Broadcast Receiver.
<receiver
            android:name="com.test.MyBroadcastReceiver"
            android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <category android:name="com.test" />
            </intent-filter>
        </receiver>

**Comment by jkasten2** [comment]
@pchauhan Are you using Android Studio with the following line in your `build.gradle`?
```gradle
compile 'com.onesignal:OneSignal:3.+@aar'
```

It will automatically add the SDK's BroadcastReceiver.
https://github.com/OneSignal/OneSignal-Android-SDK/blob/3.4.3/OneSignalSDK/onesignal/src/release/AndroidManifest.xml#L11-L18

If you are using Eclipse you must add the following entries.
https://documentation.onesignal.com/docs/android-sdk-setup#section-2-androidmanifest-xml

**Comment by pchauhan** [comment]
Yes i had added thats why able to reg device to one signal.

**Comment by jkasten2** [comment]
@pchauhan You only need one BroadcastReceiver with the action intent-filter `"com.google.android.c2dm.intent.RECEIVE"`. This SDK already adds one so you don't the one you listed above.

If you see the  `W/GCM-DMM: broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE pkg=com.xxxxx (has extras) }` error and your device is still subscribed then it is definitely due to your app being in a forced stopped state.

If you continue to see an issue please list the Android device models and Android OS versions you are seeing the issue on.

**Comment by pchauhan** [comment]
@jkasten2  Yes its happening in my both device 
1.HTC One M7 - 5.0 OS
2.Samsung S6 - 6.0.1 OS

**Comment by jkasten2** [comment]
@pchauhan Thanks for the details. These devices shouldn't be force stopping your app. The other thing that could put them into this state would be a crash or a 3rd party task killer like Greenify.

**Comment by dev-JE02** [comment]
It is also happening on my device Samsung S8 6.0. How do I know the library is crashing somewhere? I could register and get an ID, but when sending notifications to the device I always get the GCM CANCELLED error.

**Comment by jkasten2** [comment]
@dev-JE02 The `GCM CANCELLED` logcat entry can happen if your app crashed from at any point and the app wasn't reopened.

Or if the `<receiver>` tag is missing from your `AndroidManifest.xml`. This is added automatically with Android Studio / Gradle with our SDK. However make sure you don't have `tools:node="replace"` in your main `AndroidManifest.xml` as this cause it to remove entries from all libraries.

**Comment by dev-JE02** [comment]
The line about the `tools:node="replace"` should definitely be in the guides somewhere. Android Studio automatically inserts it to the manifest

**Comment by jkasten2** [comment]
@dev-JE02 Android Studio project's don't normally include this, however it may have provided this as an autocorrect option. We have added this to our troubleshooting guide.
https://documentation.onesignal.com/docs/troubleshooting-android#section-error-appid-format-is-invalid

**Comment by jkasten2** [comment]
@ironhide0396 Make sure you don't have an Android Studio debugger attached to your app when you close it as this will force killed the app. Please let us know the device model if this wasn't the issue.

**Comment by ironhide0396** [comment]
No detaching the debugged did not work out..
I'm currently using OnePlus 6
Android Oreo 8.1.0

**Comment by jkasten2** [comment]
@ironhide0396 Thanks, I don't believe that device has any sort of modifications to Android to change this force kill behavior however do you see this same issue on the Android Emulator?

Are you using the OneSignal `NotificationExtenderService`? Do you see the issue if you only send a basic notification with only a body set? Without setting priority or any other options like images

**Comment by ironhide0396** [comment]
I did not initially use it but after your suggestion i used it as follows
`
public class BackgroundNotification extends NotificationExtenderService {
    @Override
    protected boolean onNotificationProcessing(OSNotificationReceivedResult notification) {
        OverrideSettings overrideSettings = new OverrideSettings();
        overrideSettings.extender = new NotificationCompat.Extender() {
            @Override
            public NotificationCompat.Builder extend(NotificationCompat.Builder builder) {
                // Sets the background notification color to Green on Android 5.0+ devices.
                return builder.setColor(new BigInteger("FF00FF00", 16).intValue());
            }
        };
        OSNotificationDisplayedResult displayedResult = displayNotification(overrideSettings);
        Log.d("OneSignalExample", "Notification displayed with id: " + displayedResult.androidNotificationId);
        return false;
    }
}`

And here is the manifest entry
`   <service
            android:name=".BackgroundNotification"
            android:permission="android.permission.BIND_JOB_SERVICE"
            android:exported="false">
            <intent-filter>
                <action android:name="com.onesignal.NotificationExtender" />
            </intent-filter>
        </service>`

The same issue is being faced by OnePlus users as shown on other threads,having the similar issue
[https://github.com/OneSignal/OneSignal-Android-SDK/issues/461](url)

Any help will be appreciated.
Or a simple tutorial will help too
I did follow and try to run the sample code present on github as well as followed all steps mentioned on the website.
For some reasons it doesn't seem to work
If you wish i can attach the code for the same too.

**Comment by ironhide0396** [comment]
I modified the onesignal application by using the legacy server key of Firebase Console project instead of the regular one .
The app runs fine now on all android devices other than Oreo.
On Oreo the same issue is recurring 
`W/GCM-DMM: broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE pkg=com.xxxxx (has extras) `

Any solution for this will be appreciated

**Comment by jkasten2** [comment]
@ironhide0396 Using the legacy vs the normal Firebase server key shouldn't have any effect on the end device like this. The `GCM-DMM: broadcast intent callback: result=CANCELLED` message means the device did get a message from Google's server however the "Google Play services" app could not wake your app due your app being force closed.

Someone did report that using the `NotificationExtenderService` did cause this same issue however https://github.com/OneSignal/OneSignal-Android-SDK/issues/547#issuecomment-393107812. Let us know if disabling it has any effect for you.
