### ISSUE TITLE
[question]: The equivalent of `setNotificationOpenedHandler` in 5.x.x

### ISSUE THREAD

**Issue by hdralexandru** [OneSignal/OneSignal-Android-SDK#1905]
### How can we help?

What is the equivalent of `setNotificationOpenedHandler` in 5.x.x?

The method I'm talking about can't be resolved and the [docs](https://documentation.onesignal.com/docs/example-trigger-iam-from-push-open#step-1-code-setup) says that it's the same as before.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
Hello thank you for reaching out that doc page was missed and will be updated! [Here is the documentation](https://documentation.onesignal.com/docs/mobile-sdk#setting-notification-click-listeners) explaining what to use. The migration guide [here](https://github.com/OneSignal/OneSignal-Android-SDK/blob/user-model/main/MIGRATION_GUIDE.md) may also be helpful.
