### ISSUE TITLE
[question]: When using the 5.x.x API how to make background notifications work even when notifications are disabled for my app.

### ISSUE THREAD

**Issue by stefan-tkii** [OneSignal/OneSignal-Android-SDK#1907]
### How can we help?

So far I have been using OneSignal version 4.8.6 for my app. And I had made use of the API defined here: https://documentation.onesignal.com/v9.0/docs/sdk-reference#unsubscribewhennotificationsaredisabled-method for enabling notifications to work even when the permission for them was disabled. I was reading the documentation about the new 5.x.x API but could not find the corresponding API for this same functionality.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello there!

We are looking at adding this capability to our API, but currently, the workaround is to create a 2nd OneSignal app to register the push tokens. You can get the token with [this method](https://documentation.onesignal.com/docs/mobile-sdk#push-token) even if the user did not accept notifications.

Then, use the OneSignal [Create Subscription](https://documentation.onesignal.com/reference/create-subscription) REST API call to register the device to your secondary OneSignal app_id for your silent notifications.

Hope this helps! Let us know if you have any additional questions or concerns.
