### ISSUE TITLE
MultiDex error

### ISSUE THREAD

**Issue by burhanaksendir** [OneSignal/OneSignal-Android-SDK#191]
When I add the below dependencies in `build.gradle`, I am getting a multiDex error.
```gradle
    // Required for OneSignal, even if you have added FCM.
    compile 'com.google.android.gms:play-services-gcm:+'
   
    // Required for geotagging
    compile "com.google.android.gms:play-services-location:+"
```
Any help on how to fix this?

**Comment by jkasten2** [comment]
@burhanaksendir Could you reply with the full exact error it is giving you?

**Comment by burhanaksendir** [comment]
@jkasten2 
`Error:Execution failed for task ':app:transformClassesWithDexForDebug'.com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexIndexOverflowException: Cannot merge new index 67541 into a non-jumbo instruction.`

All of the dependecies in my gradle file are listed below:

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:support-v4:25.3.0'
    compile 'com.android.support:appcompat-v7:25.3.0'
    compile 'com.android.support:recyclerview-v7:25.3.0'
    compile 'com.android.support:design:25.3.0'
    compile 'com.android.support:cardview-v7:25.3.0'
    compile 'com.google.code.gson:gson:2.8.0'
    compile 'com.onesignal:OneSignal:3.+@aar'
    compile 'com.google.android.gms:play-services-gcm:+'
    compile "com.google.android.gms:play-services-location:+"
    compile 'com.jakewharton.timber:timber:4.5.1'
    compile 'com.squareup.okhttp3:mockwebserver:3.6.0'
    compile 'com.nhaarman.listviewanimations:lib-core:3.1.0@aar'
    compile 'com.nhaarman.listviewanimations:lib-manipulation:3.1.0@aar'
    compile 'com.nhaarman.listviewanimations:lib-core-slh:3.1.0@aar'
    compile 'com.github.bumptech.glide:glide:3.7.0'
    compile files('libs/nineoldandroids-library-2.4.0.jar')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    testCompile 'junit:junit:4.12'
    compile files('libs/universal-image-loader-1.9.5.jar')
    compile('com.crashlytics.sdk.android:crashlytics:2.6.7@aar') {
        transitive = true;
    }

**Comment by jkasten2** [comment]
@burhanaksendir You are running into the 65K method dex limit. This is correlated to the number libraries in your project which is why you might have just seen this after adding OneSignal.

You should be able to enable `jumboMode` in your project to resolve the issue.

```gradle
android {
    ...
    dexOptions {
        jumboMode true
    }
}
```
http://stackoverflow.com/questions/26093664/android-studio-only-dexexception-cannot-merge-new-index-65536-into-a-non-jumbo

Thanks.
