### ISSUE TITLE
[Bug]: disabling location sharing not working

### ISSUE THREAD

**Issue by JNaehringApploft** [OneSignal/OneSignal-Android-SDK#1910]
### What happened?

The latest sdk shares the geo location when it is available in the app, although location sharing is disabled when initializing the one signal sdk.
  
```kotlin
OneSignal.initWithContext(this, ONESIGNAL_APP_ID)
OneSignal.Location.isShared = false
``` 

### Steps to reproduce?

```Markdown
1. have an app that uses geo location and integrate one signal sdk v5.0.4 with location sharing disabled
2. install and start the app
3. grant location permission (e.g. through custom ui)
4. make sure that custom app code accesses the location
5. close and restart the app at least once
6. open the onesignal dashboard for this project and look for a new subscription
7. see that the new subscription shows the location point
```

### What did you expect to happen?

I would expect that the geo location is not read and send to one signal servers, when location sharing is disabled.

### OneSignal Android SDK version

5.0.4

### Android version

13

### Specific Android models

```Markdown
Poco x4 Pro - Android 13
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello @JNaehringApploft thank you for reaching out! I have reproduce this issue and am investigating a solution. We will let you know progress here.

**Comment by johanlantz** [comment]
@jennantilla imho, two weeks is too long to address this. Customers using 5.0.x with location are likely in violation of their privacy policies, gdpr and disclousures with AppStore and Google Play. If they have said that they are not sharing information with third-parties, then presumably, uploading highly sensitive information such as gps coordinates to onesignal without user consent is really bad.

**Comment by jennantilla** [comment]
@johanlantz we appreciate your patience! This will be included in the next release of the SDK.

**Comment by jennantilla** [comment]
Hi everyone, thanks for your patience! Just an update that a fix for this has been added in our latest release, [5.1.0](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.0).
