### ISSUE TITLE
Notification Listener

### ISSUE THREAD

**Issue by 1appstudio** [OneSignal/OneSignal-Android-SDK#1914]
### How can we help?

**Requirement:

My app is in the foreground and open always. Now when a push is received, i need to listen and read parameters data.**

I have installed the latest version of Onesignal.

implementation 'com.onesignal:OneSignal:[5.0.0, 5.99.99]'.

But in my old code has following listener:

   OneSignal.setNotificationWillShowInForegroundHandler(new OneSignal.OSNotificationWillShowInForegroundHandler() {
              @Override
              public void notificationWillShowInForeground(OSNotificationReceivedEvent osNotificationReceivedEvent) {
  }
});

After updating the version i have met an error. The listener its now working and shwoing a compilation error.
**Cannot resolve method 'setNotificationWillShowInForegroundHandler' in 'OneSignal'**

**How can i dow it in latest version?.**

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello @1appstudio thanks for reaching out!

The new method for handling foreground notifications is `OneSignal.getNotifications().addForegroundLifecycleListener`. Code samples for Java and Kotlin can be found [here](https://documentation.onesignal.com/docs/mobile-sdk#handling-notifications-before-theyre-presented-when-the-app-is-in-the-foreground).

Let us know if you have any additional questions or concerns!

**Comment by 1appstudio** [comment]
Complated as well.. But now i did not get compilation error. But notification is not shown to my app.

Plas Kindly help me
