### ISSUE TITLE
[Bug]: OneSignalService.onPostAppCreated java.lang.NullPointerException

### ISSUE THREAD

**Issue by albertoderodrigo** [OneSignal/OneSignal-Android-SDK#1917]
### What happened?

Since que upgraded from OneSignal 4.X.X to OneSignal 5.0.4 we started to see the following error on Firebase crashlytics.

> Caused by java.lang.NullPointerException:
       at com.onesignal.core.internal.application.impl.ApplicationService.getAppContext(ApplicationService.kt:39)
       at com.onesignal.core.internal.preferences.impl.PreferencesService.getSharedPrefsByName(PreferencesService.kt:234)
       at com.onesignal.core.internal.preferences.impl.PreferencesService.get(PreferencesService.kt:134)
       at com.onesignal.core.internal.preferences.impl.PreferencesService.getString(PreferencesService.kt:42)
       at com.onesignal.common.modeling.ModelStore.load(ModelStore.kt:165)
       at com.onesignal.common.modeling.SimpleModelStore.<init>(SimpleModelStore.kt:23)
       at com.onesignal.core.internal.config.ConfigModelStore.<init>(ConfigModelStore.kt:8)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
       at com.onesignal.common.services.ServiceRegistrationReflection.resolve(ServiceRegistration.kt:89)
       at com.onesignal.common.services.ServiceProvider.getServiceOrNull(ServiceProvider.kt:79)
       at com.onesignal.common.services.ServiceProvider.getService(ServiceProvider.kt:67)
       at com.onesignal.common.services.ServiceProvider.getService$com_onesignal_core(ServiceProvider.kt:39)
       at com.onesignal.internal.OneSignalImp.initWithContext(OneSignalImp.kt:188)
       at com.onesignal.OneSignal.initWithContext(OneSignal.kt:135)

[Full Log](https://github.com/OneSignal/OneSignal-Android-SDK/files/13407951/io.socialgamesonline.slotcom_issue_b195941da1928b51d7cb0e43076dd8dc_crash_session_655A9A2B0047000146387AE80C881853_DNE_0_v2_stacktrace.txt)

This happens on the start up and in a variety of devices and Android Versions.

<img width="1242" alt="Screenshot 2023-11-20 at 09 05 09" src="https://github.com/OneSignal/OneSignal-Android-SDK/assets/18699142/0184e55d-ebbc-4437-9b6f-6e8cd56e6638">

### Steps to reproduce?

```Markdown
Upgrade to OneSignal 5.0.4 aande wait for the errors on Firebase crashlytics.

We didn't find a way to reproduce it in our test devices.
```

### What did you expect to happen?

No errors on FIrebase crashlytics

### OneSignal Android SDK version

5.0.4

### Android version

13, 12, 11, 10, 9

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Thank you for reaching out! We'll investigate this.

**Comment by albertoderodrigo** [comment]
Hi we just updated to the latest of the sdk 5.0.5 and the problem remains.

<img width="717" alt="Screenshot 2023-12-14 at 09 36 28" src="https://github.com/OneSignal/OneSignal-Android-SDK/assets/18699142/11dbca34-c9c4-43c8-a90e-2cb40db11111">

this is a fresh log

[io.socialgamesonline.slotcom_issue_b195941da1928b51d7cb0e43076dd8dc_crash_session_657A7843002D00017F30B9EF82B82DED_DNE_0_v2_stacktrace (1).txt](https://github.com/OneSignal/OneSignal-Android-SDK/files/13670741/io.socialgamesonline.slotcom_issue_b195941da1928b51d7cb0e43076dd8dc_crash_session_657A7843002D00017F30B9EF82B82DED_DNE_0_v2_stacktrace.1.txt)

**Comment by albertoderodrigo** [comment]
Hello just for your info we just updated to the latest versión 5.1.0 and the error remains.

[io.socialgamesonline.slotcom_issue_b195941da1928b51d7cb0e43076dd8dc_crash_session_6595FBD7003100011A74FA3E34186E71_DNE_0_v2_stacktrace.txt](https://github.com/OneSignal/OneSignal-Android-SDK/files/13827360/io.socialgamesonline.slotcom_issue_b195941da1928b51d7cb0e43076dd8dc_crash_session_6595FBD7003100011A74FA3E34186E71_DNE_0_v2_stacktrace.txt)

This is the top error in our app :(

<img width="1291" alt="Screenshot 2024-01-04 at 08 35 38" src="https://github.com/OneSignal/OneSignal-Android-SDK/assets/18699142/00d1c96b-f2ac-460c-ab2c-593d889c2ce8">

**Comment by albertoderodrigo** [comment]
Hello we released a new version with the 5.1.1 and the error persists (But we reduced ARN thx!). 

This is a log with the last version
 
[io.socialgamesonline.slotcom_issue_b195941da1928b51d7cb0e43076dd8dc_crash_session_65B0A5B7008E00012846EADB61154D90_DNE_0_v2_stacktrace.txt](https://github.com/OneSignal/OneSignal-Android-SDK/files/14034347/io.socialgamesonline.slotcom_issue_b195941da1928b51d7cb0e43076dd8dc_crash_session_65B0A5B7008E00012846EADB61154D90_DNE_0_v2_stacktrace.txt)

Can you give me some feedback @jennantilla please is the most frequent error on our app.

Regards

**Comment by albertoderodrigo** [comment]
Hello? any news regarding this @jennantilla.

**Comment by nan-li** [comment]
Hi @albertoderodrigo, Thank you for following up with your updates and attaching new stacktraces.

I am noting for ourselves to investigate that the stacktraces show **two scenarios** that triggered the `getAppContext` NPE:
```
com.onesignal.core.internal.preferences.impl.PreferencesService.getSharedPrefsByName(PreferencesService.kt:234)
```
```
com.onesignal.core.internal.device.impl.DeviceService.packageInstalledAndEnabled(DeviceService.kt:106)
```

We have no updates yet.

**Comment by albertoderodrigo** [comment]
Hi @nan-li,

We can add more logs or traces at the moment that the exception is raised. What information could help you?

**Comment by nan-li** [comment]
Hi @albertoderodrigo,

I have looked at your logs again, and they all arise from your app's method `onPostAppCreated` calling `OneSignal.initWithContext`. Can you share what kind of context you are passing?

```
       at com.onesignal.OneSignal.initWithContext(OneSignal.kt:135)
       at io.socialgamesonline.slotcom.features.OneSignalService.onPostAppCreated(OneSignalService.kt:38)
```

Also, do you see any crashes that originate from other sources that are not from you calilng the method, such as BroadcastReceivers, etc?

**Comment by albertoderodrigo** [comment]
Hi @nan-li.

We use the getApplicationContext from the custom Application. This is provided on the onCreate event.

<img width="591" alt="Screenshot 2024-02-23 at 14 55 23" src="https://github.com/OneSignal/OneSignal-Android-SDK/assets/18699142/f55c3fd7-892b-47dd-9aa2-58d99fc7347d">

I just checked a lot of this crashes an all are originated from the same source. Has your `initWithContext` checks if context is null then the only possibility that i see is that sometimes ApplicationService init has not been called before the trying to acquire the context from it.

**Comment by jkasten2** [comment]
We have a fix that will lower and possibly fix all crashes related to this `null` `Context` being thrown from `initWithContext` issue in the [OneSignal-Android-SDK 5.1.6](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.6) release.

@albertoderodrigo  if you continue to seeing this issue after updating to 5.1.6 please let us know the new percentages of crashes the new stack traces.

**Comment by albertoderodrigo** [comment]
Hi @jkasten2, we just releases a hotfix with your update. On Monday I will let you know if it has disappeared or not. 

Thx

**Comment by albertoderodrigo** [comment]
Hi @jkasten2, the error disappeared!! Thx!

**Comment by jkasten2** [comment]
@albertoderodrigo The is awesome to hear! Appreciate you reporting back the results!
