### ISSUE TITLE
OneSignal.setLocationShared(false) goes into full effect only after app is reinstalled

### ISSUE THREAD

**Issue by Talkless** [OneSignal/OneSignal-Android-SDK#192]
I have tried `OneSignal.setLocationShared(false)` method to disable location as that we really don't need it in our use case.

Though, even after:
* `OneSignal.setLocationShared(false)`
* Location service disabled
* App cache cleared
* Device restarted
* And, User entry deleted from OneSignal dashboard

I can still see location of re-subscribed user!

Only after uninstalling and then installing app I could no longer see location in OneSignal's All Users table.

Looks like _as if_ OneSignal library caches location and it does not delete it upon `OneSignal.setLocationShared(false)` is called. I believe it should.

**Comment by jkasten2** [comment]
Fixed in the commit above. Will be part of the 3.4.4. release.

**Comment by Talkless** [comment]
Thanks!
