### ISSUE TITLE
Push

### ISSUE THREAD

**Issue by 1appstudio** [OneSignal/OneSignal-Android-SDK#1929]
### How can we help?

Hi I implemented Onesignal for Amazon firestick. Push notifications is not received in amazon firestick. What can I do

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @1appstudio thanks for reaching out! Are you using our [Amazon SDK](https://documentation.onesignal.com/docs/amazon-sdk-setup)? Can you please provide some additional details about how you set it up and any logs capturing the issue?

**Comment by jennantilla** [comment]
Closing due to no response. @1appstudio if you are still having issues please let us know.

**Comment by jkasten2** [comment]
@1appstudio If you are still seeing an issue sending to Amazon devices please see https://github.com/OneSignal/OneSignal-Android-SDK/issues/1936#issuecomment-2024161687
