### ISSUE TITLE
ANR executing service app..../com.onesignal.SyncService

### ISSUE THREAD

**Issue by iForests** [OneSignal/OneSignal-Android-SDK#193]
I am using OneSignal SDK v3.4.3, and got a lot of ANRs. We see more than 20 ANRs for about 10K daily active users in Google Play Console.

Please let me know if you need any information. Thanks.

**Comment by jkasten2** [comment]
@iForests Were you able to solve the ANR issue with the service?

**Comment by iForests** [comment]
Not sure yet. We have another app using OneSignal too, but the ANR doesn't happen there. I'll check my code carefully and report again if the issue is on com.onesignal.SyncService. Thanks.

**Comment by imranbaig1977** [comment]
We are seeing the same ANR for v3.4.3

Executing service com.weswap.app/com.onesignal.SyncService
