### ISSUE TITLE
[Bug]: I cant get to compile with the last commit on main branch ?

### ISSUE THREAD

**Issue by tmijieux** [OneSignal/OneSignal-Android-SDK#1930]
### What happened?

I checkout the last commit on main  https://github.com/OneSignal/OneSignal-Android-SDK/commit/08b951c99243188c8616d8de10d04e5bfcb0b01b by 2 december 2023
And it does not compile.

The delegated property seems to have wrong syntax ?  https://github.com/OneSignal/OneSignal-Android-SDK/commit/896ec5048d8a1a88d83300207cad987cba3f45ae
  
Compilation just failed with the following error message:
`  e: C:\...\OneSignal-Android-SDK\OneSignalSDK\onesignal\src\main\java\com\onesignal\NotificationPermissionController.kt: (45, 42): Function invocation 'lazy(...)' expected`
  
Also when fixing by removing the equals assignment sign , there is another error that says the attribute is not applicable on delegated properties.
  
I believe the correct version is:
```
    val supportsNativePrompt: Boolean by lazy {
        Build.VERSION.SDK_INT > 32 &&
            OSUtils.getTargetSdkVersion(OneSignal.appContext) > 32
    }
```

### Steps to reproduce?

```Markdown
just checkout 08b951c99243188c8616d8de10d04e5bfcb0b01b and build in Android Studio
```

### What did you expect to happen?

it should compile just fine.

### OneSignal Android SDK version

main 08b951c99243188c8616d8de10d04e5bfcb0b01b

### Android version

13

### Relevant log output

```Shell
`  e: C:\...\OneSignal-Android-SDK\OneSignalSDK\onesignal\src\main\java\com\onesignal\NotificationPermissionController.kt: (45, 42): Function invocation 'lazy(...)' expected`
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
This is now fixed in the PR noted above and has been merged into main.
