### ISSUE TITLE
[Bug]:  Users automatic go to unsubscribed after delivered push

### ISSUE THREAD

**Issue by felipemmatos** [OneSignal/OneSignal-Android-SDK#1936]
### What happened?

Without any reason, all my apps are not receiving pushs. Old apps that I didn't make any update are with the same issue. This is happening at the amazon Fire devices. All users are showing unsubscribed.

### Steps to reproduce?

```Markdown
1 . Install the app 
2. The onesignal dashboard will show the user is subscribed
3. After send the push, the status is delivered and the user changed to unsubscribed.
```

### What did you expect to happen?

Receive pushs

### OneSignal Android SDK version

4.8.6

### Android version

13, 7.0, 6, 5.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello @felipemmatos thank you for your patience. Are you still facing this issue? We have not received any other reports of this and push should be working normally. Did you recently update any [Firebase credentials](https://documentation.onesignal.com/docs/generate-firebase-credentials)? If you are still seeing this, can you please provide a [log](https://documentation.onesignal.com/docs/capturing-a-debug-log) of this behavior? We'll be happy to take a deeper look. Thank you!

**Comment by felipemmatos** [comment]
Hello, here another user with the same issue:

https://github.com/OneSignal/OneSignal-Unity-SDK/issues/664￼
[Bug]: Notification doesn't work on Amazon Kindle Fire HD 10 · Issue #664 · OneSignal/OneSignal-Unity-SDK
github.com

This is happening with amazon fire devices. I use onesginal long time and I have many apps with the SDK. All the apps are showing the same issue without any update. Nothing change with my firebase credentials.

Hope you guys can fix this issue.

Thanks,

Felipe

**Comment by jennantilla** [comment]
Hi @felipemmatos! Are you still experiencing this? Would you be able to send over the log from your devices so we can confirm it is the same issue reported on the Unity issue you linked? Appreciate it!

**Comment by jennantilla** [comment]
Closing due to no response. Please let us know if you still need any assistance!

**Comment by jkasten2** [comment]
@felipemmatos could you try re-saving your Amazon setting on the OneSignal dashboard?
![image](https://github.com/OneSignal/OneSignal-Android-SDK/assets/645861/ad3f9f5a-58a5-41a4-a3bd-cc52e2b501d2)


This is a work around that should get you up and running while we investigate the root cause.

**Comment by jkasten2** [comment]
@felipemmatos let us know if re-saving your Amazon configure, noted above, fixes the issue for you.
