### ISSUE TITLE
[question]: Startup and Persistent Activity Issue: Seeking Assistance with OneSignal and Intercept X

### ISSUE THREAD

**Issue by raissetto** [OneSignal/OneSignal-Android-SDK#1938]
### How can we help?

I'm currently addressing an issue related to the use of OneSignal in our app, highlighted by reports from Sophos Intercept X. The primary problem revolves around the app's automatic startup upon device boot and its persistent activity even when the device is locked.

We've meticulously reviewed the manifest, and there seem to be no configurations justifying this behavior. Based on our investigation, it appears that OneSignal settings might be involved in triggering these reports from Intercept X.

We've ensured that permissions and configurations comply with both OneSignal and Sophos Intercept X guidelines, but the issue persists.

I was wondering if you've received similar reports from other users or if you have specific advice on how we can address this situation. Any assistance you can provide would be greatly appreciated.

Thank you very much for your time and cooperation.

![github](https://github.com/OneSignal/OneSignal-Android-SDK/assets/1456800/7dc5f0cc-641a-4e96-84cf-3ec240069c98)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
@raissetto thank you for flagging. We're looking into this.

**Comment by jkasten2** [comment]
> I'm currently addressing an issue related to the use of OneSignal in our app, highlighted by reports from Sophos Intercept X. The primary problem revolves around the app's automatic startup upon device boot and its persistent activity even when the device is locked.

> We've meticulously reviewed the manifest, and there seem to be no configurations justifying this behavior. Based on our investigation, it appears that OneSignal settings might be involved in triggering these reports from Intercept X.

* app's automatic startup upon device boot
   - Android doesn't put notifications back in the shade when the device is restarted. OneSignal restores them when device is rebooted as the end-user may have not seen them yet. Only notifications that haven't been interacted with are restored, such as swiping them away or tappning on them.
 * its persistent activity even when the device is locked
     - This is mostly being triggered as when a push is received, as it need to display it on the lock screen.


I installed the [Sophos Intercept X for Mobile](https://play.google.com/store/apps/details?id=com.sophos.smsec&hl=en_US&gl=US) app and didn't immediate detect any issues with the 5.1.8 SDK, on our example app. I did a scan in the Intercept X app too, when does that report trigger? Could you also try updating to 5.1.8 and see if you still see this issue?

**Comment by jkasten2** [comment]
Closing due to no response
