### ISSUE TITLE
[Bug]: SDK v5 unable to exclude unnecessary modules

### ISSUE THREAD

**Issue by bsiegel** [OneSignal/OneSignal-Android-SDK#1939]
### What happened?

The [V5 migration guide](https://github.com/OneSignal/OneSignal-Android-SDK/blob/user-model/main/MIGRATION_GUIDE.md) indicates that for greater flexibility, consuming apps can pick and choose which modules to include rather than including the omnibus "OneSignal" module:

> `com.onesignal:core`: The required core module provided by the OneSignal SDK, this must be included.
> `com.onesignal:notifications:` Include to bring in notification based functionality.
> `com.onesignal:in-app-messages`: Include to bring in in app message functionality.
> `com.onesignal:location`: Include to bring in location-based functionality.

`in-app-messages` has a hard dependency on `notifications`, which is odd and hopefully can be decoupled in the future. `location` has no hard dependencies. And of course `core` has no hard dependencies on any of the above, meaning the consuming application can be compiled with just `core`, or with any combination of `core` and the above modules, with no errors at compile time. However at runtime, excluding any of these modules leads to a crash:

> Unable to create application com.example.MyApplication: java.lang.Exception: Service interface com.onesignal.location.ILocationManager could not be instantiated

This is because all of the above modules are referenced and loaded by reflections in [OneSignalImpl.initWithContext](https://github.com/OneSignal/OneSignal-Android-SDK/blob/5.0.5/OneSignalSDK/onesignal/core/src/main/java/com/onesignal/internal/OneSignalImp.kt#L234)

The `core` library either needs to be fixed so that these modules are truly optional, or `core` should have hard dependencies on all three required modules.

### Steps to reproduce?

```Markdown
1. Create a sample app and add dependencies on `com.onesignal:core` and `com.onesignal:in-app-messages` but do not include a dependency on `com.onesignal:location`.
2. Compile the application.
3. Run the application. It crashes on launch as described above.
```

### What did you expect to happen?

The SDK works, and location-related functionality is excluded.

### OneSignal Android SDK version

5.0.5

### Android version

13, 12, 11, 10, 9, 8, 7.1, 7.0, 6, 5.1, 5.0, 4.4, 4.3 or below

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
@bsiegel thank you for flagging this! We are currently working on improving Android modularization and will let you know when a fix is ready!

**Comment by jennantilla** [comment]
@bsiegel thanks for your patience! Just an update our latest release, [5.1.0](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.0), includes a fix to improve modularization. When you have a chance, please update to this version and let us know if you are seeing any further issues.
