### ISSUE TITLE
idsAvailable called back on different thread

### ISSUE THREAD

**Issue by westito** [OneSignal/OneSignal-Android-SDK#194]
I had a strange issue what happened very randomly. Got "NetworkOnMainThread" exception randomly. Finally I found it. I don't know it is a feature or bug but I create this issue for warning devs.

In my code I call idsAvailable in an Observable what flatMaps it to an api call to my backend. At first tests there was no problem. But users started to report crashes at login. But it was hard to reproduce. But finally I found it!

The problem is: If there alredy a userid "if (getUserId() != null)", the callback function called immediately on the calling thread. But if the id will be available later, the callback function called on main thread! What i am not expected.

So the solution is calling the callback on the calling thread (if possible by saving the looper of calling thread). Or run on ui thread in both cases. But at least please add a warning to the documentation about this.

**Comment by jkasten2** [comment]
@westito Sorry about the issues this caused you. I have added this to our documentation.
https://documentation.onesignal.com/docs/android-native-sdk#section--idsavailable-

Thanks.
