### ISSUE TITLE
[Bug]: OneSignal.User.pushSubscription.id is always blank

### ISSUE THREAD

**Issue by kpturner** [OneSignal/OneSignal-Android-SDK#1964]
### What happened?

Everything is working OK from a push notification perspective, but now I need to do something with the subscription id.  I used to be able to get this from `OneSignal.User.pushSubscription.id` bit now, with version 5.0.4, this is always blank.

Furthermore, I tried adding a listener like so to see if I could derive the id from there like so:

```
const listener = (event: PushSubscriptionChangedState) => {
  // Get the subscription id from the event
};

// Add the listener
OneSignal.User.pushSubscription.addEventListener("change", listener);

```
but that particular listener never gets triggered.   I have tried the `login`, `logout`, `optIn`, `optOut` but no sign of life on this listener at all.

### Steps to reproduce?

```Markdown
1. Install 5.0.4
2. Run any of the `login`, `logout`, `optIn`, `optOut` methods after initialisation
3. Try to get the subscription id from `OneSignal.User.pushSubscription.id`
```

### What did you expect to happen?

I expect to be able to get the subscription id from `OneSignal.User.pushSubscription.id`

### OneSignal Android SDK version

5.0.4

### Android version

13

### Specific Android models

```Markdown
Any
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @kpturner by the looks of it, you are using the Cordova SDK, is that correct? We are aware of this issue and working a solution and will be tracking the progress [here](https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/918#issuecomment-1895889004). Thanks for your patience while we implement this fix!
