### ISSUE TITLE
[Bug]: Fix for the ConcurrentModificationException

### ISSUE THREAD

**Issue by gapspt** [OneSignal/OneSignal-Android-SDK#1967]
For a long time already I've seen this or similar exceptions in the Google Play Developer console coming from the OneSignal SDK:
```
Fatal Exception: java.util.ConcurrentModificationException:
       at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1029)
       at java.util.ArrayList$Itr.next(ArrayList.java:982)
       at com.onesignal.common.events.EventProducer.fire(EventProducer.kt:49)
       at com.onesignal.core.internal.application.impl.ApplicationService.setCurrent(ApplicationService.kt:51)
       at com.onesignal.core.internal.application.impl.ApplicationService.onActivityStarted(ApplicationService.kt:151)
       at android.app.Application.dispatchActivityStarted(Application.java:420)
       at android.app.Activity.dispatchActivityStarted(Activity.java:1451)
       at android.app.Activity.onStart(Activity.java:1969)
```
And I've seen in the changelogs some attempts to try and fix it. It seems that all the attempts were unsuccessful, as the issue persists in 5.1.1.
But I believe I have the fix for it, the issue is in the following code:
https://github.com/OneSignal/OneSignal-Android-SDK/blob/709b441073bf87f6cb228b4aae1ab33e99317777/OneSignalSDK/onesignal/core/src/main/java/com/onesignal/common/events/EventProducer.kt#L47-L53

Despite its name, the majority of the `ConcurrentModificationException` bugs do not happen because one thread modified a collection while another thread was accessing it: the problem is usually modifying it within the same thread while iterating it.
This can happen when some method is called during a normal iteration which causes the same collection to be modified (either by adding or removing elements).

There's one pattern that stands out above all others, which is when managing events, and it is exactly this case (clearly seen in the stack trace above).
Since the piece of code responsible for the event firing doesn't know what the event callbacks will do, it is imperative to assume that those callbacks can for example register or unregister events themselves, i.e. that they can cause that same collection to be modified. No amount of synchronized blocks or special concurrent collection types will fix that, and that's why the previous attempts to fix the problem were unsuccessful, because they don't grasp the root cause.

The fix is quite simple though, you just need to **_make a copy of the collection and iterate over the copy_**. The original collection can thus be freely modified with no issue whatsoever.
More concretely, in the `fire` function you can just create a copy `val copy = ArrayList(subscribers)` and iterate over the copy `for (s in copy)`.

Additionally, I believe the `synchronized` blocks should be removed: It seems unfruitful to have a synchronized block around each access of the collection that is already synchronized (as it is initialized with `Collections.synchronizedList`). Less code should always be preferred and those `synchronized` blocks seem to be useless in this case.

**Comment by jinliu9508** [comment]
@gapspt, thanks for your input, we have fixed and released version 5.1.2 to address the bug causing the concurrent modification exception. We are now closing this issue. Thank you again for your contribution to resolving this issue! Please feel free to reach out if you encounter more issues.
