### ISSUE TITLE
sometimes notification title disappears automatically in android

### ISSUE THREAD

**Issue by mahmood4429** [OneSignal/OneSignal-Android-SDK#197]
sometimes notification title missed out in android. only icon and time is shown.

**Comment by jkasten2** [comment]
@mahmood4429 Please make sure you don't have another push notification SDK in your app as it could be display it instead.

If you still see the issue can you include the OneSignal SDK version in your app, Android version and model of the device, and the notification options you set?

Also please link OneSignal support to this thread and we can take a look at your notification as well.

**Comment by jkasten2** [comment]
@mahmood4429 We haven't had any other reports of this. Please include a screenshot and more details if you are still having this issue and we can reopen this.
