### ISSUE TITLE
Callback for methods login and logout

### ISSUE THREAD

**Issue by ilhomsoliev** [OneSignal/OneSignal-Android-SDK#1971]
### How can we help?

How do I call callback after successful or unsuccessful completation of some methods like login and logout?

Basically, I want to run a code only after successful login

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @ilhomsoliev thanks for reaching out!

We removed callbacks to methods like `login` in 5.x.x. The SDK now uses a system of caching and retrying that will persist through app cold starts.

Could you please share a little information on your use case?

Although `login` does not have a callback, we recently added a UserStateObserver which can be added to fire when the user state changes (e.g., upon login).

More information in our [migration guide](https://github.com/OneSignal/OneSignal-Android-SDK/blob/user-model/main/MIGRATION_GUIDE.md).

Thanks!
