### ISSUE TITLE
How to keep Dashboard clean?

### ISSUE THREAD

**Issue by ilhomsoliev** [OneSignal/OneSignal-Android-SDK#1976]
### How can we help?

Hello! Let's look into this case: Let say user had app version 1, when updating the app the user has app version 2 now, but in Dashboard these two app versions are like two different subscriptions. My question is, is there any way around to make these two subscriptions as one, because the first one (with app version 1) is essentially 'useless'? 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @ilhomsoliev thanks for reaching out! It sounds like after an app update, a new subscription for the same user is being created? I will work on reproducing this to investigate further. Or, if you have logs from your device capturing this behavior, feel free to share them here.

In the meantime, if you wish to "clean up" your dashboard, you can delete subscriptions based on a different data. For example, if you wish to delete subscriptions with app version 1, in your Audience > Segments tab you can setup a segment with the App Version filter.
 
You can delete subscribers in bulk from the OneSignal Dashboard. Details and recommendations are in this guide: https://documentation.onesignal.com/docs/delete-users

Let us know if you have any additional questions or concerns.​﻿
