### ISSUE TITLE
Sessions not incrementing in OneSignal Dashboard

### ISSUE THREAD

**Issue by ilhomsoliev** [OneSignal/OneSignal-Android-SDK#1978]
### How can we help?

I have subscriptions type of Push-app, and it most subscriptions it stays 1, and some others work fine. When is incrementing actually triggered in app? How to fix this? And it relates to Usage durations, too.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @ilhomsoliev thanks for reaching out! This is a known issue that we are working on fixing on the backend. I'll update you here when resolved!

**Comment by jennantilla** [comment]
Hello again! This should now be resolved. I'll go ahead and close this issue but please let us know if you have any additional questions or concerns. Thanks!
