### ISSUE TITLE
Why is that OneSignalId is empty sometimes?

### ISSUE THREAD

**Issue by ilhomsoliev** [OneSignal/OneSignal-Android-SDK#1979]
### How can we help?

Basically, OneSignalId is empty when I call `OneSignal.User.onesignalId`. This is what I see in logs from OneSignal:
`[DefaultDispatcher-worker-4] OperationRepo.enqueue(operation: {"name":"update-subscription","appId":"****,"onesignalId":"local-****","subscriptionId":"****","type":"PUSH","enabled":true,"address":"****","status":"SUBSCRIBED"}, flush: false)`

Is that normal that OneSignalId starts with 'local'?

And also, when I search user with subscriptionId provided it is different user, because I have login in my app, and when user is changed I login user with different externalId but in this case it is changed, but `OneSignal.User.onesignalId` gives me empty string. And it stays the same.

(externalId is the user who logined in last)

What should I do?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @ilhomsoliev that is correct--if a onesignal_id starts with `local-` it is basically no onesignal ID / missing onesignal ID.

There are various reasons why the OneSignal Id could be in this state. Would you be able to send over the [full logs](https://documentation.onesignal.com/docs/capturing-a-debug-log) form the device so we can pinpoint the issue?

Thanks!

**Comment by EinfachHans** [comment]
@jennantilla i also experienced this, and documented it here: https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/973

**Comment by jinliu9508** [comment]
Hi @ilhomsoliev, in your case, I would recommend using OneSignal.getUser().addObserver to listen for onesignalId when it becomes available. Note that the IDs might not be updated immediately after you log in/out due to network delays. By using the observer, you can retrieve the most recent ID when it becomes available.

**Comment by jkasten2** [comment]
Closing due to no response.
