### ISSUE TITLE
De-serializing notifications

### ISSUE THREAD

**Issue by 2x2xplz** [OneSignal/OneSignal-Android-SDK#198]
It's great to be able to easily convert an OSNotification or OSNotificationPayload to a JSONObject or JSON string via toJSONObject() (formerly the "stringify" methods). However, without the ability to deserialize the JSON back into the original objects, most of the processing is based on the raw JSON rather than the objects -- i.e. after passing an OSNotification from an OpenedHandler to an Intent, or Activity to a DialogFragment.

Ideally the OSNotification & OSNotificationPayload objects should have a constructor which accepts a JSONObject.

**Comment by jkasten2** [comment]
@2x2xplz Thanks for the suggestion. Just added this in commit 307b8c01a22cb7973194f91c8b107e32e19dcc54
