### ISSUE TITLE
[question]: 'onNotificationReceived' callback not triggered when application is in background mode

### ISSUE THREAD

**Issue by TusharGabani25890** [OneSignal/OneSignal-Android-SDK#2000]
### How can we help?

I have referred this https://documentation.onesignal.com/docs/service-extensions#android-notification-service-extension link and performed mentioned steps (like create **NotificationServiceExtension** class, manifest files changes) to receive notification when application is in background.  I have print message on **onNotificationReceived** method callback. But unfortunately I didn't get any print message event single time. I have tried 50 times but didn't get success.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@TusharGabani25890 Hello thank you for reaching out. Could you please provide the following information
1. The SDK version you are using?
2. Is the app in the background or closed?
3. Are you sending background update notifications or visual notifications?
