### ISSUE TITLE
[Bug]: Consent Decision blocks SDK interactions (like optOut)

### ISSUE THREAD

**Issue by mwoedtke** [OneSignal/OneSignal-Android-SDK#2029]
### What happened?

First at all we thought, that, if the consent is required and not given, it would be possible to subscribe, unsubscrive channels or optIn, optOut to pushes. We thought that only some data for of OneSignal (tracking etc.) would be prevented and the consent wont disable the whole feature.

At least it should be possible to optOut to the pushes if the consent is removed. 
Current behaviour is that if the consent is required, given, subscribed to channels and optIn everything works fine.
If then the consent gets removed, its not possible to optOut again and after the try to opt out and set the consentGiven to false the pushes will get recieved furthermore.
In addition its not possible to subscripe to channels and optIn to pushes, when the consent is not given but required.

### Steps to reproduce?

```Markdown
1. Setup Consent in the App
2. Setup SDK (set consentRequired, set consentGiven, initWithContext, subscribe channels, optIn) 
3. Receive pushes (everything fine until here)
4. User removes App-Consent (e.g. usercentrics)
5. Remove OneSignal-Consent (consentGiven = false)
6. OneSignal optOut
7. Send Push-Notification
8. App receives Push-Notification while no consent is given and its optOuted
```

### What did you expect to happen?

I would expect that the consent does not effect the whole sdk communication and it should be possible to optIn, optOut, subscribe to channels and reveive pushes while consent is not given.

The consent should only allow or prevent sending privacy relevant data used by OneSignal.

At least it should be possible to optOut while consent is not given.

### OneSignal Android SDK version

5.1.1

### Android version

13, 12, 11, 10, 9, 8, 7.1, 7.0, 6, 5.1, 5.0, 4.4, 4.3 or below

### Specific Android models

```Markdown
Doesn't matter. It happens on all devices. In my case it was a Samsung S10. Same issue on iOS.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jinliu9508** [comment]
@mwoedtke Thank you for reporting. The team will discuss this behavioral disparity, which disallows opting out while consent is not given, and reach back out to you.

**Comment by jkasten2** [comment]
If consent is revoked at anytime this SDK stops making all network calls to prevent leaking any data, this is by design.

To solve your issue I believe you just need to swap steps 5 and 6 in your example.
* That is call `optOut()` before setting `consentGiven = false`
