### ISSUE TITLE
[question]: GoogleService Account key dependency

### ISSUE THREAD

**Issue by Kalo2412** [OneSignal/OneSignal-Android-SDK#2032]
### How can we help?

About the Android push notifications setup in the dashboard we need to upload a Service Account Key file from Google Firebase Account Project. In our scenario we have multi tenant application. When we need to isolate every client – meaning different app for different client it seems to me that we need to generate different Firebase Account Keys. When scaling our business with more than 50 clients it means > 50 different projects in Firebase – > 50 Account Key Files. However Firebase free tier has a limit for 10 different projects. In this case we need to pay for additional services for Google. How can we resolve this?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@Kalo2412 Thanks for reaching out. This is out of scope of an SDK, you will most likely either need to reach out to OneSignal support and/or Firebase support depending on your situation.

That said from what I know about Firebase you can use more than one package (android app) per Firebase project. You can also generate more than one Firebase Account Key per Firebase project. You can limit they each key to sending notifications only too if you need to for extra security.
* If that doesn't fit your needs then you will most likely need to reach out to Firebase support to get a plan to support more than 10 projects per account then.
