### ISSUE TITLE
Amazon users show as Not subscribed

### ISSUE THREAD

**Issue by westlinkin** [OneSignal/OneSignal-Android-SDK#204]
I config app as the documents described. It works on Android devices, but it couldn't send notifications to Amazon devices. As the image shows, all Amazon users are not subscribed. 

![image](https://cloud.githubusercontent.com/assets/1687198/24835211/d196cee0-1d2d-11e7-95e5-adb6becb468d.png)

How to fix this?

**Comment by jkasten2** [comment]
@westlinkin The most common cause of this is missing the following under `<application>` in your `AndroidManifest.xml`.
```XML
<amazon:enable-feature android:name="com.amazon.device.messaging" android:required="false"/>
```

Please double check our full setup guide if you run into any other issues.
https://documentation.onesignal.com/docs/amazon-sdk-setup#section-setup-sdk-android-studio-

**Comment by westlinkin** [comment]
I enabled product flavor, so after manifest file mergers, the `amazon:enable-feature` tag becomes `enable-feature` tag, it losts `amazon` namespace. How to fix it?

In `amazon/AndroidManifest.xml` ( under `amazon` flavor folder), I declared 
```
<amazon:enable-feature android:name="com.amazon.device.messaging" android:required="false"/>
```

after gradle merges the `AndroidManifest.xml` files, it becomes 
```
<enable-feature
            android:name="com.amazon.device.messaging"
            android:required="false" />
```

**Comment by EmilAlipiev** [comment]
i have the same problem. after adding this line, I am seeing "not subscribed" instead of "outdated google play services". i followed all steps in the documentation. what could be the problem?
