### ISSUE TITLE
[question]: How to pass APK security check for apps using a web view? 

### ISSUE THREAD

**Issue by iAmWillShepherd** [OneSignal/OneSignal-Android-SDK#2056]
### How can we help?

A user reported that a security check flagged their APK because it enabled Remote WebView Debugging (something to do with this file: `com/onesignal/n5.java`). They believe that the SDK has integrated itself into their actual web app (something I understand to be impossible). Are there any features in our SDK that can install itself into a view?

Maybe the person experiencing the issue can share some useful info here (ref: [Discord](https://discord.com/channels/834476227003547689/837790237295509534/1225787486949867580)).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@iAmWillShepherd it is probably seeing this part of the code:
https://github.com/OneSignal/OneSignal-Android-SDK/blob/main/OneSignalSDK/onesignal/in-app-messages/src/main/java/com/onesignal/inAppMessages/internal/display/impl/WebViewManager.kt#L445-L451

However as you can see it doesn't enable WebView debugging unless you set OneSignal's log level to DEBUG or VERBOSE.

**Comment by jkasten2** [comment]
Closing this issue, as the security report is a false positive.
