### ISSUE TITLE
[question]: Detecting Permission Prompt User Interactions

### ISSUE THREAD

**Issue by bundleberk** [OneSignal/OneSignal-Android-SDK#2067]
### How can we help?

How do I detect when the user clicks "don't allow" from the native notification permission popup that i trigger with OneSignal.Notifications.requestPermission() method? 
There is no callback in the method itself, also IPermissionObserver's onNotificationPermissionChange method catches it only when it is true because the permission value is false as default and when the user clicks "don't allow" it is false again so callback does not trigger when the value is the same.

I am using OneSignal 5.1.8 on Android.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dabitdev** [comment]
@bundleberk how did you fix this issue?
