### ISSUE TITLE
Initializing OneSignal in a shared library 

### ISSUE THREAD

**Issue by jwburnside** [OneSignal/OneSignal-Android-SDK#207]
This situation is a little unique so bear with me: 

- I'm developing two apps which both depend on a shared library which contains all of the models/resources/dependencies that both apps use. This means I only have to add the shared library as a dependency in the app-specific build files.
- The exception is the OneSignal dependency, however. I have to add it to the app-specific build files, since each app has to define its own onesignal_app_id. 
- Therefore I'm initializing OneSignal in an app-specific BaseActivity as opposed to the shared Application class, since I can't include the dependency in my shared library. 
- This scenario seems to work except for one issue. When I'm trying to launch activities in the NotificationOpenedHandler, the results are inconsistent at best. 

So I'm assuming the inconsistent launch behavior after notification click stems from initializing OneSignal outside of the Application class. Does this sound like it could the problem? And if so, based on the scenario I have described, is there a way in which I can initialize OneSignal in my shared Application class, and define its onesignal_app_id in the app-specific build file?

**Comment by jkasten2** [comment]
@jwburnside To use OneSignal in your shared library project use the following `manifestPlaceholders` in it's `build.gradle`.
```gradle
manifestPlaceholders = [onesignal_app_id: "${onesignal_app_id}",
                        onesignal_google_project_number: "REMOTE"]
```
Then in your app's `build.gradle` you can just include the `onesignal_app_id`.
```gradle
manifestPlaceholders = [onesignal_app_id: "11111111-2222-3333-4444-555555555555",
```

As long as OneSignal init is being called from the `onCreate` of your Application class the open `NotificationOpenedHandler` on the main thread should fire consistently. It won't matter if the code it self is in another project or class.

**Comment by jwburnside** [comment]
Thanks. I'm getting a "Could not get unknown property 'onesignal_app_id' for ProductFlavor_Decorated" error when trying to sync with the advice you provided. If this is a gradle issue feel free to close the thread, I can troubleshoot from there.

**Comment by jkasten2** [comment]
@jwburnside It an inheriting limitation with gradle. You might be able to do the following for flavors like `buildTypes` are used here https://github.com/OneSignal/OneSignal-Android-SDK/issues/9#issuecomment-170194555

**Comment by jwburnside** [comment]
Gotcha, thanks!

**Comment by jwburnside** [comment]
Looks like I overlooked the previous threads, this was answered already [here](https://github.com/OneSignal/OneSignal-Android-SDK/issues/161) and worked for me.
