### ISSUE TITLE
[Bug]: Unresponsive Notifications on Xiaomi Devices

### ISSUE THREAD

**Issue by bundleberk** [OneSignal/OneSignal-Android-SDK#2070]
### What happened?

After updating the SDK to 5.1.8, on most of the Xiaomi devices when user clicks a notification, nothing happens. 

I believe the issue is the "Display pop-up windows while running in the background" permission in the "other permissions" section on Xiaomi devices is "not granted" by default after installing the app with the 5.1.8 SDK.

After I grant the permission, notifications work properly. Also it works properly on OneSignal 4.8.7 even if this permission is not granted on Xiaomi devices. Something seems to be changed about this on OneSignal 5.x.x versions.

### Steps to reproduce?

```Markdown
1. Find a Xiaomi device.
2. Install an app that has OneSignal 5.1.8 SDK.
3. Check if the  "display popup windows while running in the background" is granted or not.
4. Send a push notification.
5. Click notification.

try it again after granting the permission from "other permissions".
```

### What did you expect to happen?

I expect the notifications open the app when clicked, in this case notifications disappear when clicked but nothing happens after.

### OneSignal Android SDK version

Release 5.1.8

### Android version

13, 12, 11, 10, 9

### Specific Android models

```Markdown
most of the Xiaomi devices.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@bundleberk Thanks for reporting, however there is another open issue #2042 that covers this. I am merging this one into existing one so we have one thread to track this issue. Please follow issue #2042 for updates.
