### ISSUE TITLE
[question]: Extremely Slow Callbacks On Version 4.8.9

### ISSUE THREAD

**Issue by bundleberk** [OneSignal/OneSignal-Android-SDK#2074]
### How can we help?

I had to downgrade to OneSignal 4.8.9 because of the bugs that 5.x.x versions had.  OSSubscriptionObserver and SetExternalId completion callbacks are extremely slow. SetExternalId callback always triggers after 5 seconds like it is done on purpose. OSSubscriptionObserver is also triggers after 5-10 seconds. Those are very long times since I need to do some other operations like setting tags to the user. Any ideas?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@bundleberk The calls back are only fired after the network call is completed. Network calls are delayed by 5 seconds so as many operations can be batched together into a single network call as an optimization.

You can call `sendTag()` before the the device is subscribed. If need to conditionally set tags if the user has accepted notification permissions or not I would recommend OSPermissionObserver instead.

**Comment by bundleberk** [comment]
backend sets the tags in our structure unfortunately not the client.

**Comment by jkasten2** [comment]
@bundleberk Splitting up setting values on the player between your backend and your app, especially on create / first start, does things more complex. In your scenario it more serial operations that depend on each other. I think moving the tag setting to the client will simply things a bit, and should make this process after.

I don't think I have the full picture of what your needs are and what you are currently doing but I'll fill in the gaps by stating some assumptions to get us on the same page. Let me know if this is right or wrong:
1. Your app has a login screen, this calls your backend, the returns some kind of `id` to your app
2. You use the `id` you got from your server and call `setExternalId `
3. When `OSSubscriptionObserver` fires you make a 2nd call to your backend, where it makes a REST API call to `PUT api.onesignal.com/players/{{ONESIGNAL_PLAYER_ID}}` to set the tags.

If the above it right I would recommend you instead you pass the tag values you want to set on the OneSignal Player from your login endpoint. So on step 1 above, pass `tags` in addition to your `id` when the end-user logs into your app. Then you call simply call `OneSignal.setExternalId(myId)` and `OneSignal,sendTags(myTags)` and the SDK will handle settings these, even if the app is swiped away or there was any connection issues.

**Comment by bundleberk** [comment]
mostly correct,

1- I call backend to get an id on app's login
2- I start listening to OSSubscriptionObserver.
3- When OSSubscriptionObserver callback fires I get the Player ID
4- I'm calling setExternalId with the id that i got from backend in Step1, and wait for the setExternalId success callback.
5- After setExternalId is successful I make the 2nd call to backend where it makes a REST API call to PUT api.onesignal.com/players/{{ONESIGNAL_PLAYER_ID}} to set the tags.

thanks for the recommendation it could work better.

**Comment by jkasten2** [comment]
Summary, the 5 second delay is by design to optimize network calls. The 15 second delay is due to operations depending on each other, which can be avoided changing how tags are externalId are used with OneSignal. While there might be a change the SDK could make to make this smoother there isn't plans to make any large changes to the 4.x.x branch, instead this would be better to 
consider for 5.x.x  and future major versions of the SDK.

If this scenario is still a concern for User Model (5.x.x) please open a new issue.
