### ISSUE TITLE
⛔️ Do NOT use Release 5.1.11 (2024/05/07) ⛔️

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-Android-SDK#2079]
## Notice
Do NOT use Release 5.1.11 which was released on 2024/05/07. This version has two new known issues:
* Unintentionally only build compatible with AGP 8 (Android Gradle Plugin) and newer.
* App may crash with `IndexOutOfBoundsException` on app startup if the device was offline in some cases.

## Addressing the issue
The issues above have been addressed in release [5.1.12](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.12), released 2024/05/08.

**Comment by rahat14** [comment]
True could not build

**Comment by DaxeshV** [comment]
yes. facing same issue 

Execution failed for task ':app:mergeExtDexDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform notifications-5.1.11.aar (com.onesignal:notifications:5.1.11) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=26, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingNoClasspathTransform: /Users/imac/.gradle/caches/transforms-3/7b486222aa3165d1f1e21dfa923dd258/transformed/jetified-notifications-5.1.11-runtime.jar.
         > Error while dexing.

**Comment by jkasten2** [comment]
@rahat14 and @DaxeshV the issues have been fixed in [5.1.12](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.12) which was released today.
