### ISSUE TITLE
[question]: I close the app and open it again and push notifications are auto-generated in my app.

### ISSUE THREAD

**Issue by RuHuaytaMars** [OneSignal/OneSignal-Android-SDK#2092]
### How can we help?

When I close the app and open it again, the notifications are generated again, such as correctly controlling that the push is not generated again if the backend is no longer sending me anything.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RuHuaytaMars** [comment]
![photo_5069318705577569127_w](https://github.com/OneSignal/OneSignal-Android-SDK/assets/86047192/28408dc1-5961-4381-a476-2e6ec68cdcd2)

**Auto regenerated notifications on.

**Comment by jkasten2** [comment]
@RuHuaytaMars when you close your app do the notifications disappear from the Notification Shade? (This happens if the app is "force stopped")
If this is the case then OneSignal restores the notification as they end-user never interacted with it, this way they don't miss the notification. If the end-user swipes away the notification or taps on it it should not restore.

**Comment by RuHuaytaMars** [comment]
Correct, what happens is that the flow of my application is an app for taxi services, that is, for each tracking status a notification is displayed whether the customer interacts with the notification or not, it disappears when it changes status as it could do so that when changing the status that push no longer appears.

**Comment by jkasten2** [comment]
>  ... it disappears when it changes status as it could do so that when changing the status that push no longer appears.

By the notification disappears is that your code is dismissing the notification? If so, make sure you use `OneSignal.Notifications.removeNotification(id)` so the OneSignal SDK knows that your app indented for notification to be dismissed, so it won't restore it.

If you don't want to display the notification if it arrives late (such as the device losses connection) I recommend setting a short TTL on the notification. The TTL is also respected the notification restore logic too.  

If there are other scenarios not covered above you can setup the [OneSignal Android Notification Service Extension](https://documentation.onesignal.com/docs/service-extensions#android-notification-service-extension) so you can control if the notification will show based on any logic you wish.
