### ISSUE TITLE
[question]: Disable In app Push Notification with new 5.x version 

### ISSUE THREAD

**Issue by simranthakkar1996** [OneSignal/OneSignal-Android-SDK#2097]
### How can we help?

I was following the OneSignal migration guide 
https://github.com/OneSignal/OneSignal-Android-SDK/blob/user-model/main/MIGRATION_GUIDE.md

And I have to disable in app message 
With the older version we had a parameter (selection) boolean that we were using as parameter of disabling in app push notification. 
With the version update I updated the code and according to the migration we can use 

**boolean getPaused()
void setPaused(boolean value)**

but I was just thinking of how we can provide the user selection boolean value to the optOut method that we have in this new version

```
OneSignal.promptForPushNotifications(false,
                    selection -> {
                        OneSignal.disablePush(!selection);
                    });
```

Thank you so much for the help

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@simranthakkar1996 The replacement for `OneSignal.disablePush(true)` is `OneSignal.getUser().getPushSubscription().optOut()`

**Comment by simranthakkar1996** [comment]
@jkasten2 I had a doubt so I understand we can use 
OneSignal.getUser().getPushSubscription().optOut()
But we would need the user selection right when we prompt the notification
So my question was the prompt that we have to give is changed I think

**Comment by jkasten2** [comment]
@simranthakkar1996 it seems your orignal code was accounting for ensuring push was enabled after permission was accepted, 
 as it sounds like you call `OneSignal.disablePush(true)` in other parts of your code.

With 5.x.x you can simply call `optIn()` and `optOut()` and this state will be taken care of for you with the SDK. Calling `optIn()` will prompt the end-user for notification permission if needed, so these are the only two methods  you need to use.

**Comment by simranthakkar1996** [comment]
So just optIn() and optOut() will do the trick 
We just are checking that if its already prompted or not and based on that we are adding condition to optIn() or optOut()
If it makes sense. Any feedback matters
Thank you so much 

```
boolean pushPrompted = OneSignal.getNotifications().getCanRequestPermission();
if (pushPrompted) {
       OneSignal.getUser().getPushSubscription().optOut();
} else {
       OneSignal.getUser().getPushSubscription().optIn();
}
```

**Comment by jkasten2** [comment]
@simranthakkar1996 If you simply have an option in your app to turn push notifications on and off then you can simply call `optOut()` or `optIn()` depending on what the user wants. If you want to know what the current status is call `getOptedIn()` so you can show that in your UI.

If there is more to it than that please explain in more detail.

**Comment by simranthakkar1996** [comment]
@jkasten2 Actually we wanna show the dialog and based on user selection we wanna either optIn or optOut 
That's why we update the method mentioned in the migration guide from

```
 OneSignal.promptForPushNotifications(false,
                     selection -> {
                         VFPreference.get().putBoolean(PUSH_NOTIFICATION_PERMISSION_DIALOG_PRESENTED, true);
                         OneSignal.disablePush(!selection);
                     });
```

To now using Continue 
```
OneSignal.getNotifications().requestPermission(Continue.with(r -> {
                if (r.isSuccess()) {
                    if (r.getData()) {
                        // User accepted the permission
                        OneSignal.getUser().getPushSubscription().optIn();
                    } else {
                        // User rejected the permission
                        OneSignal.getUser().getPushSubscription().optOut();
                    }
                } else {
                    // Handle failure
                    VFLog.e(TAG, "One-Signal Permission request failed");
                }
            }));
```

There is just one issue with this new approach that r.getData() is giving an issue that its object and we are expecting boolean type.

**Comment by simranthakkar1996** [comment]
Okay @jkasten2 I think I have figured it out I was referring to this document 
https://documentation.onesignal.com/docs/mobile-sdk#push-notifications

And they had incorrect data was missing a boolean value 
 OneSignal.getNotifications().requestPermission(Continue.with(r -> { ---------------> was missing a boolean parameter here
                if (r.isSuccess()) {
                    if (r.getData()) {
                        // User accepted the permission
                        OneSignal.getUser().getPushSubscription().optIn();
                    } else {
                        // User rejected the permission
                        OneSignal.getUser().getPushSubscription().optOut();
                    }
                } else {
                    // Handle failure
                    VFLog.e(TAG, "One-Signal Permission request failed");
                }
            }));

**Comment by jkasten2** [comment]
@simranthakkar1996 Ah I see, thanks for pointing out the documentation mistake. We will get that updated.

**Comment by nan-li** [comment]
Hi @goncalo-oliveira, I don't think you should receive them if you choose "Send Test Push" from the dashboard. Can you confirm that you do not receive if you send as "regular push"? Does your subscription show as "Unsubscribed Subscriber Opted Out" in the dashboard?

**Comment by goncalo-oliveira** [comment]
@nan-li thanks for replying.

> Does your subscription show as "Unsubscribed Subscriber Opted Out" in the dashboard?

No, the subscription continues to show as "Subscribed" after calling `optOut`.

**Comment by goncalo-oliveira** [comment]
Ok, I'm not sure what happened, but it's working now. I reset the simulator device (which rotated the device's uuid) and it worked as expected.

- Initial state is unsubscribed
- Push message not delivered
- Enabling (`optIn`) changes the state to subscribed
- Push message delivered
- Disabling (`optOut`) changes the state to unsubscribed (although it takes a few seconds)
- Push message not delivered

The code didn't change, so I'm not sure what happened.
