### ISSUE TITLE
[question]: OneSignal.OSNotificationOpenedHandler deprecated in 5.x version 

### ISSUE THREAD

**Issue by simranthakkar1996** [OneSignal/OneSignal-Android-SDK#2098]
### How can we help?

We created a class to handle notification once we open it and we are implementing 
OneSignal.OSNotificationOpenedHandler which now seems to be unavailable for 5.x version. 

Because the older version 4.x had the method which we were using something like this 
```
 @Override
    public void notificationOpened(@NonNull OSNotificationOpenedResult result) {
        JSONObject data = result.getNotification().getAdditionalData();
        if (data != null) {
            if (condition.....) {
                // condition to open specific page of the app
            } else {
                VFLog.e(TAG, "Notification Key not recognized : " + result);
            }
        }
    }
```

Thank you for answering all the question related to this migration

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@simranthakkar1996 the replacement for `setNotificationOpenedHandler` is `addClickListener`.
Exmple:
```java
OneSignal.getNotifications().addClickListener(event -> {
    JSONObject data = event.getNotification().getAdditionalData();
    Log.v(Tag.LOG_TAG, "INotificationClickListener.onClick fired" +
                       " with event: " + event);
});
```
