### ISSUE TITLE
Your use of exact alarms is causing your app to crash for some Android users

### ISSUE THREAD

**Issue by ArsalTech** [OneSignal/OneSignal-Android-SDK#2100]
### What happened?

i am getting this message from playconsole as i am using onesignal sdk to engage my users it works on decives having android version until 13 but later in 14 that causes issue i-e 
Your app schedules exact alarms without checking whether the SCHEDULE_EXACT_ALARM permission has been granted. This is causing your app to crash for users on Android 14 because the permission is no longer granted by default.

As i am using this line of onesignal oce to get notification permission but it seems that is not workig on android 14 version devices. Below is the code i uses to get notification permission.
  CoroutineScope(Dispatchers.IO).launch {
            OneSignal.Notifications.requestPermission(true)
        }

sdk i am using.
    implementation 'com.onesignal:OneSignal:[5.0.0, 5.99.99]'

### Steps to reproduce?

```Markdown
install the app.
splashscreen launches and app get crahes.
```

### What did you expect to happen?

I want to get notification permission from user sng moves to main instead of crashing.

### OneSignal Android SDK version

5.0.0

### Android version

13

### Specific Android models

```Markdown
Android version 14
```

### Relevant log output

```Shell
Your use of exact alarms is causing your app to crash for some Android users
expand_less
Your app schedules exact alarms without checking whether the SCHEDULE_EXACT_ALARM permission has been granted. This is causing your app to crash for users on Android 14 because the permission is no longer granted by default.
In most cases, alternative methods of scheduling work or inexact alarms are more appropriate. If your use of exact alarms is justified, update your app so that it checks this permission is granted before scheduling.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArsalTech** [comment]
But I am not using alarm of any type.
It's actually the notification permission that is different in android
version 14 so  make it compatible with Android 14 notification permission.

**Comment by nan-li** [comment]
The OneSignal SDK does not do anything with schedules exact alarms. Please check your own codebase and other dependencies you may have?
