### ISSUE TITLE
[question]: RE: ANR on OnePlus devices

### ISSUE THREAD

**Issue by vknow360** [OneSignal/OneSignal-Android-SDK#2107]
### How can we help?

https://github.com/OneSignal/OneSignal-Android-SDK/issues/2010

Was this fixed in 4.8.8 ? Or fix is exclusive to user centric model?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@vknow360 Thanks for surfacing. I replied to your comment here: https://github.com/OneSignal/OneSignal-Android-SDK/issues/2010#issuecomment-2150515987
