### ISSUE TITLE
[question]: OneSignal.initWithContext use too long time

### ISSUE THREAD

**Issue by gitByEOS** [OneSignal/OneSignal-Android-SDK#2108]
### How can we help?

We have added 10+ sdks on our app, so the launch time is quite long. 
sdk initialization use about 600ms, but all other sdk initialization use between 10ms-40ms, only `OneSignal.initWithContext` use 260ms.
Can you do some optimization, this aggravates the data of our app launch time!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@gitByEOS We made some improvements in [5.1.12](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.12) to avoid ANRs / lower the sdk initialization time. We will be optimizing this further in future releases.

**Comment by jinliu9508** [comment]
Hello @gitByEOS, We've made significant performance improvements in version [5.1.19](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.19), which help minimize the initialization time by roughly 50%, generally on most devices. Please give it a try and let us know how it works for you. Keep in mind that we're continuously working on further enhancements to ensure faster response times and a better customer experience.
