### ISSUE TITLE
[Bug]: Unable to login to any other external id once user_subscription_limit has reached on previous external id

### ISSUE THREAD

**Issue by areehafarooq** [OneSignal/OneSignal-Android-SDK#2124]
### What happened?

External id is not getting updated against subscription id for a specific case. If OneSignal.login is called for an external id against which user subscription limit has reached then after that logging to any other external id does not work as well. It fails with the same error POST - STATUS: 409 - Body: {"errors":[{"code":"subscription-1","title":"Operation is not permitted due to user having the maximum number of subscriptions assigned","meta":{"user_subscription_limit":200}}]} although no subscription exists against the new external id. 

### Steps to reproduce?

```Markdown
1. Call OneSignal.login with user id that has reached max user subscription limit.
2. Call OneSignal.login with any other user id that has no subscriptions.
```

### What did you expect to happen?

I expected external id to update.

### OneSignal Android SDK version

Release 5.1.13

### Android version

13

### Relevant log output

```Shell
HttpClient: Got Response = POST - STATUS: 409 - Body: {"errors":[{"code":"subscription-1","title":"Operation is not permitted due to user having the maximum number of subscriptions assigned","meta":{"user_subscription_limit":200}}]}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jfishman1** [comment]
Please contact support@onesignal.com with your app ID, the subscription ID and external ID. We can help resolve this for you.

**Comment by sw-tt-jigarkumarpatel** [comment]
Same issue found on com.onesignal:OneSignal:5.1.17...Please give proper solution

**Comment by jkasten2** [comment]
@sw-tt-jigarkumarpatel See this comment for the current solution and what is planned for the future:
https://github.com/OneSignal/OneSignal-Android-SDK/issues/2143#issuecomment-2218710776

**Comment by sahil-devinci** [comment]
@jkasten2 Is there a better solution than contacting you support?
