### ISSUE TITLE
targetSDK 34

### ISSUE THREAD

**Issue by chad171** [OneSignal/OneSignal-Android-SDK#2144]
### How can we help?

When I do the Android SDK Upgrade Assistant to version 34 it finds many problems due to "Foreground service types are required." I have 'problems' that are located in androidmanifest.xml files located in the Onesignal sdk. Google is stating that all updates will require going to version 34 before the end of August 2024.

What do I need to do to comply with the new mandate when using the Onesignal SDK?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@chad171 make sure you are either using the latest OneSignal 4.x.x or 5.x.x Android SDK. If you are already up to date please share exactly what errors you are getting.

**Comment by chad171** [comment]
I am using com.onesignal:OneSignal:5.1.17, the problems are noted in the Android SDK Upgrade Assistant, under "Foreground service types are required".

In the image everything with the version number 5.1.17 is from OneSignal.

![image](https://github.com/OneSignal/OneSignal-Android-SDK/assets/73857804/fa509dbb-fe7c-49d4-abba-75d257b2713f)

**Comment by jkasten2** [comment]
@chad171 the upgrade assistant is listing all `<service>` as it is suggesting you review them if they are foreground services. The foreground vs background is defined in code and it can't detect that automatically. Their report is a bit misleading as it sounds like a problem when really it's just something you need to review to confirm there are no issues. The report list many other libraries, even ones created by Google.

I can confirm that OneSignal does not use foreground services (only background) so it doesn't need the `foregroundServiceType` setting the report is noting. In summary 5.1.17 is safe to use when your app targets Android API level 34.
