### ISSUE TITLE
[Bug]: Text fields on in-app messages not opening soft keyboard

### ISSUE THREAD

**Issue by jasminvucelj** [OneSignal/OneSignal-Android-SDK#2145]
### What happened?

Hello, it seems in-app messages containing editable text fields are not working properly, as they don't seem to be able to open the soft keyboard. When tapped, the popup window even moves up as if to make space for the keyboard, but it doesn't show up. I've tested multiple versions and it seems the one that breaks it is 5.1.5, presumably due to the focusability change in #1999. The log output I've included is printed out when the field is tapped.

### Steps to reproduce?

```Markdown
1. Install dependency version 5.1.5 or newer
2. Trigger an in-app message containing a text field
3. Tap the text field in the message
```

### What did you expect to happen?

I expected the soft keyboard to open and allow me to edit the field.

### OneSignal Android SDK version

5.1.17

### Android version

13

### Specific Android models

```Markdown
* Xiaomi Mi 11
```

### Relevant log output

```Shell
Ignoring showSoftInput() as view=com.onesignal.inAppMessages.internal.display.impl.OSWebView{9fa2447 VFED..C.. .F....ID 0,0-1440,3200} is not served.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jinliu9508** [comment]
Hello @jasminvucelj, this has been fixed in [5.1.21](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.21). I recommend upgrade your SDK to the latest version and should you encounter more problems related to this issue, please let us know.
