### ISSUE TITLE
[question]: Notifications Not Appearing in Notification Center and Not Received on Galaxy devices in version 4.8.7

### ISSUE THREAD

**Issue by jae1jeong** [OneSignal/OneSignal-Android-SDK#2150]
### How can we help?

Issue Type: Question

Symptoms:

On some devices, notifications are received, but when checking the notification center, the notifications do not appear.
On the Galaxy Z Flip3, the notification history shows notifications from my app, but the notifications themselves are not received.
I am using OneSignal version 4.8.7.

my OneSignal Setting in application class
`

       override fun onCreate() {
        super.onCreate()

        if (BuildConfig.DEBUG) {
            Timber.plant(DebugTree())
        }
        OneSignal.initWithContext(applicationContext)
        OneSignal.setAppId(BuildConfig.SIGNAL_ID)
        OneSignal.setNotificationOpenedHandler(OneSignalNotificationClickHandler(applicationContext))
        OneSignal.promptForPushNotifications()
        NdCrashlytics.init()
`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jae1jeong** [comment]
+ I have tested the app with the battery saver mode turned off.

**Comment by jkasten2** [comment]
@jae1jeong I haven't seen this specific behavior before:
> ...the notification history shows notifications from my app, but the notifications themselves are not received. In order for the notification to show under the "Notification history" list it would have had to be visible at some point. 

### Questions
1. Do you have the Notification Category / Channels enabled for your app as well?
* If you don't see this setting Samsung OneUI 6.1 hides it by default, so you must go to Notifications > Advanced Settings > Turn on "Manage notification categories for each app."

2. Do you use the OneSignal Notification Extension Service?

3. Do you clear notifications programmatically at any point in your app?

4. Can you share the logcat when reproducing the issue?

**Comment by jae1jeong** [comment]
1. My device was turned off, so I turned it on. What is the difference between being turned off and being active?
2. Yes, I am using it.
`
class OneSignalNotificationClickHandler (private val context: Context) : OneSignal.OSNotificationOpenedHandler {

    // 알림이 열릴 때 호출되는 메서드
    override fun notificationOpened(result: OSNotificationOpenedResult) {
        val data = result.notification.additionalData
        handleNotificationClick(data)
    }

    // 알림 데이터를 기반으로 적절한 액티비티로 이동
    private fun handleNotificationClick(data: JSONObject?) {
        val intent = SplashActivity.getIntent(context, data.toString())
        intent.flags = Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TASK
        // 알림 데이터에서 추가 정보 추출 (예: "pageId")
        data?.let {
            if (it.has("pageId")) {
                val pageId = it.getString("pageId")
                // 인텐트에 추가 데이터 설정
                intent.putExtra("pageId", pageId)
            }
        }

        context.startActivity(intent)

    }
}


`

3. No.
4. It's not my device, but a few devices being used. Since it is a production app, I cannot check the logs.

**Comment by jae1jeong** [comment]
Notifications are received, but they do not appear in the notification center. This issue is the main concern.

**Comment by jkasten2** [comment]
1. I was referring to [Android: Notification Channel Categories](https://documentation.onesignal.com/docs/android-notification-categories). Not sure if you are using them, or if you disable any of them on the device for your app.
2. You would only be using [Notification Service Extension](https://documentation.onesignal.com/v9.0/docs/service-extensions#android-notification-service-extension) if you have added the `remoteNotificationReceived` method to your app.
3.  👍 
4. You are not  able to reproduce the issue on any of your test devices? Even if you can only produce the issue on the production build of your app you can check the device's system logcat. It may show a reason why the notification wasn't displayed.

5. Just to confirm the issue, even if you are watching the device when sending a push notification it doesn't show at all? Not even for a few seconds? Does the device vibrate or make a sound at all either?

6. Do you have any other SDKs / libraries or code that is using Notifications?

**Comment by jae1jeong** [comment]
I found the solution. Reason was proguard. I send with notification with small_icon_name with my drawable name, but proguard applied.

My last question is why are notification not sending when not drawable  found exception?
I thought will send with no drawable(default icon).

**Comment by jkasten2** [comment]
@jae1jeong can you share the proguard settings you are using? The SDK should have kept your custom small icon file, as it defines its own keep settings:
https://github.com/OneSignal/OneSignal-Android-SDK/blob/74911221572a91be208ed7df743a26fcf1881042/OneSignalSDK/onesignal/notifications/src/main/res/raw/consumer_onesignal_keep.xml#L6


There is also fallback logic in the SDK so I am surprised it doesn't work either:
https://github.com/OneSignal/OneSignal-Android-SDK/blob/36e682413793c3634b89de334a24942112d64bf5/OneSignalSDK/onesignal/notifications/src/main/java/com/onesignal/notifications/internal/display/impl/NotificationDisplayBuilder.kt#L326-L340

**Comment by jae1jeong** [comment]
That's weird. I didn't set keep.xml when I asked before. 
My changed code
xml/keep.xml
```
<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:tools="http://schemas.android.com/tools"
    tools:keep="@raw/direct1,@raw/direct2,@raw/direct3,@raw/nd1,@raw/nd2,@raw/nd3,@drawable/ic_notification_nd" />
```
    
   
   It worked for me.
   
   
   but some devices(galaxy note 20) not ringing my custom sound. other devices seems working well.
   I created notification channels each custom sound file.

**Comment by jkasten2** [comment]
Thanks for sharing your proguard config, I don't see anything that sticks out, and doesn't see any aggressive settings.

> but some devices(galaxy note 20 Android13) not ringing my custom sound. other devices seems working well.
I created notification channels each custom sound file.(also all enabled notification channels)

Did you change the settings for the channel after it was created? Devices won't take the new channel settings after they are created, Android has this restriction as the end-user may have changed the settings.
* If you uninstall the reinstall the app on the device this should fix this issue.
* If you already released your app and you must change this then you will need to create a new Android Channel / Category.

**Comment by jae1jeong** [comment]
I tried to remove app data then it worked. thanks.
