### ISSUE TITLE
[question]: Setting Google Android (FCM)

### ISSUE THREAD

**Issue by vietdung97** [OneSignal/OneSignal-Android-SDK#2153]
### How can we help?

My app required update FCM API (V1) so I tried setting up Google Android (FCM) but I got this error: _You are attempting to add a Service Account JSON file with a new Sender ID. This will prevent current subscriptions from receiving notifications, as they are tied to the previous Sender ID. Ensure you are uploading the file associated with the previous Firebase Project that has the same Sender ID._

My app has:

- Total Subscribed > 400
- Total Record > 700

![image](https://github.com/user-attachments/assets/ab6a54d7-cfc9-46a0-9045-330e9a0606f1)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @vietdung97,

This message comes up when trying to upload a file that has a different Sender ID than the current android subscribers are tied too.

You need to generate the Service Account JSON file from the same Firebase project as the current Sender ID found in the Cloud Messaging API (Legacy) > Sender ID

Details here as well. https://documentation.onesignal.com/docs/generate-firebase-credentials

**Comment by vietdung97** [comment]
@nan-li The Firebase project was set up by the legacy provider, I received an email saying we should update to FCM v1 because Legacy doesn't support the feature

Can you help me update it manually, I really need it because my app is available on Play Store. I can demonstrate anything if you want (except Firebase currently)

**Comment by jkasten2** [comment]
Closing due to no response
