### ISSUE TITLE
background notification in android for onesignal 

### ISSUE THREAD

**Issue by S00raj-hcbs** [OneSignal/OneSignal-Android-SDK#2155]
### How can we help?

how to handle background notification in android for onesignal sdk 5.1.17?

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@S00raj-hcbs you can create a [OneSignal Android Notification Service Extension](https://documentation.onesignal.com/docs/service-extensions) to do this.

**Comment by S00raj-hcbs** [comment]
like [Document like](https://documentation.onesignal.com/docs/osnotification-payload)

**Comment by jkasten2** [comment]
I see, the link should be point to this doc:
https://documentation.onesignal.com/v9.0/docs/osnotification-payload

The doc was written for the 4.x.x version of this SDK, however most of the properties are the same with 5.xx. We will look into fixes these docs.

In the meantime feel free to use the link above and the auto complete from Android Studio. If you would like a bit more detail you can look at the source of the interface here:
https://github.com/OneSignal/OneSignal-Android-SDK/blob/5.1.15/OneSignalSDK/onesignal/core/src/main/java/com/onesignal/notifications/INotification.kt

**Comment by S00raj-hcbs** [comment]
give me proper document for onesignal notification so i can manage in my application.

**Comment by jinliu9508** [comment]
Hello @S00raj-hcbs  this [doc](https://documentation.onesignal.com/docs/service-extensions#android-notification-service-extension) would give you the details on how to handle notifications in background. Please let us know if you have any more questions regarding the background notification.
