### ISSUE TITLE
Android, remove manifestPlaceholders

### ISSUE THREAD

**Issue by kamendo** [OneSignal/OneSignal-Android-SDK#216]
Android, feature request

Can you remove the need for manifestPlaceholders = [onesignal_app_id:"..."] ?

I am working on a project where OneSignal app id is configured dynamically from a server.

**Comment by jkasten2** [comment]
@kamendo See issue #127 to set this dynamically at run time. We don't document are we are looking into some features that will require it to be done at compile time.

Thanks.

**Comment by kamendo** [comment]
Thank you, @jkasten2!

As of version 3.5.1 - what features I will miss if I set onesignal app id at run time?
