### ISSUE TITLE
Java version?[question]: 

### ISSUE THREAD

**Issue by CarlosCMD** [OneSignal/OneSignal-Android-SDK#2166]
### How can we help?

Non-kotlin user here, which lib version is in java android?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@CarlosCMD The same version of the library is compatible with both Kotlin and Java. The API is the same, there is just a few different rules for how Java works vs Kotlin, but those are all covered in the OneSignal docs:
https://documentation.onesignal.com/docs/mobile-sdk-reference
