### ISSUE TITLE
App notification logo

### ISSUE THREAD

**Issue by S00raj-hcbs** [OneSignal/OneSignal-Android-SDK#2171]
### How can we help?

how to default small and large icon set in android notification? For **onesignal 5.1.17**

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@S00raj-hcbs this page covers how to set defaults for both large and small icons for notifications sent through OneSignal:
https://documentation.onesignal.com/docs/android-notification-icons
