### ISSUE TITLE
[Bug]: New account can not receive the push notification when swith from previous account that reached the maxmium subscriptioin number

### ISSUE THREAD

**Issue by Joemiao120** [OneSignal/OneSignal-Android-SDK#2186]
### What happened?

I have 2 accounts, the first account has the maximum number of subscriptions assigned, and it cannot receive any push notification, so I switched to another new account, after I called the logout function, I still could not receive the push notification, even I've checked the account status, opted-in, have permission.

### Steps to reproduce?

```Markdown
1. Login first account has the maximum number of subscriptions assigned
2. Logout
3. Login a new account
4. Send a push notification
```

### What did you expect to happen?

I want the second account can receive the push notification.

### OneSignal Android SDK version

5.1.20

### Android version

14

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@Joemiao120 Thanks for reporting, this is the same issue as #2143 so let's combine these together by using that one instead.

The summary from there is:
1. > It unlikely a legitimate end-user would do this 20 times, however it possible it could happen. In this case you would have to clean up the older subscriptions by deleting them. This could be done via the [OneSignal DELETE /subscriptions REST API](https://documentation.onesignal.com/reference/delete-subscription) if this comes up in the real world.
2. BUG: Even if the limit is hit switching users should be allowed, however there is a bug where the SDK doesn't recover from this. Please subscribe to issue #2143 to keep up with the status of this bug.
