### ISSUE TITLE
expose google.sent_time as a property of OSNotificationPayload

### ISSUE THREAD

**Issue by 2x2xplz** [OneSignal/OneSignal-Android-SDK#219]
The rawPayload JSON of an OSNotification object includes a google.sent_time field. However I do not see this exposed as a property. Would be nice to have an OSNotificationPayload.sentTime property rather than navigating a JSON object, like we have for notificationID. Thanks.

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration
