### ISSUE TITLE
Action button always dismisses Notification

### ISSUE THREAD

**Issue by Ioane5** [OneSignal/OneSignal-Android-SDK#220]
Is there any way to keep notification after notification action button is clicked? 

As I checked here is [line in code](https://github.com/OneSignal/OneSignal-Android-SDK/blob/e4a1d6d1bd0fadf5ce23e7b495617fcc7de2b887/OneSignalSDK/onesignal/src/main/java/com/onesignal/NotificationOpenedProcessor.java#L59) that dismisses notifications after button click.

**Comment by jkasten2** [comment]
@Ioane5 There isn't way to control this with a flag currently with our SDK. Neither with a per notification or a global stetting.

However you can use our [NotificationExtenderService](https://documentation.onesignal.com/docs/android-customizations#section-background-data-and-notification-overriding) to add your buttons. If you extend our notification and add them this way with your own `Intent` the tap event won't dismiss it as it won't be going through our SDK code.

**Comment by Ioane5** [comment]
Thanks! I thought about that option.
