### ISSUE TITLE
[question]: Hi I'm trying to handle push notification events coming from a messaging service of my company, what happens is that the push arrives and I want that when I click it redirects my app to the main screen, ActivityStart example??

### ISSUE THREAD

**Issue by RuHuaytaMars** [OneSignal/OneSignal-Android-SDK#2206]
### How can we help?

@Keep
public class OSDataReceiver implements INotificationServiceExtension, HttpObtenerServiciosV3.InterfaceNotification {
	// *****************************************
	// ***************** PUSH NOTIFICACIONES ******************
	// *****************************************
	private final int PROCESS_CERRAR_SESSION = 101;

	@Override
	public void onNotificationReceived(@NonNull INotificationReceivedEvent event) {
		try {
			Log.e("OSDataReceiver", "onNotificationReceived");
			IDisplayableMutableNotification notification = event.getNotification();
			JSONObject data = notification.getAdditionalData();
			String jsonData = data.toString();
			Log.e("SDOneSignalJSON", "id = " + notification.getNotificationId() + " - " + jsonData);
			if (!jsonData.isEmpty()) {

				event.preventDefault(true);
				BeanNotificationOS beanOneSignalPush = BeanMapper.fromJson(jsonData, BeanNotificationOS.class);
				Log.e("SDOneSignalPush", "Request : " + BeanMapper.toJson(beanOneSignalPush));
				//	new HttpGetNotification(this, this).execute(beanOneSignalPush);
				// TODO -  ya no se usara la descarga
				Context context = ApplicationClass.getInstance();
				new HttpObtenerServiciosV3(context, this, beanOneSignalPush).execute();
				//initNotification(beanOneSignalPush);
			}
			// Return true to stop the notification from displaying.
			//event.getNotification().display();
		} catch (Exception ex) {
			ex.printStackTrace();
		}
	}

My Notification Service

SDK version : One Signal 5.1.20

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jinliu9508** [comment]
Hello @RuHuaytaMars, if I understand correctly, you want to start a specific activity when the notification is clicked. If that's the case, I believe you can add a `foregroundLifecycleListener` to the notification and implement the 'onWillDisplay' method. This way, when your app is opened upon clicking the notification, you can start the desired activity. 

Here is more info for ['foregroundLifecycleListener'](https://documentation.onesignal.com/docs/mobile-sdk-reference#addforegroundlifecyclelistener)

Let me know if you have further questions, I will be glad to help!
