### ISSUE TITLE
SQLite Downgrade Exception Thrown

### ISSUE THREAD

**Issue by OlegTarashkevich** [OneSignal/OneSignal-Android-SDK#222]
Hi @jkasten2 I have a bug, please look at the screenshot
 compile 'com.onesignal:OneSignal:3.+@aar'

![2017-05-04 21 39 10](https://cloud.githubusercontent.com/assets/13828110/25719605/abbefe42-3112-11e7-882c-cdf1e593a6f9.png)

**Comment by jkasten2** [comment]
@OlegTarashkevich Are these crashes from your production app? This can only happen if a version of your app is installed with our 3.4.4+ SDK then the app is downgraded to a version before this. Downgrades should be extremely rare as users would have to side load an old APK. 

We'll implement the `onDowngrade` method to prevent this crash in the future.

**Comment by jkasten2** [comment]
@OlegTarashkevich I have added the `onDowngrade` method for future handling of SDK downgrading. c4ffa7d239275a90422e2ec64c77039dde3e8d42. This will prevent any future "3+ to 2" errors.

The only way to prevent the `"2 to 1"` errors is to not rollback to a pre-3.4.4 version of our SDK if you released your app with a 3.4.4+ version.

If the above is not the case for you then there must be some users who are side-loading an old version of your app over a new version. They will need to do a full uninstall first or clear all data on your app if they are downgrading your app.
