### ISSUE TITLE
onsignal problem with gsonFactory

### ISSUE THREAD

**Issue by FaridBeiranvand** [OneSignal/OneSignal-Android-SDK#225]
hi.i want to use oneSignal in my project and when i add this to `build.gradle`,in execution i get force close with this error:
```Java
java.lang.NoClassDefFoundError: retrofit2.converter.gson.GsonConverterFactory
```
before implemention onSignal, my project run successfuly.but after implemention i get above error.
this is my build.gradle:
```Gradle
    compile 'com.google.code.gson:gson:2.8.0'
    compile 'io.reactivex.rxjava2:rxandroid:2.0.1'
    compile 'io.reactivex.rxjava2:rxjava:2.0.8'
    compile 'com.squareup.retrofit2:retrofit:2.2.0'
    compile 'com.squareup.retrofit2:converter-gson:2.2.0'
    compile 'com.squareup.retrofit2:adapter-rxjava2:2.2.0'
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.google.android.gms:play-services-maps:10.0.1'
    compile 'com.google.android.gms:play-services-gcm:10.0.1'
    compile 'com.google.android.gms:play-services-location:10.0.1'
    compile 'com.onesignal:OneSignal:[3.5.3,4.0.0)'
```
please help me.thanks a lot.

**Comment by jkasten2** [comment]
@FaridBeiranvand Our SDK does not use the Google GSON library. Can you check the full stack trace? I should show the exact line where the issue is in the other library and/or your code.

**Comment by jkasten2** [comment]
@FaridBeiranvand Feel free to reopen this issue if you are still seeing the problem.
