### ISSUE TITLE
NotificationReceivedHandler not working properly

### ISSUE THREAD

**Issue by xsorifc28** [OneSignal/OneSignal-Android-SDK#227]
I'm using `NotificationExtenderService`, `NotificationOpenedHandler`, and `NotificationReceivedHandler`. Debugging shows that `NotificationExtenderService` is called before  `NotificationReceivedHandler`.

I've set `inFocusDisplaying` to `none` but the notification seems to show while app is in focus. My  `NotificationReceivedHandler` is supposed to override it and show a toast instead. The app does call this code, however, toast is not shown.

Setting `inFocusDisplaying1`to `inAppAlert` works as expected.

**Comment by jkasten2** [comment]
@xsorifc28 `inFocusDisplaying` won't have an effect when using a `NotificationExtenderService` as it is the final determining factor.  However you can get the focus state of your app by reading [`OSNotificationReceivedResult.isAppInFocus`](https://github.com/OneSignal/OneSignal-Android-SDK/blob/3.5.5/OneSignalSDK/onesignal/src/main/java/com/onesignal/OSNotificationReceivedResult.java#L33) and then return `true` from `onNotificationProcessing` to give the same result.

There is bit more information on this decision in issue #162.

In the next major release I am considering on  creating a `willPresent` method (similar to iOS) to replace `NotificationReceivedHandler` which I believe will clear this up in the future.

**Comment by xsorifc28** [comment]
I had tried to do bypass in `NotificationExtenderService`, but the toast wasn't showing due to an error on my end, oops.

So now the toast IS showing as well as the notification when using `NotificationReceivedHandler`. I've disabled that and modified `NotificationExtenderService` to see if `OSNotifcationReceivedResult.isAppInFocus`  is true.

Thanks for the help, looking forward to next release.
