### ISSUE TITLE
How to register test device by using the SDK?

### ISSUE THREAD

**Issue by Khang-NT** [OneSignal/OneSignal-Android-SDK#228]
I'm trying to mark my phone as test device. I can't find it in "All user" list, there are thousands users. 
What I did:
  * `sendTag("TEST", "yes")` seem like OneSignal not update user segment immediately, I don't know how long it takes, but I still don't see my device in the segment with filter `key:TEST equal value:yes`
  * Dump `userID` from the SDK by `OneSignal.idsAvailable()` and use the `userId` to filter in `All user` list. But still not found.

There is any way to register test device with the SDK?

**Comment by jkasten2** [comment]
@Khang-NT These are your best two options for setting a user as a test user currently.

`sendTag` should only take 10 to 15 seconds to get updated on the dashboard. Any delays would be related to networking issues on the device which you can run `setLogLevel` with VERBOSE and check the logcat to debug.

**Comment by Khang-NT** [comment]
Still not working.
![screen shot 2017-05-11 at 8 55 05 am](https://cloud.githubusercontent.com/assets/13332950/25928655/a8ccd2e4-3627-11e7-94d3-2df242327dfd.png)
![screen shot 2017-05-11 at 8 55 41 am](https://cloud.githubusercontent.com/assets/13332950/25928662/b0971c14-3627-11e7-9220-78fbb1baff53.png)

**Comment by jkasten2** [comment]
@Khang-NT That player id exists. Can you make sure you are checking the correct OneSignal app on your account? It starts with ce0adb as shown in your screenshot. OneSignal support from the dashboard can better check your account if you are still seeing issues.

**Comment by Khang-NT** [comment]
Oh sorry, my confusing. I have another OneSignal app for development build, I should find from it instead. 

Thanks for your response. 👍
