### ISSUE TITLE
Can onesignal client sdk receive and display  push messages sent from my own server?

### ISSUE THREAD

**Issue by ilkinulas** [OneSignal/OneSignal-Android-SDK#230]
OneSignal android sdk is very easy to setup and works great. Push notifications sent from onesignal dashboard is displayed without any problem.  👍 

Is it  possible ( and legal) to send push notifications from my own server and display it on clients that have onesignal sdk integrated?

**Comment by jkasten2** [comment]
@ilkinulas You can use this SDK to process notifications from your own server for your own apps. However not to provide a 3rd party service to send notifications without sending them through OneSignal.

Thanks.
