### ISSUE TITLE
Exception android.database.sqlite.SQLiteFullException: database or disk is full (code 13)

### ISSUE THREAD

**Issue by ominfowave** [OneSignal/OneSignal-Android-SDK#232]
```Java
Exception android.database.sqlite.SQLiteFullException: database or disk is full (code 13)
  android.database.sqlite.SQLiteConnection.nativeExecute (SQLiteConnection.java)
  android.database.sqlite.SQLiteConnection.execute (SQLiteConnection.java:562)
  android.database.sqlite.SQLiteSession.endTransactionUnchecked (SQLiteSession.java:437)
  android.database.sqlite.SQLiteSession.endTransaction (SQLiteSession.java:401)
  android.database.sqlite.SQLiteDatabase.endTransaction (SQLiteDatabase.java:536)
  com.onesignal.NotificationBundleProcessor.saveNotification (NotificationBundleProcessor.java:150)
  com.onesignal.NotificationExtenderService.processJsonObject (NotificationExtenderService.java:169)
  com.onesignal.NotificationExtenderService.processIntent (NotificationExtenderService.java:135)
  com.onesignal.NotificationExtenderService.onHandleIntent (NotificationExtenderService.java:104)
  android.app.IntentService$ServiceHandler.handleMessage (IntentService.java:66)
  android.os.Handler.dispatchMessage (Handler.java:111)
  android.os.Looper.loop (Looper.java:207)
  android.os.HandlerThread.run (HandlerThread.java:61)
```

there are more than 100 report on firebase for this bug can you please guild how to resolve this.

**Comment by jkasten2** [comment]
@ominfowave Can you add which version of the OneSignal SDK you are using?

**Comment by ominfowave** [comment]
compile 'com.onesignal:OneSignal:3.4.3@aar'

**Comment by jkasten2** [comment]
@ominfowave Can you update to 3.5.6? There have a been a number of fixes around SQLite handling since this version.

**Comment by ominfowave** [comment]
@jksasten2 i have updated to 3.5.6 yesterday,there is same error reported on firebase 


Exception android.database.sqlite.SQLiteFullException: database or disk is full (code 13)
android.database.sqlite.SQLiteConnection.nativeExecute (SQLiteConnection.java)
android.database.sqlite.SQLiteConnection.execute (SQLiteConnection.java:560)
android.database.sqlite.SQLiteSession.endTransactionUnchecked (SQLiteSession.java:437)
android.database.sqlite.SQLiteSession.endTransaction (SQLiteSession.java:401)
android.database.sqlite.SQLiteDatabase.endTransaction (SQLiteDatabase.java:525)
com.onesignal.NotificationBundleProcessor.a (NotificationBundleProcessor.java:169)
com.onesignal.NotificationExtenderService.a (NotificationExtenderService.java:176)
com.onesignal.NotificationExtenderService.processJsonObject (NotificationExtenderService.java:142)
com.onesignal.NotificationExtenderService.onHandleIntent (NotificationExtenderService.java:110)
android.app.IntentService$ServiceHandler.handleMessage (IntentService.java:65)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:136)
android.os.HandlerThread.run (HandlerThread.java:61)

**Comment by jkasten2** [comment]
@ominfowave Seems we need to specificity handle this error when `endTransaction` is called. We will look into it for the next release.

**Comment by ominfowave** [comment]
@jkasten2 is this issue resolved in 3.5.7

**Comment by jkasten2** [comment]
@ominfowave Sorry it was not, their was some more common issues that prompted a sooner release of 3.5.7 without this.

How wide spread is the issue for you? Do you have a crashlytics or Google Play Developer report you could share?

**Comment by ominfowave** [comment]
There is too many reports on firebase console 
![image 1](https://user-images.githubusercontent.com/4697885/26959890-99a49d12-4cf0-11e7-887b-9845c11ded6f.png)     
![image 2](https://user-images.githubusercontent.com/4697885/26959896-a244e6c0-4cf0-11e7-9164-80afe31a6355.png)

**Comment by jkasten2** [comment]
@ominfowave Thanks for the details. Could you contact support from the dashboard while logged into your OneSignal account? Link them to this github issue and they can check a few more things from there.

**Comment by jkasten2** [comment]
@ominfowave This is now fixed in the 3.5.8 SDK update. Thanks.

**Comment by yogeshivu** [comment]
@jkasten2 can i know how to fix this sqlite database full error as i am unable to find a solution for it to fix it in my android application

**Comment by sundeeprs** [comment]
Is this issue solved, i am still getting below error. Any solution, please suggest

android.database.sqlite.SQLiteFullException: database or disk is full (code 13)
07-30 13:58:21.252 11646 17512 E ACRA    : 	at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
07-30 13:58:21.252 11646 17512 E ACRA    : 	at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:553)
07-30 13:58:21.252 11646 17512 E ACRA    : 	at android.database.sqlite.SQLiteSession.endTransactionUnchecked(SQLiteSession.java:437)
07-30 13:58:21.252 11646 17512 E ACRA    : 	at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:401)
07-30 13:58:21.252 11646 17512 E ACRA    : 	at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:522)
07-30 13:58:21.252 11646 17512 E ACRA    : 	at com.verizon.app.db.sqllite.SQLLiteDbHelper.deleteAll(SQLLiteDbHelper.java:88)

**Comment by jkasten2** [comment]
@sundeeprs Can you post the full stack trace? I don't see OneSignal in yours above but we will need this to pin point the issue.
