### ISSUE TITLE
Onesignal ANR - Broadcast of Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 ... }

### ISSUE THREAD

**Issue by mitonline** [OneSignal/OneSignal-Android-SDK#239]
Hi,
We are seeing ANR in onesignal SDK for broadcast intent CONNECTIVITY_CHANGE.  This looks similar to Bug #237 but for a different broadcast intent. Just including this one also, If it is similar to Bug #237. Please mark it as duplicate.
Please see attached stacktrace.
[onesignal_connectivity_change.txt](https://github.com/OneSignal/OneSignal-Android-SDK/files/1043723/onesignal_connectivity_change.txt)

We are using the latest onesignal android native sdk.
From build.gradle
compile 'com.onesignal:OneSignal:[3.5.3,4.0.0)'

**Comment by jkasten2** [comment]
@mitonline Thanks for reporting. These ANRs both have the same stack trace on the main thread.
