### ISSUE TITLE
Exception java.lang.IllegalStateException: GoogleApiClient is not connected yet.

### ISSUE THREAD

**Issue by ominfowave** [OneSignal/OneSignal-Android-SDK#241]
Exception java.lang.IllegalStateException: GoogleApiClient is not connected yet.
com.google.android.gms.internal.zzaak.zzb (zzaak.java)
com.google.android.gms.internal.zzaan.zzb (zzaan.java)
<OR>.zzb (zzaan.java)
com.google.android.gms.internal.zzaal.zzb (zzaal.java)
<OR>.zzb (zzaal.java)
<OR>.zzb (zzaal.java)
<OR>.zzb (zzaal.java)
<OR>.zzb (zzaal.java)
com.google.android.gms.internal.zzarl.removeLocationUpdates (zzarl.java)
<OR>.removeLocationUpdates (zzarl.java)
<OR>.removeLocationUpdates (zzarl.java)
com.onesignal.LocationGMS$GoogleApiClientListener.a (LocationGMS.java:300)
com.onesignal.i$e.<init> (i.java:273)
com.onesignal.LocationGMS$LocationHandler.onConnected (LocationGMS.java:251)
com.google.android.gms.common.internal.zzm.zzq (zzm.java)
com.google.android.gms.internal.zzaal.zzo (zzaal.java)
com.google.android.gms.internal.zzaaj.zzvE (zzaaj.java)
com.google.android.gms.internal.zzaaj.onConnected (zzaaj.java)
com.google.android.gms.internal.zzaan.onConnected (zzaan.java)
com.google.android.gms.internal.zzzy.onConnected (zzzy.java)
com.google.android.gms.common.internal.zzl$1.onConnected (zzl.java)
com.google.android.gms.common.internal.zzf$zzj.zzwZ (zzf.java)
com.google.android.gms.common.internal.zzf$zza.zzc (zzf.java)
com.google.android.gms.common.internal.zzf$zza.zzu (zzf.java)
com.google.android.gms.common.internal.zzf$zze.zzxa (zzf.java)
com.google.android.gms.common.internal.zzf$zzd.handleMessage (zzf.java)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:136)
android.app.ActivityThread.main (ActivityThread.java:5034)
java.lang.reflect.Method.invokeNative (Method.java)
java.lang.reflect.Method.invoke (Method.java:515)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:786)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:602)
dalvik.system.NativeStart.main (NativeStart.java)

i have seen approx 100 crash on firebase

**Comment by jkasten2** [comment]
@ominfowave We have fixed this in the 3.5.7 update we just released today.

**Comment by ominfowave** [comment]
@jkasten2 is this issue resolved in 3.5.7 ?
