### ISSUE TITLE
I need check if a notification has been pressed

### ISSUE THREAD

**Issue by eugenio-caicedo** [OneSignal/OneSignal-Android-SDK#243]
I have the library installed as follows:

````
OneSignal.startInit(this)
          .autoPromptLocation(true)
          .setNotificationOpenedHandler(new OneSignalHandler(this))
          .inFocusDisplaying(OneSignal.OSInFocusDisplayOption.InAppAlert)
          .init();
````

And the OneSignalHandler class is defined as follows:

````
public class OneSignalHandler implements OneSignal.NotificationOpenedHandler {
  ...

    @Override
    public void notificationOpened(OSNotificationOpenResult result) {
        //After checking several things the main activity is called.
        ....
        Intent intent = MainActivity.createIntent(context, showing);
        context.startActivity(intent);
    }
}
````

But in the console, I get that the Main activity is called before the notificationOpened method. That is, the call flow is as follows:

1. The notification is received and clicked on it.
2. The Main activity is called (onCreate and onStart)
3. The notificationOpened method of the OneSignalHandler class is executed.
4. It is redirected to Main activity by step 3.

So, How I check if a notification has been pressed? I was using the library version: 'com.onesignal:OneSignal:[3.5.3,4.0.0)'.

I need to make several things in the onCreate method of the Main activity, but only if the notification is pressed.

**Comment by jkasten2** [comment]
@eugenio-caicedo Make sure your calling `OneSignal.startInit` from the `onCreate` method of your `Application` class so the callback can fire before your Activity is created.

If you need change which Activity is started based on the notification see the link below.
https://documentation.onesignal.com/v3.0/docs/android-customizations#section-changing-the-open-action-of-a-notification

**Comment by eugenio-caicedo** [comment]
Thanks @jkasten2 for your help.

I solved the problem by adding this to the manifest:
 `<meta-data
            android:name="com.onesignal.NotificationOpened.DEFAULT"
            android:value="DISABLE" />`
