### ISSUE TITLE
Request with non-existing photo url return 200

### ISSUE THREAD

**Issue by nevraydin** [OneSignal/OneSignal-Android-SDK#250]
Hello,

When we try to send non-existing photo url with "big_picture" parameter, it returns 200 and not sending this notification. Also after this request, notifications are never sent, even it has correct request parameters.

**Comment by jkasten2** [comment]
@nevraydin Could you provide the full JSON payload you are sending through the REST API? Could you also link this issue to OneSignal support so they can look at it with your account as well?

**Comment by jkasten2** [comment]
@nevraydin Messaging OneSignal support in the bottom right red bubble while logging into the OneSignal dashboard is the best option. You can also email support@onesignal.com. Please included your notification,  app, and player / user id you're testing with so they can look into it.
