### ISSUE TITLE
Text Arrangement Error on Android 4.1 when setting a background image

### ISSUE THREAD

**Issue by Luesey** [OneSignal/OneSignal-Android-SDK#252]
![image](https://user-images.githubusercontent.com/29471293/27207941-6b885d32-527d-11e7-8df8-388b8d793df7.png)

Text arrangement on android 4.1 is different to other devices.

**Comment by jkasten2** [comment]
Since Android 4.1 is used on a declining 1% of Android devices and this feature is only used by a limited number of apps we do no plan on investigating a fix for this bug.
