### ISSUE TITLE
Unable to add OneSignal SDK

### ISSUE THREAD

**Issue by saintjab** [OneSignal/OneSignal-Android-SDK#260]
Hi, I tried adding the SDK to my dependencies but gradle sync always brings error whenever I added the SDK. Error:
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

When I remove  this: compile 'com.onesignal:OneSignal:[3.5.3,4.0.0)'
my gradle sync just fine.

**Comment by matijagorsek** [comment]
Did you resolve problem?
