### ISSUE TITLE
Onesignal icon sound and vibration works partially

### ISSUE THREAD

**Issue by waheed25** [OneSignal/OneSignal-Android-SDK#261]
I have customized the onesignal push notification icon and sound when i installed project on samsung mobile it works perfect but when i install on on a local brand called Qmobile its sound and vibration not working and only  the defualt icon shows and on the same time this notification on samsung mobile works perfect

**Comment by jkasten2** [comment]
@waheed25 If you don't customize the sound does it work correctly on your Qmobile device? Can you check the logcat for any errors or warnings when the notification is received?

Please include the exact model and Android version of this device as well.

**Comment by waheed25** [comment]
no without customization it not works too.the models of mobiles that i used is one Qmobile J7 and other is Qmobile Z12 both having the marshmallow version .I solved this issue because my code was fine the issue in mobile notice managment in latest version of marshmallow you have to manually enable the notification in the app setting.
Actually that was my bad.
