### ISSUE TITLE
How OneSignal register user?

### ISSUE THREAD

**Issue by donnerstag4** [OneSignal/OneSignal-Android-SDK#266]
Hi, 
Can you explain how OneSignal register user and where you put that function in example app demo?

Thank you

**Comment by jkasten2** [comment]
@donnerstag4 The device is registered when the SDK is initialized. Make sure you complete at minimum steps 1 and 2 below.
https://documentation.onesignal.com/docs/android-sdk-setup

Check out the example projects below to see a full example.
https://github.com/OneSignal/OneSignal-Android-SDK/tree/master/Examples
