### ISSUE TITLE
Support Shape Drawable for Images

### ISSUE THREAD

**Issue by jtkac** [OneSignal/OneSignal-Android-SDK#269]
Hello, 

I'm having trouble getting the onesignal_bgimage_default_image to cause the notification title and body colors to change over to a desired spec. Is there some trick to doing so, does the app have to be open, does the default image have to be in jpg/png format, or is the feature buggy?

Extra info:
`onesignal_bgimage_default_image` is an xml shape file (does it have to be an image format?)

Color res:
```xml
<color name="onesignal_bgimage_notif_title_color">@color/white</color>
<color name="onesignal_bgimage_notif_body_color">@color/black</color>
```

Thank you!

**Comment by jkasten2** [comment]
@jtkac The background image feature only supports image/bitmap formats as it uses `BitmapFactory.decodeStream` to load them. The SDK does not support xml shape files at this time.

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration
