### ISSUE TITLE
Custom Sound Error

### ISSUE THREAD

**Issue by eugenio-caicedo** [OneSignal/OneSignal-Android-SDK#272]
I have added a file called **alert.wav** to the /res/raw/ folder in the android app and I added android_sound: _"alert"_ on the rails server but the sound that is heard is the one that comes by default for notifications. I also tested with android_sound: _"alert.wav"_. but I get the same error. Do I need to do any additional configuration? In the manifest file for example.

**Comment by jkasten2** [comment]
@eugenio-caicedo Your sound file should be `alert` in this case. However I recommend trying to give it a more unique name in-case it is conflicting with something else.

Also I recommend unzipping your APK to ensure it is not being omitted from it.

Thanks.

**Comment by eugenio-caicedo** [comment]
The file name is a big mistake, I should have changed it to `custom_alert`. But this was also due to specifying a `setSound` in the `NotificationCompat.Builder`.

Thanks for your help @jkasten2
