### ISSUE TITLE
11.0.2 Support 

### ISSUE THREAD

**Issue by beraybentesen** [OneSignal/OneSignal-Android-SDK#275]
For  compile 'com.onesignal:OneSignal:3.5.8'
-> 
Found versions 11.0.2, 10.0.1. Examples include com.google.android.gms:play-services-base:11.0.2 and com.google.android.gms:play-services-gcm:10.0.1 less... 

Why do you use 10.0.1 ?

**Comment by jkasten2** [comment]
@beraybentesen We define a range which has been tested to work with our SDK. Version 3.5.8 was tested to work with 9.0.0 through 10.0.1 at the time.
https://github.com/OneSignal/OneSignal-Android-SDK/blob/3.5.8/OneSignalSDK/onesignal/maven-push.gradle#L32

We can confirm that everything still works correctly with gms 11.0.2 with OneSignal 3.5.8 so you can add the following to your `app/build.gradle` to update it's dependencies.
```
compile 'com.google.android.gms:play-services-gcm:11.0.2'
compile 'com.google.android.gms:play-services-location:11.0.2'
```

**Comment by jkasten2** [comment]
We have added this to the setup docs. Feel free to reopen this issue if you have any more questions on our GMS decencies.
