### ISSUE TITLE
Application with an implementation of OneSignal fails to Compile

### ISSUE THREAD

**Issue by jtkac** [OneSignal/OneSignal-Android-SDK#278]
Everything in the app was working normally until quite recently when OneSignal failed to compile.

## What I had:

            compile 'com.onesignal:OneSignal:[3.5.3,4.0.0)'

## What I replaced it with:

             compile 'com.onesignal:OneSignal:[3.5.3,3.99.99)'

Then I tried the 4.0.0 snapshot:

            repositories {
                  maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
            }

            dependencies {
                  compile 'com.onesignal:OneSignal:4.0.0-SNAPSHOT'
            }

 but that didn't do the trick either. Any advice?

#Reference -> https://documentation.onesignal.com/v3.0/docs/android-sdk-setup

**Comment by jkasten2** [comment]
@jtkac Can you attach the full compile error?

**Comment by jtkac** [comment]
As it turns out I had a data proxy service in the background which was inhibiting the SDK from downloading. Sorry!
