### ISSUE TITLE
Failed to resolve: com.android.support:customtabs:[26.0.0,26.1.0)

### ISSUE THREAD

**Issue by amin1softco** [OneSignal/OneSignal-Android-SDK#281]
hi
all my project today say this error for onesignal i think some fixes needed.

````
Could not resolve all dependencies for configuration ':amin1softco:_armv7DebugApkCopy'.
   > Could not find any version that matches com.android.support:customtabs:[26.0.0,26.1.0).
     Versions that do not match:
         26.0.0-alpha1
         25.3.1
         25.3.0
         25.2.0
         25.1.1
         + 19 more
     Required by:
         project :amin1softco > com.onesignal:OneSignal:3.6.0

````

fix for now.
````
compile 'com.onesignal:OneSignal:3.5.8'
````

**Comment by gerbenrobijn** [comment]
I can confirm this, the temp. fix also works.

**Comment by jkasten2** [comment]
@amin1softco @gerbenrobijn The 3.6.0 SDK has been updated to be compatible with Android O when targeting API level 26. This version now depends on version 26 of the `support-v4` library as it is required to show notifications for Android O. 

Google switch to using their own Maven repository instead of downloading them through the Android SDK. See the instructions below to add this as a repository to your `build.gradle`.
https://developer.android.com/topic/libraries/support-library/setup.html

If you are not ready to update your project yet and are still starting 25 or lower with `targetSdkVersion` you can add the following decencies to override the ones included by the SDK.
```
compile 'com.android.support:support-v4:25.+'
compile 'com.android.support:customtabs:25.+'
```

**Comment by baole** [comment]
You can exclude it from dependencies as below:

```
    compile ('com.onesignal:OneSignal:[3.5.3,4.0.0)') {
        exclude module: 'play-services-location'
        exclude group: 'com.android.support'
    }
```

**Comment by slazutkin** [comment]
Same issue with React Native project

> A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find any version that matches com.android.support:support-v4:[26.0.0,26.1.0).
     Versions that do not match:
         26.0.0-alpha1
         25.3.1
         25.3.0
         25.2.0
         25.1.1
         + 32 more
     Searched in the following locations:
         file:/C:/asdk/extras/android/m2repository/com/android/support/support-v4/maven-metadata.xml
         file:/C:/sources/lab/trash/coinpulse-native/android/sdk-manager/com/android/support/support-v4/maven-metadata.xml
         file:/C:/sources/lab/trash/coinpulse-native/android/sdk-manager/com/android/support/support-v4/
     Required by:
         project :app > com.onesignal:OneSignal:3.6.0

Setting **compile 'com.onesignal:OneSignal:3.5.8'** doesn't help, it still tries ti use 3.6.0 version

Any ideas?

**Comment by baole** [comment]
You probably need to add Google Maven repository

For Gradle, add this line on top level build.gradle

```
buildscript {
    repositories {
       ....
        maven { url 'https://maven.google.com' }
     .....
    }

```

**Comment by slazutkin** [comment]
Helped changing in file 'node_modules\react-native-onesignal\android\build.gradle':
**from**:
compile 'com.onesignal:OneSignal:3.+@aar'
**to**:
compile 'com.onesignal:OneSignal:3.5.8'

But is doesn't seem to be a good solution

**Comment by jkasten2** [comment]
@slazutkin We have updated the troubleshooting guide to make the required changes more clear.
https://documentation.onesignal.com/docs/troubleshooting-android#section-error-failed-to-resolve-com-android-support-customtabs-26-0-0-26-1-0-

Let me know if you have any feedback on it.

Thanks.

**Comment by amin1softco** [comment]
> @slazutkin We have updated the troubleshooting guide to make the required changes more clear.
https://documentation.onesignal.com/docs/troubleshooting-android#section-error-failed-to-resolve-com-android-support-customtabs-26-0-0-26-1-0-

Let me know if you have any feedback on it.

Thanks.



maven.google.com
 create some other strange incompatibility in my app.

**Comment by jkasten2** [comment]
@amin1softco Could you let us know the specifics errors / incompatibilities?

**Comment by amin1softco** [comment]
@jkasten2  yeah some problem with support.v4
````
Error:(24, 36) error: package android.support.v4.animation does not exist
````
but without maven.google.com and 3.5.8 every thing normally

**Comment by jkasten2** [comment]
@amin1softco 
The 3.6.0 SDK depends on `com.android.support` revision 26.
The 3.58 SDK depends on the newest available version downloaded between 24.0.0 and 25.3.

The only class that is under the `android.support.v4.animation` namespace is `AnimatorCompatHelper`.
https://developer.android.com/reference/android/support/v4/animation/package-summary.html

Is this something you are using directly or something another library is depending on that is giving you this error?

**Comment by amin1softco** [comment]
before your update or repository changing , v3.6.0 work properly and every thing wok normally after update and using maven.google.com this strange error occur and my class using support-v4.animation have error and with 3.5.8 now every thing normally...

**Comment by jkasten2** [comment]
`android.support.v4.animation` is a package / namespace. Could you list the specific classes you are using?

They could have moved to `android.support.v4.view.animation` or `android.support.animation` in the Android Support Library update.

**Comment by hardikJoshi123** [comment]
Same issue i faced today

**Comment by jkasten2** [comment]
@hardikJoshi123 Did the [OneSignal troubleshooting guide](https://documentation.onesignal.com/docs/troubleshooting-android#section-error-failed-to-resolve-com-android-support-customtabs-26-0-0-26-1-0-) help you reslove the issue?

**Comment by Tom29** [comment]
@amin1softco hello, i get the same trouble. This is my first time i test app on android.
i already put `compile 'com.onesignal:OneSignal:3.5.8'` in the `dependencies` , but still not get rid of this error. anything else needed ?

**Comment by chitra8** [comment]
Error:Failed to resolve: com.android.support:customtabs:[26.0.0,26.2.0)

Error:Failed to resolve: annotationProcessor

Error:Failed to resolve: com.android.support:support-v4:[26.0.0,26.2.0)

Error:Failed to resolve: com.android.support:support-v4:[26.0.0,26.2.0)

facing the same issue @OneSignal troubleshooting guide is no help

**Comment by jkasten2** [comment]
@chitra8 Adding the following to your `build.gradle` should fix your issue.
```gradle
repositories {
    maven { url 'https://maven.google.com' }
}
```

I have updated the link above to include the `com.android.support:support-v4:[26.0.0,26.2.0)` error as well. This is now required for new versions of Google libraries they moved their libraries out of the Android SDK and into this maven repo.

**Comment by mginz83** [comment]
I am saming the same issue. Here is my project gradle
```
buildscript {
    repositories {
        jcenter{ url "http://jcenter.bintray.com/" }
        maven{url "https://maven.google.com"}
        //mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

Here is my app gradle
```

apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    defaultConfig {
        applicationId "com.fuhnatik.pickyourpros"
        manifestPlaceholders = [onesignal_app_id: "000000000000",
                                // Project number pulled from dashboard, local value is ignored.
                                onesignal_google_project_number: "0000000000"]
        minSdkVersion 16
        targetSdkVersion 25
        versionCode 1
        versionName "A.0.14.3"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
    }
    useLibrary 'org.apache.http.legacy'
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    sourceSets { main { assets.srcDirs = ['src/main/assets', 'res/assets/'] } }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'br.com.simplepass:loading-button-android:1.7.2'
    //debugCompile 'com.squareup.leakcanary:leakcanary-android:1.5.1'
    compile 'com.onesignal:OneSignal:[3.6.2, 3.99.99]'
    compile 'de.hdodenhof:circleimageview:2.1.0'
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.parse:parse-android:1.15.7'
    compile 'com.parse:parsefacebookutils-v4-android:1.10.3@aar'
    compile 'com.android.support:design:25.3.1'
    compile 'com.android.support:support-vector-drawable:25.3.1'
    compile 'com.android.support:support-v4:25.3.1'
    compile 'com.scottyab:aescrypt:0.0.1'
    compile 'com.facebook.android:facebook-android-sdk:4.25.0'
    testCompile 'junit:junit:4.12'
    compile files('libs/java-json.jar')


}
```

**Comment by akki777** [comment]
I am facing the same issue...`android.support.v4.animation.*` is missing and I cannot find any solution.
Android Plugin upgrade to 3.0 requires buildToolsVersion to 26+ and this package is missing.
Plz Help.

**Comment by alexsmartens** [comment]
+1 I'm having the same issue

**Comment by jkasten2** [comment]
@akki777 @akki777 The Android Support Library revision 26 moved some classes around. [See my comment this](https://github.com/OneSignal/OneSignal-Android-SDK/issues/281#issuecomment-322708849) of where they moved to.

We require revision 26 for Android O compatibility which is why you may not seen this issue until adding OneSignal.

**Comment by paco7777** [comment]
Put jcenter() after maven()

**Comment by jkasten2** [comment]
@paco7777 If you are seeing the same message as the `amin1softco` then make sure you have `maven.google.com` in your `build.gradle`.

```gradle
repositories {
    maven { url "https://maven.google.com" }
    mavenCentral()
    jcenter()
}
```

**Comment by paco7777** [comment]
Thanks for your answer :)

Robin Chalandon

2018-06-15 20:22 GMT+02:00 Josh Kasten <notifications@github.com>:

**Comment by phuonglam1510** [comment]
I have same issue. Already have  `maven { url "https://maven.google.com" }` line in build.gradle file but still error. I noticed that the line 'jcenter()' is above maven line. So i moved it below maven and it worked. Not sure why :(

**Comment by zendorx** [comment]
What to do if it does not help? I have this gradle template in unity but problem remains
`// GENERATED BY UNITY. REMOVE THIS COMMENT TO PREVENT OVERWRITING WHEN EXPORTING AGAIN

buildscript {
    repositories {
        google()
        maven { url "https://maven.google.com" }
        mavenCentral()
        jcenter()
    }`
