### ISSUE TITLE
java.lang.NoSuchMethodException: onOSSubscriptionChanged [class com.onesignal.OSSubscriptionStateChanges]

### ISSUE THREAD

**Issue by rameshkumarkhatri** [OneSignal/OneSignal-Android-SDK#285]
I am adding callback to get userID from OneSignal, I have added code in application class :
```Java
 OneSignal.startInit(this)
                .inFocusDisplaying(OneSignal.OSInFocusDisplayOption.Notification)
                .setNotificationReceivedHandler(new NotificationReceivedHandler(getApplicationContext()))
                .setNotificationOpenedHandler(new NotificationOpenedHandler(getApplicationContext()))
                .unsubscribeWhenNotificationsAreDisabled(true)
                .init();

        OneSignal.addSubscriptionObserver(new OSSubscriptionObserver() {
            @Override
            public void onOSSubscriptionChanged(OSSubscriptionStateChanges stateChanges) {
                if (!stateChanges.getFrom().getSubscribed() &&
                        stateChanges.getTo().getSubscribed()) {
                    MyLog.e("ONESIGNAL", "Application: You've successfully subscribed to push notifications!");
                    DEVICE_TOKEN = stateChanges.getTo().getUserId();
                    OneSignalCommonFunctionality.saveIsSentToken(getApplicationContext(), false);
                    OneSignalCommonFunctionality.sendRegistrationToServer(DEVICE_TOKEN, getApplicationContext());
                }

                MyLog.i("ONESIGNAL", "Application: onOSPermissionChanged: " + stateChanges);

                // TODO: 8/23/2017 Send OneSignal token to server
//                    RegistrationIntentService.sendRegistrationToServer(DEVICE_TOKEN, context);
            }
        });
        OneSignal.setSubscription(true);
```

But the issue is `onOSSubscriptionChanged` is called some time after killing app then start app. 

I have added following dependencies in app gradle:
```gradle
    compile 'com.onesignal:OneSignal:[3.5.3,4.0.0)'
```

Can anyone have idea how to get the oneSignal userID, deviceToken when deviceToken/userID update?

**Comment by jkasten2** [comment]
@rameshkumarkhatri The `onOSSubscriptionChanged` callback can fire at anytime while your app is running either in the background or foreground. You can call `removePermissionObserver` at any point on your same observer instance to prevent it from firing however.

Could you provide a full stack trace of the `java.lang.NoSuchMethodException` error if you are still getting it?

Thanks.

**Comment by rameshkumarkhatri** [comment]
@jkasten2  It was not working everytime so I removed this method now  OneSignal.idsAvailable to get id of device.

**Comment by jkasten2** [comment]
@rameshkumarkhatri `OneSignal.addSubscriptionObserver` only hangs on to a weak reference to prevent it from leaking an Android `Context` if you setup the interface on an `Activity` for example. Since you newed up an `OSSubscriptionObserver` anonymous class without keeping an reference of your own it will get garbage collected.

**Comment by rameshkumarkhatri** [comment]
@jkasten2  Got it. Weak reference is garbage collected. Thanks for your reply. :)

**Comment by jkasten2** [comment]
Feel free to reopen this issue if the changing your referencing doesn't fix it.
