### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException GoogleApiClient is not connected yet.

### ISSUE THREAD

**Issue by junlaecho** [OneSignal/OneSignal-Android-SDK#288]
com.google.android.gms.internal.zzbco.zze (Unknown Source)
--
  | com.google.android.gms.internal.zzccb.removeLocationUpdates (Unknown Source)
  | com.onesignal.LocationGMS$FusedLocationApiWrapper.removeLocationUpdates (LocationGMS.java:312)
  | com.onesignal.LocationGMS$LocationUpdateListener.onLocationChanged (LocationGMS.java:296)
  | com.google.android.gms.internal.zzcdi.zzq (Unknown Source)
  | android.os.HandlerThread.run (HandlerThread.java:61)

**Comment by jkasten2** [comment]
@junlaecho This looks to be a possible race condition that in rare cases could cause this crash. Just to confirm you are on the latest 3.6.1 SDK?
