### ISSUE TITLE
OneSignal JAR for Eclipse

### ISSUE THREAD

**Issue by david2410** [OneSignal/OneSignal-Android-SDK#291]
Can you upload the latest JAR library for Eclipse? The one in this repo is outdated.

**Comment by jkasten2** [comment]
@david2410 Thanks for reporting, just updated the jar to 3.6.1 on master. Can be downloaded by pressing "View Raw" below.
https://github.com/OneSignal/OneSignal-Android-SDK/blob/3792d372fc0dfe57d14511164aec76e461edf837/OneSignalSDK.jar

We update this .jar manually. If we missed updating this in the future, it can be downloaded manually by clicking on one of the .aar links from below.
https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.onesignal%22%20AND%20a%3A%22OneSignal%22

The `.aar` can be extracted with an unzipper and can use the contained `classes.jar`.
