### ISSUE TITLE
Fatal Exception: java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by g123k** [OneSignal/OneSignal-Android-SDK#30]
Hello,

I have an application in production which uses the OneSignal SDK. I also have included Fabric/Crashlytics and it notifies me about a crash related to the SDK, that I can't reproduce :

> Fatal Exception: java.lang.NoSuchMethodError: android.app.Activity.requestPermissions
>        at com.onesignal.AndroidSupportV4Compat$ActivityCompatApi23.requestPermissions(AndroidSupportV4Compat.java:66)
>        at com.onesignal.AndroidSupportV4Compat$ActivityCompat.requestPermissions(AndroidSupportV4Compat.java:57)
>        at com.onesignal.PermissionsActivity.requestPermission(PermissionsActivity.java:59)
>        at com.onesignal.PermissionsActivity.onCreate(PermissionsActivity.java:47)
>        at android.app.Activity.performCreate(Activity.java:5218)
>        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
>        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2038)
>        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2099)
>        at android.app.ActivityThread.access$600(ActivityThread.java:145)
>        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
>        at android.os.Handler.dispatchMessage(Handler.java:119)
>        at android.os.Looper.loop(Looper.java:137)
>        at android.app.ActivityThread.main(ActivityThread.java:4873)
>        at java.lang.reflect.Method.invokeNative(Method.java)
>        at java.lang.reflect.Method.invoke(Method.java:528)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
>        at dalvik.system.NativeStart.main(NativeStart.java)

This crash seems to be related with devices running Android L (5.1) or below.

**Comment by jkasten2** [comment]
We currently have a check to make sure that the code listed in your stack trace is only run on Android device 6.0+. Could you report of a few of the device with the following properties of each.
model number, Android version, and is rooted.

You send us a support message at support@onesignal.com or through the red button in the right hand corner when you're looked into our site with a link to some of your Crashlytics reports and we can take a look in more detail.

Thanks.

**Comment by jkasten2** [comment]
@g123k Are you still seeing this issue?

**Comment by jkasten2** [comment]
@g123k It might be related this issue.
http://stackoverflow.com/questions/26346336/unknown-device-in-the-crashlytics-log

We will add an Android version check to the Activity code to prevent this crash on Google's review emulators.

Thanks.

**Comment by rbarriuso** [comment]
We're also getting this crash from a Motorola Defy Mini XT320 with Android v4.3.1. We're using OneSignal-Cordova-SDK v1.12.3 which seems to use OneSignal-Android-SDK v2.3.0

**Comment by jkasten2** [comment]
Fixed in commit 46d52c9c3089d56253a5ff43c4c95c8b78575a30
