### ISSUE TITLE
Open Launch URL in an in-app view

### ISSUE THREAD

**Issue by YuyangHYY** [OneSignal/OneSignal-Android-SDK#305]
IOS launch in app as default when open notification, but android when open notification will launch web browsers not in android app.
After I check, is it  android need to use 'OSNotificationOpenResult' this function? and how to set in code?

**Comment by jkasten2** [comment]
@YuyangHYY The OneSignal iOS SDK starts an in-app WebView when a notification with a launch url is set is open. This Android SDK opens the default web browser. Are you asking for a in-app WebView for Android to match iOS?

**Comment by YuyangHYY** [comment]
YES, I want android platform like IOS, can starts an in-app WebView.

**Comment by jkasten2** [comment]
@YuyangHYY Thanks for confirming, setting this as a feature request.

As an alternative you can open your URL inside of Ionic/Cordova. Instead of setting a Launch URL you can set additional data on the notification. Then in your code setup a [handleNotificationOpened](https://documentation.onesignal.com/docs/cordova-sdk#section--handlenotificationopened-) callback were you can read the URL from passed in object and redirect to it.

**Comment by YuyangHYY** [comment]
@jkasten2 I am using this code by [https://documentation.onesignal.com/docs/ionic-sdk-setup](url)
This one can open in-app view in IOS device but can not open in-app view in android devices, so I have to change this code to **handleNotificationOpened** then should in-app view function can show in both IOS and android? And I am using ionic3 is it can use **handleNotificationOpened** ?
var notificationOpenedCallback = function(jsonData) {
      console.log('notificationOpenedCallback: ' + JSON.stringify(jsonData));
    };

    window["plugins"].OneSignal
      .startInit("YOUR_APPID", "YOUR_GOOGLE_PROJECT_NUMBER_IF_ANDROID")
      .handleNotificationOpened(notificationOpenedCallback)
      .endInit();

**Comment by jkasten2** [comment]
@YuyangHYY You will need to make two different changes to open URL in your app instead for both iOS and Android in the same way.

1. Omit sending Launch URL and instead set your own key with the URL on Additional Data. This is under Options on the OneSignal dashboard below the Launch URL field. If you are using the REST API this is the `data` field.
2. Add code to your `notificationOpenedCallback ` above to read your URL from `jsonData.notification.payload.additionalData.yourKeyName`. Then use something like `cordova-plugin-inappbrowser` to open an in-app browser to show the custom page. There is a [guide here](https://www.thepolyglotdeveloper.com/2016/01/launch-websites-with-ionic-2-using-the-inappbrowser/) on using that plugin.

**Comment by YuyangHYY** [comment]
Did you mean like this?
```
var notificationOpenedCallback = function(jsonData) {
      console.log('notificationOpenedCallback: ' + JSON.stringify(jsonData));
    };

    window["plugins"].OneSignal
      .startInit("YOUR_APPID", "YOUR_GOOGLE_PROJECT_NUMBER_IF_ANDROID")
      **.handleNotificationOpened(jsonData.notification.payload.additionalData.yourKeyName)**
      .endInit();
```

And what's that mean "yourKeyName"?

And one more question:
![2017-10-13 14 31 56](https://user-images.githubusercontent.com/19391002/31533200-d1b34834-b023-11e7-9c03-b72c55230836.png)

Before I just copy my 'url' in Launch URL, I never put anything in 'key' and 'value' which in ADDITIONAL DATA. So I have to input something in  'key' and 'value' right? What should I put if I just want to push a 'url'

**Comment by jkasten2** [comment]
@YuyangHYY Your code should be something like this.

```javascript
var notificationOpenedCallback = function(jsonData) {
      console.log('notificationOpenedCallback: ' + JSON.stringify(jsonData));
      var openUrl = jsonData.notification.payload.additionalData.openUr;
      // Add code here to use openURL.
      // Example of using the cordova-plugin-inappbrowser plugin.
      // cordova.InAppBrowser.open(openUrl , "_system", "location=true");
};

window["plugins"].OneSignal
      .startInit("YOUR_APPID")
      .handleNotificationOpened(notificationOpenedCallback)
      .endInit();
```

On the OneSignal dashboard leave "Launch URL" blank. Enter `openURL` as the Key under Additional data and your full URL under Value.

**Comment by YuyangHYY** [comment]
Problem solved. Can close issues already.
Thanks you very much!!!

**Comment by fjwgomez** [comment]
Im trying to implement this. My app just open a url webpage.. I need send a custom url throgh onesignal and not open the pre configured url but the custom from onesignal.  Please help. Sory about my english.
**This is the code of my home.ts**

import { Component } from '@angular/core';
import { Platform} from 'ionic-angular'; //import { NavController ,Platform} from 'ionic-angular';
import { InAppBrowser } from '@ionic-native/in-app-browser';



@Component({
 template:"<p>...Cargando</p>"
})
export class HomePage {

  constructor(private iab: InAppBrowser,public platform: Platform) {
     platform.ready().then(() => {
      let browser = this.iab.create('https://www.wtec.tk','_blank',{zoom:'no',location:'no'});
     
      browser.show();
           
    });
  }
}

**this is my app.component.ts code:**

import { Component } from '@angular/core';
import { Platform } from 'ionic-angular';
import { StatusBar } from '@ionic-native/status-bar';
import { SplashScreen } from '@ionic-native/splash-screen';
//import { InAppBrowser } from '@ionic-native/in-app-browser';
import { HomePage } from '../pages/home/home';
import {OneSignal} from '@ionic-native/onesignal';
//import { Cordova } from '@ionic-native/core';
//import { variable } from '@angular/compiler/src/output/output_ast';

@Component({
  templateUrl: 'app.html'
})
export class MyApp {
  rootPage:any = HomePage;

  constructor(platform: Platform, statusBar: StatusBar, splashScreen: SplashScreen, public onesignal: OneSignal, /*private iab: InAppBrowser,*/) {
    platform.ready().then(() => {
      statusBar.styleDefault();
      splashScreen.hide();
  
      // OneSignal Code start:
      // Enable to debug issues:
      // window["plugins"].OneSignal.setLogLevel({logLevel: 4, visualLevel: 4});
  
      var notificationOpenedCallback = function(jsonData) {
        console.log('notificationOpenedCallback: ' + JSON.stringify(jsonData)); //console.log al inicio linea de cod org
    
      };
  
      window["plugins"].OneSignal
        .startInit("44c83999-7684-469d-8317-7ae6c5c8a900", "39384729352") 
        .handleNotificationOpened(notificationOpenedCallback) // codigo funcionando
        .endInit();
    });
  }
}

thanks a lot for any help or tip

**Comment by jkasten2** [comment]
@fjwgomez I sounds like you are looking for the same thing as **YuyangHYY** here so I recommend following the instructions above.

Please specify what your stuck on or not understanding if your still running into issues. Also please open an issue on the [OneSignal-Cordova-SDK](https://github.com/OneSignal/OneSignal-Cordova-SDK/issues) repo instead of replying here. This thread got off topic from Android native going to lock this thread to prevent further drifting.
