### ISSUE TITLE
On FirebaseMessagingService onMessageReceived method how can I get message text

### ISSUE THREAD

**Issue by bingdow** [OneSignal/OneSignal-Android-SDK#306]
So neither of 
`remoteMessage.getNotification().getBody()`
and 
`remoteMessage.getData().containsKey("body") )`
I can get message text but title.
How can I get message text from RemoteMessage object on FirebaseMessagingService onMessageReceived method

**Comment by jkasten2** [comment]
@bingdow We don't have documentation on parsing our payload with the FCM library. However you might be able to grab the `alert` key on data if it exists. 
```Java
remoteMessage.getData().containsKey("alert")
```

We don't have docs on FCM as our [OneSignal NotificationExtenderService](https://documentation.onesignal.com/docs/android-customizations#section-background-data-and-notification-overriding) should cover any custom notificaitons cases.

**Comment by jkasten2** [comment]
@bingdow Feel free to reopen this issue if you need any more details.
