### ISSUE TITLE
Silent pushes now show a blank message with icon and app name and no next [A bug reported in OneSignal/OneSignal-Cordova-SDK but was probably forgotten]

### ISSUE THREAD

**Issue by epetre** [OneSignal/OneSignal-Android-SDK#311]
https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/220

**Comment by jkasten2** [comment]
@epetre Thanks for the reminder. 2.2.1 of the Cordova SDK has been released to fix this issue.
