### ISSUE TITLE
Notify Notification

### ISSUE THREAD

**Issue by SunryTeang** [OneSignal/OneSignal-Android-SDK#317]
i want like this   
NotificationManager mNotificationManager = (NotificationManager)getSystemService(Context.NOTIFICATION_SERVICE);
            mNotificationManager.notify(0,mBuilder.build());

but i don't know onesignal function which one for this

**Comment by jkasten2** [comment]
@SunryTeang You don't need to add this code your app. The OneSignal SDK will take care of the displaying of the notification for after setting it up.
https://documentation.onesignal.com/docs/android-sdk-setup

Please provide more details if this wasn't your question.

**Comment by SunryTeang** [comment]
@jkasten2 thank you
