### ISSUE TITLE
Push notification to devices with Google Play services. 

### ISSUE THREAD

**Issue by Keshava11** [OneSignal/OneSignal-Android-SDK#319]
Is One-Signal Android SDK supports sending push notification to devices without Google Play services ?
If it is possible, can you guide for the docs as current Android documentation, still suggests something else. 

Thanks

**Comment by Alamgir** [comment]
@Keshava11 OneSignal requires Google Play services to receive push notifications. You can refer to the setup portion of the OneSignal Android SDK documentation here: https://documentation.onesignal.com/docs/android-sdk-setup

**Comment by Keshava11** [comment]
@Alamgir Actually I already checked the documentation and while implementing I also found a thread where it was written that one-signal sdk now also facilitates sending push notification to devices without Google play services. That's why asked here if it is true or not.

**Comment by Alamgir** [comment]
@Keshava11 to confirm with you, OneSignal cannot currently send push notifications to devices without Google Play services - can you perhaps link to the thread you're referring to?

The only other Android push support that we have is through ADM to FireOS (Amazon) devices.
