### ISSUE TITLE
 java.lang.NoSuchMethodError: com.google.android.gms.common.internal.zzaa.zzb

### ISSUE THREAD

**Issue by Xy-joe** [OneSignal/OneSignal-Android-SDK#327]
i was able to compile the dependencies and sync the gradle file and was also able to import com.onesignal.OneSignal but imediately i run my application, It crashes with these error. Note: I also added the OneSignal.startInit(this)
.inFocusDisplaying(OneSignal.OSInFocusDisplayOption.Notification)
.unsubscribeWhenNotificationsAreDisabled(true)
.init();
in my application class. Space will not permit me to paste the complete error

**Comment by Alamgir** [comment]
@Xy-joe can you post your gradle dependencies?

**Comment by Xy-joe** [comment]
@Alamgir  these are my dependencies  
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'

    })


    compile'com.android.support:appcompat-v7:26.1.0'
    compile'com.android.support:design:26.1.0'
    compile'com.android.support:recyclerview-v7:26.0.0'
    compile'com.android.support:cardview-v7:26.1.0'
    compile'com.github.bumptech.glide:glide:3.7.0'
    compile 'com.android.support:support-v4:26.1.0'
    compile 'com.android.support:support-v13:26.1.0'
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.google.firebase:firebase-database:9.8.0'
    compile 'com.google.firebase:firebase-storage:9.8.0'
    compile 'com.google.firebase:firebase-core:9.8.0'
    compile 'com.google.firebase:firebase-auth:9.8.0'
    compile 'com.google.firebase:firebase-crash:9.8.0'
    compile 'com.google.firebase:firebase-messaging:9.8.0'
    compile 'com.firebaseui:firebase-ui-storage:0.6.0'
    compile 'com.firebaseui:firebase-ui-database:0.6.0'
    compile 'com.firebase:firebase-client-android:2.3.1'
    compile 'com.ernestoyaquello.stepperform:vertical-stepper-form:0.9.9'
    compile 'de.hdodenhof:circleimageview:1.2.1'
    // One signal
    compile 'com.onesignal:OneSignal:[3.6.2, 3.99.99]'
    compile 'com.google.android.gms:play-services-gcm:9.8.0'

    compile 'com.vanniktech:emoji-google:0.5.1'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.jakewharton:butterknife:8.5.1'
    //event bus
    compile 'org.greenrobot:eventbus:3.0.0'
    compile 'com.andkulikov:transitionseverywhere:1.7.4'
    compile 'net.yslibrary.keyboardvisibilityevent:keyboardvisibilityevent:2.1.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'



    testCompile 'junit:junit:4.12'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.5.1'

}

**Comment by Xy-joe** [comment]
buildscript {
    repositories {
        mavenCentral()
        jcenter()
    }


    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
        classpath 'com.google.gms:google-services:3.0.0'
        classpath 'com.jakewharton:butterknife-gradle-plugin:8.5.1'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        maven {
            url 'https://maven.google.com'
        }
     //   maven { url "https://jitpack.io"
    }
}

**Comment by Alamgir** [comment]
@Xy-joe have you tried omitting `com.google.android.gms:play-services-gcm:9.8.0` and `com.google.firebase:firebase-messaging:9.8.0` from your dependencies? OneSignal already declares GCM as a dependency and doesn't require you to declare FCM or GCM

**Comment by Xy-joe** [comment]
@Alamgir I've tried it  this is the error it throws back  
 java.lang.IllegalAccessError: tried to access class com.google.android.gms.common.internal.zzac from class com.google.firebase.provider.FirebaseInitProvider
                                                                                     at com.google.firebase.provider.FirebaseInitProvider.zza(Unknown Source)
                                                                                     at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
                                                                                     at android.app.ActivityThread.installProvider(ActivityThread.java:5015)
                                                                                     at android.app.ActivityThread.installContentProviders(ActivityThread.java:4589)
                                                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4522)
                                                                                     at android.app.ActivityThread.access$1500(ActivityThread.java:151)

**Comment by Xy-joe** [comment]
Now i tried commenting out the one signal dependencies but yet once i try to run my application, it still gives me the same error

apply plugin: 'com.android.application'
apply plugin: 'com.jakewharton.butterknife'

android {
    compileSdkVersion 26
    buildToolsVersion '25.0.3'
    defaultConfig {
        applicationId "com.schoolunite.xyjoe.schoolunite"
        multiDexEnabled true
        minSdkVersion 17
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
       /** manifestPlaceholders = [onesignal_app_id: "fddcaf89-98ff-443e-8832-7df8cf97fc24",
                            //    Project number pulled from dashboard, local value is ignored.
                               onesignal_google_project_number: "REMOTE"]**/
        jackOptions {
            enabled true
        }
    }

   compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
        incremental false
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    packagingOptions {
        exclude 'META-INF/DEPENDENCIES.txt'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/dependencies.txt'
        exclude 'META-INF/LGPL2.1'
    }
}


dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'

    })


    compile'com.android.support:appcompat-v7:26.1.0'
    compile'com.android.support:design:26.1.0'
    compile'com.android.support:recyclerview-v7:26.1.0'
    compile'com.android.support:cardview-v7:26.1.0'
    compile'com.github.bumptech.glide:glide:3.7.0'
    compile 'com.android.support:support-v4:26.1.0'
    compile 'com.android.support:support-v13:26.1.0'
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.google.firebase:firebase-database:10.0.0'
    compile 'com.google.firebase:firebase-storage:10.0.0'
    compile 'com.google.firebase:firebase-core:10.0.0'
    compile 'com.google.firebase:firebase-auth:10.0.0'
    compile 'com.google.firebase:firebase-crash:10.0.0'
    compile 'com.firebaseui:firebase-ui-storage:1.0.1'
    compile 'com.firebaseui:firebase-ui-database:1.0.1'
    compile 'com.firebase:firebase-client-android:2.3.1'
    compile 'com.ernestoyaquello.stepperform:vertical-stepper-form:0.9.9'
    compile 'de.hdodenhof:circleimageview:1.2.1'
    // One signal
   // compile 'com.onesignal:OneSignal:[3.6.2, 3.99.99]'
    compile 'com.vanniktech:emoji-google:0.5.1'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.jakewharton:butterknife:8.5.1'
    //event bus
    compile 'org.greenrobot:eventbus:3.0.0'
    compile 'com.andkulikov:transitionseverywhere:1.7.4'
    compile 'net.yslibrary.keyboardvisibilityevent:keyboardvisibilityevent:2.1.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'

    testCompile 'junit:junit:4.12'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.5.1'

    compile 'com.android.support:palette-v7:26.1.0'
}


apply plugin: 'com.google.gms.google-services'

Now this is the current app:gradle file. @Alamgir  can you go through it and tell me exactly what and where I'm suppose to make adjustments

**Comment by Alamgir** [comment]
@Xy-joe since it looks like you're having dependency resoution issues with OneSignal ommitted, I would recommend using the gradle dependencies tool to figure out which of your libraries is causing those Firebase classes to be missing...

`./gradlew app:dependencies` 
or
 `./gradlew dependencyInsight --dependency play-services-gcm --configuration compile`

you can try switching `play-services-gcm` to the firebase core library to see if there are any conflicts within the firebase library as well

Refer to here: https://www.mkyong.com/gradle/gradle-display-project-dependency/

**Comment by cbedoy** [comment]
I had the same issue, but I fixed following the next steps:
```
   ext {
    supportLibVersion = "26.1.0"
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile "com.android.support:appcompat-v7:${supportLibVersion}"
    compile "com.android.support:design:${supportLibVersion}"
    compile "com.android.support:cardview-v7:${supportLibVersion}"
    compile "com.android.support:recyclerview-v7:${supportLibVersion}"
    //Compile 
    compile 'com.onesignal:OneSignal:[3.6.1, 3.9.9]'

//Force update
    **def gmsVersion = '10.2.6'
    compile("com.google.android.gms:play-services-gcm:${gmsVersion}") {
        force = true
    }
    compile("com.google.android.gms:play-services-location:${gmsVersion}") {
        force = true
    }**

    //ANDROID CONFIGURATION
   android {
    **compileSdkVersion 26
    buildToolsVersion "26.0.2"**
    defaultConfig {
        applicationId "YOUR.APPLICATION.ID"
        minSdkVersion 19
        **targetSdkVersion 26**
        .....
    }    
}
 
```

You should use the last **buildToolsVersion** cuz OneSignal is using, also **compileSdkVersion** should be **26**  and **targetSdkVersion**

They're using the last support library to **supportLibVersion = "26.1.0"**

And force override google-play-services.

It's very frustrating and basically I did a frankestein of research content from several pages and similar issues, I hope this work for you!

Regards.

**Comment by Xy-joe** [comment]
@cbedoy I've been offline for a while. I just got back. Thanks a lot for the solution you gave. It worked smoothly for me. I was almost looking for an alternative to OneSignal

**Comment by Mehrankhan10** [comment]
i am facing this problem kindly someone help  me 


`java.lang.NullPointerException: 
  at com.myapplication.AppPathTrackingActivity.displayLocation (AppPathTrackingActivity.java:413)
  at com.myapplication.AppPathTrackingActivity.onConnected (AppPathTrackingActivity.java:573)
  at com.google.android.gms.common.internal.GmsClientEventManager.onConnectionSuccess (Unknown Source)
  at com.google.android.gms.common.api.internal.zzav.zzb (Unknown Source)
  at com.google.android.gms.common.api.internal.zzaj.zzat (Unknown Source)
  at com.google.android.gms.common.api.internal.zzaj.onConnected (Unknown Source)
  at com.google.android.gms.common.api.internal.zzbd.onConnected (Unknown Source)
  at com.google.android.gms.common.api.internal.zzp.onConnected (Unknown Source)
  at com.google.android.gms.common.internal.zzf.onConnected (Unknown Source)
  at com.google.android.gms.common.internal.BaseGmsClient$PostInitCallback.handleServiceSuccess (Unknown Source)
  at com.google.android.gms.common.internal.BaseGmsClient$zza.deliverCallback (Unknown Source)
  at com.google.android.gms.common.internal.BaseGmsClient$zza.deliverCallback (Unknown Source)
  at com.google.android.gms.common.internal.BaseGmsClient$CallbackProxy.deliverCallback (Unknown Source)
  at com.google.android.gms.common.internal.BaseGmsClient$zzb.handleMessage (Unknown Source)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:163)
  at android.app.ActivityThread.main (ActivityThread.java:6221)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:904)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:794)`
