### ISSUE TITLE
Don't open web browser when clicked into notification

### ISSUE THREAD

**Issue by sinhpn92** [OneSignal/OneSignal-Android-SDK#328]
I set `launchUrl` in notification, but it's don't open web browser when click into notification. I'm debug and see that this line in `OneSignal` class return true:

`boolean defaultOpenActionDisabled = "DISABLE".equals(OSUtils.getManifestMeta(inContext, "com.onesignal.NotificationOpened.DEFAULT"));`

So that, method `openURLFromNotification` not called.

What's wrong here? How can i fix it? Have any ideal for my problem?

**Comment by Alamgir** [comment]
@sinhpn92 It looks like you have indicated through your manifest placeholders that you want OneSignal to handle an open event with the default behavior (open your launcher Activity) as referenced here: https://documentation.onesignal.com/docs/android-customizations#section-changing-the-open-action-of-a-notification

Remove the  `<meta-data android:name="com.onesignal.NotificationOpened.DEFAULT" android:value="DISABLE" />` from your `AndroidManifest.xml` and your URL should open properly

**Comment by jkasten2** [comment]
@sinhpn92 Feel free to reply if the above answer did not help
