### ISSUE TITLE
Feature Request: ability to manually change count on badge

### ISSUE THREAD

**Issue by rostopira** [OneSignal/OneSignal-Android-SDK#339]
My app has a lot of different notifications, but I want to show badge only for chat notifications.
Would be perfect to have methods `OneSignal.increaseBadgeCount()` and `OneSignal.resetBadgeCount()`

**Comment by JorgeZapa** [comment]
This is one of the features i am interested in because of similar reasons. It would be really interesting to set the badge count in android the same you can do with IOS.

**Comment by eugenio-caicedo** [comment]
I was just about to suggest the same thing. I needed it for the current application. But I see that you do not have that support.

**Comment by BenoitClaveau** [comment]
I need to override the badge count in DB by a value read in the notification like iOS.

**Comment by jkasten2** [comment]
Thanks for the suggestion, this isn't built into OneSignal right now but we have details on how to turn off the automatic setting of badges in this guide.
https://documentation.onesignal.com/docs/android-customizations#section-app-icon-badge-counts

You can then use this library to set your own badge values
https://github.com/leolin310148/ShortcutBadger

**Comment by eugenio-caicedo** [comment]
@jkasten2 Thanks for the reference. I thought about disabling the badge count, but the library you mentioned does not work on all devices. I had noticed that detail only using the OneSignal library.

**Comment by jkasten2** [comment]
@rostopira ShortcutBadger seems to support most Android launchers. Is there launchers that it is missing that you need? Or any other libraries you have seen fill in some of the gaps supporting other launchers?

It might be something someone has requested before if you take a look through their Open and Closed issue
https://github.com/leolin310148/ShortcutBadger/issues

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration

**Comment by rostopira** [comment]
Is it still under consideration?

**Comment by rgomezp** [comment]
yes
