### ISSUE TITLE
OneSignal-Android-SDK  Disable and enable  vibrate problem

### ISSUE THREAD

**Issue by MahariAndroid** [OneSignal/OneSignal-Android-SDK#343]
There is  a  bug on the loading   of vibrate value  from  preferences,see the function "getVibrate()"  in the line 1640 from OneSignal.java  file 

static boolean getVibrate(Context context) {
      return OneSignalPrefs.getBool(OneSignalPrefs.PREFS_ONESIGNAL,
              OneSignalPrefs.PREFS_GT_SOUND_ENABLED,true)
 

It must be OneSignalPrefs.PREFS_GT_VIBRATE_ENABLED  instead of  OneSignalPrefs.PREFS_GT_SOUND_ENABLED.

Can you  correct  this  issue please!

**Comment by Alamgir** [comment]
@MahariAndroid thanks for pointing this out, it will get fixed in the next release!
