### ISSUE TITLE
Notification not showing when targeted SDK for 27 version

### ISSUE THREAD

**Issue by kafabih4raka** [OneSignal/OneSignal-Android-SDK#352]
Hello, I have used OneSignal SDK that using targeted version to 27, I have tested to send notification using OneSignal dashboard, but on my logcat that looked like this : 
```Java
android W/dalvikvm: Unable to resolve superclass of Lcom/onesignal/OneSignalJobServiceBase; (120)
android W/dalvikvm: Link of class 'Lcom/onesignal/OneSignalJobServiceBase;' failed
android W/dalvikvm: Unable to resolve superclass of Lcom/onesignal/GcmIntentJobService; (3388)
android W/dalvikvm: Link of class 'Lcom/onesignal/GcmIntentJobService;' failed
android E/dalvikvm: Could not find class 'com.onesignal.GcmIntentJobService', referenced from method com.onesignal.GcmBroadcastReceiver.startGCMService
android W/dalvikvm: VFY: unable to resolve const-class 3284 (Lcom/onesignal/GcmIntentJobService;) in Lcom/onesignal/GcmBroadcastReceiver;
android D/dalvikvm: DexOpt: unable to opt direct call 0x02ca at 0x50 in Lcom/onesignal/GcmBroadcastReceiver;.startGCMService
android W/dalvikvm: Unable to resolve superclass of Lcom/onesignal/JobIntentService$JobServiceEngineImpl; (121)
android W/dalvikvm: Link of class 'Lcom/onesignal/JobIntentService$JobServiceEngineImpl;' failed
android E/dalvikvm: Could not find class 'com.onesignal.JobIntentService$JobServiceEngineImpl', referenced from method com.onesignal.JobIntentService.onCreate
android W/dalvikvm: VFY: unable to resolve new-instance 3298 (Lcom/onesignal/JobIntentService$JobServiceEngineImpl;) in Lcom/onesignal/JobIntentService;
android W/dalvikvm: Unable to resolve superclass of Lcom/onesignal/JobIntentService$JobServiceEngineImpl; (121)
android W/dalvikvm: Link of class 'Lcom/onesignal/JobIntentService$JobServiceEngineImpl;' failed
android D/dalvikvm: DexOpt: unable to opt direct call 0x5a09 at 0x0d in Lcom/onesignal/JobIntentService;.onCreate
```

**Comment by jkasten2** [comment]
@kafabih4raka Thanks for details. We have identified an issue with our SDK being able to access `NotificationCompat.Builder.mNotification` due to the Android Support Library revision 27 restricting access to package-private now.

Your log above seems to be unrelated to this though. Are you using Proguard on your app? If so do you have custom rules defined? Could you share your `app/build.gradle`?

**Comment by kafabih4raka** [comment]
I am sorry, I using proguard for release, but I have set debugable true, shrink false and minify false now,
here more details

android W/dalvikvm: VFY: unable to resolve virtual method 1084: Landroid/content/Context;.startForegroundService (Landroid/content/Intent;)Landroid/content/ComponentName;
android I/dalvikvm: Could not find method android.app.NotificationManager.getActiveNotifications, referenced from method com.onesignal.NotificationRestorer.restore
android E/dalvikvm: Could not find class 'android.os.PersistableBundle', referenced from method com.onesignal.NotificationRestorer.showNotifications
android W/dalvikvm: VFY: unable to resolve new-instance 512 (Landroid/os/PersistableBundle;) in Lcom/onesignal/NotificationRestorer;
android E/dalvikvm: Could not find class 'android.app.job.JobInfo$Builder', referenced from method com.onesignal.NotificationRestorer.startDelayedRestoreTaskFromReceiver
android W/dalvikvm: VFY: unable to resolve new-instance 123 (Landroid/app/job/JobInfo$Builder;) in Lcom/onesignal/NotificationRestorer;

**Comment by mayurwish** [comment]
Is this issued been fixed? We had downgraded our Support library to 26.0.2 following this issue.
Waiting for this issue to be solved

**Comment by kafabih4raka** [comment]
Same for me, I do downgrade the Build Tools to 26.0.0 and targeted SDK version to 25

**Comment by jkasten2** [comment]
@mayurwish @kafabih4raka We be fixing the compatibility with the Android Support library 27 in the next OneSignal SDK update. In the mean time you can still target Android SDK 26 and use the Android Support library 26.X

**Comment by dniHze** [comment]
Btw any updates on upgrade to Support Lib 27?

**Comment by jkasten2** [comment]
Just fixed compatibility in the pull above. We will be releasing an update later this week with this fix included.

**Comment by mayurwish** [comment]
Great! looking forward to this update.

**Comment by jkasten2** [comment]
@mayurwish Just released 3.7.0 which includes this fix

**Comment by mayurwish** [comment]
@jkasten2 Thanks, migrating to updated release.

**Comment by alexjolig** [comment]
I got `implementation 'com.onesignal:OneSignal:3.10.3'` and I still get this error. Is there still problems with `buildToolsVersion '28.0.3'` ? Cuz i'm using this
