### ISSUE TITLE
Cannot import OneSignal 3.6.5 on android studio 3.0

### ISSUE THREAD

**Issue by rifkyfu32** [OneSignal/OneSignal-Android-SDK#354]
Error:Could not find OneSignal.aar (com.onesignal:OneSignal:3.6.5).
Searched in the following locations:
    https://jcenter.bintray.com/com/onesignal/OneSignal/3.6.5/OneSignal-3.6.5.aar

**Comment by jkasten2** [comment]
@rifkyfu32 Can you try following the guide below?
https://documentation.onesignal.com/docs/troubleshooting-android#section-failed-to-resolve-com-onesignal-onesignal-3-6-0-3-99-99-

Attach both your root `build.gradle` and your `app/build.gradle` if you are still seeing an issue.

**Comment by rifkyfu32** [comment]
Forgive me, yesterday i got that problem, but somehow now gradle already resolve...

**Comment by jkasten2** [comment]
@rifkyfu32 It could have been an issue with Android Studio using the gradle cache on your system or a networking error on your system trying to search for the OneSignal library. 

Feel free to reopen if you are still seeing an issue.
