### ISSUE TITLE
Error:Cannot change strategy of configuration ':app:sandboxWearApp' after it has been resolved.

### ISSUE THREAD

**Issue by StevenStarz** [OneSignal/OneSignal-Android-SDK#357]
Step to reproduce the bug:
once i include

`plugins {
    id 'com.onesignal.androidsdk.onesignal-gradle-plugin' version '0.7.0'
}
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'`

before that i have got a error that `Error:Could not find com.android.support.constraint:constraint-layout:1.0.0-alpha7,` and apparently i don't use that plugins, so i remove it and run into this problem

but if i remove the included 
`plugins {
    id 'com.onesignal.androidsdk.onesignal-gradle-plugin' version '0.7.0'
}
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'`

is working fine

**Comment by jkasten2** [comment]
@StevenStarz Can you open a [new issue on the OneSignal-Gradle-Plugin](https://github.com/OneSignal/OneSignal-Gradle-Plugin/issues/new) and fill out all the information in the template? This will give us the details we need to reproduce the issue.

Thanks.
