### ISSUE TITLE
Problem with OneSignal android SDK

### ISSUE THREAD

**Issue by NalyLas** [OneSignal/OneSignal-Android-SDK#361]
When I add the  `compile 'com.onesignal:OneSignal:[3.6.5, 3.99.99]'` line I always have the same error
```Java
Error:Execution failed for task ':app:processDebugManifest'.
Manifest merger failed with multiple errors, see logs
```

I try all the issues's solutions you send but no working for me.
This is my build.graddle
```gradle
apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    buildToolsVersion "26.0.0"
    defaultConfig {
        applicationId "xxx.xxxx"
        minSdkVersion 15
        targetSdkVersion 26
        versionCode 32
        versionName "1.9.2"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        manifestPlaceholders = [onesignal_app_id: "xxx-xxxx-xxxx",
                                // Project number pulled from dashboard, local value is ignored.
                                onesignal_google_project_number: "REMOTE"]
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'),
                    'proguard-rules.pro'
        }
    }
}
android {
    useLibrary 'org.apache.http.legacy'
}

dependencies {
    compile 'com.onesignal:OneSignal:[3.6.5, 3.99.99]'
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile files('libs/universal-image-loader-1.8.6.jar')
    compile files('libs/zbar.jar')
    compile 'com.android.support:appcompat-v7:26.0.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.android.support:design:26.0.+'
    compile 'com.google.android.gms:play-services-analytics:11.2.0'
    compile 'junit:junit:4.12'
    compile 'com.google.android.gms:play-services-gcm:11.2.0'
    compile 'com.google.android.gms:play-services-maps:11.2.0'
    testCompile 'junit:junit:4.12'

}
apply plugin: 'com.google.gms.google-services'
```

**Comment by jemshit** [comment]
try adding 
    compile 'com.google.android.gms:play-services-loation:11.2.0' as well

**Comment by jkasten2** [comment]
@NalyLas Could you attach the full build log? There should be some additional entries before or after the `app:processDebugManifest` error you are seeing.

The issue however is most likely due to some interdependencies using mixed version between the Android Support library and Google Play servers. You can add the [OneSignal-Gradle-Plugin](https://github.com/OneSignal/OneSignal-Gradle-Plugin#setup) which is fix any conflicting versions. Let us know if adding this resolves your issue.

**Comment by NalyLas** [comment]
Thanks!!! I added the OneSignal-Gradle-Plugin and it fix all conflicts. Everything worked correctly until I updated the android API.
Thank you @jkasten2 now my app it's working again!!!

**Comment by jkasten2** [comment]
@NalyLas Awesome, good to hear our plugin worked well!

**Comment by chitgoks** [comment]
Im doing this in Android Studio 3. 

Error:Unable to resolve dependency for: ... Could not resolve com.onesignal:OneSignal:[3.7.1, 3.99.99].

I added the plugin and apply at the top most

**Comment by jkasten2** [comment]
@chitgoks Can you try following this steps in this guide?
https://documentation.onesignal.com/docs/troubleshooting-android#section-failed-to-resolve-com-onesignal-onesignal-3-7-1-3-99-99-

If it doesn't help can you copy the full error?

**Comment by chitgoks** [comment]
Yep, same. only difference was i removed maven { url 'https://maven.google.com' }
because i already have mavenCentral()

Error:Unable to resolve dependency for ':app@googleFreeDebug/compileClasspath': Could not resolve com.onesignal:OneSignal:[3.7.1,3.99.99].

**Comment by chitgoks** [comment]
well ... anyway... the problem is fixed. i did not specify targetSdkVersion (i never do) so this was what the error message was pertaining to.

**Comment by jkasten2** [comment]
@chitgoks Thanks for exact error.
`Cannot get property 'apiLevel' on null object`

It seems this is thrown from the [OneSignal-Gradle-Plugin](https://github.com/OneSignal/OneSignal-Gradle-Plugin) due to a bug. I created a new issue for this so we can handle the case where the project doesn't set `targetSdkVersion`.
https://github.com/OneSignal/OneSignal-Gradle-Plugin/issues/20
