### ISSUE TITLE
UpgradeReceiver missing completeWakefulIntent for Android O and later

### ISSUE THREAD

**Issue by niqo01** [OneSignal/OneSignal-Android-SDK#365]
If I am not mistaken, looking at the source code,
the `UpgradeReceiver` extending WakefulBroadcastReceiver is never calling `completeWakefulIntent` for Android O and later.
The NotificationRestorer.startDelayedRestoreTaskFromReceiver schedule a new job but never calls `completeWakefulIntent`

See:
https://github.com/OneSignal/OneSignal-Android-SDK/blob/master/OneSignalSDK/onesignal/src/main/java/com/onesignal/UpgradeReceiver.java 
https://github.com/OneSignal/OneSignal-Android-SDK/blob/master/OneSignalSDK/onesignal/src/main/java/com/onesignal/NotificationRestorer.java

**Comment by jkasten2** [comment]
@niqo01 Thanks for the catch, you are correct that `completeWakefulIntent` should be called for Android Oreo (8.0)+ since we using a `JobScheduler` here.

We will fix this in the next update.
Thanks.

**Comment by jkasten2** [comment]
@niqo01 After taking another look I realized that the `startWakefulService` is what takes the wake lock, however this isn't being called so this won't be an issue.

I did switch this to a `BroadcastReceiver` so this isn't misleading in pull https://github.com/OneSignal/OneSignal-Android-SDK/pull/393
