### ISSUE TITLE
How to retrieve notification channel id from a Notification?

### ISSUE THREAD

**Issue by niqo01** [OneSignal/OneSignal-Android-SDK#366]
I need to know what Android O channel is set for a notification but I can't find how to retrieve this information from an OsNotification.
https://documentation.onesignal.com/docs/android-native-sdk#section--osnotification-

**Comment by niqo01** [comment]
To be exact I want to know what's the `existing_android_channel_id` set client side.

**Comment by jkasten2** [comment]
@niqo01 This currently isn't a property available on the [`OSNotifiationPayload`](https://github.com/OneSignal/OneSignal-Android-SDK/blob/3.6.5/OneSignalSDK/onesignal/src/main/java/com/onesignal/OSNotificationPayload.java#L65) class. It is something that will need to be added and the code to populate it from the payload.

It should be contained within `OSNotifiationPayload.rawPayload` where you can print this out and find the channel id within.

I am marking this as a feature request to build this into the SDK.

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration
