### ISSUE TITLE
Custom sound notification

### ISSUE THREAD

**Issue by eugenio-caicedo** [OneSignal/OneSignal-Android-SDK#368]
I am trying to change the sound that has the default notification. For that, I do an override of the sound in the OverrideSettings class, but I can not make it reproduce. The notification is played with the sound of notifications by default, even ignores the "string" passed on the server.

````
OverrideSettings overrideSettings = new OverrideSettings();
overrideSettings.extender = new NotificationCompat.Extender() {
    @Override
    public NotificationCompat.Builder extend(NotificationCompat.Builder builder) {
        builder.setSound(Uri.parse("content://media/internal/audio/media/29"));
    }
};
````

**Comment by eugenio-caicedo** [comment]
Using the NotificationCompat.Builder class if it worked for me, but I need to solve it using the OverrideSettings class.

**Comment by jkasten2** [comment]
@eugenio-caicedo This will not work for Android Oreo (8.0) devices if you are targeting Android API level 26 or higher. With Oreo [Notification Categories / Channels](https://documentation.onesignal.com/docs/android-notification-categories) are now in control of the sound as well as some other settings. 
This may also not work if you have set an Android group on OneSignal.

If the above is not the case I recommend trying to add `builder.setDefaults(0);` as well.

**Comment by eugenio-caicedo** [comment]
Adding `builder.setDefaults (0);` It worked very well. Thanks @jkasten2

**Comment by jkasten2** [comment]
@eugenio-caicedo Good to hear that worked! The root of the issue is if the defaults flag `Notification.DEFAULT_SOUND` is set then it will override custom sounds. You can pass vibration, led, or any other settings to `setDefaults` if you still need them.

**Comment by eugenio-caicedo** [comment]
Excellent, this would be good to add it in the one signal documentation. I would save a lot of common mistakes for a custom sound. Thanks.
