### ISSUE TITLE
method plugins() not found on onesignal gradle plugin

### ISSUE THREAD

**Issue by kafabih4raka** [OneSignal/OneSignal-Android-SDK#369]
Hello, I have bugs hehe, in your documentation I must adding this in the gradle

```gradle
plugins {
    id 'com.onesignal.androidsdk.onesignal-gradle-plugin' version '0.7.0'
}
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
```

but in the logs I have error as seen below

```Java
Error:(4, 0) Could not find method plugins() for arguments [build_30kl937vqpu07tx72a2sks80r$_run_closure1$_closure2@27c361dd] on object of type org.gradle.api.internal.initialization.DefaultScriptHandler.
```

**Comment by jkasten2** [comment]
@kafabih4raka Does this build error a way if you remove the `onesignal-gradle-plugin`? If so can you create a new issue issue below filling out all the details you can on the template?
https://github.com/OneSignal/OneSignal-Gradle-Plugin/issues/new

**Comment by kafabih4raka** [comment]
when I removed onesignal-gradle-plugin from the gradle, it disappear.
