### ISSUE TITLE
Stacking the notifications - icons

### ISSUE THREAD

**Issue by rafalzawadzki** [OneSignal/OneSignal-Android-SDK#37]
We are implementing the push notifications for some user messaging and we were trying to stack the messages nicely.
Each message can have different large icon and in this case when they stack on eachother, the icon should be changed into app icon. As on example from your documentation:

![Image](https://www.filepicker.io/api/file/ZwvB3F4bRqepRE03huzU)

We couldnt find a way to make it - it seems there is always an icon from the last notification shown. Is it possible to achieve that?

**Comment by jkasten2** [comment]
Thanks for the report, I'll look into getting a fix for this in the next release.
