### ISSUE TITLE
Websites using OneSignal SDK fail to show an image in the notification on Samsung Internet browser

### ISSUE THREAD

**Issue by billyjay** [OneSignal/OneSignal-Android-SDK#370]
In case of Samsung internet, when websites show a notification using OneSignal SDK, the image fails to load. You can test this on www.deccanchronicle.com or www.gozefo.com ( under explore furniture>Beds) After changing the User Agent of the Browser to that of Chrome, the image loads fine.

**Comment by jkasten2** [comment]
@billyjay Could you open an issue on the repo below instead for issues with the OneSignal web SDK?
https://github.com/OneSignal/OneSignal-Website-SDK/issues

This SDK is just for native Android Apps.

Thanks.

**Comment by billyjay** [comment]
Sure. Will do. Thanks!
