### ISSUE TITLE
App crashing on Google Pixel XL Oreo 8.0

### ISSUE THREAD

**Issue by YasirAmeen** [OneSignal/OneSignal-Android-SDK#371]
My App was working fine but since Android Oreo has come to Google Pixel XL it keeps Crashing following is the Exception stack-trace
```java
Fatal Exception: java.lang.AbstractMethodError: abstract method "boolean 
android.app.job.JobServiceEngine.onStartJob(android.app.job.JobParameters)" at 
android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:108) at 
android.os.Handler.dispatchMessage(Handler.java:105) at 
android.os.Looper.loop(Looper.java:164) at 
android.app.ActivityThread.main(ActivityThread.java:6541) at 
java.lang.reflect.Method.invoke(Method.java) at 
com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) at 
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```
Can anyone help me with this ?

**Comment by ifucolo** [comment]
I have the same issue, and has 2500 crashes, and its really bad thing :S
OneSignal has any information about this bug?

**Comment by junaidwarsi1994** [comment]
i Am having Crashes Too at Google pixel XL 8.0 only

**Comment by Saqlainz** [comment]
This issue should be addressed as we are in a very critical position now.

**Comment by junaidwarsi1994** [comment]
@ifucolo  what target sdk are you using in tha app ?

**Comment by ifucolo** [comment]
@junaidwarsi1994 25

**Comment by junaidwarsi1994** [comment]
try updating the target version to 26 and let me know if problem solves

**Comment by jkasten2** [comment]
Updating to the OneSignal SDK 3.6.5 or newer should fix any issues related to Jobs with Android 8.0 (Oreo) with OneSignal.

If you are using the `com.onesignal.NotificationExtender` make sure to add `BIND_JOB_SERVICE ` to this.
```XML
<service
   android:name=".YOUR_CLASS_NAME"
   android:permission="android.permission.BIND_JOB_SERVICE"
   android:exported="false">
   <intent-filter>
      <action android:name="com.onesignal.NotificationExtender" />
   </intent-filter>
</service>
```

Feel free to reply if you are still running into this same error.

**Comment by SurajPadmasali** [comment]
This will always happen when you move to the new release version of Android or iOS. Wait for its official release or give sometimes to the developer to update their apps and fix the bugs. OR you can try these [possible solutions](https://www.megebyte.com/how-to-fix-apps-crashing-freezing-issue-on-google-pixel-2-2-xl/) if not wait.
