### ISSUE TITLE
addSubscriptionObserver or idsAvailable?

### ISSUE THREAD

**Issue by mradzinski** [OneSignal/OneSignal-Android-SDK#372]
Hi everyone! Quick question over here: I've the need to keep a constant record on my server of the player Id. When the user logs out from one account I need to be able to delete that player Id from that account, and if the user logs back into my app with a different account I need to be able to re-assign that player Id to the second account.

Going through the documentation and examples I saw that `idsAvailable` is deprecated in favor of `addSubscriptionObserver`. From the documentation of `addSubscriptionObserver` I got that the callback will be called when: 

> - Getting a Registration ID (push token) from Google 
> - **Getting a player/user ID from OneSignal**
> - setSubscription(boolean) is called 
> - User disables or enables notifications

However, `Getting a player/user ID from OneSignal` seems to happen only once (whenever the user opens the app for the first time), and even worst I have no control on when exactly that callback will be triggered again during the lifecycle of the app.

So, in order to be able to delete and re-assign player id's: Is it safe to use `idsAvailable` and to assume that player id's are generated only once and that the id will at least stay the same unless the app is uninstalled and re-installed? If not, how can I get the player Id at will so that I can re-assign it to a different user account?

Cheers and thanks!

**Comment by jkasten2** [comment]
@mradzinski The OneSignal player / user id will stay the same while the app is installed on the device. If OneSignal can detect the app was reinstalled on the same device the id will also stay the same.

The subscription and permission observers will only fire when a properties changes. Even if the app is closed and reopened the observer won't first again unless something changed about the state.

If you need to use your own custom id you can use `sendTags` to assign your own as an alternative  to the OneSignal id.

**Comment by mradzinski** [comment]
Awesome @jkasten2, thanks for the explanation.
