### ISSUE TITLE
OneSignal.deleteTag() doesn't seem to be working anymore

### ISSUE THREAD

**Issue by Reza-Soltani** [OneSignal/OneSignal-Android-SDK#373]
Hi there,

I have a user-based application, when someone login to his/her account, I will tag him with a unique user-id based on him phone number. 
And when someone tries to logout, I will delete this tag, and then he don’t get any notification which is right behavior.

But if a user removes his application before logout, I can’t delete the tag. So I have a check that if it’s first run of the app, then I will delete the tag (We are sure that in first run of the application, the user is logged out). But this idea is not working, the user still will get notifications from server. Do you have an idea why this is not working?

Thank you for your great service.

**Comment by jkasten2** [comment]
@Reza-Soltani For this case you can call [`getTags`](https://documentation.onesignal.com/docs/cordova-sdk#section--gettags-) on the first run. Then you can call [`deleteTags`](https://documentation.onesignal.com/docs/cordova-sdk#section--deletetags-) on any keys you need to remove.

**Comment by endymion00** [comment]
@jkasten2 so deleteTag is not suppose to work anymore? 
I tagged some users with tag userId and after that I noticed that the recommended tag is user_id. So I performed a deleteTag('userId') and a sendTag('user_id','xxxxxxxx') but as I see only sendTag works and deleteTag never deletes the tag.

**Comment by jkasten2** [comment]
@endymion00 `deleteTag` will only makes a network call if the SDK knows this key has been set already by the SDK. If you set the key with a REST API call directly then the key won't be deleted by the SDK from the onesignal.com backend. Or if you fully uninstalled and reinstalled the app on the device and OneSignal was able to detect it was the same device through the Google ad id. In this case even if you set the tag from the SDK before since the data was cleared for the app the SDK does not know the key exists.
 
Calling `getTags` fixes your delete issue since it will download the existing tags from onesignal.com so the SDK knows these are tags already set.

**Comment by show47** [comment]
😎 Thank you!

**Comment by endymion00** [comment]
@jkasten2 thank you for your answer.
By the way, regarding getTags is there something similar related to sendTag? When was testing this I also noticed that sometimes sendTag didn't set the tag (I meant calling sendTag to set an existing key)

**Comment by jkasten2** [comment]
@endymion00 Overriding wont' have this issue unless you making changes to the same key outside of the SDK and trying reset the key back to the exact same value for the key. That is if you set `key:" a"` on the SDK, then set `key: "b"` from the REST API, then try to set `key: "a"` again from the SDK. On the last step going back to `"a"` won't work in this case however setting SDK `key: "c"` will.

The best rule to follow if you need to set tags from both the REST API and the SDK is to use different keys.

**Comment by endymion00** [comment]
@jkasten2 thank your for clarifying this. I would suggest to include this information in the official documentation.
Regards

**Comment by jkasten2** [comment]
@endymion00 We do have a warning already the REST API documentation already.
https://documentation.onesignal.com/reference#edit-device
It doesn't explain the specifics however i noted above

**Comment by parthanjaria** [comment]
I am trying to use delete tag. but it does not seem to work, even after using getTags. 
So this is the code I have written. Why does it seem to not work? 
`public void deleteTags(){
        ArrayList<String> tagsToBeDeleted = new ArrayList<>();
        tagsToBeDeleted.add("Age");
        tagsToBeDeleted.add("AvgStrideLength");
        tagsToBeDeleted.add("CurrentMonthLeagueCount");
        OneSignal.deleteTags(tagsToBeDeleted);
    }

    public void getTags(){
        OneSignal.getTags(tags -> System.out.println(("OneSignal : "+ tags.toString())));
    }`

These methods are called in MainActivity.

**Comment by Godsmack121Kcamsdog** [comment]
I am trying to use deleteTag also. And have the same problem as discussed before.
I`ve tried several different variants:
1.  
                        Log.e("OneSignal", "logout: " + tags.names().toString());
                        OneSignal.sendTag("exhibition:test", "test_tag_on_logout");
                        OneSignal.deleteTag(getExhibitionAlias() + ":ticketExtra");
                        OneSignal.deleteTag("exhibition:first_name");
                        OneSignal.deleteTag(getExhibitionAlias() + ":last_name");
                        OneSignal.sendTag(getExhibitionAlias() + ":test_tag", "tag");
2.
 OneSignal.getTags(tags -> {
                        Log.e("OneSignal", "logout: " + tags.names().toString());
                        OneSignal.sendTag("exhibition:test", "test_tag_on_logout");
                        OneSignal.deleteTag(getExhibitionAlias() + ":ticketExtra");
                        OneSignal.deleteTag("exhibition:first_name");
                        OneSignal.deleteTag(getExhibitionAlias() + ":last_name");
                        OneSignal.sendTag(getExhibitionAlias() + ":test_tag", "tag");
                        });

In both cases I see Log.e output, so this code is called, but I can`t see any of tags edited or deleted in the OneSignal admin console.
Please, provide any feedback or help. Is anything wrong?
