### ISSUE TITLE
Wrong intent type using OS deeplinks in launch URL on Android platforms

### ISSUE THREAD

**Issue by pmaroco** [OneSignal/OneSignal-Android-SDK#375]
Hello! 

I was creating a notification containing an OS level deeplink using the Launch URL field as described [here](https://documentation.onesignal.com/v3.0/docs/links#section-os-level-deep-links), but it's creating a VIEW intent instead of a MAIN intent after opening the notification.

That said, if the app is opened in the background and a notification containing a deeplink is opened, a second instance of the app is opened and killed after performing some actions. Further investigation, this behavior only happens on Android, since deeplinks in iOS are working fine.

**Comment by jkasten2** [comment]
@pmaroco I'll follow up with you on the PR you linked to above.
