### ISSUE TITLE
Excessive wakeups from version 3.6.3 to 3.6.5

### ISSUE THREAD

**Issue by JamesQAQ** [OneSignal/OneSignal-Android-SDK#380]
Google Play reports excessive wakeups caused by OneSignal.

In our case we were never reported excessive wakeups greater then 0.5%. After updating OneSignal version to 3.6.3, it starts generating excessive wakeups.

Until version 3.6.5 this problem still exists. Is there any method to solve it?

![2017-11-27 11 11 56](https://user-images.githubusercontent.com/6916615/33250189-b5235bde-d2f4-11e7-923a-1f86198200d5.png)

![2017-11-27 11 12 18](https://user-images.githubusercontent.com/6916615/33250194-c4847f9a-d2f4-11e7-993e-385eaa200ee0.png)

**Comment by iballan** [comment]
I got the same reports !

**Comment by joelfernandes19** [comment]
Any updates on this? I'm seeing the same reports too.

**Comment by jkasten2** [comment]
Can you sure the percentages of Android version effected? Are you able to reproduce any additional wake ups on your test devices?

**Comment by jkasten2** [comment]
I believe this issue should be fixed in the 3.8.2 SDK update.
https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/3.8.2

Feel free to reply and we can reopen you are still seeing an issue with the `ALARM_WAKEUP`
