### ISSUE TITLE
Android Studio 3.0.1: Error:(22, 0) Could not find method plugins()

### ISSUE THREAD

**Issue by amitinfostretch** [OneSignal/OneSignal-Android-SDK#382]
I am getting following problem after updating gradle and Android Stdudio 3.0.1

Error:(22, 0) Could not find method plugins() for arguments [build_1049pxmidf1iwuzzil2ognsyi$_run_closure1$_closure5@8d7bbd] on object of type com.android.build.gradle.AppExtension.

Below is my shared link

https://photos.app.goo.gl/XL3akNb8QXMHyXU93

**Comment by jkasten2** [comment]
@amitinfostretch The following section of code needs to be moved to the very top of the file.
```gradle
plugins {
    id 'com.onesignal.androidsdk.onesignal-gradle-plugin' version '0.8.0'
}
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
```

We just added this to our troubleshooting guide.
https://documentation.onesignal.com/v3.0/docs/troubleshooting-android#section-error-22-0-could-not-find-method-plugins-for-arguments-on-object-of-type-com-android-build-gradle-appextension

**Comment by jkasten2** [comment]
@rakeshnambiar The code you pasted looks like it is from both your `app/build.gradle` and your root `build.gradle`. Can you split this up into 2 sections?

I also don't see `com.onesignal.androidsdk.onesignal-gradle-plugin` in your `build.gradle`.  The section noted above should be added to the vary top of your `app/build.gradle`. Thanks!
