### ISSUE TITLE
data is returned as [object object] , JSON format is expected.

### ISSUE THREAD

**Issue by devqx** [OneSignal/OneSignal-Android-SDK#398]
am currently building an app that pushes a notification to a user with additional data, when trying to fetch the data sent from one signal , i get [object object], how can i get data from this ?

**Comment by jkasten2** [comment]
@devqx You can access additional data from the [NotificationOpenedHandler](https://documentation.onesignal.com/docs/android-native-sdk#section--notificationopenedhandler-) with the following code.
```java
JSONObject data = result.notification.payload.additionalData;
```

You can then call `data.optString("customkey", null);` for example to get the value set on a specific key.
