### ISSUE TITLE
Request: Add push message id "i" to NotificationOpenedHandler

### ISSUE THREAD

**Issue by pstreef** [OneSignal/OneSignal-Android-SDK#40]
I am trying to make a link between the push message that was clicked and background data that I received. In background data I can use the push message "i" index, but this is not available in additional data. Would it be possible to add this?

**Comment by jkasten2** [comment]
Sure, we can look into adding this as I can see how this would be useful.

**Comment by jkasten2** [comment]
@pstreef We just added this in our 3.0.0 SDK release. See #79 for an example of getting the OneSignal notification id with this new interface.

Thanks.
