### ISSUE TITLE
ONESIGNAL_USERSTATE_SYNCVALYES_CURRENT_STATE and my sofa

### ISSUE THREAD

**Issue by Jamie-Landeg-Jones** [OneSignal/OneSignal-Android-SDK#402]
Why the hell is ONESIGNAL_USERSTATE_SYNCVALYES_CURRENT_STATE retrieving and reporting my device ID along with my current position to such a precise detail that if you threw a grenade at those coordinates, you'd blow up my sofa?

And yes, I'm serious.

**Comment by gdeglin** [comment]
Hi. The device's location is reported to OneSignal for notifications that you may send or trigger that are location related, and only when your app has been granted location permission by the device. This  If you do not plan to send notifications related to device location, you can disable this by calling `OneSignal.setLocationShared(false)` before calling `OneSignal.initWithLaunchOptions`.
