### ISSUE TITLE
New ANR issues found in play store .Broadcast of Intent { act=android.intent.action.BOOT_COMPLETED flg=0x8000010 cmp=com.onmo.discover/com.onesignal.BootUpReceiver (has extras) }

### ISSUE THREAD

**Issue by krishna2122** [OneSignal/OneSignal-Android-SDK#403]
Currently I am using one signal   compile 'com.onesignal:OneSignal:3.6.3'.
It is giving this ANR in my play store app.

https://play.google.com/store/apps/details?id=com.onmo.discover

[onesignal_anr.txt](https://github.com/OneSignal/OneSignal-Android-SDK/files/1610806/onesignal_anr.txt)

**Comment by jkasten2** [comment]
@krishna2122 Could you share the code you are running in `onCreate` method of your `com.onmo.discover.app.DiscoverApplication`? The issue is there is to much work happening here on the main thread.

**Comment by krishna2122** [comment]
Thanks @jkasten2  here is the onCreate code of the application com.onmo.discover.app.DiscoverApplication .

@Override
    public void onCreate() {
        super.onCreate();
        mApplication = this;
        OneSignal.startInit(this)
                .inFocusDisplaying(OneSignal.OSInFocusDisplayOption.Notification)
                .unsubscribeWhenNotificationsAreDisabled(true)
                .init();

        OneSignal.idsAvailable(new OneSignal.IdsAvailableHandler() {
            @Override
            public void idsAvailable(String userId, String registrationId) {
                String player_id = userId;
                MultiProcessPreferenceProvider.setPreferenceString(AppConstants.SharedPref.ONE_SIGNAL_PLAYER_ID, player_id);
                Log.d("OneSignal::", "player_id:" + player_id);
                if (registrationId != null)
                    Log.d("OneSignal:", "registrationId:" + registrationId);

            }
        });
      
        AppsFlyerLib.getInstance().setImeiData(DeviceInfo.getDeviceIdIMEI(this));
        AppsFlyerLib.getInstance().setAndroidIdData(DeviceInfo.getAndroidDeviceId(this));
        AppsFlyerLib.getInstance().setCurrencyCode("USD");
        AppsFlyerLib.getInstance().startTracking(getApplication(), getString(R.string.apps_flayer_dev_key));
        AppsFlyerLib.getInstance().reportTrackSession(this);
        GoogleAnalyticsTrackers.initialize(this);
        GoogleAnalyticsTrackers.getInstance(this).get(GoogleAnalyticsTrackers.Target.APP);
        Twitter.initialize(this);
        playerManager = new PlayerManager();
        playerManager.onCreate(this);
        InstallConfig installConfig = new InstallConfig.Builder().build();
       // HashMap config = new HashMap();
        try {

            Core.init(All.getInstance());
            Core.install(this, getString(R.string.helpshift_api_key),
                    getString(R.string.helpshift_app_domain), getString(R.string.helpshift_app_id),
                    installConfig);
            /*OneSignal.startInit(this)
                    .inFocusDisplaying(OneSignal.OSInFocusDisplayOption.Notification)
                    .unsubscribeWhenNotificationsAreDisabled(true)
                    .init();*/

        } catch (Exception e) {
            e.printStackTrace();
        }
        if (mDatabaseFactory == null) {
            mDatabaseFactory = new DatabaseFactory(getApplicationContext());
        }
        mRequestManager = RequestManager.getInstance(getApplicationContext());
        mRequestResponseDelegate = RequestResponseDelegate.getInstance();
        doInitialisation();
    }

    public void doInitialisation() {
        if (managerDelegate == null) {
            managerDelegate = new ManagerDelegate(mApplication);
        }
        if (_appConfig == null) {
            _appConfig = new AppConfig(getApplicationContext());
        }

    }

**Comment by jkasten2** [comment]
Since there is a number of things being initialized here, you will need to move some of it to a new thread to solve the main thread taking to long issue. I recommend you profile your app start to see what it taking the time.

This doesn't look to be a OneSignal related issue however if find any issues with OneSignal creating a delay here feel free to reply with the details and I'll reopen the issue.

**Comment by pedrofsn** [comment]
I've the same issue `Broadcast of Intent { act=android.intent.action.BOOT_COMPLETED flg=0x89000010 cmp=br.MY_PACKAGE_HERE/com.onesignal.BootUpReceiver (has extras) }.` The last ocurrency/ANR was detected by google play console was in Samsung S20 5G with Android 11 (SDK 30). On the last 15 minutes we got almost 30k ANRs. 😞

**Comment by pedrofsn** [comment]
@jkasten2 the crashes mentioned OneSignal, can you help me with this?

**Comment by Jeasmine** [comment]
Hey @pedrofsn! I would recommend upgrading to version 4.x.x; the last one until this moment is https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.4.0. There has been a lot of bug fixing that is not backported to 3.x.x versions. 4.x.x is a major release with breaking changes, so you might want to check the release notes for https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.0.0

**Comment by pedrofsn** [comment]
Thanks @Jeasmine. I'll do that!

**Comment by 123dma** [comment]
We're having the same problem over here. Many YEARs related to this error. Motorola manufacturer devices only. 
We are using onesignal version 'com.onesignal:OneSignal:4.6.2

Motorola Moto C Plus
Motorola moto e5 play
Motorola Moto G (3rd Gen)
Motorola moto e6 play

**Comment by vlad-roid** [comment]
also still there in 4.7.0, haven't tried the newer versions
any updates on this?

**Comment by jkasten2** [comment]
@vlad-roid Thanks for reporting, could you share the full stack trace for all threads from the ANR report, as well as your `Application.onCreate` code so we can help find the root cause.

**Comment by vlad-roid** [comment]
@jkasten2 "Stack trace not available" pops up on the Play Store console. Regarding `onCreate`, this is everything:
```
    OneSignal.initWithContext(this)
    OneSignal.setAppId(getString(R.string.onesignal_app_id))
    OneSignal.unsubscribeWhenNotificationsAreDisabled(true)
    OneSignal.setRemoteNotificationReceivedHandler(this)
    OneSignal.setNotificationOpenedHandler(this)
    OneSignal.setLocationShared(false)
    OneSignal.disableGMSMissingPrompt(true)
```

**Comment by jkasten2** [comment]
@vlad-roid Thanks for the code, I don't see anything in there that would cause a slow down on starting your app process. We would need a stack trace or steps to reproduce to be able to find the issue.

**Comment by vlad-roid** [comment]
Sorry missed one bit:
```
    if (consent) {
        OneSignal.provideUserConsent(true)
        OneSignal.disablePush(false)
    }
```
`consent` is read from shared prefs

**Comment by jkasten2** [comment]
@vlad-roid You could omit reading shared prefs of this. You only need to call `OneSignal.provideUserConsent(true)` once and the SDK will remember it for you. You also don't have to call `OneSignal.disablePush(false)` here, as the device won't send any data to OneSignal until `OneSignal.provideUserConsent(true)` is called as some point in your app. _(assuming you are calling `OneSignal.setRequiresUserPrivacyConsent` before `OneSignal.initWithContext` or have the specific meta-data key in your `AndroidManifest.xml` )_

Removing any I/O or disk read / writes off the main thread will prevent some ANRs. This could resolve small percentage to all your ANRs depends on what your root cause(s) are.

**Comment by nan-li** [comment]
Hi @vlad-roid,

Checking in if these suggestions led to any reduction in ANRs for you?
