### ISSUE TITLE
One Signal not working with firebase analytics

### ISSUE THREAD

**Issue by reeteshkumar39** [OneSignal/OneSignal-Android-SDK#406]
it gives this error in integration from both docs
```java
java.lang.NoSuchMethodError: No static method zzb(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzac; or its super classes (declaration of 'com.google.android.gms.common.internal.zzac' appears in /data/app/in.playx.app-1/base.apk)
```

**Comment by reeteshkumar39** [comment]
01-11 12:38:15.095 16038-16038/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: in.playx.app, PID: 16038
                                                   java.lang.NoSuchMethodError: No static method zzb(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzac; or its super classes (declaration of 'com.google.android.gms.common.internal.zzac' appears in /data/app/in.playx.app-2/base.apk)
                                                       at com.google.firebase.provider.FirebaseInitProvider.zza(Unknown Source)
                                                       at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
                                                       at android.app.ActivityThread.installProvider(ActivityThread.java:5417)
                                                       at android.app.ActivityThread.installContentProviders(ActivityThread.java:4988)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4923)
                                                       at android.app.ActivityThread.access$1500(ActivityThread.java:144)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1424)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:155)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5696)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)

**Comment by jkasten2** [comment]
@reeteshkumar39 It looks you have a mixture of different versions of Google Play services / FCM libraries in your build.gradle. Can you Open your app/build.gradle (Module: app) file, add the following to the very top (line 1).
```gradle
plugins {
    id 'com.onesignal.androidsdk.onesignal-gradle-plugin' version '0.8.0'
}
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
```

**Comment by reeteshkumar39** [comment]
buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
    }

    dependencies {
        classpath 'io.fabric.tools:gradle:1.24.4'
    }
}
apply plugin: 'com.android.application'
apply plugin: 'io.fabric'

repositories {
    maven { url 'https://maven.fabric.io/public' }
    maven { url "https://jitpack.io" }
}

android {
    compileSdkVersion 26
    buildToolsVersion '26.0.0'
    defaultConfig {
        applicationId 'in.playx.app'
        minSdkVersion 16
        targetSdkVersion 26
        versionCode 26
        versionName '2.4.4'
        vectorDrawables.useSupportLibrary = true //for content resouces crashes

        multiDexEnabled true
        manifestPlaceholders = [onesignal_app_id               : "20b73505-94de-4e0e-a9e6-4cbebc7275aa",
                                // Project number pulled from dashboard, local value is ignored.
                                onesignal_google_project_number: "REMOTE"]

    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    sourceSets { main { assets.srcDirs = ['src/main/assets', 'src/main/assets/'] } }
    productFlavors {
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    //  compile 'com.android.support:multidex:1.0.0'

    //    compile files('libs/pgsdk.jar')
    compile('com.crashlytics.sdk.android:crashlytics:2.6.2@aar') {
        transitive = true;
    }

    //compile 'com.android.volley:volley:1.0.0'

     compile 'com.google.firebase:firebase-core:10.0.1'
    compile 'com.squareup.retrofit:retrofit:1.9.0'
    compile 'com.android.support:appcompat-v7:26.0.0'
    compile 'com.android.support:design:26.0.0'
    compile 'com.android.support:cardview-v7:26.0.0'
    compile 'com.android.support:recyclerview-v7:26.0.0'
    compile 'com.facebook.android:facebook-android-sdk:4.5.0'
    compile 'com.squareup:otto:1.3.8'
    compile 'com.jakewharton:butterknife:7.0.1'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.mcxiaoke.volley:library:1.0.19'
    compile 'com.daimajia.androidanimations:library:1.1.3@aar'
    compile 'com.squareup.okhttp:okhttp:2.3.0'
    compile 'com.github.bumptech.glide:glide:3.7.0'
    compile 'me.relex:circleindicator:1.1.6@aar'
    compile 'de.hdodenhof:circleimageview:2.0.0'
    compile 'jp.wasabeef:glide-transformations:2.0.0'
    compile 'jp.wasabeef:picasso-transformations:2.1.0'
    compile 'com.jpardogo.materialtabstrip:library:1.1.0'
    compile 'com.orhanobut:dialogplus:1.11@aar'
    compile 'com.nineoldandroids:library:2.4.0'
    compile 'io.github.kexanie.library:MathView:0.0.6'
    compile 'pub.devrel:easypermissions:0.2.0'
    compile 'com.onesignal:OneSignal:[3.7.1, 3.99.99)'
    compile 'com.intuit.sdp:sdp-android:1.0.4'
    compile 'cn.pedant.sweetalert:library:1.3'
    compile 'com.razorpay:checkout:1.4.1'
    compile 'com.github.iwgang:countdownview:2.1.6'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.android.support:support-v4:26.+'
}

configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                details.useVersion '26.0.0'
            }
        }
    }
}
apply plugin: 'com.google.gms.google-services'

**Comment by reeteshkumar39** [comment]
mind blowing working ..........
