### ISSUE TITLE
Usage Of OneSignal Plugin Inside Android Library Module

### ISSUE THREAD

**Issue by agr111** [OneSignal/OneSignal-Android-SDK#409]
There seems to be issues using OneSignal at the library module level. It works when `OneSignal` is configured in the main app module's build.gradle file. But modifying the library module's build.gradle so that `OneSignal` files can be placed inside the library module seem to produce Gradle errors.

```Could not find property 'applicationVariants' on com.android.build.gradle.LibraryExtension```

Library Module build.gradle

```
plugins {
    id 'com.onesignal.androidsdk.onesignal-gradle-plugin' version '0.8.1'
}

apply plugin: 'com.android.library'
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

dependencies {
    ...
    implementation 'com.onesignal:OneSignal:[3.7.1, 3.99.99]'
    ...
}

```

Root build.gradle

```
dependencies {
        classpath 'com.android.tools.build:gradle:3.1.0-alpha07'
        ...
    }

ext {
compileSDKVersion = 27
buildToolVersion = '27.0.2'
...
}
```

**Comment by jkasten2** [comment]
@agr111 This actually an issue with the OneSignal-Gradle-Plugin. I have open an issue on this repo instead where we can continue there.
