### ISSUE TITLE
Badge icon number - Count out of sync after reboot

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-Android-SDK#41]
After Android is rebooted OneSignal notifications do not reappear so the badge count value is no longer in sync with the number of notifications. Notifications should reappear or the counter should reset on boot.

May also be an issue when notifications are cleared programmatically.

**Comment by ismly** [comment]
same here.. can we hide these cadge counts? click on app but, cant delete the count number...

**Comment by jkasten2** [comment]
You can disable the auto badge counting until a fix is created by adding the following to your `AndroidManifest.xml`.
```xml
<application ...>
   <meta-data android:name="com.onesignal.BadgeCount" android:value="DISABLE" />
</application>
```

If you still want badge support in your app but want to control it manually you can use the following library in your app.
https://github.com/leolin310148/ShortcutBadger

Thanks.

**Comment by sagar23jan** [comment]
I added the metadata key but the badge still doesn't go away.

**Comment by jkasten2** [comment]
@sagar23jan The meta-data key keeps the SDK from updating the badge value. Android launchers remember the value unless you fully uninstall then reinstall the app.

You can use the library above if you have already released your app and you would like to clear the existing value.

**Comment by absagar** [comment]
I simply added the `ShortcutBadger.applyCount(context, 0);` after I init OneSignal in my application's code, which seems to work. Thanks for the workaround.

**Comment by erhanharm** [comment]
Thanks for workaround.

I've added my application ;)

On Sat, May 28, 2016 at 3:36 PM, Abhishek Sagar <notifications@github.com>
wrote:

> I simply added the ShortcutBadger.applyCount(context, 0); after I init
> OneSignal in my application's code, which seems to work. Thanks for the
> workaround.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/one-signal/OneSignal-Android-SDK/issues/41#issuecomment-222306363>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAL1JgVkDW1ICJCJFYqUc1rYbgT4TyB-ks5qGDa7gaJpZM4IPeuV>
> .
>



-- 
*Erhan Harmankaya*

http://tr.linkedin.com/in/erhanharmankaya

**Comment by jkasten2** [comment]
Fixed in [Release 2.5.0](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/2.5.0).

**Comment by shahzadiqbal** [comment]
How to get Badge count? if we want to use Badge count in our app.

**Comment by jkasten2** [comment]
@shahzadiqbal Please see issue #87
