### ISSUE TITLE
Getting Error when try to send PushNotification

### ISSUE THREAD

**Issue by programmorem** [OneSignal/OneSignal-Android-SDK#412]
I tried to send a push notification from an Android device. 
Here is my Code:
```java
try {
                OneSignal.postNotification(new JSONObject(
                                "{'contents': {'en':['" + message + "']}, " +
                                "'include_player_ids': ['" + user_id + "'], " +
                                "'headings': {'en': 'Tag sub Title HI {{user_name}}'}, " +
                                "'data': {'openURL': 'https://imgur.com'}," +
                                "'buttons':[{'id': 'id1', 'text': 'Go to GreenActivity'}, {'id':'id2', 'text': 'Go to MainActivity'}]}"),
                        new OneSignal.PostNotificationResponseHandler() {
                            @Override
                            public void onSuccess(JSONObject response) {
                                Log.d("LOL", "postNotification Success: " + response.toString());
                            }

                            @Override
                            public void onFailure(JSONObject response) {
                                Log.d("LOL", "postNotification Failure: " + response.toString());
                            }
                        });
            } catch (JSONException e) {
                e.printStackTrace();
            }`
```
But every time I run this code I get the following Error:
```java
01-16 14:52:54.665 6983-7283/com.futumorrow.raycroud.futumorrow D/LOL: postNotification Failure: {"errors":["Notification contents for each language must be a string"]}
```

Si only wants to send the SAME Message to all Languages.

**Comment by jkasten2** [comment]
@programmorem Can you make sure `message` is set to a non-null and non-blank string? I also recommend calling `toString()` on your `JSONObject` and print it to the logcat to make sure it was added to the payload correctly.

**Comment by programmorem** [comment]
@jkasten2 Hey, I fixed the Problem. Thanks for your help. It helps me a lot. The [ ] after 'en': was the error..
Here is the working Code: `JSONObject jsonObject = new JSONObject(
                                "{'contents': {'en': '" + message + "'}, " +
                                "'include_player_ids': ['" + user_id + "'], " +
                                "'headings': {'en': 'Tag sub Title HI {{user_name}}'}, " +
                                "'data': {'openURL': 'https://imgur.com'}," +
                                "'buttons':[{'id': 'id1', 'text': 'Go to GreenActivity'}, {'id':'id2', 'text': 'Go to MainActivity'}]}");`
Thanks for all, again.
