### ISSUE TITLE
onesignal backup as firebase

### ISSUE THREAD

**Issue by rokto** [OneSignal/OneSignal-Android-SDK#414]
I was trying to use one signal as backup plan of firebase failure. So, but in get data of one signal there is  an extra {custom={"a":{}}.  How to avoid this extra token. In firebase getdata there is no {custom={"a":{}} susch type parameters .

**Comment by jkasten2** [comment]
@rokto OneSignal and basically all other push notification services use FCM / GCM to send notifications to devices. This is for two reasons; 1. It is taxing on devices' resources and battery if each app needs it own direct network connection; 2. FCM / GCM can wake the device from doze mode if high priority is needed.

If for some reason just the Firebase dashboard was down but not their API service then OneSignal could be used as a backup in this case though. 😄 

There isn't a configuration option to change the payload being sent from OneSignal through FCM. Your app will need to handle both formats in this case.
