### ISSUE TITLE
problem on adding id on build.gradle...

### ISSUE THREAD

**Issue by hashirmdv** [OneSignal/OneSignal-Android-SDK#419]
iam using android ide.it is an android mobile app for developing android app(https://play.google.com/store/apps/details?id=com.aide.ui&referrer=utm_source%3Daidewebsite%26utm_campaign%3Dhomepage).

when i using below `manifestPlaceholders = [onesignal_app_id: "3beb3078-e0f1-4629-af17-fde833b9f716",
                                // Project number pulled from dashboard, local value is ignored.
                                onesignal_google_project_number: "REMOTE"]`

shows the error
`aapt:manifest merge problem:/storage/emulated/0/onesignal_android_sdk/examples/androidstudio/aspp/build/bin/injected/androidmanifest.xml 
error:attribute meta_dat#onesignal_app_id@value at androidmanifest.xml require a place holder substitution but it is not provided.`

please help me

**Comment by jkasten2** [comment]
@hashirmdv I believe the AIDE still has a limitation on `manifestPlaceholders` so you won't be able to follow the Android Studio / Gradle setup for this SDK. Instead however you can add our OneSignalSDK.jar directly by and include the require `AndroidManifest.xml` entries manually.
https://documentation.onesignal.com/docs/android-sdk-setup-eclipse#section-2-androidmanifest-xml

I recommend you suggest to AIDE add support for `manifestPlaceholders`. We don't plan on removing this requirement from our .aar. Thanks.
