### ISSUE TITLE
Unable to hide alert dialog when app is in focus

### ISSUE THREAD

**Issue by buddhasaikia** [OneSignal/OneSignal-Android-SDK#421]
When the app is in focus, I need to show notification in android notification drawer instead of in app alert dialog. I tried `inFocusDisplaying(OneSignal.OSInFocusDisplayOption.Notification)` but still it is showing alert dialog. Any help would be highly appreciated.

**Comment by jkasten2** [comment]
@buddhasaikia That is all you should need. Full example.
```java
OneSignal.startInit(this)
         .inFocusDisplaying(OneSignal.OSInFocusDisplayOption.Notification)
         .unsubscribeWhenNotificationsAreDisabled(true)
         .init();
```

Can you make sure you are using the latest 3.7.1 release? If so make sure you are not calling OneSignal.startInit() any where else in your code without this option.

Lastly make sure you don't have any other GCM / FCM code that could be displaying the notification as an alert.

**Comment by buddhasaikia** [comment]
oh! Yes. That was the issue. I see OneSignal.startInit() in multiple places. Thanks for your support.
