### ISSUE TITLE
AbstractMethodError, JobHandler.handleMessage on some Android 8.0 devices

### ISSUE THREAD

**Issue by calanti** [OneSignal/OneSignal-Android-SDK#424]
Yesterday we released an update to our app, and OneSignal is causing quite a lot of issues for 2 devices so far with this error;
```
java.lang.AbstractMethodError: 
  at android.app.job.JobServiceEngine$JobHandler.handleMessage (JobServiceEngine.java:108)
  at android.os.Handler.dispatchMessage (Handler.java:105)
```
The affected devices are;
> Nexus 5X (bullhead) - Android 8.0
> Mate 10 Pro (HWBLA) - Android 8.0

2 days ago is when we released an update containing a much more up-to-date version of the OneSignalSDK, as per the documentation is it in our gradle file as;
`compile 'com.onesignal:OneSignal:[3.7.1, 3.99.99]'`

This release caused hundreds of crashes on (probably all) the Android 8.0 devices because we didn't add the `BIND_JOB_SERVICE ` permission in the manifest. So, while adding this has definitely solved the majority of issues for yesterdays release, there is still an issue present as mentioned above.

**Comment by calanti** [comment]
After playing with it this is only a problem when proguard is enabled, long story short I have proguarded OneSignal working successfully on Adnroid 8.0 and 8.1 by adding this to my proguard rules;

`-keep class com.onesignal.JobIntentService$* {*;}`

I can only test on an emulator since I don't have a physical 8.0/8.1 device, but so far so good.

**Comment by jkasten2** [comment]
@calanti Thanks for the details, we have included it in our SDK with the commit above and it will be included in our next release.
