### ISSUE TITLE
Multiple dex files define Lcom/onesignal/ADMMessageHandler$Receiver;

### ISSUE THREAD

**Issue by onepas** [OneSignal/OneSignal-Android-SDK#431]
Dear
We use OneSignal with cocos, but we get an error:
`
Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/onesignal/ADMMessageHandler$Receiver;
`
gradle:
`
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile project(':libcocos2dx')

    compile 'com.onesignal:OneSignal:3.+@aar'
}
`

**Comment by jkasten2** [comment]
The error means OneSignal is included twice in your project.

Did you also add OneSignal with SDKBox? If so then I believe it adds it's own copy so you don't need to add `compile 'com.onesignal:OneSignal:3.+@aar'`.

**Comment by onepas** [comment]
Thank you, It worked
