### ISSUE TITLE
VerifyError: com.onesignal.OneSignal

### ISSUE THREAD

**Issue by rasoulinejad** [OneSignal/OneSignal-Android-SDK#437]
Android: 4.2.1
Manufacturer: HUAWEI
Model: HUAWEI G700-U10
----
Android: 4.4.4
Manufacturer: HTC
Model: HTC Desire 620

java.lang.VerifyError: com.onesignal.OneSignal
when init OneSignal on application class:
	OneSignal.startInit(getApplicationContext())
                                .inFocusDisplaying(OneSignal.OSInFocusDisplayOption.None)
                                .setNotificationOpenedHandler(new CustomNotificationOpenedHandler())
                                .disableGmsMissingPrompt(true)
                                .init();

**Comment by jkasten2** [comment]
@rasoulinejad Can you include the full stack trace of the error?

Do you have `multiDexEnabled true` set in your `build.gradle`? If so make sure to double check Google's instructions on setting up support for for Pre 5.0 devices.
https://developer.android.com/studio/build/multidex.html

**Comment by jkasten2** [comment]
@rasoulinejad Please reply with the full stack trace if you are still seeing this error and we can reopen this issue. Or let us know if the above solved the issue for you.
