### ISSUE TITLE
Why onesignal_google_project_number is needed if pulled from remote

### ISSUE THREAD

**Issue by caipivara** [OneSignal/OneSignal-Android-SDK#438]
Hi

I see in [documents](https://documentation.onesignal.com/docs/android-sdk-setup) that I need to add `onesignal_google_project_number: "REMOTE"`.

Why this value is needed? can I ignore it in my setup and have it like the next example?

```
android {
   defaultConfig {
      manifestPlaceholders = [onesignal_app_id: "PUT YOUR ONESIGNAL APP ID HERE"]
    }
 }
```

**Comment by jkasten2** [comment]
@caipivara The `onesignal_google_project_number` key is still required to as it is still in the `AndroidManifest.xml`. We have to wait until the next major release (4.0.0) to remove this as it will break builds of those are relying on a local value.

Thanks.

**Comment by markosole** [comment]
Hi I know this is closed but it still requires `onesignal_google_project_number` in  `AndroidManifest.xml`
I am just guessing what is needed to iOS platform and how to configure it.

**Comment by jkasten2** [comment]
I can confirm `onesignal_google_project_number` was removed in OneSignal's `AndroidManifest.xml` in the OneSignal-Android-SDK 4.0.0. So this doesn't need to be set any longer in your `manifestPlaceholders `.

There was never a similar setting for iOS for the OneSignal SDK.
