### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException at NotificationOpenedProcessor.java line 67

### ISSUE THREAD

**Issue by DimaKoz** [OneSignal/OneSignal-Android-SDK#45]
I got a crashlog (see [log.txt](https://github.com/one-signal/OneSignal-Android-SDK/files/241535/log.txt)).
About device:
<img width="954" alt="screen shot 2016-04-29 at 1 15 28" src="https://cloud.githubusercontent.com/assets/3092276/14903157/4fd2efac-0db0-11e6-8777-0878c030bb52.png">

**Comment by jkasten2** [comment]
@DimaKoz Thanks again for these. We haven't seen any reports of `SQLiteDatabaseLockedException` with our SDK but after reviewing our code I see we are creating multiple `OneSignalDbHelper` instances with different Android Contexts which is most likely creating the issue.

Let us know the steps needed to reproduce this issue if you can, we can then write a test case for this.

Thanks.

**Comment by jkasten2** [comment]
@DimaKoz Just fixed this in our 3.0.3 release.
