### ISSUE TITLE
Grouping and other things not working in Android 8.1.0

### ISSUE THREAD

**Issue by calanti** [OneSignal/OneSignal-Android-SDK#453]
Our production app does not seem to group notifications properly on Android 8.1.0 (Observed on the Nexus 5X), we believed it was to do with our payload being incorrect, however after spending some time testing a variety of options in the templates on the OneSignal dashboard, we are still unable to get notifications to group at all on 8.1.0. 

We have also observed the following issues;

> Specifying colors (accent and led) does not work as per documentation (e.g. #XXXXXXXX), it only works without the # symbol. (e.g. XXXXXXXX)

> A single notification will display the correct 'small icon' specified, but when multiple notifications are received (but didn't group), the 'small icon' changes to the default bell, please see attached screenshots.

> Setting the led color with format '#XXXXXXXX' or '#XXXXXX' will display the system default LED color. Setting this color with format 'XXXXXXXX' or 'XXXXXX' will display a white LED color only. Observed this on Xiaomi Mi Max (Android 6.0.1), the Nexus 5X does not have LED. This happens with both single and multiple notifications. The same applies to setting 'LED COLOR' on a Category, and applying that category to the message tempalate.

> Grouping works as expected on Xiaomi Mi Max (Android 6.0.1).

### Single notification on Android 8.0.1 displaying correctly ###
![fm single notification](https://user-images.githubusercontent.com/12170223/36844727-d8513222-1d8e-11e8-892a-90873ef8229a.jpg)

### Multiple (should be grouped) notifications on Android 8.0.1 not grouping as expected, and default bell replaces the specified icon ###
![fm double notification](https://user-images.githubusercontent.com/12170223/36844773-0030f516-1d8f-11e8-8597-fcfb115e030a.jpg)

### The template settings used ###
![fm notification template settings](https://user-images.githubusercontent.com/12170223/36844789-0b63ef7e-1d8f-11e8-9e95-ab542afdcfa0.JPG)

A few other minor issues observed;

> When editing a message template and specifying the category, it will always return to default '(Created in app)'

> A screenshot on this page 'https://documentation.onesignal.com/docs/customize-notification-icons' under 'To set the color on per notification bases set android_accent_color' shows you should specify the asset icon res name as 'xxxx.png', however when the file extension '.png' is supplied, it will not work and only display the default bell.

**Comment by jkasten2** [comment]
@calanti Thanks for reporting all these issues to us!

> Specifying colors (accent and led) does not work as per documentation (e.g. #XXXXXXXX), it only works without the # symbol. (e.g. XXXXXXXX)

We will look into this one and update the our tooltips and documentation for the color format.

> A single notification will display the correct 'small icon' specified, but when multiple notifications are received (but didn't group), the 'small icon' changes to the default bell, please see attached screenshots.

It looks like your notifications were grouped (AKA stacked) in your 2nd screenshot. Did you use the Group key "newmessage" on both notifications you sent? The small icon used for the group is the one named `ic_stat_onesignal_default` per the [Android Notification Icons](https://documentation.onesignal.com/docs/customize-notification-icons#section-1-generate-icons) guide. The per notification small icon will be shown once you expand the group to see all notifications. Do note that expanding the group to view each notification as a whole was not added until Android 7.

> Setting the led color with format '#XXXXXXXX' or '#XXXXXX' will display the system default LED color. Setting this color with format 'XXXXXXXX' or 'XXXXXX' will display a white LED color only. Observed this on Xiaomi Mi Max (Android 6.0.1), the Nexus 5X does not have LED. This happens with both single and multiple notifications. The same applies to setting 'LED COLOR' on a Category, and applying that category to the message tempalate.

I'll try reproducing the LED color issue and will get back you.

> Grouping works as expected on Xiaomi Mi Max (Android 6.0.1).

Notification grouping is quite different in Android 6 and older devices. The OneSignal SDK ends up generates a single notifications as an inbox type, where in Android 7 it ends up generating most of the group view for us. Xiaomi's MIUI Android ROM skin changes the notification templates which effects their look so it is hard to say which is the issue here. Can you test with an Android 6 device or emulator with vanilla Android?

> When editing a message template and specifying the category, it will always return to default '(Created in app)'

Was able to reproduce this, we will get a fix out for this soon.

> A screenshot on this page 'https://documentation.onesignal.com/docs/customize-notification-icons' under 'To set the color on per notification bases set android_accent_color' shows you should specify the asset icon res name as 'xxxx.png', however when the file extension '.png' is supplied, it will not work and only display the default bell.

Thanks, we will get this screenshot updated

**Comment by calanti** [comment]
No problem, happy to help!

>It looks like your notifications were grouped (AKA stacked) in your 2nd screenshot. Did you use the Group key "newmessage" on both notifications you sent? The small icon used for the group is the one named ic_stat_onesignal_default per the Android Notification Icons guide. The per notification small icon will be shown once you expand the group to see all notifications. Do note that expanding the group to view each notification as a whole was not added until Android 7.

Yes the "newmessage" group key was the same for both notifications. I can confirm actually that having a different group key has 2 completely separate stacks as shown below;
![fm double notification completley seperate](https://user-images.githubusercontent.com/12170223/36886095-8090fa94-1e25-11e8-98f8-af8c94d6cffa.jpg)

So, the group key works to some extent, but what we would like to achieve is the Viber example below (3 messages were sent to viber from the same user, it simply shows the notif_count in the title and only displays the last message. It is important to us that this is how the grouping works, otherwise it just shows x amount of lines for each message.
![viber example](https://user-images.githubusercontent.com/12170223/36886306-b6c4c81a-1e26-11e8-90ba-3df3195be798.jpg)

Note GetMed is a React Native app that uses react-native-onesignal and also has the same issues, I presume the native side of this package is just the android sdk anyway?

**Comment by jkasten2** [comment]
### Colors
I looked into the accent color and LED issue and they should both be ARGB hex format without the hash `#`. Example `FFFF0000` for red. We will update our docs for both fields.
However you noted that `AARRGGBB` was not working for you for the LED color? It is possible that your device does not support apps customizing the LED color. Also note for Android 8 device the LED color has to be set in the Android Category. I just tested our LED color option and it working correctly on one of our Android 7.1.2 devices.

### Grouping
For you groping question, we simply pass the Group Key you enter on OneSignal to Android 7+ devices  to the Android `setGroup` method on the notification. Android it self then generates the summary notification as you have in your recent screenshot with your `GetMed` and `Findmate` apps. This is noted here.
https://developer.android.com/training/notify-user/group.html

The Gmail and Twitter app end up using this default behavior too. We find it provide a great users experience too as the user can see the full details of each message without the need to open your app as they can expanded and see the full message body and details of each.

### Custom Notification Generation
It looks like in the case of Viber they are just displaying one notification and then they just update the existing notification with the last message each time. If you feel this is best for you app you can do so with OneSignal by setting up our `NotificationExtenderService` with instructions below.
https://documentation.onesignal.com/docs/android-customizations#section-background-data-and-notification-overriding
Then to always replace the same notification set `overrideSettings.androidNotificationId` to the same integer value.

**Comment by calanti** [comment]
> However you noted that AARRGGBB was not working for you for the LED color? It is possible that your device does not support apps customizing the LED color. Also note for Android 8 device the LED color has to be set in the Android Category. I just tested our LED color option and it working correctly on one of our Android 7.1.2 devices.

The device in question is the Xiaomi Mi Max running Android 6.0.1, unfortunately I do not have access to other devices to test. Yes this device allows custom LED coloring, for example Viber shows a purple LED, Messenger shows a green LED. Setting the LED color for OS notifications does do something since it displayed white instead of the default blue, however I am trying to set a light red color. I have even tried blue or green, just in case red was blacklisted for being similar to low battery or something.

>We find it provide a great users experience too as the user can see the full details of each message without the need to open your app as they can expanded and see the full message body and details of each.

I understand and agree with this argument now. The problem in our case for both our apps is that message content can be quite sensitive, so we opted not to show a preview, but rather "You have a new message" or "x new messages from...", therefore it just looks incorrect having the same notification repeated several times, especially if its a message from the same user. I believe you should provide an option to toggle this different grouping logic maybe?

> It looks like in the case of Viber they are just displaying one notification and then they just update the existing notification with the last message each time. If you feel this is best for you app you can do so with OneSignal by setting up our NotificationExtenderService with instructions below.

I believed this to be the case originally, so I also tried to set the collapse key in the template, this does replace the notification, but unfortunately it does not alert the user for any further notifications, and it does not display the quantity. 

I still think Viber is grouping rather than replacing, since it shows the quantity of messages next to the Viber title., but please correct me if I am wrong. 

I will look into notification overriding anyway and try to mimic the Viber grouping.

**Comment by jkasten2** [comment]
> The device in question is the Xiaomi Mi Max running Android 6.0.1, unfortunately I do not have access to other devices to test. Yes this device allows custom LED coloring, for example Viber shows a purple LED, Messenger shows a green LED. Setting the LED color for OS notifications does do something since it displayed white instead of the default blue, however I am trying to set a light red color. I have even tried blue or green, just in case red was blacklisted for being similar to low battery or something.

Hmm, could be a special API for the Xiaomi MIUI to allow set the LED color. MIUI 8 required this to allow customizing the large icon so I suspect this is the case.

> I understand and agree with this argument now. The problem in our case for both our apps is that message content can be quite sensitive, so we opted not to show a preview, but rather "You have a new message" or "x new messages from...", therefore it just looks incorrect having the same notification repeated several times, especially if its a message from the same user. I believe you should provide an option to toggle this different grouping logic maybe?

I see, I believe setting "LOCKSCREEN VISIBILITY" to "Private" on the notification will give you what you need.

> I believed this to be the case originally, so I also tried to set the collapse key in the template, this does replace the notification, but unfortunately it does not alert the user for any further notifications, and it does not display the quantity.

If you still want the Viber like behavior you will still need to use the `NotificationExtenderService` is suggested. We designed `collapse id` on the SDK to do silent updates to the existing notifications.

> I still think Viber is grouping rather than replacing, since it shows the quantity of messages next to the Viber title., but please correct me if I am wrong.

It looks like they did the replacement behavior here, don't use the Viber myself however so just going off your screenshot. If you expand and unlock the phone do you see anything different? The number 3 you're refereeing to is most likely the [`subText`](https://developer.android.com/reference/android/support/v4/app/NotificationCompat.Builder.html#setSubText(java.lang.CharSequence)) field [noted here](https://android-developers.googleblog.com/2016/06/notifications-in-android-n.html). They probably just track it in their app and increment it.

**Comment by calanti** [comment]
>It looks like they did the replacement behavior here, don't use the Viber myself however so just going off your screenshot. If you expand and unlock the phone do you see anything different? The number 3 you're refereeing to is most likely the subText field noted here. They probably just track it in their app and increment it.

After testing further with Viber, the notification can be expanded to show all the messages, please see screenshots below. I don't believe this is possible with simple replacement?

![viber min](https://user-images.githubusercontent.com/12170223/36890353-7a0c8a36-1e38-11e8-9c0d-f116b9334889.jpg)

![viber max](https://user-images.githubusercontent.com/12170223/36890371-8c438556-1e38-11e8-9660-73c0677685ac.jpg)

**Comment by jkasten2** [comment]
> After testing further with Viber, the notification can be expanded to show all the messages, please see screenshots below. I don't believe this is possible with simple replacement?

It still seems like they are only using one notification and updating it here. They seem be setting different content for the normal notification vs the expanded notification however. The expanded notification could be a big text style or an inbox style.

**Comment by calanti** [comment]
After further testing, I was wrong about the collapse_id causing it to not vibrate/alert the user when the notification gets updated, it very much does, and since we don't show the content of the message this is perfect for us. It would be nice to track the number of messages, so I will have a play with the extender service to see what's possible.

Thanks for all your help as always.

**Comment by jkasten2** [comment]
Good to hear!, feel free to reply if any of the above was not resolved.

**Comment by anastely** [comment]
> @jkasten2 @calanti
> I'm a little bit late sorry, if anyone else has an issue with a white LED notification color, you should remove `android_led_color` if it is present in API call and **only** set It in the Android Category. It looks like the white led color is caused by the value set twice.
> 
> You should also as said before create a new category for each try on re-install the app.
> 
> I was just able to reproduce the issue.
> Tested with react-native and android sdk

I'm sorry too :) But I'm trying since yesterday to change the bell icon default notification, I followed the Docs, but still, I got the **bell** icon. do you solve this issue or have a workaround, I'm using RN too :)?
