### ISSUE TITLE
Strange http error in logcat

### ISSUE THREAD

**Issue by vaniakerer** [OneSignal/OneSignal-Android-SDK#455]
Hi!
I use Android Emulator from Android Studio, Google Pixel, Android 8
All works great, but in logs I see error: 
[osgnl.txt](https://github.com/OneSignal/OneSignal-Android-SDK/files/1775145/osgnl.txt)

That's normal?

**Comment by jkasten2** [comment]
@vaniakerer It looks like a 500 error was return from OneSignal to the device. Are you getting this consistently or just saw this once? If it was a one off note that the SDK will retry for you so updates are not lost.

**Comment by vaniakerer** [comment]
Yes, it happened just once

**Comment by jkasten2** [comment]
Thanks for the update, it must have been a short issue with the OneSignal server at that time.
