### ISSUE TITLE
JobIntentService.java sample implementation

### ISSUE THREAD

**Issue by SAFatemi** [OneSignal/OneSignal-Android-SDK#460]
Salam.
I need to use `OneSignalSDK/onesignal/src/main/java/com/onesignal/JobIntentService.java` in my project.
But don't know how to implement.
Please help..

**Comment by jkasten2** [comment]
@SAFatemi This is actually the same as `android.support.v4.app.JobIntentService` which you can find their docs for below.
https://developer.android.com/reference/android/support/v4/app/JobIntentService.html

`com.onesignal.JobIntentService` was only added directly to OneSignal incase the app developer didn't update to the Android Support Library 26.1.0 or newer. It should not be used directly in your app. It was created as public by mistake in our package and will be making it package-private soon.

Thanks.

**Comment by SAFatemi** [comment]
Thank you for your reply.
I know my problem not related with OneSignal project, but my you can help me.
I want to implement background service that work on API >=19 without termination and without using any dependency like [EverNote Android-Job](https://github.com/evernote/android-job) or [FireBase Job Dispatcher](https://github.com/firebase/firebase-jobdispatcher-android).
Do you have any solution?

**Comment by jkasten2** [comment]
@SAFatemi Sorry but this is off topic for this repo. However if you can create a stackoverflow question and reply with the link here I can try to follow up there. I recommend providing more detail around what you mean by "without termination" and why it is important not to use other dependencies.

**Comment by SAFatemi** [comment]
This is my SO question:
[https://stackoverflow.com/questions/49107140/android-oreo-keep-signalr-connected-in-background](https://stackoverflow.com/questions/49107140/android-oreo-keep-signalr-connected-in-background)
Thanks.
