### ISSUE TITLE
License change

### ISSUE THREAD

**Issue by gnunicode** [OneSignal/OneSignal-Android-SDK#464]
@jkasten2 The license of OneSignal is a nonfree license because of the restriction about only using the code for OneSignal, which prevents any apps that use the code from being introduced to F-Droid. For example, this is currently holding up Lichess from being introduced to F-Droid. Could the license please be changed back to the original MIT license?

**Comment by jkasten2** [comment]
@gnunicode The OneSignal modified MIT license states that the SDK or it's any portions of it's code can only be used with the OneSignal service.
https://github.com/OneSignal/OneSignal-Android-SDK/blob/3.8.0/LICENSE#L15-L16

Could you link to the specific F-Droid license lines that conflict with this requirement?

Thanks.

**Comment by gnunicode** [comment]
F-Droid is an app store, and the [inclusion policy] (https://f-droid.org/en/docs/Inclusion_Policy/) states that all software must be free and libre. (Free in this case is not about price but freedom to use the software - libre means the same and is to clarify so it's clear it isn't about price). The license of the SDK does not fulfil thus requirement since the restriction on only using it with OneSignal restricts the ways users may use the software.

As further evidence, the Inclusion Criteria says to use the GNU license list if unsure about a license. The GNU license list sets a precedent for this with the [original JSON license](https://www.gnu.org/licenses/license-list.html#JSON) which is an MIT license with an added clause to use the software for good not evil. Despite the seemingly benign nature of this clause, it is rejected as nonfree as it restricts uses of the software. The OneSignal clause is even more restrictive than this so it is definitely not allowed.

**Comment by jkasten2** [comment]
@gnunicode Thanks for the links. In reviewing I see that Google Play services is not allowed either.
> We cannot build apps using Google’s proprietary “play-services”. Please talk to upstream about an untainted build flavor (either using microg or removing non-free deps completely).

This SDK directly relies on the Google Play services library to register for a push token and to receive pushes from FCM / GCM so we won't be able to remove this. Almost all push notifications SDKs will use this as Android Oreo 8.0+ does not allow you to keep background services running forever to do their own connection handling to a non Google service unless the app is whitelisted manually by the user.

**Comment by gnunicode** [comment]
Ah OK, thanks for this information.
