### ISSUE TITLE
Crash on makeAndroidParamsRequest()

### ISSUE THREAD

**Issue by vinhdangd** [OneSignal/OneSignal-Android-SDK#468]
I got a crash on my app with following stacktrace and I am not sure how it happened.

| java.lang.InternalError: Thread starting during runtime shutdown
-- | --
 | at java.lang.Thread.nativeCreate(Native Method)
 | at java.lang.Thread.start(Thread.java:730)
 | at com.onesignal.OneSignalRestClient.get(OneSignalRestClient.java:74)
 | at com.onesignal.OneSignal.makeAndroidParamsRequest(OneSignal.java:755)
 | at com.onesignal.OneSignal.access$1300(OneSignal.java:79)
 | at com.onesignal.OneSignal$4$1.run(OneSignal.java:722)
 | at java.lang.Thread.run(Thread.java:761)

Please support me.

**Comment by jkasten2** [comment]
@vinhdangd Do you use `Thread.setDefaultUncaughtExceptionHandler` in your app? Issue #443 noted this might be the case.

Going to merge this with issue #287 since this is the same issue. Please feel free to follow up there. Thanks.

**Comment by vinhdangd** [comment]
Thank you for supporting.
