### ISSUE TITLE
Open Launch URL in an in-app view Ionic 3  Cordova

### ISSUE THREAD

**Issue by fjwgomez** [OneSignal/OneSignal-Android-SDK#476]
I have the next code bout when i click in the notification nothing happens. Please help
ADDITIONAL DATA KEY: enlace

var notificationOpenedCallback = function(jsonData) {
        console.log('notificationOpenedCallback: ' + JSON.stringify(jsonData));
        var openUrl = jsonData.notification.payload.additionalData.enlace;
        // Add code here to use openURL.
        // Example of using the cordova-plugin-inappbrowser plugin.
        //cordova.InAppBrowser.open(openUrl , "_system", "location=true");
        let browser = this.iab.create('openUrl','_blank',{zoom:'no',location:'no'});
        browser.show();
             
  };
  
  window["plugins"].OneSignal
        .startInit("44c83999-7684-469d-8317-7ae6c5c8a900","39384729352")
        .handleNotificationOpened(notificationOpenedCallback)
        .endInit();

**Comment by jkasten2** [comment]
@fjwgomez This repo is only for the native Android OneSignal SDK. Please open a issue on our Cordova SDK for Ionic apps below.
https://github.com/OneSignal/OneSignal-Cordova-SDK/issues

Also please include the exact additional data you are sending in the new issue as well as any logcat or xcode output you are getting.

Thanks.
