### ISSUE TITLE
Error: more than one library with package name 'com.google.android.gms.license'

### ISSUE THREAD

**Issue by gcatak** [OneSignal/OneSignal-Android-SDK#486]
Today, I opened Android Studio, then I get this error. Yesterday, there was a no problem such that!

> Error:Execution failed for task ':app:processDebugResources'.
> 
Error: more than one library with package name 'com.google.android.gms.license'

com.google.android.gms:play-services-xxx libraries was 

**11.8.0**

Onesignal library was 

'com.onesignal:OneSignal:[**3.6.2**, 3.99.99]'

Then I changed them to latest version. 

**Now App/Gradle:**

    apply plugin: 'com.android.application'
    
    android {
        compileSdkVersion 27
        buildToolsVersion "23.0.3"
    
        defaultConfig {
            applicationId "xxx.xxx.xxx"
            minSdkVersion 15
            targetSdkVersion 24
            versionCode 10
            versionName 'x.x.x'
            manifestPlaceholders = [onesignal_app_id: "xxxxx-xx-xxx",
                                    // Project number pulled from dashboard, local value is ignored.
                                    onesignal_google_project_number: "XXX"]
    
        }
        buildTypes {
            release {
                minifyEnabled false
                proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            }
        }
        productFlavors {
        }
    }
    
    repositories {
        maven { url 'https://maven.google.com' }
    }
    
    
    dependencies {
        compile fileTree(dir: 'libs', include: ['*.jar'])
        compile 'com.mcxiaoke.volley:library:1.0.18'
        compile 'com.github.chrisbanes.photoview:library:1.2.3'
        compile 'com.facebook.android:facebook-android-sdk:4.0.1'
        compile 'com.google.android.gms:play-services-ads:12.0.0'
    
        //compile 'com.google.android.gms:play-services-ads:11.2.2'
    
        compile 'com.pkmmte.view:circularimageview:1.1'
        compile 'com.melnykov:floatingactionbutton:1.3.0'
        compile 'com.squareup.okhttp:okhttp:2.5.0'
        compile 'com.github.bumptech.glide:glide:3.7.0'
        //compile 'com.android.support:appcompat-v7:26.1.0'
    
        compile 'com.android.support:appcompat-v7:27.1.0'
        compile 'com.android.support:cardview-v7:27.1.0'
        compile 'com.android.support:recyclerview-v7:27.1.0'
        compile 'com.android.support:design:27.1.0'
        compile 'com.balysv:material-ripple:1.0.2'
        compile "com.google.firebase:firebase-messaging:12.0.0"
        compile 'com.github.hotchemi:android-rate:1.0.1'
        compile 'com.onesignal:OneSignal:[3.7.1, 3.99.99]'
        compile 'com.google.android.gms:play-services-analytics:12.0.0'
    }
    
    apply plugin: 'com.google.gms.google-services'

**Project/Gradle:**

    // Top-level build file where you can add configuration options common to all sub-projects/modules.
    
    buildscript {
        repositories {
            jcenter()
        }
        dependencies {
            classpath 'com.android.tools.build:gradle:2.2.3'
    
            classpath 'com.google.gms:google-services:3.1.1'
    
          //  classpath 'com.google.gms:google-services:3.0.0'
    
            // NOTE: Do not place your application dependencies here; they belong
            // in the individual module build.gradle files
        }
    }
    
    allprojects {
        repositories {
            jcenter()
        }
    }

But I am still getting same error that stated above. How can I solve this problem? Why did this problem occur Today when there was no problem, yesterday?

**Comment by jkasten2** [comment]
@gcatak You have few things out of date which I believe is causing the issue.

#### app/build.gradle
`buildToolsVersion "23.0.3"` - I recommend updating this to the latest `'27.0.3'` version
`targetSdkVersion 24` - set to `27`

#### build.gradle
`classpath 'com.android.tools.build:gradle:2.2.3'` - update to `3.0.1`
After both `jcenter()` add `google()`
```gradle
buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
        classpath 'com.google.gms:google-services:3.1.1'
    }
}

allprojects {
    repositories {
        jcenter()
        google()
    }
}
```

**Comment by jkasten2** [comment]
@gcatak I also recommend adding the [OneSignal-Gradle-Plugin](https://github.com/OneSignal/OneSignal-Gradle-Plugin) to your project as this will ensure all your decencies are aligned to prevent build and runtime issues due to mis-match versions.

**Comment by jkasten2** [comment]
@gcatak Let us know if suggestions above worked for you. If not, please provide your updated `build.gradle` files in full and we can reopen this issue and take a look.

**Comment by davekedar** [comment]
I am facing the same issue `// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        google()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
`
please help 
![onesignal](https://user-images.githubusercontent.com/11268363/41032942-7abcc18e-69a2-11e8-85b3-648606ed3890.png)

**Comment by davekedar** [comment]
@jkasten2 plz help on this

**Comment by Rualan** [comment]
@jkasten2 did you find a solution to this?

**Comment by jkasten2** [comment]
@davekedar  @Rualan  You will need to use `maven { url "https://maven.google.com" }` instead of `google()` if your Gradle version is less than 4.0. However I recommend updating the Gradle version number in your project from the `gradle-wrapper.properties` since Gradle 4.0 has been out for a while.

Also `jcenter()` should be after `google()`, otherwise you may see the noted here:
https://stackoverflow.com/questions/49839322/errorfailed-to-resolve-android-arch-corecommon1-1-0
