### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'int android.content.Intent.getIntExtra(java.lang.String, int)' on a null object reference

### ISSUE THREAD

**Issue by asfdfdfd** [OneSignal/OneSignal-Android-SDK#493]
I have latest SDK (3.8.3). Those crashes started to appear after upgrading to 3.8.2.

[com.mirrorai.app_issue_807_crash_5AC76AA9019700011466FF3E3E4839DC_DNE_0_v2.txt](https://github.com/OneSignal/OneSignal-Android-SDK/files/1889951/com.mirrorai.app_issue_807_crash_5AC76AA9019700011466FF3E3E4839DC_DNE_0_v2.txt)
[com.mirrorai.app_issue_807_crash_5AC9958401C0000148663850BDEA06C4_DNE_0_v2.txt](https://github.com/OneSignal/OneSignal-Android-SDK/files/1889952/com.mirrorai.app_issue_807_crash_5AC9958401C0000148663850BDEA06C4_DNE_0_v2.txt)
[com.mirrorai.app_issue_807_crash_5AC77862009D000116AF5A598D552CDC_DNE_0_v2.txt](https://github.com/OneSignal/OneSignal-Android-SDK/files/1889953/com.mirrorai.app_issue_807_crash_5AC77862009D000116AF5A598D552CDC_DNE_0_v2.txt)

**Comment by jkasten2** [comment]
@asfdfdfd Thanks for the full logs, to summarize those logs; the root of the crashes of all 3 of them is the following.
```java
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Intent.getIntExtra(java.lang.String, int)' on a null object reference
       at android.support.v4.content.WakefulBroadcastReceiver.completeWakefulIntent(WakefulBroadcastReceiver.java:123)
       at com.onesignal.NotificationRestoreService.onHandleIntent(NotificationRestoreService.java:44)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

This is the same issue as #488 which has been fixed. It isn't in a release yet but it will included in one later this week.
