### ISSUE TITLE
Receiving 2 notifications with Ionic 3 and Onesignal

### ISSUE THREAD

**Issue by marcelojunin** [OneSignal/OneSignal-Android-SDK#494]
My device get the notifications perfectly when the app is opened or in background. But if I close the app, It’ll get two notifications.

    `constructor(platform: Platform, statusBar: StatusBar, splashScreen: SplashScreen, oneSignal: OneSignal) {
           platform.ready().then(() => {
          statusBar.styleDefault();
         splashScreen.hide();

      oneSignal.startInit("XXXXXXXXXXXXXXXXXXX", "XXXXXXXXXXXXXXXXXXXX")
                   .sendTag('email', 'XXXXXXXXXXXXXXXXXX')
                  .endInit();
       });
      };`

I’ve injected a Onesignal dependency as public or private and the error continue. I thought that the error happen in backend and I made a test using the onesignal website, but not work again.

look the example:
![double](https://user-images.githubusercontent.com/20614813/38633973-9c8cd362-3d97-11e8-92e4-8404bcecee63.PNG)

**Comment by jkasten2** [comment]
@marcelojunin This looks another plugin / SDK in your app is displaying a 2nd notification when it receives a notification payload. I recommend running `ionic cordova plugin list` to find other plugins and run `ionic cordova plugin rm` to remove the other push notification plugin.

For future Ionic / Cordova issues please use this repo.
https://github.com/OneSignal/OneSignal-Cordova-SDK/issues
Thanks
