### ISSUE TITLE
Problem managing sound and vibrations

### ISSUE THREAD

**Issue by marcoroche** [OneSignal/OneSignal-Android-SDK#506]
I'm using the package Cordova SDK that uses this package. When I look at the code, I think the problem comes from this package. 
I already posted an issue with no answer 
#https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/353

**Comment by jkasten2** [comment]
@marcoroche Sorry for the delay, followed up with you the thread you linked to. Closing this one in favor of your other issue.
