### ISSUE TITLE
Null point exception on com.onesignal.UserStatePushSynchronizer.addOnSessionOrCreateExtras

### ISSUE THREAD

**Issue by rameshvoltella** [OneSignal/OneSignal-Android-SDK#514]
Hi

i am getting  Null point exception on onesignal 

> com.onesignal.UserStatePushSynchronizer.addOnSessionOrCreateExtras

Am using onesignal **version 3.8.4**

Just started to get on googleplaystore crash report

Affected device :Motorola Moto E (2nd Gen) (otus_ds)
Affected 10 times today

I am showing the log below

```
java.lang.NullPointerException: 
 
  at com.onesignal.UserStatePushSynchronizer.addOnSessionOrCreateExtras (UserStatePushSynchronizer.java)
  or                     .getUserSubscribePreference (UserStatePushSynchronizer.java)
  or                     .setPermission (UserStatePushSynchronizer.java)
 
  at com.onesignal.OneSignalStateSynchronizer.getUserSubscribePreference (OneSignalStateSynchronizer.java)
 
  at com.onesignal.OSSubscriptionState.<init> (OSSubscriptionState.java)
 
  at com.onesignal.OneSignal.getCurrentSubscriptionState (OneSignal.java)
  or                     .getSavedAppId (OneSignal.java)
 
  at com.onesignal.OneSignal.access$1100 (OneSignal.java)
  or                     .access$1502 (OneSignal.java)
  or                     .access$1802 (OneSignal.java)
  or                     .onAppFocus (OneSignal.java)
 
  at com.onesignal.OneSignal$3.complete (OneSignal.java)
 
  at com.onesignal.PushRegistratorGPS$2.run (PushRegistratorGPS.java)
 
  at java.lang.Thread.run (Thread.java:761)
```

As i am using proguard this is only i can able to show .

Please ask for any help regarding this issue

**Comment by jkasten2** [comment]
@rameshvoltella Thanks for reporting, we review the `addOnSessionOrCreateExtras` method in our SDK to see if we can find any issues.

**Comment by Nightsd01** [comment]
@rameshvoltella We resolved a null pointer issue recently in 3.9.0 and based on the stack trace you provided, I believe it is a related issue.

Can you tell me if this issue is still occurring in version 3.9.0 of the OneSignal SDK? Thanks!

**Comment by Nightsd01** [comment]
(Didn't mean to close)

**Comment by Nightsd01** [comment]
Closing issue due to no response - I will assume 3.9.0 fixed this issue for you. If not, please feel free to reply and we'll be happy to reopen & investigate

**Comment by rameshvoltella** [comment]
@ Nightsd01 sorry for late replay yes its resolved
