### ISSUE TITLE
Failed push

### ISSUE THREAD

**Issue by ali-mahmoodvand** [OneSignal/OneSignal-Android-SDK#518]
I send push notification for my subscribed users and failed a lot of segment users.
Then unsubscribe my user immediately
I loss ~100K from my user in last 2 push notification .
[Before send users](http://141.105.69.159/onesignal/img/1525081142317.jpg)
[Failed count](http://141.105.69.159/onesignal/img/1525080906975.jpg)
[After send users](http://141.105.69.159/onesignal/img/1525081153524.jpg)
@gdeglin please help

**Comment by jkasten2** [comment]
@ali-mahmoodvand For an issue like this I recommend contacting OneSignal support. This can be done from the support bubble in the bottom right while signed into your account or sending an email to support@onesignal.com with your app id and notification ids included.

One thing I do recommend checking is if OneSignal is still working for you on your test devices. If you remove the OneSignal SDK from your app and don't have any other `BroadcastReceivers` in your app Google will report the device a unsubscribed as shown in your screenshot.
