### ISSUE TITLE
Update google-services

### ISSUE THREAD

**Issue by ravenfeld** [OneSignal/OneSignal-Android-SDK#528]
When update com.google.gms:google-services:3.3.1
We have the following error
com.google.gms.googleservices.GoogleServicesPlugin.versionCompare(GoogleServicesPlugin.groovy:349)
The mistake would be related to the fact that you used 12 in your SDK if I understood correctly.
The version of firebase in 15. *. * corrects me in the worry of the blow ironing in 12 would be a pity for my case

**Comment by jkasten2** [comment]
@ravenfeld Google's `com.google.gms:google-services` Gradle plugin version 3.3.0 has some bugs causing builds to fail noted in this Google issue.
https://issuetracker.google.com/issues/79122163

I haven't tested 3.3.1 but there might still be some incompatibles with their plugin. We will test this version and get back to you.

In the mean time you can use version `com.google.gms:google-services:3.2.1` or remove it from your project as it isn't required for OneSignal.

Also please include the full error you are getting if possible.

**Comment by jkasten2** [comment]
Going to merge this issue #528 since this is the same issue with `com.google.gms:google-services:3.3.X` compatibility.
