### ISSUE TITLE
Gradle Plugin com.google.gms:google-services:3.3.x Bug - java.lang.NumberFormatException: For input string: " 12"

### ISSUE THREAD

**Issue by mjalijani** [OneSignal/OneSignal-Android-SDK#534]
**Description:**

i'm importing the onesignal in mt project and im getting this error : 

> Caused by: java.lang.NumberFormatException: For input string: " 12"

i'm using the last version 

>implementation  'com.onesignal:OneSignal:3.9.0' 

and i'm also using  :

> classpath 'com.google.gms:google-services:3.3.1'

>     implementation 'com.google.android.gms:play-services-analytics:15.0.0'

>     implementation 'com.crashlytics.sdk.android:crashlytics:2.9.1'

![screenshot 51](https://user-images.githubusercontent.com/21081719/39966090-40a12534-56bb-11e8-853a-b21bf264ddf1.png)

**Comment by jkasten2** [comment]
@mjalijani `com.google.gms:google-services:3.3.1` has a bug where it is not compatible with some projects.

This is noted in this open Google Issue
https://issuetracker.google.com/u/1/issues/79230924

OneSignal does not need this Gradle plugin so you can remove it if you don't need it for anything else. Or downgrade to 3.2.1.

**Comment by jkasten2** [comment]
@mjalijani I am no long able to reproduce this issue with `com.google.gms:google-services:4.0.1` so closing this issue.
