### ISSUE TITLE
notification does not show when android phone is locked

### ISSUE THREAD

**Issue by msjt13** [OneSignal/OneSignal-Android-SDK#538]
sending notification to android device using api of one signal in php. It works fine when phone is unlocked and awake. But notification does not show when android phone is locked and screen is off. And another issue is after a long time of not using the app. Notification does not show even in unlocked and awake mode. 

Here is php code: 
` 

       public function sendNotification($title, $sub_title, $players, $value, $image_url='noti_large'){
        
         $headings = array(
            "en" => $title
        );
        
        $content = array(
            "en" => $sub_title
        );
        
        $fields = array(
            'app_id' => "APP_ID",
            'include_player_ids' => $players,
            'data' => array("value" => $value),
            'small_icon' => 'noti_small',
            'large_icon' => $image_url,
            'ios_attachments' => array(
                'id1' => $image_url,
            ),
            'contents' => $content,
            'headings'=> $headings
        );
        
        $fields = json_encode($fields);
        
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, "https://onesignal.com/api/v1/notifications");
        curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/json; charset=utf-8',
                                                   'Authorization: Basic NGEwMGZmMjItY2NkNy0xMWUzLTk5ZDUtMDAwYzI5NDBlNjJj'));
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
        curl_setopt($ch, CURLOPT_HEADER, FALSE);
        curl_setopt($ch, CURLOPT_POST, TRUE);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $fields);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE);

        $response = curl_exec($ch);
        curl_close($ch);
        
        return $response;
    }`

here is app application class
`
    
    public class ApplicationClass extends Application {

    Context context = this;

    @Override
    public void onCreate() {
        super.onCreate();

        SharedPreferences SP = getApplicationContext().getSharedPreferences(Config.session, MODE_PRIVATE);
        Boolean is_logged_in = SP.getBoolean("is_logged_in", false);

        if(is_logged_in){

            OneSignal.setSubscription(true);

            OneSignal.startInit(this)
                    .inFocusDisplaying(OneSignal.OSInFocusDisplayOption.Notification)
                    .unsubscribeWhenNotificationsAreDisabled(true)
                    .autoPromptLocation(true)
                    .setNotificationOpenedHandler(new NotificationHandler())
                    .init();
        }
    }

    private class NotificationHandler implements OneSignal.NotificationOpenedHandler{

        @Override
        public void notificationOpened(OSNotificationOpenResult result) {

            if(result != null){

                JSONObject jsonObject = result.notification.payload.additionalData;

                try{

                    String value = jsonObject.getString("value");

                    if(value != null){

                        Intent intent = new Intent(getApplicationContext(), OrderPreview.class);
                        intent.setFlags(Intent.FLAG_ACTIVITY_REORDER_TO_FRONT | Intent.FLAG_ACTIVITY_NEW_TASK);
                        intent.putExtra("order_id", value);
                        Log.d("debug", "data: "+value);
                        startActivity(intent);

                        return;
                    }

                }catch (JSONException e) {

                    e.printStackTrace();
                }
            }

            Intent intent = new Intent(getApplicationContext(), SplashScreen.class);
            startActivity(intent);
        }
    }
    }
`

**Comment by jkasten2** [comment]
@msjt13 Do you see the notification once you unlock your device? This is most likely a setting issue with the device. Can you let us know the device model and android version?

**Comment by msjt13** [comment]
no, no notification after unlocking device

**Comment by msjt13** [comment]
i just edited my question. It works when phone is locked but screen is on. It does not work when phone locked and screen is off. 

And another issue is after a long time of not using the app, notification is not shown in any mode of device.

**Comment by jkasten2** [comment]
@msjt13 This sounds like the behavior of some Xiaomi I have seen. It can happen on other devices such as Huawei. There are some other manufacturer that have issues like this and OneSignal's docs provides some details on how the disable this force close behavior.
https://documentation.onesignal.com/docs/notifications-show-successful-but-are-not-being-shown#section-the-app-is-force-stopped

**Comment by msjt13** [comment]
thank your for ur support 👍

**Comment by jkasten2** [comment]
@msjt13 It looks like this was your issue? Please let us know if not and we can re-open this issue.

**Comment by nihar89** [comment]
I have same issue with Xiomi and Huawei devices. If device are locked for long time, notification not coming. After unlock the phone, notification coming immediately. Any solution?
