### ISSUE TITLE
OneSignal in integration test with UIAutomator

### ISSUE THREAD

**Issue by eugenio-caicedo** [OneSignal/OneSignal-Android-SDK#546]
**Description:**

This is a question for the team because I do not find documentation on how to use OneSignal in integration tests. I would like to be able to test based on local notifications (if possible). Thanks.

**Environment**

OneSignal 3.8.4

**Comment by jkasten2** [comment]
@eugenio-caicedo We don't have any specific documentation on unit testing apps with OneSignal. However this SDK does have internal unit tests and shadows that might find helpful in mocking parts of OneSignal. It uses Robolectric and you can see the source below. 
https://github.com/OneSignal/OneSignal-Android-SDK/tree/master/OneSignalSDK/unittest

**Comment by eugenio-caicedo** [comment]
@jkasten2 It is not the answer I expected, but thank you very much for the help. I will try to use unit tests. But in reality, it would be an excellent SDK help for OneSignal tests in the integration test.
