### ISSUE TITLE
Onesignal Notifications are received only when app is used recently

### ISSUE THREAD

**Issue by ashisharora119** [OneSignal/OneSignal-Android-SDK#547]
**Description:**
Most of times i don't receive notifications. Its not received when i open the app and send again. I always swipe close the app.

**Environment**
onesignal : 3.8.3 , 3.8.4
compileSdkVersion 27
targetSdkVersion 27

**Steps to Reproduce Issue:**
1. Just dont use app for a day
2.Next day when i send notification from onesignal website i don't get it. System says delivered but its not shown.

**Anything else:**

I have Used NotificationExtenderService.
public class NotificationExtenderBareBones extends NotificationExtenderService

**Comment by jkasten2** [comment]
@ashisharora119 Can you include the models and Android versions of the devices you seeing this issue on? Some Xiaomi and Huawei are know to force kill apps after some time or when swiping the app away.

More details an other devices noted below
https://documentation.onesignal.com/docs/notifications-show-successful-but-are-not-being-shown#section-the-app-is-force-stopped

**Comment by ashisharora119** [comment]
Its Huawei Honor 9 Lite
So whats the solution
I don't see its happening when i directly user FCM

**Comment by jkasten2** [comment]
@ashisharora119 Do you still see the issue if you remove `NotificationExtenderService`? It is possible the issue you're seeing is related to #475. However the notification should still display in this case however Huawei's ROM behavior might be effecting this by omitting it instead.

**Comment by ashisharora119** [comment]
Yes i confirm , the issue is mainly because of NotificationExtenderService.
Once removed notifications start coming

**Comment by jkasten2** [comment]
@ashisharora119 Thanks for confirming, it looks like the `Huawei Honor 9 Lite` runs Android 8.0. Huawei normally modifies Android pretty heavily on there devices so this could explain the delayed behavior of most Android 6+ devices noted in #475 vs the no show on this device.

When you have a `NotificationExtenderService` and send a notification can you capture the logcat from the device when you send a notification? Interested to see what kind of state it reports when this happens

**Comment by jkasten2** [comment]
@ashisharora119 I am going to merge this issue with #475 since fixing this should fix this related issue. Feel free to add any more details to this issue though and we still review it when fixing #475
