### ISSUE TITLE
Notification not delivered

### ISSUE THREAD

**Issue by leonardoxh** [OneSignal/OneSignal-Android-SDK#55]
I started developed an app with the one signal push notification service, but for some reasons in come devices when the app is removed from the history (slide away) the notifications is not showed anymore, but not the one signal panel the status of the notification is delivered...

It happens on a Asus Zendfone devices.

Anyone with the same problem ?

**Comment by jkasten2** [comment]
The delivery status reports successful if the notification so sent to Google's GCM server without an error. It isn't confirmation of delivery to the device itself.

It is possible that swiping away your app from the Recent Apps list is putting your app into a "force stopped" state. This isn't a normal Android behavior but Asus may have modified Android for this device to do this.

See if there is a setting like there is for Huawei or Xiaomi devices noted in our [3. Notifications show successful but are not being shown](https://documentation.onesignal.com/docs/common-problems#3-notifications-show-successful-but-are-not-being-) section. I would check that your device also has the latest Android update installed as well.

Thanks.

**Comment by leonardoxh** [comment]
Thanks for your reply.

Really when I slide away the notification the app services are not running anymore, but another apps like What's App stay running even if we slide it away from recents, there is a way to continue running the app on this case?

**Comment by jkasten2** [comment]
@leonardoxh It could be that Asus made an exception for popular apps. Can you check the `logcat` after swipe your app away and when you send a few notifications after this?

Let us know if you're seeing the kind of entries shown in this example log.
https://gist.github.com/jkasten2/fb83b1df754cf26df378

**Comment by leonardoxh** [comment]
Yeah,

The app really closes, and there is nothing what we can do, on most of the phones the app still working well.

Thanks again for your comment :+1:
