### ISSUE TITLE
Add option to disable tracking of installed applications

### ISSUE THREAD

**Issue by rostopira** [OneSignal/OneSignal-Android-SDK#550]
**Description:**

According to Google's [Privacy, Security, and Deception](https://play.google.com/about/privacy-security-deception/personal-sensitive/), section "Personal and Sensitive Information", all apps that are using OneSignal SDK violate policies, unless they show proper consent and specify collection list of installed apps in their Privacy Policy. It's even stated in list of common violations:

> Here are some examples of common violations:
> An app that doesn’t treat a user’s inventory of installed apps as personal or sensitive user data and doesn’t comply with the Privacy Policy, Secure Transmission, and Prominent Disclosure requirements.

**Anything else:**

Installed packages tracking code starts here: https://github.com/OneSignal/OneSignal-Android-SDK/blob/3a4d4353b1d803852e3b9986b828c9b823801ce5/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java#L1196

**Comment by gdeglin** [comment]
Hi. Thanks for the report.

This is part of a feature that allows to to target notifications based on the category of apps your users tend to use. The feature is implemented by reviewing a limited list of popular applications, and does not send the whole list of installed apps to OneSignal or any other parties.

![screenshot 2018-05-22 17 25 15](https://user-images.githubusercontent.com/4891/40397009-2786256e-5de5-11e8-9c9a-9fce5cdb49d6.png)

If you wish to disable this, you can do so by commenting out the following lines from OneSignal.java:
```
try {
         List<PackageInfo> packList = packageManager.getInstalledPackages(0);
         JSONArray pkgs = new JSONArray();
         MessageDigest md = MessageDigest.getInstance("SHA-256");
         for (int i = 0; i < packList.size(); i++) {
            md.update(packList.get(i).packageName.getBytes());
            String pck = Base64.encodeToString(md.digest(), Base64.NO_WRAP);
            if (awl.has(pck))
               pkgs.put(pck);
         }
         deviceInfo.put("pkgs", pkgs);
      } catch (Throwable t) {}
```
