### ISSUE TITLE
When try to make GDPR Changes in my app device not registering to OneSignal Dashboard 

### ISSUE THREAD

**Issue by gsksarath** [OneSignal/OneSignal-Android-SDK#551]
For more details check the below link
https://stackoverflow.com/questions/50481038/onesignal-gdpr-changes-not-registering-the-device

**Comment by gsksarath** [comment]
Got Reply From OneSignal Support Team

These are the below steps need to follow for OneSignal GDPR

Step 1 - 

You will need to initialize OneSignal first, then call these methods.

Step 2 - 

Just call

OneSignal.setRequiresUserPrivacyConsent(true);
Then when you prompt for consent and the user says OK, you can use this method to mark the answer and initialize OneSignal:

Step 3 - 

public void onUserTappedProvidePrivacyConsent(View v) {
  //will initialize the OneSignal SDK and enable push notifications
  OneSignal.provideUserConsent(true);
}

**Comment by jkasten2** [comment]
@gsksarath `setRequiresUserPrivacyConsent(true)` must be called **before** OneSignal is initialized. Example:
```java
public void onCreate() {
    super.onCreate();
    // Prevents OneSignal from sending any data until `provideUserConsent` is called.
    OneSignal.setRequiresUserPrivacyConsent(true);

    // OneSignal Initialization
    OneSignal.startInit(this)
        .inFocusDisplaying(OneSignal.OSInFocusDisplayOption.Notification)
        .unsubscribeWhenNotificationsAreDisabled(true)
        .init();
}

public void onUserTappedProvidePrivacyConsent(View v) {
    // will initialize the OneSignal SDK and enable push notifications
    OneSignal.provideUserConsent(true);
}
```

https://documentation.onesignal.com/docs/android-native-sdk#section--setrequiresuserprivacyconsent-
