### ISSUE TITLE
Android 8.0 Outdated Android Support Libraries

### ISSUE THREAD

**Issue by Ericky14** [OneSignal/OneSignal-Android-SDK#553]
**Description:**

When running this plugin with nativescript on android 8.0, push notifications don't come through, and on the onesignal dashboard, I see a warning saying "Outdated android support libraries"
What libraries do I need for this plugin and what version?

**Environment**

1. What version of the Android SDK are you using? 26
2. How did you add the SDK to your project (eg. maven) nativescript

**Steps to Reproduce Issue:**
  Example:

  1. Add the OneSignal SDK to your project
  2. Place your App ID in the application's gradle file
  3. Attempt to receive a push notification

Steps:
1. Run on android 8.0 with targetSdkVersion=26

**Comment by jkasten2** [comment]
@Ericky14 The Android Support library version should match `targetSdkVersion`. So in this case you should also have 26. The nativescript SDK pulls in the latest Google Play services that should include version 26 fo the Android Support library. One thing I recommend checking is that your Android SDK is up to date on your system. 

The issue could be however that the Google Play services dependencies isn't including all the parts of the Android Support library that OneSignal needs. I recommend trying out the changes in this https://github.com/roblav96/nativescript-onesignal/pull/36 PR and comment on the PR if it solves your issue.

**Comment by Ericky14** [comment]
@jkasten2 
I am running into this error when I add onesignal-gradle-plugin just like you mentioned in that PR, but using android studio to build the project this time.
```
Android dependency 'com.android.support:design' has different version for the compile (27.1.0) and runtime (27.0.1) classpath. You should manually set the same version via DependencyResolution
```

How do I resolve these conflicts?

**Comment by jkasten2** [comment]
@Ericky14 Let's follow up on this error your new ticket  that better fits this error
https://github.com/OneSignal/OneSignal-Gradle-Plugin/issues/39

**Comment by trungnguyennam** [comment]
I have similar issue with Eclipse version. How can i resolve this issue?
