### ISSUE TITLE
Confusing documentation on `to` and `from` fields  in `OSSubscriptionStateChanges`

### ISSUE THREAD

**Issue by runningcode** [OneSignal/OneSignal-Android-SDK#559]
It's a bit confusing what the `to` and `from` fields in the `OSSubscriptionStateChanges` object mean. The documentation adds to the confusion.

![was-now-from-to](https://user-images.githubusercontent.com/332597/40848137-98ee78ba-65be-11e8-8fe9-90fabe76ec23.png)

**Comment by fatsjohonimahnn** [comment]
We fixed this in our docs, thanks for pointing it out: https://documentation.onesignal.com/docs/android-native-sdk#section--ossubscriptionstatechanges-

`getFrom()` is what the subscription state was in the past
`getTo()` is what the subscription state is currently
