### ISSUE TITLE
Custom notification sound not working [Android 8.1.0]

### ISSUE THREAD

**Issue by Hardkaise** [OneSignal/OneSignal-Android-SDK#560]
**Description:**
I am developping application with custom sound, I had tested my app in several phone.
It's working perfectly on Samsung Galaxy S6 (android 7.0) but not in One Plus 6 (oreo 8.1.0).
The notification appears but the sound played is always the system sound notification.

**Environment**
I'm using targetSdkVersion 27 with minSdkVersion 19 and compileSdkVersion 27
My version of one signal is 3.9.1

Please, need some help

**Comment by jkasten2** [comment]
@Hardkaise Android Oreo (8.0) introduced Notification Categories / Channels. They must be used if you want to customize priority, sound, LED Color, Badges, Lockscreen visibility or vibration. More details on the requirements, how to setup, and using them below.
https://documentation.onesignal.com/docs/android-notification-categories

**Comment by An3ramirez** [comment]
muchas gracias amigo llevaba rato luchando con este problema.

**Comment by dameunbite** [comment]
For anyone that is trying to play a custom notification sound in a react native app. I spent a lot of time figuring this, when is a documentation error.

The documentation says that you have to add the sound resource in: /android/app/res/raw when is actually in: res/raw

<img width="898" alt="Screen Shot 2020-07-20 at 11 34 08 PM" src="https://user-images.githubusercontent.com/48269003/88010012-e49a6f00-cae1-11ea-8be3-0eb50ccb3982.png">

I think the react native onesingal custom sound notification is out dated
