### ISSUE TITLE
Plugin not applied

### ISSUE THREAD

**Issue by charchit28** [OneSignal/OneSignal-Android-SDK#562]
Failed to apply plugin [id 'com.onesignal.androidsdk.onesignal-gradle-plugin']

Gradle sync failed: Failed to apply plugin [id 'com.onesignal.androidsdk.onesignal-gradle-plugin']
                Consult IDE log for more details (Help | Show Log) (277ms)

**Comment by jkasten2** [comment]
@charchit28 Can you get the full error? Please fully fill out the ticket template below so we can look into reproducing the issue.
https://github.com/OneSignal/OneSignal-Gradle-Plugin/issues/new
