### ISSUE TITLE
Tags are not sent before calling OneSignal.provideUserConsent(false)

### ISSUE THREAD

**Issue by CyxouD** [OneSignal/OneSignal-Android-SDK#565]
**Description:**

Using new consent mechanism I want to deactivate SDK in some cases (i.e. logging out) by calling `OneSignal.provideUserConsent(false)`. Before deactivating, I send tags, but tags are not sent, which is tested by looking in OneSignal dashboard. In my case I remove previously added tag, but it doesn't work for changing too. On the other side, If I remove `OneSignal.provideUserConsent(false)` line, then tag is removed/changed successfully

**Environment**

Android version: 5.1
OneSignal version: 3.9.1, installed with Gradle

**Steps to Reproduce Issue:**

1. Add the OneSignal SDK to your project
2. Place your App ID in the application's gradle file
3. Place
```
 OneSignal.setRequiresUserPrivacyConsent(true);
 OneSignal.startInit(this).init();
```
 in your Application's class onCreate()
4. In some point of the app, when consent was received, call provideUserConsent(true) and send tag
 ```
OneSignal.provideUserConsent(true);
OneSignal.sendTag("someTag", "someValue");
```
5. Make sure that tag with "someTag" as a name and "someValue" as a value displayed in OneSignal Dashboard
6. In some point of the app, when consent was revoked, change tag which you sent previously
and call provideUserConsent(false)
```
OneSignal.sendTag("someTag", "");
OneSignal.provideUserConsent(false);
```
7. Make sure that previously sent tag is not changed in OneSignal Dashboard

Provide you with a sample project and an app where this behavior can be reproduced
[OneSignalTagTest.zip](https://github.com/OneSignal/OneSignal-Android-SDK/files/2083624/OneSignalTagTest.zip)
[app-debug.apk.zip](https://github.com/OneSignal/OneSignal-Android-SDK/files/2083633/app-debug.apk.zip)
![image 2018-06-08 11 51 36](https://user-images.githubusercontent.com/17162008/41148717-4d8430aa-6b12-11e8-8eb9-f054989de9f8.jpg)

**Comment by jkasten2** [comment]
@CyxouD Sorry for the delay, thanks for providing all these details. The issue is due to the SDK stoping all actions as soon as `OneSignal.provideUserConsent(false);` is called. However since tag changes are delayed to batch network requires more efficiently it also cancels this which means the network call is never made to delete the tag in your case.

We'll make a change to ensure any pending updates that were made before `provideUserConsent(false)` are still sent to OneSignal.

**Comment by rgomezp** [comment]
Follow in #777
