### ISSUE TITLE
Unable to cancel a summary notification

### ISSUE THREAD

**Issue by DenisBronx** [OneSignal/OneSignal-Android-SDK#57]
Hi, i'm using 2.4.1 SDK and i'm not able to cancel the notification by the id that returns from OSNotificationDisplayedResult.

From the debug i can see that 2 notificationId are generated (one for the summary notification and the other for individual notification). In the OSNotificationDisplayedResult object that returns i have only the notificationId used for individual notifications and if i try to cancel the notification from that id it doesn't work, but if i try to cancel it using the notificationId of the summary notification that i previously seen in the debug it works.

**Comment by jkasten2** [comment]
@DenisBronx The `NotificationExtenderService` does not have built in support for grouped notifications at this time. You can create your own summary notification instead of letting the OneSignal SDK displaying the notification

You can instead modify our SDK by adding a new filed to `OSNotificationDisplayedResult` and set it in the `GenerateNotification` class.

**Comment by jkasten2** [comment]
The following would need to be updated to support getting both the summary and individual notification displayed. Some details on what will need to be modified to support this.

Add new field to `OSNotificationDisplayedResult`
https://github.com/OneSignal/OneSignal-Android-SDK/blob/3.4.3/OneSignalSDK/onesignal/src/main/java/com/onesignal/OSNotificationDisplayedResult.java#L31

Change `NotificationBundleProcessor.Process` to create and return OSNotificationDisplayedResult with both ids set.
https://github.com/OneSignal/OneSignal-Android-SDK/blob/3.4.3/OneSignalSDK/onesignal/src/main/java/com/onesignal/NotificationBundleProcessor.java#L77

Usage of the above would have to change here.
https://github.com/OneSignal/OneSignal-Android-SDK/blob/3.4.3/OneSignalSDK/onesignal/src/main/java/com/onesignal/NotificationExtenderService.java#L94

**Comment by jkasten2** [comment]
@DenisBronx Just quick update, we have made some improvements to our SDK in 3.4.4 which will auto dismiss the summary notification after all it's child notifications are removed.

I'll leave this open however until we add a way to cancel a specific group key.

**Comment by jkasten2** [comment]
@DenisBronx Notifications can now cleared by their group key with the `cancelGroupedNotifications` method now part of the 3.5.6 release.
