### ISSUE TITLE
[Question] Identify app users combining FCM and OneSignal

### ISSUE THREAD

**Issue by jasperrietrae** [OneSignal/OneSignal-Android-SDK#576]
Hi.

Sorry for asking here, I couldn't find it anywhere else!

I have an app for a client where we only save the app users by storing their unique device id and adding their FCM push key to this in the database. The client now asks us if we can integrate OneSignal so that they can send segment push notifications to multiple users within a group/tag at the same time (https://documentation.onesignal.com/docs/segmentation#section-built-in-segments).

What are the options for this?

**Comment by jkasten2** [comment]
@jasperrietrae You can use the the [Add a Device](https://documentation.onesignal.com/reference#add-a-device) REST API to import devices into OneSignal. You can set tags so you can later create any filters or segments you need.

However for Android notifications to show on the device from OneSignal you must use this SDK in your app. The format OneSignal sends to the device is not displayed by the Firebase SDK.

**Comment by jasperrietrae** [comment]
@jkasten2 Thanks so much for the quick and helpful response!

So if I understood correctly I need to build it so that each user is imported to the OneSignal API. In this list of users we can send the push notification segments according to the documentation I linked. Correct?

**Comment by jkasten2** [comment]
@jasperrietrae Correct, you can import and your custom keys/values as tags with the REST API. Then you can use the segment features you linked too. The import is optional, the SDK still must be added to your app for the notification to be displayed.

**Comment by jasperrietrae** [comment]
@jkasten2 and then we also send the FCM/APS push token to OneSignal so that OneSignal is still pushing it that way, but it can be segmented with OneSignal's API. Correct?

**Comment by jkasten2** [comment]
Correct.

Note for iOS you must add the device to OneSignal as device_type 0 and use it's APNs token not the FCM token.
