### ISSUE TITLE
Can we set the option "banner" (in notifications settings) as default?

### ISSUE THREAD

**Issue by roysG** [OneSignal/OneSignal-Android-SDK#581]

**Comment by fatsjohonimahnn** [comment]
Banner notifications only work on android 5 - 7.

For android 8+ they introduced Categories to make customizations to notifications and add this functionality there.

Please see our docs on Android Categories here: https://documentation.onesignal.com/docs/android-notification-categories

To show banner notifications on android, you can set the priority to High on the notification.

You can send notifications with high priority through the Dashboard > New Message > Options > Priority 

OR

Through the API using the priority parameter and passing the integer value 10 for high or leave it blank for normal which is default. See our API delivery section docs for more.

**Comment by roysG** [comment]
Yes, this is exactly what i did , but i required in addition go manually to my app settings and enable the option "banner" in notification settings and chnage it to active.

Is there any way to enable "banner" option by default without do it manually?

**Comment by jkasten2** [comment]
@roysG You can send a notification from the OneSignal dashboard or REST API with high priority as Jon noted above without needing to change any device settings.

**Comment by roysG** [comment]
Yes, you right and this is exactly what i did, but unless i will not manually allow the banner option in notification settings of my app, the notification will not bump me on top, even when i send the notification as the high priority.

Tested in android v7 hawueii p10 plus.

**Comment by fatsjohonimahnn** [comment]
Please contact OneSignal support through our website with your appID, notification ID and the playerID of the device so we can look into this deeper.

Will close this for now since we need to investigate the account deeper. Thanks

**Comment by cg-adam** [comment]
I have the same issue, notifications are only in background and never show on top.

**Comment by jkasten2** [comment]
@cg-adam Make sure you have created a Notification Category / Channel with High Priority and use it on your notification. See the following guide and setting up and using them with OneSignal
https://documentation.onesignal.com/docs/android-notification-categories
