### ISSUE TITLE
Image failed to display in scheduled push notifications

### ISSUE THREAD

**Issue by bharatbondu** [OneSignal/OneSignal-Android-SDK#582]
**Description:**

Scheduled push notifications failed to display the big image. I tried adding image link, uploaded file in filestack and google drive. nothing worked. But when I send a push with image immediately it is displaying.

**Environment**

1. I'm using android sdk 25.
2. Built the app using phonegap version 7.0.1
3. Installed the android using $ cordova platform add android
4. Added the one signal SDK manually by downloading it from github.

**Steps to Reproduce Issue:**

1. Add OneSignal SDK manually to the project
2. Add big picture to the notification using link/upload
2. Schedule a push notification 
3. Send push

**Comment by jkasten2** [comment]
@bharatbondu If you have a number of notifications in the notification shade on the device it won't automatically expand to show the big image. You will need to swipe down with 2 fingers to expanded it.

As a test you can try setting the large icon to the same URL to make sure your URL is correct.

**Comment by bharatbondu** [comment]
@jkasten2 It's not about the multiple notifications in the notification shade. I cleared all other notifications and checked many times. URLs are also correct!

It works when I'm sending push notifications immediately. Only when I schedule a notification it doesn't work.

**Comment by jkasten2** [comment]
@bharatbondu Which scheduling options are you using? I recommend also contacting OneSignal support linking them this thread. They can look at your account to verify everything looks correct on your specific notifications.

**Comment by bharatbondu** [comment]
@jkasten2  I'm using 'Begin schedule at particular time' option. 
Sure, thanks for the suggestion.

**Comment by jkasten2** [comment]
@bharatbondu I'll let them follow up with you but feel free to reply if you have any more details.

**Comment by bharatbondu** [comment]
thanks, @jkasten2. I already contacted them & shared required details.
Waiting for their response.

**Comment by fatsjohonimahnn** [comment]
We responded to your ticket on our support channel, will close this and continue the conversation through our support channel.
