### ISSUE TITLE
In amazon kindle notifications are opening in browser

### ISSUE THREAD

**Issue by vivekb91** [OneSignal/OneSignal-Android-SDK#583]
**Description:**
When tapping on the notification in amazon kindle device, it opens in browser instead of app.

**Environment**
Onesignal SDK version 3.9.1
Android SDK version is 27.0.1

**Steps to Reproduce Issue:**
1. Send the notification to any kindle device.
2. Tap on the notification

**Comment by jkasten2** [comment]
@vivekb91 Are you sending the notification though the OneSignal dashboard or through the REST API? Can you ensure the Launch URL or the `url` on the REST API isn't set to any value including a blank string? I recommend messaging OneSignal support with your notification Id so they can check this on their end.

**Comment by vivekb91** [comment]
@jkasten2 we are sending notification from Onesignal dashboard.

**Comment by jkasten2** [comment]
@vivekb91 I recommend contacting OneSignal support for this issue since they can look at your specific notifications on their end.

**Comment by vivekb91** [comment]
@jkasten2 thank you.

**Comment by EmilAlipiev** [comment]
I am having the same problem. have you found a solution for this?

**Comment by sercangedik** [comment]
We are facing the same problem, is there any workaround we can apply for now before you fix it?

**Comment by EmilAlipiev** [comment]
@sercangedik I asked their support over the portal but they didnt give me any answer since a week. It looks like that they dont even know themselves what the problem is

**Comment by vivekb91** [comment]
@EmilAlipiev @sercangedik when we contacted them they told us to set a launch URL manually or try simply adding test://test. It is working for us. No other fixes found yet.

**Comment by jkasten2** [comment]
@vivekb91 @EmilAlipiev @sercangedik There was a fixed deployed on OneSignal's backend that should fix sending a blank URL param when doing so though the OneSignal dashboard.
