### ISSUE TITLE
Custom Sound not working!

### ISSUE THREAD

**Issue by Kamoba** [OneSignal/OneSignal-Android-SDK#586]
**Description:**
Hi, Even based on the advice given on [this post](https://github.com/OneSignal/OneSignal-Android-SDK/issues/272) I still can't play a different sound when receiving the notification.
based on the documentation I modified my apk, created the res/raw folder in my apk file and put it my audio file (Alarm_Survivor.wav).

**Environment**
I use an html Android app (Thunkable).

I receive the notification with the following request (default sound):
```
{
  "app_id": "xxxxxxxxxxxxmyAppIDxxxxxxxxxxxxx",
  "included_segments": ["Active Users"],
  "android_sound": "Alarm_Survivor",
  "large_icon":"iconApp.png",
  "data": {"foo": "bar"},
  "contents": {"en": "Hello your alarm triggled!"}
}
```
I tryed different extension file .mp3 and .ogg, tryed rename audio file and tryed to put it on assets folder but nothing.

**Comment by rostopira** [comment]
@Kamoba if you have shrinkResources enabled in build.gradle, then you should explicitly tell shrinker to keep that file

**Comment by jkasten2** [comment]
@Kamoba Android only supports lower case files in the `res` directory, the file name must contain only lowercase a-z, 0-9, or underscore. Normally Android Studio / Gradle will throw a build error when the file name does not match this format so double check the directory as well. Your sound file should be located at `app/src/main/res/raw/alarm_survivor.wav`.

If your app is targeting Android API 26 or higher then you will also need to setup a Category / Channel to support custom sounds on Android Oreo 8 and newer. 
https://documentation.onesignal.com/docs/categories

**Comment by Kamoba** [comment]
Woohoo it's working! Thanks a lot gays!

**Comment by sonicwong** [comment]
@rostopira 
May you tell me how to make shrinker to keep that file?
I am using ionic 3.x

**Comment by rostopira** [comment]
@sonicwong I've never worked with ionic, but in native sdk you should add file `keep.xml` in `res/xml` folder with following content

```
<?xml version="1.0" encoding="utf-8"?>
<resources
    xmlns:tools="http://schemas.android.com/tools"
  
  tools:keep="@raw/your_sound_file,@drawable/maybe_some_picture"/>
```
This will tell shrinker to keep specific resources.

**Comment by sonicwong** [comment]
@kossoko
just add below resource line:

'''<platform name="android">
       <resource-file src="resources/se/my.mp3" target="res/raw/my.mp3" />
</platform>'''

**Comment by KOSSOKO** [comment]
@sonicwong thanks for you answer.
I added 
`<resource-file src="platforms/android/res/raw/onesignal_default_sound.mp3" target="platforms/android/res/raw/onesignal_default_sound.mp3" />`
but still have no sound. I use Android 7.

**Comment by sonicwong** [comment]
@kossoko, what cordova android version that u are using? try to downgrade to 6.3.

**Comment by nijesh17** [comment]
Custom sound not working in Android Oreo 8 and newer, I have already created Category / Channel, here is my code

`const notification: IOneSignalPushNotification = {
      include_player_ids: [this._userProfile.signalId],
      data: {
        redirect: "location",
      },
      contents: { en: 'This is test content' },
      large_icon: "https://s3.amazonaws.com/be-my-buddy-images/Logo_B%404x.png",
      priority: 4,
      ios_sound: 'sound8.wav',
      android_sound: 'sound8',
      android_channel_id: 'xxxxxxx-4462-xxxx-884a-xxxxxxxxxx'
    };`
In network http request all the given data was send successfully but when I check OneSignal delivery report the **sound was default** 
<img width="1409" alt="Screenshot 2019-04-29 at 3 06 08 PM" src="https://user-images.githubusercontent.com/2499917/56887936-773f9000-6a90-11e9-9d64-fba75273eefe.png">

**Comment by rostopira** [comment]
@nijesh17 Custom sound on Oreo must be linked to `NotificationChannel`
Then in onesignal console you must set notification channel and custom sound

**Comment by nijesh17** [comment]
@rostopira Can you explain bit more

**Comment by KOSSOKO** [comment]
@rostopira in my case, I have android 7, but can't be able to have custom sound.

**Comment by rostopira** [comment]
@KOSSOKO yeah, notification channels was introduced in nougat
@nijesh17 sorry, I don't have time for that

OneSignal team should add detailed instructions for that, I would suggest you to create separate issue for that

**Comment by KOSSOKO** [comment]
@rostopira ok, I understand now why It doesnt work. Thanks a lot.

**Comment by ankitmeddo** [comment]
Those who has shrinkResources true in app/build.gradle.. Just remove this line and it will work.

**Comment by wellbranding** [comment]
I don't get the sound even after shrinking resources. Here is my issue:
https://github.com/OneSignal/OneSignal-Android-SDK/issues/1072
