### ISSUE TITLE
NullPointerException: Attempt to read from field 'org.json.JSONObject com.onesignal.UserState.syncValues' on a null object reference 

### ISSUE THREAD

**Issue by alaa-alshaikh** [OneSignal/OneSignal-Android-SDK#612]
I'm Updating my build to the latest OneSignal SDK, got this error, 
 fabric.io :

Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'org.json.JSONObject com.onesignal.UserState.syncValues' on a null object reference
       at com.onesignal.UserStatePushSynchronizer$1.onSuccess(UserStatePushSynchronizer.java:34)
       at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:208)
       at java.lang.Thread.run(Thread.java:762)

I can see that it been covered and solved [here](https://github.com/OneSignal/OneSignal-Android-SDK/issues/503) but its not working in the latest SDK

My code : 
  OneSignal.startInit(this)
                .setNotificationOpenedHandler(new OneSignalNotificationOpenedHandler(this))
                .inFocusDisplaying(OneSignal.OSInFocusDisplayOption.Notification)
                .unsubscribeWhenNotificationsAreDisabled(true)
                .init();

gradle  : 
    compile 'com.onesignal:OneSignal:[3.9.1, 3.99.99]'

again its working  when in the first install BUT whats its not working is when i tried to update the exiting apps in the store to the latest OneSignal

**Comment by jkasten2** [comment]
@alaa-alshaikh Thanks for reporting. It looks like this might be a race condition with the OneSignal initializing while on another thread `OneSignal.getTags()` was called.  Can you share the code how your calling `OneSignal.getTags()`?

**Comment by alaa-alshaikh** [comment]
Hi @jkasten2, Thanks for answering! the problem is i don't call OneSignal.getTags() all, all i'm doing is initializing the OneSignal and passing the Notification Opened Handler 

```
 private void initOneSignal() {
        OneSignal.startInit(this)
                .inFocusDisplaying(OneSignal.OSInFocusDisplayOption.Notification)
                .setNotificationOpenedHandler(new OneSignalNotificationOpenedHandler(this))
                .unsubscribeWhenNotificationsAreDisabled(true)
                .init();
    }
```

```
public class OneSignalNotificationOpenedHandler implements OneSignal.NotificationOpenedHandler {

    private static final String KEY_URI = "uri";
    private final Context context;

    public OneSignalNotificationOpenedHandler(final Context context) {
        this.context = context;
    }

    @Override
    public void notificationOpened(final OSNotificationOpenResult result) {
        String launchUrl = "";
        try {
            launchUrl = result.notification.payload.additionalData.getString(KEY_URI);
        } catch (Exception e) {
            // ignore.
        }
        context.startActivity(getIntent(launchUrl));
    }

    private Intent getIntent(final String launchUrl) {
        final Intent launchIntent;
        if (!TextUtils.isEmpty(launchUrl)) {
            launchIntent = new Intent(context, WebViewActivity.class);
            launchIntent.putExtra(WebViewActivity.LINK_URL, launchUrl);
            launchIntent.putExtra(WebViewActivity.IS_PUSH_NOTIFICATION, true);
        } else {
            launchIntent = new Intent(context, SplashActivity.class);
            launchIntent.putExtra(SplashActivity.IS_PUSH_NOTIFICATION, true);
        }

        launchIntent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        return launchIntent;
    }

```

Thats how I'm using the OneSignal !

**Comment by jkasten2** [comment]
The following from your logcat points to `getTags` returning from a network response from onesignal.com.
```java
at com.onesignal.UserStatePushSynchronizer$1.onSuccess(UserStatePushSynchronizer.java:34)
```
This point to this line in the source of this SDK.
https://github.com/OneSignal/OneSignal-Android-SDK/blob/3.10.1/OneSignalSDK/onesignal/src/main/java/com/onesignal/UserStatePushSynchronizer.java#L34

Can you double check where your calling `getTags` again? Could this have only been included in a older version of your app? Or possible you are using OneSignal in some sub project of your main project?

**Comment by jkasten2** [comment]
@alaa-alshaikh Are you still seeing this crash? If so can you get in touch with OneSignal support. I think it would be best to make sure that your on the latest version as this might have been a crash from an older version since the line numbers don't seem to line up in the stack trace.
