### ISSUE TITLE
Behind Proxy App

### ISSUE THREAD

**Issue by vahid263** [OneSignal/OneSignal-Android-SDK#614]
I am using Onesignal SDK in my android mobile app and myapp is behind a proxy server, how can I change the http://onesignal.com URL in my SDK?

**Comment by jkasten2** [comment]
@vahid263 The URL for all calls the SDK makes can be changed below.
https://github.com/OneSignal/OneSignal-Android-SDK/blob/master/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignalRestClient.java#L44

We do not plan to make this configurable so you will need to build and use a local copy of this SDK. Thanks.

**Comment by vahid263** [comment]
I changed this line and build a Jar file and use in my project but I have the following error:
`09-14 17:24:00.866 12761-13010/com.onesigtest E/dalvikvm: Could not find class 'android.app.job.JobInfo$Builder', referenced from method com.onesignal.NotificationRestorer.startDelayedRestoreTaskFromReceiver
09-14 17:24:02.081 12761-13114/com.onesigtest E/dalvikvm: Could not find class 'android.app.NotificationChannel', referenced from method com.onesignal.NotificationChannelManager.createChannel
09-14 17:24:02.081 12761-13114/com.onesigtest E/dalvikvm: Could not find class 'android.app.NotificationChannel', referenced from method com.onesignal.NotificationChannelManager.createDefaultChannel
09-14 17:24:02.081 12761-13114/com.onesigtest E/dalvikvm: Could not find class 'android.app.NotificationChannel', referenced from method com.onesignal.NotificationChannelManager.createRestoreChannel
09-14 17:24:30.896 12761-13072/com.onesigtest E/dalvikvm: Could not find class 'android.app.job.JobScheduler', referenced from method com.onesignal.OneSignalSyncServiceUtils.cancelSyncTask
09-14 17:24:30.901 12761-13072/com.onesigtest E/dalvikvm: Could not find class 'android.app.job.JobInfo$Builder', referenced from method com.onesignal.OneSignalSyncServiceUtils.scheduleSyncServiceAsJob
`

**Comment by jkasten2** [comment]
These ` E/dalvikvm: Could not find class ` errors are expected in the logcat for Android devices before 5.0. It is just letting you know it could not find these classes as your app loads into memory. It does not cause any issues in your app as the calls are guarded with runtime checks so they won't create any issues.
