### ISSUE TITLE
Android Pie: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/location/LocationListener

### ISSUE THREAD

**Issue by ShabanKamell** [OneSignal/OneSignal-Android-SDK#615]
Due to restrictions on non-SDK interfaces https://developer.android.com/about/versions/pie/restrictions-non-sdk-interfaces
i get this exception:
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/location/LocationListener

**Comment by jkasten2** [comment]
@ShabanKamell Can you share the full error message? It is most a warning only showing in the logcat as this SDK proving geotagging for push notifications. `com.google.android.gms.location.LocationListener` is part of the Google Play services library. You can ignore this warning if you don't use this feature.

This SDK does not use the NDK and only uses Java. Nor does it access any hidden Android OS API.
