### ISSUE TITLE
how to recompile sdk ?

### ISSUE THREAD

**Issue by vahid263** [OneSignal/OneSignal-Android-SDK#621]
I want to know how can I recompile sdk and use the output Jar file?
please help me.

**Comment by jkasten2** [comment]
@vahid263 You can open the following project folder in Android Studio and build the `onesignal` project.
https://github.com/OneSignal/OneSignal-Android-SDK/tree/master/OneSignalSDK

Or run `./gradlew onesignal:build` from the terminal.

This will create `.aar` files under `onesignal/build/outputs/aar/`. You can extract `classes.jar` from it however it is recommend to use the `.aar` instead to as this will add needed `AndroidManifest.xml` for you, as well as proguard settings.

**Comment by vahid263** [comment]
@jkasten2 
when I run ./gradlew onesignal:build I got the following Error in my Terminal


* What went wrong:
Execution failed for task ':onesignal:lint'.
> Lint found errors in the project; aborting build.
  
  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...
  
  Errors found:
  
  /Users/apple/Desktop/mine/OneSigSDK_NEW/OneSignal-Android-SDK/OneSignalSDK/onesignal/src/main/java/com/onesignal/TrackGooglePurchase.java:88: Error: Must be one of: PackageManager.PERMISSION_GRANTED, PackageManager.PERMISSION_DENIED [WrongConstant]
           iapEnabled = context.checkCallingOrSelfPermission("com.android.vending.BILLING");
           ~~~~~~~~~~

**Comment by jkasten2** [comment]
@vahid263 We haven't configured Android's lint for our project. You can ignore the lint error, the `onesignal/build/outputs/aar/` folder and files will still be created.
