### ISSUE TITLE
No notification sound while on call

### ISSUE THREAD

**Issue by amourinho** [OneSignal/OneSignal-Android-SDK#627]
**Description:**
There is no notification sound played while on a call. Notifications were sent with NORMAL priority, in a category with the importance set to IMPORTANT. The notification is received but no sound played. Now, if you end the phone call, and resend the notification and all should be back to normal. Is this a bug? Or could this be an additional feature?

**Environment**
LG G6, Android OS 8.0.0
Target and Compile SDK Version 26
Build Tools Version 27.0.3
OneSignal Version [3.10.1, 3.99.99]

**Steps to Reproduce Issue:**
1. Implement OneSignal on the Android device as per the OneSignal documentation
2. Create a category and define a sound file as per the OneSignal documentation
3. Set the category's notification importance to IMPORTANT
4. Make a phone call (I've tested with my voicemail) and then send yourself a notification.

**Comment by jkasten2** [comment]
@amourinho I believe you have to set "Override Do not Disturb" on the notification category / channel if it should be played even during a call.
https://www.xda-developers.com/android-oreo-notification-phone-call/

I haven't tested this but the information above seems to point to this. Setting this on the category / channel isn't an option on the OneSignal dashboard but you can test it out by using code in your app to create your own channel.

**Comment by jkasten2** [comment]
@amourinho Let us know if the above does not help and we can reopen this issue and look into it. Thanks.
