### ISSUE TITLE
LeakCanary shows - com.onesignal.ActivityLifecycleHandler.curActivity leaks

### ISSUE THREAD

**Issue by harshitaahuja** [OneSignal/OneSignal-Android-SDK#63]
LeakCanary shows - com.onesignal.ActivityLifecycleHandler.curActivity leaks
using latest version 2.4.3

**Comment by jkasten2** [comment]
@harshitaahuja Thanks for the report. It does get nulled out in [onActivityStopped](https://github.com/OneSignal/OneSignal-Android-SDK/blob/615309f79ba6ddfbdce22992bd777a8c76f8a30b/OneSignalSDK/onesignal/src/main/java/com/onesignal/ActivityLifecycleHandler.java#L90), [onActivityDestroyed](https://github.com/OneSignal/OneSignal-Android-SDK/blob/615309f79ba6ddfbdce22992bd777a8c76f8a30b/OneSignalSDK/onesignal/src/main/java/com/onesignal/ActivityLifecycleHandler.java#L101), and [onActivityPaused](https://github.com/OneSignal/OneSignal-Android-SDK/blob/615309f79ba6ddfbdce22992bd777a8c76f8a30b/OneSignalSDK/onesignal/src/main/java/com/onesignal/ActivityLifecycleHandler.java#L79). Could you enable `OneSignal.LOG_LEVEL.DEBUG` and attach the logcat as well?

**Comment by jkasten2** [comment]
@harshitaahuja Also could you let us know if your calling OneSignal init from an Activity or an Application class.

**Comment by jemmyphan** [comment]
i've found the same leak, the static activity seems to be holding the detached fragment from being garbaged. (maybe) 

* id.xxx.HomeFragment has leaked:
* GC ROOT static com.onesignal.ActivityLifecycleHandler.curActivity
* references id.xxx.fragNavController
* references com.ncapdevi.fragnav.FragNavController.mFragmentManager
* references android.support.v4.app.FragmentManagerImpl.mActive
* references java.util.ArrayList.array
* references array java.lang.Object[].[0]
* leaks id.xxx.HomeFragment instance

**Comment by jkasten2** [comment]
@jemmyphan Thanks for the report.

Which OneSignal SDK version are you using?

Are you calling OneSignal init from an `Activity` or an `Application` class?

Can you call `OneSignal.setLogLevel(OneSignal.LOG_LEVEL.VERBOSE, OneSignal.LOG_LEVEL.WARN);` and attach the logcat entries when the leak is reported?

**Comment by jemmyphan** [comment]
I'm using 2.6.2,
it's  initialized on application class.
[log.txt](https://github.com/OneSignal/OneSignal-Android-SDK/files/686803/log.txt)
thanks @jkasten2

**Comment by jkasten2** [comment]
@jemmyphan Thanks for the log, it seems `curActivity` is being set to `null` before the leak entry is being printed. It seems you have removed most of the time stamp entries so I can't tell how close to what seems to be a race condition.

@jemmyphan @harshitaahuja Can you try the latest 3.4.2 version? A number of things have changed since the version you have tested on so this may no longer be an issue. See the upgrade guide below.
https://documentation.onesignal.com/docs/upgrading-to-android-sdk-30

**Comment by jemmyphan** [comment]
okay thanks, i'll try it soon @jkasten2

**Comment by jkasten2** [comment]
@jemmyphan @harshitaahuja I wasn't able to get leakcanary 1.5.0 to show `com.onesignal.ActivityLifecycleHandler.curActivity` as a leak.

Feel free to reopen this project if you can reproduce the issue with the soon to be released 3.4.4.
