### ISSUE TITLE
subscriptionEnabled not true even when approving permissions

### ISSUE THREAD

**Issue by udarts** [OneSignal/OneSignal-Android-SDK#631]
**Description:**

I am having an issue where when a user approves the permission (set using a manual popup). And I check the getPermissionSubscriptionState, it returns the following:

```` javascript
userSubscriptionEnabled: 'true',
subscriptionEnabled: 'false',
notificationsEnabled: 'true'
````

According to the code, it mentions the following:
```` javascript
// Notifications enabled for app? (Android Settings)
boolean notificationsEnabled = permissionState.getEnabled();

// User subscribed to OneSignal? (automatically toggles with notificationsEnabled)
boolean subscriptionEnabled = subscriptionState.getSubscribed();
````
So subscriptionEnabled should be the same as that notificationsEnabled is, but it is not for the version on android I mentioned below. Other versions seem to be fine.

**Environment**

So far only happening on Android Nougat 7.1 (API 25).
I followed the documentation as described on OneSignal (React-native documentation as I also use iOS).

**Steps to Reproduce Issue:**

I did all the steps as I should, but on SDK other than the 7.1, I receive the push notification (if approved by user).

This must be a bug in the SDK for android somehow.

Btw, this is the code I use to register on android:

```` javascript
if (Platform.OS === 'android') {
    OneSignal.init("id");
    // console.log(this.state.firstTime);
    Alert.alert(
        I18n.t('notifications title'),
        I18n.t('notifications subtitle'), 
       [
            {text: I18n.t('notifications no'), onPress: () => {
                OneSignal.setSubscription(false);
            }, style: 'cancel'},
            {text: I18n.t('notifications ok'), onPress: () => {
                OneSignal.setSubscription(true);
            }}
        ],
        { cancelable: false }
    )
}
````

**Comment by jkasten2** [comment]
@udarts The device is most likely having an issue getting a Firebase push token. It could also not be registering with OneSignal as well. To know which is the issue I recommend listing all properties from `OneSignal.getPermissionSubscriptionState()`

https://documentation.onesignal.com/docs/android-native-sdk#section--getpermissionsubscriptionstate-
These model objects also have a `toString()` which will shows all properties as JSON.

I also recommend checking your logcat for any OneSignal, GCM, or FCM errors as this would tell you more details.

**Comment by Nightsd01** [comment]
@udarts Thanks for posting a detailed issue, but please do not open the same issue on multiple repos (original issue [here](https://github.com/geektimecoil/react-native-onesignal/issues/638))
