### ISSUE TITLE
:app:debugRuntimeClasspath error gradle alpha10 and alpha11

### ISSUE THREAD

**Issue by furkanozalp** [OneSignal/OneSignal-Android-SDK#632]
Hi 

I get "ERROR: Cannot change strategy of configuration ':app:debugRuntimeClasspath' after it has been resolved" error in gradle:3.3.0-alpha10 and gradle:3.3.0-alpha11 but works before gradle:3.3.0-alpha10 version. How can I fix ?

Android Studio 3.3 Canary 11

**Comment by jkasten2** [comment]
@furkanozalp This is an issue part of the OneSignal-Gradle-Plugin. `gradle:3.3.0-alpha09` or older will need to be used until there is a fix.

Closing this issue in favor of this already opened issue.
https://github.com/OneSignal/OneSignal-Gradle-Plugin/issues/66#issuecomment-423362343
