### ISSUE TITLE
High Number of Partial Wake locks from com.onesignal.RestoreKickOffJobService

### ISSUE THREAD

**Issue by rampr** [OneSignal/OneSignal-Android-SDK#633]
**Description:**

Google Play shows a lot of stuck locks for this tag -> *job*/com.hashcube.sudokuquest/com.onesignal.RestoreKickoffJobService 

**Environment**

1. Onesignal version 3.10.1
2. maven/gradle
3. Android versions 8.0.0 8.1.0 and 9.0 according to google play

**Steps to Reproduce Issue:**

1. I'm not able to reproduce the issue, but google play reports this.
2.
3.

**Anything else:**

Attaching a screenshot.
![screen shot 2018-09-24 at 6 43 21 pm](https://user-images.githubusercontent.com/100719/45954478-bbfed680-c02a-11e8-92ec-59e37310384c.png)
Android documentation recommends using other means instead of using wakelocks - 
https://developer.android.com/training/scheduling/wakelock

Can this be done?

**Comment by jkasten2** [comment]
@rampr Thanks for the report.

The [`RestoreKickoffJobService`](https://github.com/OneSignal/OneSignal-Android-SDK/blob/3.10.1/OneSignalSDK/onesignal/src/main/java/com/onesignal/RestoreKickoffJobService.java) is using a `JobScheduler` instead of a manual wake lock. It is extending our  [`OneSignalJobServiceBase`](https://github.com/OneSignal/OneSignal-Android-SDK/blob/3.10.1/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignalJobServiceBase.java) which is a `JobService`.

`JobService` however does hold a wakelock while the job is running so this is way it is showing on the Google report. This is noted below.
https://developer.android.com/reference/android/app/job/JobService.html#onStartJob(android.app.job.JobParameters)

The wakelock volume looks very low, is this causing any issues for you users or hitting any vitals issues?

**Comment by rampr** [comment]
@jkasten2 Thanks for the response.
The volume is less because we were rolling out a release. I will share updated numbers in a few days so we can see the exact volume.

But we are in the bottom 14% percentile compared to other apps in the similar category. So that is what is troubling. Any thoughts on the above ?

**Comment by jkasten2** [comment]
@rampr We haven't changed anything in the last few versions around this. What versions did you update from?

The `RestoreKickoffJobService` restores any notifications back to the notification shade if they haven't been interacted by with by the user (User either tapping or swiping it away).  It has been around for some time in the SDK. It runs when your app gets updated from the Google Play store and when the device reboots.

This job should only take a few seconds in most cases. If you sent a large number of notifications in the past week it could take a few seconds longer.

Does the report break now the percentage of Android versions effected?

**Comment by rampr** [comment]
@jkasten2 We moved from 3.8.0 to 3.10.1 atleast a month ago. We fixed a few wakelock issues ourselves in the update that we rolled out recently.

Maybe it is still showing old data. I will wait a few more days to see if it changes and update this issue with more details.

**Comment by rampr** [comment]
@jkasten2 I have more details actually. I am taking data for the past 30 days. This data includes both onesignal versions 3.8.0 and 3.10.1

There are 3 wake locks that are present (Please see screenshot).
- RestoreJobService
- SyncJobService
- RestoreKickoffJobService

![image](https://user-images.githubusercontent.com/100719/45996799-1fd0e000-c0bb-11e8-8979-d36a2cdd3a00.png)

The android versions affected are 9, 8.1.0 and 8.0.0, with 9.0 at ~22K sessions, 8.1.0 at ~113K sessions and 8.0.0 at ~1M sessions. This split is not for onesignal wake tags only.

**Comment by jkasten2** [comment]
@rampr In version 2.8.2 we added a `setRequiredNetworkType` flag to `com.onesignal.SyncJobService` so this should lower the duration of the wakelock. As it won't be waking up to try to sync any missed tags or sessions unless there is a network connection.
https://github.com/OneSignal/OneSignal-Android-SDK/commit/bfb8006770d622dc169702ab0383c70dfde78396#diff-94c5d5923e7e08f42219e5c32b20c284R131

This `SyncJobService` is only run if tags and sessions could not be sent to OneSignal when the app was in use.

I don't believe there is anything we can do to lower the number here. Let use know if it is also effecting the Android Vitals section or if it just showing here. We haven't had any other reports of this.
