### ISSUE TITLE
Indonesian language not correctly detected

### ISSUE THREAD

**Issue by drayan85** [OneSignal/OneSignal-Android-SDK#64]
We are having some issue  on segmenting the android user (iPhone working fine). We tried to segment the user by Language Code. If the user device locale is Indonesian Bahasa, it is not registering for some reason. For Android Chinese language is also segmenting working. Could you please help on this issue.

**Comment by jkasten2** [comment]
@drayan85 Are the device not registering at all or just not to the correct language?

**Comment by drayan85** [comment]
Device has been registered successfully. 
![screen shot 2016-06-24 at 11 32 24 am](https://cloud.githubusercontent.com/assets/4456232/16327246/726532f2-39ff-11e6-97e9-577501139aa2.png)

But in the segment that device is not recognise as Indonesian Bahasa device and when we push that device getting English push instead of Indonesia Bahasa.
![screen shot 2016-06-24 at 11 29 59 am](https://cloud.githubusercontent.com/assets/4456232/16327271/c5383ae2-39ff-11e6-8f01-aab3933f4b4f.png)
In the above screen shot, among the 4 android devices one device locale is Indonesia Bahasa.

**Comment by jkasten2** [comment]
@drayan85 Can print out the returned value from the following code?
```Java
Locale.getDefault().getLanguage();
```

This is sent the OneSignal to determine the language.

**Comment by drayan85** [comment]
Locale.getDefault().getLanguage() values is 'in'
We have tried change the locale in couple of devices(Nexus 6P (N), SAMSUNG S4 GT-I9505 (5.0.1)) to test as well but result is same.

**Comment by jkasten2** [comment]
Odd that is it is returning 'in', the device should be returning 'id' for that function. 'in' isn't listed in [ISO 639](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)

Can you add a screenshot of the language list in the Android system settings for the device?

**Comment by drayan85** [comment]
![13493337_10209289062446020_330541691_o](https://cloud.githubusercontent.com/assets/4456232/16327722/18fd29da-3a05-11e6-9ddd-37e98de693ba.png)

**Comment by drayan85** [comment]
Locale.getDefault().getLanguage() : in
Locale.getDefault().getDisplayLanguage() : Indonesia
Locale.getDefault().getDisplayName() : Indonesia (Indonesia)
Locale.getDefault().getDisplayName() : ID
Locale.getDefault().getDisplayName() : Indonesia

**Comment by jkasten2** [comment]
@drayan85 Looks Java doesn't meet the ISO 639-1 standard for a few languages including Indonesia according to one of Google's older Android docs.
https://web.archive.org/web/20160215064626/http://developer.android.com/reference/java/util/Locale.html

I'll create a SDK fix for these languages.

**Comment by drayan85** [comment]
@jkasten2  thanks, please let us know once you fix this. We will hold our release.

**Comment by drayan85** [comment]
@jkasten2 , I would like to know the status issue since it is a difficult to target the Indonesian Bahasa users in their language.

**Comment by jkasten2** [comment]
@drayan85  Just fixed it in commit 7b9caf56335649519da107f0c696ca40bdd97bc7. It will be included in the next release.

**Comment by drayan85** [comment]
@jkasten2 thanks
