### ISSUE TITLE
User isn't marked "opted out" after setSubcription(false) when using OneSignal.provideUserConsent(false)

### ISSUE THREAD

**Issue by IvanShafran** [OneSignal/OneSignal-Android-SDK#647]
**Description:**
Hi!
I've tried to implement push notification subscription status switching.
But it doesn't work as expected.
Could you please point out what is wrong?

My code:
```
fun updateState(isAnalyticsEnabled: Boolean, isAdsEnabled: Boolean) {
        if (!isInitialized) {
            isInitialized = true
            OneSignal
                .startInit(context)
                .inFocusDisplaying(OneSignal.OSInFocusDisplayOption.Notification)
                .unsubscribeWhenNotificationsAreDisabled(true)
                .init()
          OneSignal.setRequiresUserPrivacyConsent(true)
        }

        OneSignal.setSubscription(isAdsEnabled)
        OneSignal.provideUserConsent(isAdsEnabled && isAnalyticsEnabled)
}
```

**Environment**
1. Any android OS(>=21) and any device
2. Internet is on
3. OneSignal Android SDK 3.10.2
4. Notification is enabled

**Steps to reproduce**
1. Start application and call updateState(isAnalyticsEnabled = true, isAdsEnabled = true)
**Expected**: User is appeared in admin console. Application can send custom tags via `OneSignal.sendTags(tags)`
**Reality**: as expected
2. Call updateState(isAnalyticsEnabled = false, isAdsEnabled = true)
**Expected**: User is still in admin console and is **not** marked as "opted out". Application can **not** send custom tags via `OneSignal.sendTags(tags)`
**Reality**: as expected
3. Call updateState(isAnalyticsEnabled = false, isAdsEnabled = false)
**Expected**: User is still in admin console and **is marked** as "opted out". Application can **not** send custom tags via `OneSignal.sendTags(tags)`
**Reality**: User is **not** marked as "opted out"

**Comment by jkasten2** [comment]
@IvanShafran Thanks for all details and the break down all the cases!

When `OneSignal.provideUserConsent(false);` is called the OneSignal SDK stops sending any updates to onesignal.com. Including any unsynced changes as you case where you have set `setSubscription` false since the network request would not have been triggered right away.

This is the same issue as #565.

**Comment by rgomezp** [comment]
Follow in #777
