### ISSUE TITLE
Got double notification when using custom Notification

### ISSUE THREAD

**Issue by juniorfrogie** [OneSignal/OneSignal-Android-SDK#652]
**Description:**

(your description here)
I want to customize content to display in notification. In Application class, I init OneSignal with setNotificationReceivedHandler(new CustomNotificationReceivedHandler(this)). 
**Environment**
SDK 27

**Comment by fatsjohonimahnn** [comment]
Please contact OneSignal support with your OneSignal app ID and details listed in our docs on this here: https://documentation.onesignal.com/docs/duplicated-notifications
