### ISSUE TITLE
[Onesignal 3.10.2]   java.lang.IllegalArgumentException  com.onesignal.OneSignalSyncServiceUtils.scheduleSyncServiceAsJob

### ISSUE THREAD

**Issue by mitonline** [OneSignal/OneSignal-Android-SDK#653]
**Description:**

We are seeing some crashes on the developer console with the above exception. Are using version 3.10.2.
All the crashes seen happen only on the following devices:
Z91 and Z61 (Device Vendor: Lava)
and all the crashes are seein in Android Version 7.1 and 8.1

**Environment**

Android SDK: 27
OneginalSDK: 3.10.2
Integrated Onesignal sdk using build.gradle (android studio)

**Steps to Reproduce Issue:**

Haven't been able to reproduce this issue yet. All the crashes yet are on only the above 2 devices.

**Anything else:**

(crash stacktraces, as well as any other information here)
Attached the complete stacktrace for the crash
[crash.txt](https://github.com/OneSignal/OneSignal-Android-SDK/files/2497912/crash.txt)

**Comment by samanyougarg** [comment]
I am facing the same issue in some of my apps as well. Please advise a fix.
