### ISSUE TITLE
I got error from fabric reported about  NotificationBundleProcessor.java class

### ISSUE THREAD

**Issue by rodow254** [OneSignal/OneSignal-Android-SDK#66]
So right that i just said the error show on fabric the detail is about

Fatal Exception: java.lang.NullPointerException
com.onesignal.NotificationBundleProcessor.ProcessFromGCMIntentService (NotificationBundleProcessor.java:57)
com.onesignal.GcmIntentService.onHandleIntent (GcmIntentService.java:54)
android.app.IntentService$ServiceHandler.handleMessage (IntentService.java:65)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:137)
android.os.HandlerThread.run (HandlerThread.java:61)

and it said NotificationBundleProcessor.java:57 : null pointer exception. so can you guys check about this class and the line of reported showing.

**Comment by restart916** [comment]
i have same issue.

**Comment by sujeshshetty** [comment]
I too got a similar issue today .

Fatal Exception: java.lang.NullPointerException: Attempt to write to field 'java.lang.Integer com.onesignal.NotificationExtenderService$OverrideSettings.androidNotificationId' on a null object reference
       at com.onesignal.NotificationBundleProcessor.ProcessFromGCMIntentService(NotificationBundleProcessor.java:57)
       at com.onesignal.GcmIntentService.onHandleIntent(GcmIntentService.java:54)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by jkasten2** [comment]
@rodow254 @restart916 @sujeshshetty 

Thanks for the reports, just fixed in [version 2.5.1](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/2.5.1). Just deployed to Maven Central so it may take a few hours before it shows up there.
