### ISSUE TITLE
OneSignal.h file not found

### ISSUE THREAD

**Issue by Denmal1982** [OneSignal/OneSignal-Android-SDK#664]
flutter build ios:

 === BUILD TARGET path_provider OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/myUser/AndroidStudioProjects/myApp/ios/OneSignalNotificationServiceExtension/NotificationService.m:1:9: fatal error: 'OneSignal/OneSignal.h' file not found
    #import <OneSignal/OneSignal.h>

flutter doctor:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.10.2, on Mac OS X 10.13.6 17G65, locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.2)
[✓] Connected device (1 available)

please tell me where is the problem

**Comment by Nightsd01** [comment]
@Denmal1982 please post this issue on our Flutter SDK repo. 

https://github.com/OneSignal/OneSignal-Flutter-SDK/issues
