### ISSUE TITLE
Android 7+ auto grouping of 4 or more notifications does not track open

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-Android-SDK#666]
## Issue
On Android Nougat (7.0)+ when 4 or more notifications are received Android will auto group them. However the `Intent` it sets up just launches the app's main `Activity` so this causes OneSignal to not be able to track an open.

## Workaround
Set the same [Group Key](https://documentation.onesignal.com/docs/android-customizations#section-notification-grouping) for all your notifications. This will make the OneSignal Android SDK setup it's own group notification with it's own `Intent`.

### Implementation Options
Need to re-evaluate what should happen when tapping on the summary notification to fix this issue. Three possible 3 candidates are;
1. _Count the most recent notification in the group as opened._ **Leaving all others in the group.**
2. _Count the most recent notification in the group as opened._ **Dismissing all others in the group.**
3. Count all notifications in the group as opened.
   -  When a group key is set from OneSignal this is what is done today.
   - Considering moving off of this as conversions could be misleading since the user could have opened a very large group of notifications (up to 49).

### Implementation Details
* For options 1 and 2 above, the most recent notification should be determined at click time.
* Check if `.setGroup` was called from the app's `NotificationExtenderService`.
   - We want to make sure we leave the group as is in this case since the app is handling it.
* `OSNotificationOpenResult.notification` contains the most recent however `groupedNotifications` contains a list of all notifications in that ground.

### Solution 1
Always set a group internally on Android 7+ so OneSignal will setup a group `Intent`. This will have the side effect of notifications grouping at 2 instead of 4 however.
### Solution 2
On Android 7+ check all notifications in the shade, if there are 3 currently in the shade create a group. It doesn't matter if the notification was created from OneSignal or not since we need to prevent Android from executing it's auto grouping at 4 notifications.

**Comment by rgomezp** [comment]
Issue is being addressed and is being tracked internally.

**Comment by ejain** [comment]
How was this resolved? I don't see `groupedNotifications` in the event, which according to https://github.com/OneSignal/react-native-onesignal/issues/1046 is an issue with the native SDK...

Ideally, I'd want to have the most recent notification opened, with the rest left in place; is this still an option?

**Comment by ejain** [comment]
Just upgraded react-native-opensignal to 4.3.0, and while I do now see a `groupedNotifications` property in the notification opened event, this property is null when a grouped notification was opened...
