### ISSUE TITLE
Get a dialog that shows over my UI and want to hide this

### ISSUE THREAD

**Issue by sratanjee** [OneSignal/OneSignal-Android-SDK#67]
![quickmemo _2016-06-30-09-06-33](https://cloud.githubusercontent.com/assets/3424642/16498154/39c6aaf2-3eaf-11e6-97fb-f243aea1ba2d.png)

I'd like to dismiss this from the user's view, and log it to debug.

**Comment by jkasten2** [comment]
@sratanjee This will only show up if you have called `OneSignal.setLogLevel` in your code. You should remove this call in the production version of your app.
