### ISSUE TITLE
App fails CTS test due to invalid intent

### ISSUE THREAD

**Issue by ron-k** [OneSignal/OneSignal-Android-SDK#675]
The SDK includes the following intent:
[android.intent.action.ACTION_BOOT_COMPLETED]

https://github.com/OneSignal/OneSignal-Android-SDK/blob/82a0a419b8712407adc6e5e6c2613476ab9d31e9/OneSignalSDK/onesignal/src/main/AndroidManifest.xml#L88

Cause:
This is invalid intent which causes Compatibility Test Suite to fail: all intents starting with "android.intent" are considered system and must be registered within the appropriate system file. I suggest removing it from SDK's manifest

Steps to reproduce:
1. Integrate the OneSignal Android SDK into an app
2. Preload the app (making it system)
3. Run the Compatibility Test Suite
3.1 The specific test that was run and failed:
run cts -m CtsSignatureTestCases -t android.signature.cts.IntentTest#shouldNotFindUnexpectedIntents

**Comment by jkasten2** [comment]
`ACTION_BOOT_COMPLETED` is valid intent and it can be used by any app, just requires the permission `android.permission.RECEIVE_BOOT_COMPLETED`.
https://developer.android.com/reference/android/content/Intent#ACTION_BOOT_COMPLETED

If you have removed this permission this could be why `cts` is showing this.

**Comment by ron-k** [comment]
Please note the valid intent value:
android.intent.action.BOOT_COMPLETED

Compared to the one appearing in the manifest:
android.intent.action.ACTION_BOOT_COMPLETED

**Comment by jkasten2** [comment]
Ah you are correct, we will remove `ACTION_BOOT_COMPLETED` in the next release!
