### ISSUE TITLE
Onesignal registration count is too low compare to play store (installed/update)count on recent update of onesignal sdk

### ISSUE THREAD

**Issue by gsksarath** [OneSignal/OneSignal-Android-SDK#685]
Is works fine in development environment, 
The difference is 75% between play store & onesignal

**Comment by jkasten2** [comment]
@gsksarath I recommend following up with OneSignal support if you haven't already. Closing this ticket due to inactivity.

**Comment by gsksarath** [comment]
@jkasten2 i feel the major difference in two weeks period of time after that it's ok now onesignal registration is greater than the play store, i don't the cause of the delay about that two weeks
