### ISSUE TITLE
No User was found in my Dashboard

### ISSUE THREAD

**Issue by zionnite** [OneSignal/OneSignal-Android-SDK#69]
Hello every one,

> I have an issue with my coding, i have set up my GCM key in my app in one signal and i copy my app id to my coding when i run : ionic run android every thing work fine but yet no user was found in my dashboard... 

Here is my code:

```
app.run(function($ionicPlatform){
    $ionicPlatform.ready(function(){
          var notificationOpenedCallback = function(jsonData) {
            console.log('didReceiveRemoteNotificationCallBack: ' + JSON.stringify(jsonData));
          };

          window.plugins.OneSignal.init("f26a3e0d-c385-437c-a80e-dd73d6c5a33d",
                                         {googleProjectNumber: "168827415175"},
                                         notificationOpenedCallback);

          // Show an alert box if a notification comes in when the user is in your app.
          window.plugins.OneSignal.enableInAppAlertNotification(true);
    });
});

```

Please I need your Help

**Comment by jkasten2** [comment]
@zionnite Can you add `alert` and `console.log` before and after `window.plugins.OneSignal` to make sure your code is running?

If this doesn't solve your issue please create a new issue on our Cordova repository below since this one is for Android native only.
https://github.com/OneSignal/OneSignal-Cordova-SDK/issues

**Comment by zionnite** [comment]
thanks it did add a user to my app dashboard but on of the user are subscribe to my notification, even when i used the setsubscription to true...

**Comment by jkasten2** [comment]
@zionnite What does it say in the 'Subscribed' column on the Users page on the OneSignal dashboard. If it is Yes then do you get a success when you send a notification?

If you open the red chat bubble when you are signed into your OneSignal account support can take a look at your account.
