### ISSUE TITLE
Build Errors after adding OneSignal

### ISSUE THREAD

**Issue by DevenRathod2** [OneSignal/OneSignal-Android-SDK#698]
@bryanatonesignal  @varundeva @jkasten2 No that last error was fix  (Manifest merger failed with multiple errors) but after adding all onesignal push notification codes
```gradle
        manifestPlaceholders = [
                onesignal_app_id: '51b99042-2041-4eb5-afc5-e94b5db99e1a',
                onesignal_google_project_number: 'REMOTE',
                contentProviderAuthority: contentProviderAuthority
        ]
```
![capture](https://user-images.githubusercontent.com/44080100/50898061-ff435080-1433-11e9-8ccd-00e72c581c80.PNG)

it create 5 new errors so please help me to fix this

_Originally posted by @DevenRathod2 in https://github.com/_render_node/MDEyOklzc3VlQ29tbWVudDQ1MjY3MjIzNg==/timeline/issue_comment#issuecomment-452672236_

**Comment by jkasten2** [comment]
@DevenRathod2 Could you please provide the code and the full errors to these lines and we can take a look.

**Comment by rgomezp** [comment]
Closing due to no response
