### ISSUE TITLE
NotificationExtenderService has been killed after receiving notification

### ISSUE THREAD

**Issue by drbear95** [OneSignal/OneSignal-Android-SDK#699]
**Description:**
Hello, i have problem with NotificationExtenderService.
Currently im using OneSignal.NotificationReceivedHandler and NotificationExtenderService.
When Im killing the app ( by swipe ), then Im pushing new notification and after that my NotificationExtenderService doesn't receiving any notifications until i kill my application once more.
My OneSignal.NotificationReceivedHandler working properly in this case ( when application is up)

Simplifying my NotificationExtenderService implementation is opening new activity after receiving notification with specific property in payload.

**Environment**
OneSignal SDK 3.10.5

Tested on:
Android API 21 - 27
Android Studio Emulators

**Code**
- OneSignal init

```kotlin
OneSignal.startInit(this)
                .inFocusDisplaying(OneSignal.OSInFocusDisplayOption.None)
                .setNotificationReceivedHandler(AlarmNotificationReceivedHandler())
                .unsubscribeWhenNotificationsAreDisabled(true)
                .init()
```

- Manifest

```xml
<service
            android:name=".app.emergency.receivers.AlarmReceiver"
            android:exported="false"
            android:permission="android.permission.BIND_JOB_SERVICE">
            <intent-filter>
                <action android:name="com.onesignal.NotificationExtender" />
            </intent-filter>
</service>
```

- NotificationExtenderService onNotificationProcessing method

```kotlin
override fun onNotificationProcessing(notification: OSNotificationReceivedResult?): Boolean {
			if (notification?.payload?.additionalData != null) {
				if (notification.payload.additionalData.getBoolean("IsActivation")) {
					val intent = Intent(this, FullscreenAlarmActivity::class.java)

					intent.addFlags(Intent.FLAG_ACTIVITY_BROUGHT_TO_FRONT or Intent.FLAG_ACTIVITY_NEW_TASK)

					intent.putExtra (...)
					
					startActivity(intent)
				}else{
					(...)
				}
			}
			return true
	}
```

**Comment by jkasten2** [comment]
@drbear95 Just to confirm, you are always sending `IsActivation` with your notifications as `data` on the OneSignal notification? I see you are always returning `true` from `onNotificationProcessing` which tells the OneSignal SDK you have process a notification for it not to show one of its own.

If my above details is what you expect for your app then something in your `FullscreenAlarmActivity` class that is only allowing it to be shown once. I recommend creating a new Activity and adding logging to it's `onCreate` and `onResume` methods. I also recommend adding logging to the top of `onNotificationProcessing` to make sure it is always firing.

**Comment by drbear95** [comment]
At first i did onesignal gradle plugin update and somehow it fixed my service then i figured out that there is problem with starting my activity. I changed flags in my intent and everything works fine right now.

Here is my solution for flags:
I changed this
```kotlin
intent.addFlags(Intent.FLAG_ACTIVITY_BROUGHT_TO_FRONT or Intent.FLAG_ACTIVITY_NEW_TASK)             
```
to this
```kotlin 
intent.addFlags(Intent.FLAG_ACTIVITY_BROUGHT_TO_FRONT or Intent.FLAG_ACTIVITY_MULTIPLE_TASK or Intent.FLAG_ACTIVITY_NEW_TASK)
```
Thank you for your time

**Comment by jkasten2** [comment]
@drbear95 Good to hear you got things working! Closing this issue.

I do want to point out that it isn't recommended to display an Activity directly from a received event like you have in your example code. There are UX / UI exceptions such as a VOIP app, just wanted to make sure you have considered this.
