### ISSUE TITLE
com.onesignal.UserStatePushSynchronizer$1.onSuccess   Fatal Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by leonidkabanen** [OneSignal/OneSignal-Android-SDK#700]
**Description:**

I have such crash for production build. I couldn't reproduce it but I see about 9k crashes for users:
```java
UserStatePushSynchronizer.java line 34 com.onesignal.UserStatePushSynchronizer$1.onSuccess   Fatal Exception: java.lang.NullPointerException
```

**Environment**
1) 40% of crashes -  Android 7
    36% - Android 8
    23% - Android 6
    1% - Android 9

**Crash log:**

```java
UserStatePushSynchronizer.java line 34 com.onesignal.UserStatePushSynchronizer$1.onSuccess   Fatal Exception: java.lang.NullPointerException

Attempt to read from field 'org.json.JSONObject com.onesignal.be.b' on a null object reference
com.onesignal.UserStatePushSynchronizer$1.onSuccess (UserStatePushSynchronizer.java:34)
com.onesignal.OneSignalRestClient$5.run (OneSignalRestClient.java:208)
java.lang.Thread.run (Thread.java:762)
```

**Comment by jkasten2** [comment]
@leonidkabanen Thanks for the details. We will look into this stack trace to see if we can find the root of the cause.

**Comment by djendacott** [comment]
@jkasten2 Any update on this? I'm experiencing lots of crashes because of the same issue.

**Comment by jkasten2** [comment]
@show47 This has actually already been completed in number of releases ago. The SDK support both GCM and FCM client libraries so there can be a smooth migration.

Also this stack trace isn't related to GCM or FCM, it has to due with the SDK sending sending tags, sessions, etc to the https://onesiganl.com REST API endpoints.

**Comment by rgomezp** [comment]
Closing due to no response

**Comment by talk2pran** [comment]
I am also facing the same crash issue on mostly on Android 6.0,7.0 and 7.1.

**Comment by rgomezp** [comment]
@talk2pran ,
What SDK version are you using? Please describe your environment including where you are testing, etc...

**Comment by rgomezp** [comment]
Closing due to no response
