### ISSUE TITLE
Android : java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/api/Api$zzc;

### ISSUE THREAD

**Issue by LogeshwariMurugan** [OneSignal/OneSignal-Android-SDK#702]
My build.gradle:
---------------------
apply plugin: 'com.android.application'
android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "com.innoart.justcopy"
        minSdkVersion 21
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
        multiDexEnabled true
    }
    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/ASL2.0'
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:cardview-v7:27.1.1'
    implementation 'com.itextpdf:itextg:5.5.10'
    implementation 'com.android.support:recyclerview-v7:27.1.1'
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support:design:27.1.1'

    implementation 'com.google.firebase:firebase-core:16.0.1'
    implementation 'com.google.firebase:firebase-auth:16.0.3'
    implementation 'com.google.android.gms:play-services-auth:16.0.0'
    implementation 'com.firebaseui:firebase-ui-auth:3.3.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    implementation 'com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.8.+'
    implementation 'com.android.support:support-v4:27.1.1'
    implementation 'com.android.support:support-vector-drawable:27.1.1'
    testImplementation 'junit:junit:4.12'
    implementation 'com.rmtheis:tess-two:5.4.1'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation project(':edgedetection')
    implementation project(':openCVLibrary340')
    implementation 'com.jakewharton:butterknife:8.8.1'
    implementation 'com.karumi:dexter:4.1.0'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
    implementation 'info.androidhive:imagefilters:1.0.7'
    // for dropbox
    implementation 'com.dropbox.core:dropbox-core-sdk:2.0.1'
    // for facebook
    implementation 'com.facebook.android:facebook-login:[4,5)'
    implementation project(':linkedin-sdk')

//    implementation 'com.google.android.gms:play-services-drive:11.6.0'
//    implementation 'com.google.api-client:google-api-client:1.25.0'
//    implementation "com.google.android.gms:play-services-drive:11.6.0"
//    implementation 'com.google.api-client:google-api-client:1.23.0'
//    implementation 'com.google.oauth-client:google-oauth-client-jetty:1.23.0'
//    implementation 'com.google.apis:google-api-services-drive:v3-rev110-1.23.0'
//    implementation 'com.google.http-client:google-http-client-gson:1.26.0'
//    implementation('com.google.api-client:google-api-client-android:1.26.0') {
//        exclude group: 'org.apache.httpcomponents'
//    }
//    implementation('com.google.apis:google-api-services-drive:v3-rev136-1.25.0') {
//        exclude group: 'org.apache.httpcomponents'
//    }
    //implementation 'com.google.android.gms:play-services-drive:9.0.2'
    implementation 'com.google.android.gms:play-services-drive:8.4.0'
    implementation('com.google.api-client:google-api-client-android:1.23.0') {
        exclude group: 'org.apache.httpcomponents'
    }
    implementation 'com.google.api-client:google-api-client:1.25.0'
    implementation('com.google.apis:google-api-services-drive:v3-rev29-1.22.0') {
        exclude group: 'org.apache.httpcomponents'
    }

    implementation 'com.google.oauth-client:google-oauth-client-jetty:1.23.0'
}

apply plugin: 'com.google.gms.google-services'

Issue:  ( at line Drive.DriveApi.newDriveContents(mGoogleApiClient).setResultCallback(new*)
-------

Process: com.innoart.justcopy, PID: 25038
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/api/Api$zzc;
        at com.google.android.gms.drive.Drive.<clinit>(Unknown Source:0)

class:( for android drive storage)
------------
**Drive.DriveApi.newDriveContents(mGoogleApiClient).setResultCallback(new** ResultCallback<DriveContentsResult>() {
            @Override
            public void onResult(DriveContentsResult result) {
                // If the operation wasn't successful, return
                if (!result.getStatus().isSuccess()) {
                    Log.e(TAG, "Failed to create new content!.");
                    return;
                }
                Log.i(TAG, "New content has been created.");
                // Get an output stream for the contents.
                OutputStream outputStream = result.getDriveContents().getOutputStream();
                // Write the bitmap data from it.
                ByteArrayOutputStream bitmapStream = new ByteArrayOutputStream();
                image.compress(Bitmap.CompressFormat.PNG, 100, bitmapStream);
                try {
                    outputStream.write(bitmapStream.toByteArray());
                } catch (IOException e1) {
                    Log.i(TAG, "Unable to write file contents.");
                }
                // Create the initial metadata - MIME type and title.
                // Note that the user will be able to change the title later.
                MetadataChangeSet metadataChangeSet = new MetadataChangeSet.Builder()
                        .setMimeType("image/jpeg").setTitle("myPhoto.png").build();
                // Create an intent for the file chooser, and start it.
                IntentSender intentSender = Drive.DriveApi
                        .newCreateFileActivityBuilder()
                        .setInitialMetadata(metadataChangeSet)
                        .setInitialDriveContents(result.getDriveContents())
                        .build(mGoogleApiClient);
                try {
                    startIntentSenderForResult(
                            intentSender, REQUEST_CODE_CREATOR, null, 0, 0, 0);
                } catch (SendIntentException e) {
                    Log.i(TAG, "Failed to launch file chooser.");
                }
            }
        });

**Comment by jkasten2** [comment]
@LogeshwariMurugan I checked your build.gradle but I do not see OneSignal. Can you double check that you have pasted the correct build.gradle here and it is complete?

**Comment by rgomezp** [comment]
Closing due to no response
