### ISSUE TITLE
 how to get the login token  upon authentication?

### ISSUE THREAD

**Issue by muzaheed57** [OneSignal/OneSignal-Android-SDK#709]
how many type of token available ?
i see there is token for  push notification . Do the token will be assigned for each push notification?
or it will be a single token for all  push notification?

and how to get the login token  upon authentication?

**Comment by rgomezp** [comment]
Hello,
Each device has its own token. You can get the user's token using the `getPushToken` method. You'll be able to find more info in our documentation [here](https://documentation.onesignal.com/docs/android-native-sdk#section-status-methods)
