### ISSUE TITLE
The player id change each time app get installed after an unistalling the app

### ISSUE THREAD

**Issue by rameshvoltella** [OneSignal/OneSignal-Android-SDK#725]
Hi

The player id is changing each time after we uninstall and install app on the same device,What may be the problem or is this an expected behavior.Why because i have just made a new app via one signal with new onesignal App Id this issue is only in my new app, my App1 via onesignal have no issue(App means example Onsignalapp1,onesignalapp2 both have diffrent app id) via one signal console.

in the App1 every time if i uninstall and install app ,player id is same,But App2 which is newly created have this issue
Please help to understand the problem

**Comment by jkasten2** [comment]
@rameshvoltella The `player_id` will change for the device when fully uninstalling the app then reinstall it if the OneSignal can't get the Google `ad_id` for the device. Either due to the user opting out or if there was some kind of error getting it.

In your case since it is working with one of your apps but not the other it is most likely due to the `com.google.android.gms.ads.identifier.AdvertisingIdClient` class not being included in your APK. This could be due to different dependencies in your `build.gradle`.
I recommend checking your logcat for any errors or warning due to ad_id or this class.

**Comment by rameshvoltella** [comment]
i will provide the info related what all am adding in my project

app grdel
```
buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/' }
    }
    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.12.1'
    }
}
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'
android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "in.my pakage"
        minSdkVersion 15
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        manifestPlaceholders = [onesignal_app_id               : "my app id",
                                // Project number pulled from dashboard, local value is ignored.
                                onesignal_google_project_number: "REMOTE"]

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true

    }
......
}
dependencies {
    implementation "com.onesignal:OneSignal:$onesignal_version"
    implementation 'com.google.android.gms:play-services-auth:16.0.1'
}
apply plugin: 'com.google.gms.google-services'

```

Main gradle

```
buildscript {
    ext.kotlin_version = '1.2.71'
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.0.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
```

in my application class

```
OneSignal.startInit(this)
                .inFocusDisplaying(OneSignal.OSInFocusDisplayOption.Notification)
                .setNotificationOpenedHandler(OneSignalNotificationOpenedHandler(applicationContext))
                .unsubscribeWhenNotificationsAreDisabled(true)
                .init()
```

only google lib am using is com.google.android.gms:play-services-auth.Am writing the app in kotlin.Do you need any more info?

**Comment by rameshvoltella** [comment]
Hi

i have resolved the issue by adding
`' implementation "com.google.firebase:firebase-analytics:16.0.1'`

Once add it its working fine can you tell me why it happen?
