### ISSUE TITLE
Google play service error 

### ISSUE THREAD

**Issue by max-pro** [OneSignal/OneSignal-Android-SDK#727]
Hello all,
Im using Android onesignal. Setup not showing any error. Even user register successfully on onesignal dashboard. But failed to subscribe user. Getting error Google play service failed initialize.please check your gcm version in androidmanifest

**Comment by jkasten2** [comment]
@max-pro Hello, could you check the logcat from the device for any additional errors or warnings that included FCM or GCM and attach the full entries here?

I also recommend trying your app on a few different devices or an emulator as the issue could be related to a specific device.

**Comment by rgomezp** [comment]
Closing due to no response
