### ISSUE TITLE
NotificationExtenderService background not works with Firebase Database

### ISSUE THREAD

**Issue by CeccoCQ** [OneSignal/OneSignal-Android-SDK#735]
I've an issue with NotificationExtenderService class.
If II try to retrieve data from firebase realtime database, the callback not works (I suppose because the JobIntentService was killed before the completion of Firebase Task).

This is my code:
```
public class OSNotificationService extends NotificationExtenderService {

    @Override
    protected boolean onNotificationProcessing(final OSNotificationReceivedResult receivedResult) {
        // ........... custom code
        if (!receivedResult.isAppInFocus) {
        FirebaseDatabase.getInstance().getReference()
                    .child("users")
                    .child(myUserId)
                    .addListenerForSingleValueEvent(new ValueEventListener() {
                        @Override
                        public void onDataChange(@NonNull DataSnapshot dataSnapshot) {
                                //never called
                        }

                        @Override
                        public void onCancelled(@NonNull DatabaseError databaseError) {
                                //never called
                        }
                    });
        }

        displayNotification(overrideSettings);

        return false;
    }
```
If I execute the addListenerForSingleValueEvent method in the MainActivity (for example), all works fine.

**Comment by jkasten2** [comment]
@CeccoCQ As soon as you return from `onNotificationProcessing` the instance of your `OSNotificationService` class will go out of scope. The wake lock will also be released so even if you hold on to a static reference it still may not execute.

You will need to wait for the Firebase database response before returning from `onNotificationProcessing`. See this thread for some ways to do so.
https://stackoverflow.com/questions/30659569/wait-until-firebase-retrieves-data
