### ISSUE TITLE
NotificationReceivedHandler or NotificationExtenderService?

### ISSUE THREAD

**Issue by icsd** [OneSignal/OneSignal-Android-SDK#736]
In which case should I subclass the `NotificationReceivedHandler.class` and in which case should I subclass the `NotificationExtenderService.class` ? Could you provide an example?

As I can understand from your tutorials I would subclass the  `NotificationExtenderService.class` in order to execute some tasks asynchronously in the background when a _Push Notification_ arrives at the device or to customize the Notification UI.
What about `NotificationReceivedHandler.class`?

**Environment**
1. My project is built with target SDK 26
2. I use ` implementation 'com.onesignal:OneSignal:[3.9.2, 3.99.99]' ` in build.gradle

**Comment by jkasten2** [comment]
@icsd Sorry for the delay.
`NotificationReceivedHandler` was designed to have your app react to a push when it is received when your app is in use.
`NotificationExtenderService` is designed to handle push receives no matter the state of your app and provide more powerful options such as overriding specific settings, or suppress the notification from showing at all.

**Comment by cirogg** [comment]
Hello. How should i implement the NotificationExtenderService ?

**Comment by AlbertVilaCalvo** [comment]
@cirogg you can see how to set up the `NotificationExtenderService` in https://documentation.onesignal.com/docs/service-extensions

**Comment by AlbertVilaCalvo** [comment]
also this 2 links contain information about notifications in the background:

https://documentation.onesignal.com/docs/android-customizations#section-background-data-and-notification-overriding

https://documentation.onesignal.com/docs/silent-notifications
