### ISSUE TITLE
Firebase Not Initialized - Device Not Subscribed

### ISSUE THREAD

**Issue by joblolin95** [OneSignal/OneSignal-Android-SDK#738]
**Description:**
Hello! I have an app configured with OneSignal that doesn't receive notifications on certain installs. I say "certain installs" because there are times the app doesn't receive notifications on a device, but then uninstalling and then re-installing the app will occasionally allow notifications to come through as desired. 

When notifications aren't coming through,             `OneSignal.getPermissionSubscriptionState().getSubscriptionStatus().getSubscribed()`
 returns false. Otherwise, it is true. 

Upon closer inspection, I noticed the logs below related to Firebase initialization on a device I'm not receiving notifications for. OneSignal is the only component in my app that uses Firebase. I don't know of any way to deterministically reproduce the issue, but on first appearance it seems related to [#681](https://github.com/OneSignal/OneSignal-Android-SDK/issues/681#issue-388545496).

**Environment**
In my root build.gradle file     
`classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.1, 0.99.99]'`

In my app-level build.gradle file
`implementation 'com.onesignal:OneSignal:[3.10.7, 3.99.99]'`

I am not explicitly importing play services or firebase anywhere in my list of dependencies, but I am using several Android support libraries (if that's pertinent).

I call the following in my Application class onCreate
```
OneSignal.startInit(mCtx)
                    .autoPromptLocation(false)
                    .setNotificationReceivedHandler(new OneSignalNotificationReceivedHandler())//custom handler
                    .setNotificationOpenedHandler(new OneSignalNotificationOpenedHandler())//custom handler
                    .inFocusDisplaying(OneSignal.OSInFocusDisplayOption.None)
                    .unsubscribeWhenNotificationsAreDisabled(true)
                    .disableGmsMissingPrompt(false)
                    .init();
```

**Steps To Reproduce Issue**
I haven't determined how to reproduce - I've had my app connect to OneSignal on one install, and then fail to connect after a fresh install on the same device.

**Anything Else**
```
04-15 07:11:44.225 8172-8172/? I/FirebaseInitProvider: FirebaseApp initialization unsuccessful
```

Sometimes I get this log as well
```
04-15 07:11:46.911 8172-8276/? D/FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
```

**EDIT**
Upon further investigation, I was noticing the problem was regularly occurring on minified release builds; non-minified release builds were subscribing perfectly. Looking further with this in mind, I found the following message in logcat.

```
04-15 14:25:46.962 21450-21450/? W/System.err: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/gcm/GoogleCloudMessaging;
04-15 14:25:46.963 21450-21450/? W/System.err:     at com.onesignal.OSUtils.hasGCMLibrary(Unknown Source:0)
        at com.onesignal.OSUtils.a(Unknown Source:29)
        at com.onesignal.OneSignal.init(Unknown Source:87)
        at com.onesignal.OneSignal.init(Unknown Source:89)
        at com.onesignal.OneSignal.a(Unknown Source:0)
        at com.onesignal.OneSignal$Builder.init(Unknown Source:0)
        at my.package.App.onCreate(Unknown Source:134)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5920)
        at android.app.ActivityThread.access$1100(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.gcm.GoogleCloudMessaging" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/my.package-xN83km5rt7qC2N11drKAiw==/base.apk"],nativeLibraryDirectories=[/data/app/my.package-xN83km5rt7qC2N11drKAiw==/lib/arm64, /data/app/my.package-xN83km5rt7qC2N11drKAiw==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    	... 18 more
```

Working on a hunch, I included the following in app/build.gradle (taken from the onesignal module build.gradle) and the problem disappeared.

```
implementation 'com.google.android.gms:play-services-base:12.0.1'
implementation 'com.google.android.gms:play-services-gcm:12.0.1'
api 'com.google.firebase:firebase-messaging:12.0.1'
```

Any idea as to why this behavior would occur?

**Comment by jkasten2** [comment]
@joblolin95 Thanks for the details and digging in. `hasGCMLibrary` has a guard around the class `GoogleCloudMessaging` reference but it would seem when the code in minified it drops the guard. It probably does this since it assumes it isn't possible for it to throw and thinks it is dead code.
https://github.com/OneSignal/OneSignal-Android-SDK/blob/master/OneSignalSDK/onesignal/src/main/java/com/onesignal/OSUtils.java#L98-L105

I wasn't able to reproduce the issue with a standard proguard rules. Could you reproduce the issue in an example project and share it here?

**Comment by joblolin95** [comment]
@jkasten2 [Here](https://www.dropbox.com/s/itqj8etguj50v8c/Test%20Project.zip?dl=1) is a link to a small, zipped up sample app I used to recreate the issue. It subscribed when not minified, but when the build was minified the app would no longer subscribe to OneSignal.

The OneSignal app id and what more will need to be added in the build.gradle file.
Let me know if you need anything more!

**Comment by rgomezp** [comment]
Hi Joseph,
Thanks for your patience. We were able to reproduce the issue and found a workaround:
> build.gradle
Replace:
`proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'`
with
`proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'`

Hopefully, you don't need those extra optimizations. If you do, you may need to go into the file and tweak specific settings depending on which ones you absolutely need. Those settings tend to be a lot more aggressive and are likely at the root of this issue.
@joblolin95

**Comment by rgomezp** [comment]
Closing due to no response
