### ISSUE TITLE
Play Services outdated dialog

### ISSUE THREAD

**Issue by leonardoxh** [OneSignal/OneSignal-Android-SDK#74]
Hi,

When I test in devices with Google play services outdated the one signal prompt me a dialog update the play services...

There is a way to disable this ?

**Comment by jkasten2** [comment]
@leonardoxh The prompt will only show if the device has the "Google Play Store" installed on the device but the "Google Play services" app is older than the version of the library you built your app with. You can use an older version of the Google Play services library back to 7.0.0 if you choose.

Let us know if this is still an issue for you and we can look into adding an option to disable it completely.

Thanks.

**Comment by leonardoxh** [comment]
I think this is because I have excluded the google play services dependencies from the one signal artifact and forced it to a new version.

```groovy
compile("com.onesignal:OneSignal:${oneSignalVersion}") {
  exclude(group: 'com.google.android.gms', module: 'play-services-gcm')
  exclude(group: 'com.google.android.gms', module: 'play-services-location')
}
```

I'll back it this artifact, and see if this solves the problem.

**Comment by jkasten2** [comment]
@leonardoxh `compile("com.onesignal:OneSignal:...")` shouldn't be bring in Google Play services so the extra lines you added shouldn't change anything.

If your seeing "To receive push notifications please press 'Update' to enable 'Google Play services'." this comes from our SDK. It was prompting in the 1.x version of our SDK but wasn't working in our 2.x versions until version [2.5.2](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/2.5.2).

**Comment by leonardoxh** [comment]
I'm using the version 2.6.0...

It's the same issue faced on #75

**Comment by jkasten2** [comment]
I'll add an option for this next week.

**Comment by jkasten2** [comment]
@leonardoxh Just added an option to disable this with the OneSignal.Builder class and string values to override the text. See the following commit for more details.
https://github.com/OneSignal/OneSignal-Android-SDK/commit/1b8eb3728beedd02ccf14168d7f1cc42ec099116

We will be adding full documentation for this soon and the options will be included in the next release.

Thanks.

**Comment by leonardoxh** [comment]
@jkasten2  :+1: 

Really thanks
