### ISSUE TITLE
Could not find android_channel_id Error - Post

### ISSUE THREAD

**Issue by icsd** [OneSignal/OneSignal-Android-SDK#740]
I have created a Category (Channel) with a Channel ID.
I call Post `https://onesignal.com/api/v1/notifications` and pass the parameter `android_channel_id` with value, the one that was created from the OneSignal Dashboard when I created the Channel, and I receive an email with the following error:

`{"CompanyId":null,"UserId":"234085379a3-a154-b099-cb5336cae598","IncidentIdentifier":"PushNotificationFTError","Type":2,"Data":"{\"ExceptionMessage\":\"The remote server returned an error: (400) Bad Request.\",\"ErrorsMessage\":\"{\\\"errors\\\":[\\\"Could not find android_channel_id\\\"]}\"}","Id":"7ef9de4d-de6a-45f6-a594-7d36ebcd1cd7","Version":"AABBAACzBU=","CreatedAt":"2019-04-17T09:48:41.5879837+00:00","UpdatedAt":"2019-04-17T09:48:41.5879837+00:00","Deleted":false}`

However, when I send a Push Notification from _OneSignal Dashboard -> Messages_ and select  the same Category I don't receive this email error.

What could be wrong? Could you provide an example of a `Post` with `android_channel_id` as parameter ?

**Environment**
1. My project is built with target SDK 26
2. I use implementation 'com.onesignal:OneSignal:[3.9.2, 3.99.99]' in build.gradle

**Comment by jkasten2** [comment]
@icsd Can you double check that both the `android_channel_id` and `app_id` are correct? You can double check the `android_channel_id` from here:
https://documentation.onesignal.com/docs/android-notification-categories#section-from-the-rest-api

The `android_channel_id` is a string parameter as a UUID. So it should be added just like `app_id`.

I recommend including the full JSON payload you are sending and contacting OneSignal support so they can double check the ids you are sending.

**Comment by rgomezp** [comment]
Closing due to no response
