### ISSUE TITLE
onesignal.com used Cloudflare to restrict access

### ISSUE THREAD

**Issue by Deke20** [OneSignal/OneSignal-Android-SDK#743]
![56563458-6389ba80-65b4-11e9-9729-8fc11422bfd7](https://user-images.githubusercontent.com/47948254/56598894-13374a80-65fe-11e9-9db9-c006cf170166.png)

**Comment by Deke20** [comment]
what's the meaning of closing the issue without any further explanation !!!
any help please ??

**Comment by rgomezp** [comment]
We have an issue template. Please follow it so that we can address your issue properly
