### ISSUE TITLE
Detection of rooted devices

### ISSUE THREAD

**Issue by ron-k** [OneSignal/OneSignal-Android-SDK#751]
**Description:**

The SDK implements detection mechanism for whether the devices is rooted, the code is located in the class _**com.onesignal.RootToolsInternalMethods**_ :

https://github.com/OneSignal/OneSignal-Android-SDK/blob/08d0315093ed943b57bc71adbf15a1fbd7289577/OneSignalSDK/onesignal/src/main/java/com/onesignal/RootToolsInternalMethods.java#L27

There seems no actual functionality dependent on this mechanism, it's just there to report this information to your back-end.

Such functionality raises alert for a penetration-testing software suits analysing the app using your SDK.

**Environment**

This functionality is present since at  v2.0 (at least)

**Anything else:**
Please remove it or advise how this can be removed during the integration of the SDK.

**Comment by rgomezp** [comment]
Hello,
Thank you for reaching out with your concerns. While we don't plan on removing this functionality, feel free to fork the repository and make your own build without this code.

We actually allow app owners to use this simple boolean value as a filter when targeting users.
<img width="755" alt="Screen Shot 2019-05-06 at 6 18 15 PM" src="https://user-images.githubusercontent.com/11739227/57265277-c014bd00-702b-11e9-9566-dd464be4051f.png">
