### ISSUE TITLE
Notification from Google Play

### ISSUE THREAD

**Issue by ronnyrolim** [OneSignal/OneSignal-Android-SDK#759]
**Description:**

I received a google play notification after inserting the onesignal codes in build.grade (app)

`buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/' }
    }
    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.12.1'
    }
}
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

repositories {
    maven { url 'https://maven.google.com' }
}`

> Cross-app Scripting
> Your app(s) are using a WebView that is vulnerable to cross-app scripting.
> 
> To address this issue, follow the steps in this Google Help Center article.

[https://support.google.com/faqs/answer/9084685](url)

**Environment**

**Steps to Reproduce Issue:**

1. (your steps here)
2.
3.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by rgomezp** [comment]
Hello,
It's not clear to me that this is an issue with our SDK. The message is describing a WebView

**Comment by rgomezp** [comment]
Closing due to no response
