### ISSUE TITLE
Get all notification when open app

### ISSUE THREAD

**Issue by kshysius** [OneSignal/OneSignal-Android-SDK#76]
Hi, how to get all notification when clicked on app? or one of notification

**Comment by jkasten2** [comment]
@kshysius The SDK does not have a way to get all notifications however I'll mark this as feature request. 

In the mean time it is possible to save your own list as they are received from the [NotificationExtenderService](https://documentation.onesignal.com/docs/android-notification-customizations#background-data-and-notification-overriding). Lastly on Android 6.0+ devices it is possible to get a list of notifications in the shade for your app by calling [getActiveNotifications](https://developer.android.com/reference/android/app/NotificationManager.html#getActiveNotifications)

**Comment by Xaus** [comment]
i have same issue . i want when user opens app , all notifications in queue opened and handle their event .

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration
