### ISSUE TITLE
Problem with permissions on manifest

### ISSUE THREAD

**Issue by Hanzofm** [OneSignal/OneSignal-Android-SDK#761]
**Description:**
Recently we have submitted our Ionic App for a security audit and this is report about OneSignal:

-Vulnerability:  Android   Bad Practices: Missing Component Permission
-Description:  Any   application can access public components that are not explicitly assigned an   access permission in their manifest definition.
-Fortify   Priority: High.
-Fortify Priority: Explotable.
-Sink:

`File   Path :   ionic/platforms/android/build/intermediates/manifests/full/debug/AndroidManifest.xml   Line Number : 171   <service   android:name="com.onesignal.NotificationRestoreService" />              <receiver   android:name="com.onesignal.BootUpReceiver" >                 <intent-filter>                   <action   android:name="android.intent.action.ACTION_BOOT_COMPLETED" />`

Recommendation:
Components   without explicit access permissions should be exceptions. Unless, the   component is really intended to be accessible to all, developers should   protect components from misuse by malicious applications by explicitly   defining the access permissions in the manifest file.

**Environment**
Ionic info:

```
Ionic:

   ionic (Ionic CLI)  : 4.8.0
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.4, ios 4.5.5
   Cordova Plugins       : no whitelisted plugins (14 plugins total)

System:

   Android SDK Tools : 26.1.1 (/Users/user/Library/Android/sdk)
   ios-deploy        : 1.9.2
   ios-sim           : 7.0.0
   NodeJS            : v9.9.0 (/usr/local/bin/node)
   npm               : 5.7.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.2 Build version 10E125

```

One Signal cordova plugin version

`onesignal-cordova-plugin 2.4.6 "OneSignal Push Notifications"`

Due to security problems it should be fixed?

**Comment by jkasten2** [comment]
@Hanzofm `android:exported` is by default `false` for `services` if there is no filters. So in the case of `NotificationRestoreService` it can't be invoked externally.
https://developer.android.com/guide/topics/manifest/service-element

`BootUpReceiver` is intended to be invoked public by the system so it has `ACTION_BOOT_COMPLETED` as an intent filter.

These values are both correct, the report you have is just a warning to double check this is what was intended. In this case they are so you can safely ignore the warning.

**Comment by Hanzofm** [comment]
Hi,

We have submitted your answer to the security issue with the permissions and the answer for it is this:

> This component should be divided into two parts so that the system broadcast portion can be private, reducing the exposed surface of the application. Separate the functionality that handles system messages from the functionality that handles other messages.




-On the other hand they have reported another problem with permissions on receivers on:

Sink:
```
File Path : /platforms/android/app/build/intermediates/manifests/full/debug/AndroidManifest.xml Line Number : 180
</intent-filter>
        </receiver>
        <receiver android:name="com.onesignal.UpgradeReceiver" >
            <intent-filter>
                <action android:name="android.intent.action.MY_PACKAGE_REPLACED" />
```


Recommendation:

Components without explicit access permissions should be exceptions. Unless, the component is really intended to be accessible to all, developers should protect components from misuse by malicious applications by explicitly defining the access permissions in the manifest file.


This receiver has a intent filter with 

`android:name="android.intent.action.MY_PACKAGE_REPLACED"`

This would be especified with the package of the project no?

**Comment by rgomezp** [comment]
Repost of Michael's response in #773:
There is no known security flaw here, also with the specific receiver you mentioned above. No data is actually read with it, but instead is used to re-kickoff services. Also unless explicitly defined these cannot be controlled by an outside source.

**Comment by Hanzofm** [comment]
Could you explain and argument with a bit more detail your reasons for I can ‘copy and paste’ for the auditing company please.

Thanks a lot for your time

**Comment by rgomezp** [comment]
@Hanzofm,
Only the system can broadcast the filter `"android.intent.action.ACTION_BOOT_COMPLETED"` so there is no security threat here.
