### ISSUE TITLE
App_ID and User_ID how are they generated

### ISSUE THREAD

**Issue by veso266** [OneSignal/OneSignal-Android-SDK#764]
**Description:**
Hi I am realy fascinated about your app and player IDs that you generate for OneSignal
and would like to generate something similar for one of my apps
so how are App_ID and Player_ID generated?

app_id: e0062c76-20d6-4534-b2bb-7f2d220e8df2
player_id: a9597b22-7a83-44be-ba2f-22307f599574

does Player_ID have App id in it and OS type and all device parameters that device sends over to here https://onesignal.com/api/v1/players when registering

why are "-" for? is it for readability only or does it have any purpose? 

**Environment**

1. Latest version of SDK
2. Added with Maven

**Steps to Reproduce Issue:**

question

**Anything else:**

I know I should not share my App_ID and Player_ID but they are examples so I don't care if somebody abuses them

PS: How to you convert between APNs and FCM payloads on OneSignal backend?

Thanks for Anwsering and Best Regards

**Comment by rgomezp** [comment]
Hi. I'm happy to hear you're fascinated with our identifiers. The id's are of the UUID format which you can read all about [here](https://en.wikipedia.org/wiki/Universally_unique_identifier).

The dashes are to separate by time, version, clock_seq_hi, clock_seq_lo, node, as indicated in the original [rfc](http://www.ietf.org/rfc/rfc4122.txt).

**Comment by veso266** [comment]
Thanks
