### ISSUE TITLE
Converting between APN and FCM Message

### ISSUE THREAD

**Issue by veso266** [OneSignal/OneSignal-Android-SDK#766]
**Description:**

Hi again I was wondering how do you handle diference between APN and FCM/GCM messages on the backend, does your frontend send FCM message to the backend and then some function just convert it to APN or do you use some custom format for that (if you do, what kind of format do you use for that)

**Environment**

**Steps to Reproduce Issue:**

question

**Anything else:**

Thanks for Anwsering and Best Regards

**Comment by gdeglin** [comment]
Hi. OneSignal handles communication with the APN Service and FCM separately. Basically, when you send a notification via the OneSignal API or dashboard, we make individual API calls to APNS and FCM, each with its own protocol, to deliver your message.

You can learn more about some of the more complex technical details of our backend infrastructure on our blog: https://onesignal.com/blog/rust-at-onesignal/
