### ISSUE TITLE
Handling Push Message Payload from Frontend to BackEnd

### ISSUE THREAD

**Issue by veso266** [OneSignal/OneSignal-Android-SDK#767]
**Description:**

Hi again again: I read your wonderfull post: https://onesignal.com/blog/rust-at-onesignal/
about Rust

I know that APN and GCM/FCM uses diferent payloads
APNS one looks like this
```json
{"aps" : { "title" : "You have a notification", "body" : "Which has some text you can read if you want", "badge" : 1, "sound" : "default" }}
```
there is also an alert version
```json
{"aps" : { "alert" : "This is the alert text that I don't see any purpose in", "badge" : 1, "sound" : "default" }}
```

while 
FCM/GCM ones look like:
```json
{
            "alert" : "This is the alert text that I don't see any purpose in",
            "title" : "You have a notification",
            "subtitle" : "Some text goes here",
            "tickerText" : "Which has some text you can read if you want",
            "vibrate": 1,
            "sound": 1,
            "largeIcon": "large_icon",
            "smallIcon": "small_icon"
}
```

now you probably have some universal message that you send from frontend to backend so your classes then generate APN or FCM one from it

**Environment**

**Steps to Reproduce Issue:**

question
**Anything else:**
How would I (so you here in OneSignal) combine FCM and APN payload so you only send one Payload to backend?
Thanks for Anwsering and Best Regards

**Comment by jkasten2** [comment]
@veso266 You can a POST from your backend to `https://onesignal.com/api/v1/notifications` send a notification to both iOS and Android platforms in one call.
Example:
```JSON
{
  "app_id": "5eb5a37e-b458-11e3-ac11-000c2940e62c",
  "included_segments": ["All"],
  "data": {"foo": "bar"},
  "contents": {"en": "English Message"}
}
```

OneSignal will take care of sending the correct format to APNs and FCM for you.

**Comment by veso266** [comment]
Thanks thats what I was confused about :smile: 

PS: what is the diference between alert and title payload in APN?

**Comment by rgomezp** [comment]
**Title:**
> A short string describing the purpose of the notification. Apple Watch displays this string as part of the notification interface. This string is displayed only briefly and should be crafted so that it can be understood quickly. This key was added in iOS 8.2.

**Title Payload:**
> Include this key when you want the system to display a standard alert or a banner. The notification settings for your app on the user’s device determine whether an alert or banner is displayed. \n The preferred value for this key is a dictionary, the keys for which are listed in Table 9-2. If you specify a string as the value of this key, that string is displayed as the message text of the alert or banner. \n The JSON \U notation is not supported. Put the actual UTF-8 character in the alert text instead.
