### ISSUE TITLE
notificationOpened - Missing information

### ISSUE THREAD

**Issue by kistitan** [OneSignal/OneSignal-Android-SDK#77]
As this is my first message here I rather start with the compliment that I really like the concept of providing several extension points for the app developers to override, modify the default notification behaviour. Pretty nice :)

In most of the case I can find my way around, however sometimes I have a bit of hard time to figure out how can I achieve our needs with the current API.
Like in this case:

When the _notificationOpened_ callback is invoked we receive 3 arguments: _message_ _additionalData_ and _isActive_.

It was not clear for me that _additionalData_ is not only for our extension data but also the onsignal defined values are there (title, etc). (especiall because message was provided as a separate arument)

The only problem with this solution that the default parameters do overwrite our custom data if we use the same names (e.g. launchUrl, etc). It is fine for me to use different names for our custom data, but I did not find it in the documentation that there are some specific ids we should not use.

But this was rather a side issue currently the main issue I face is that the _group_ field is not available in the _additionalData_.
I would like to handle the _stacked_notifications_ based on the group field but at this point this information is simply not available.

Something like :

               if (data.has("grp"))
                  additionalDataJSON.put("group", data.optString("grp"));

in OneSignal.java?

Or any other suggestion?

Thanks

**Comment by jkasten2** [comment]
@kistitan Thanks for digging into the code, I would recommend adding your group code to line [978 in OneSignal.java](https://github.com/OneSignal/OneSignal-Android-SDK/blob/1b8eb3728beedd02ccf14168d7f1cc42ec099116/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java#L978).

You have some good points about `NotificationOpenedHandler`, it is over due for a refactor and I'll be looking into creating a result class like [OSNotificationPayload](https://github.com/OneSignal/OneSignal-Android-SDK/blob/1b8eb3728beedd02ccf14168d7f1cc42ec099116/OneSignalSDK/onesignal/src/main/java/com/onesignal/OSNotificationPayload.java).

Thanks.

**Comment by drayan85** [comment]
@jkasten2 I am also facing same issue to access the notification id when user click and open the notification (Access the OSNotificationPayload in the NotificationOpenedHandler).

May i know your priority on this issue which i can consider for release ? thanks

**Comment by jkasten2** [comment]
@drayan85 We are shooting for a release next week with this feature included.

**Comment by jkasten2** [comment]
@drayan85 @kistitan The [NotificationOpenedHandler](https://documentation.onesignal.com/docs/android-sdk-api#NotificationOpenedHandler) interface in the new 3.0 SDK passes a [OSNotificationOpenResult](https://documentation.onesignal.com/docs/android-sdk-api#OSNotificationOpenResult) instance which now contains a the OneSignal notification id. It will also contain a group key if it was set on the notification. They can be accessed like this now.
```Java
class ExampleNotificationOpenedHandler implements OneSignal.NotificationOpenedHandler {
  @Override
  public void notificationOpened(OSNotificationOpenResult result) {
    OSNotificationPayload payload = result.notification.payload;
    Log.d("OneSignalDebug", "Notification with OneSignal id: " + payload.notificationId);
    if (payload.groupKey != null)
       Log.d("OneSignalDebug", "Notification with groupKey: " + payload.groupKey);
  }
}
```

**Comment by drayan85** [comment]
@jkasten2 Thanks a lot.
