### ISSUE TITLE
I am new to android studio, and I HAVE DOWWNGRADED from android studio 3.3 to 2.2 now facing error like:-

### ISSUE THREAD

**Issue by atanusenstudy** [OneSignal/OneSignal-Android-SDK#771]
sorry I am new and dont know how to write issue please help.
at first:-
https://drive.google.com/open?id=1I22H1tCMP8ydGw-AHkoj_XLsPv-uBxlt
then I add
 maven {
            url "https://maven.google.com"
        }
line in build gradel;
then other error message occur:-
https://drive.google.com/open?id=11Wn0QKbEpoBCOqCBy2PrDHiQ_FOWPPKb

**Description:**

(your description here)

**Environment**

**Steps to Reproduce Issue:**

1. (your steps here)
2.
3.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by veso266** [comment]
Why did you downgrade Android Studio? Just use the latest one

The first error can be solved by adding google maven repo to build.gradle

repositories {
        mavenLocal()
        mavenCentral()
        maven {                                  // <-- Add this
            url 'https://maven.google.com/' 
            name 'Google'
        }
    } 
Tip: if you are lazy you can press Install repositories and sync project (Android studio is sometimes good at performing the right fixes for you)

as for the second error, try updating you gradle, if that fails, stackoverflow is you friend 😄 https://stackoverflow.com/questions/51024717/error-more-than-one-library-with-package-name-android-support-graphics-drawabl

**Comment by atanusenstudy** [comment]
now this has come:-
https://drive.google.com/open?id=1XZxlGMg4TFJoHPJ9nrnjOx4Hlq8DgnC5

I have reinstalled android studio 2.2 and this time no engine or emulator has downloaded and 
 
I want to know is everything is same in android studio 3.3 because I want to learn android and I have video of android studio 2.2 please help.

**Comment by veso266** [comment]
Android studio 3.3 should be the same as 2.2 just better 😄 
its better to learn the latest tools then (if you realy need this badly) downgrade once you created couple of apps in the latest version 😄 
BTW; What tutorial are you watching?


go to style.xml and change 
```xml
<style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
```
to
```xml
<style name="AppTheme" parent="Base.Theme.AppCompat.Light.DarkActionBar">
```
at least SO: https://stackoverflow.com/a/45881066 says so 😄

**Comment by atanusenstudy** [comment]
Udemy - The Complete Android N Developer Course

**Comment by jkasten2** [comment]
@atanusenstudy We can only support issues related to the OneSignal SDK here. For issues with Android Studio and Google Libraries I would recommend stackoverflow.

Thanks.
