### ISSUE TITLE
Improve security of services and receivers of manifest

### ISSUE THREAD

**Issue by Hanzofm** [OneSignal/OneSignal-Android-SDK#773]
Hi, first come from [this](https://github.com/OneSignal/OneSignal-Android-SDK/issues/761) closed issue, sorry I am not sure that clossed issues be reviewed.

We have submitted your answer to the security issue with the permissions and the answer for it is this:

_This component should be divided into two parts so that the system broadcast portion can be private, reducing the exposed surface of the application. Separate the functionality that handles system messages from the functionality that handles other messages._

-On the other hand they have reported another problem with permissions on receivers on:

**Sink:**

```
File Path : /platforms/android/app/build/intermediates/manifests/full/debug/AndroidManifest.xml Line Number : 180
</intent-filter>
        </receiver>
        <receiver android:name="com.onesignal.UpgradeReceiver" >
            <intent-filter>
                <action android:name="android.intent.action.MY_PACKAGE_REPLACED" />
```
**Recommendation:**

Components without explicit access permissions should be exceptions. Unless, the component is really intended to be accessible to all, developers should protect components from misuse by malicious applications by explicitly defining the access permissions in the manifest file.

This receiver has a intent filter with

`android:name="android.intent.action.MY_PACKAGE_REPLACED"`

This would be especified with the package of the project no? Sorry but we have blocked the release for this problem. 

Thanks a lot

**Comment by mikechoch** [comment]
There is no known security flaw here, also with the specific receiver you mentioned above. No data is actually read with it, but instead is used to re-kickoff services. Also unless explicitly defined these cannot be controlled by an outside source.

**Comment by rgomezp** [comment]
Duplicate of #761
