### ISSUE TITLE
Bad notification posted from package Name Couldn't expand RemoteViews for: StatusBarNotification on Android 4.4.4

### ISSUE THREAD

**Issue by superdiazzz** [OneSignal/OneSignal-Android-SDK#776]
**Description:**
I still received error crash in OS 4.4.4 (Kitkat) 100% occur

**Environment**
dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.11.0, 0.99.99]'
    }

```gradle
    implementation 'com.onesignal:OneSignal:[3.9.1, 3.99.99]'

```

![image](https://user-images.githubusercontent.com/10770867/59318299-c06e3b00-8cf0-11e9-9538-5fc505af3b07.png)

**Code Snippet**
```
public class OneSignalExtenderService extends NotificationExtenderService {

    @Override
    protected boolean onNotificationProcessing(OSNotificationReceivedResult notification) {

        Timber.d("ONESIGNAL masuk receiver!");

        boolean focus = notification.isAppInFocus;

        Timber.d("ONESIGNAL focus %s", focus);

        OverrideSettings overrideSettings = new OverrideSettings();
        overrideSettings.extender = builder -> {

            Uri defaultUriSound = RingtoneManager.getDefaultUri(RingtoneManager.TYPE_NOTIFICATION);
            builder.setSmallIcon(R.drawable.ic_notification);
            builder.setBadgeIconType(NotificationCompat.BADGE_ICON_SMALL);
            builder.setContentTitle(notification.payload.title);
            builder.setContentText(notification.payload.body);
            builder.setAutoCancel(true);
            builder.setSound(defaultUriSound);
            builder.setTicker(notification.payload.body);
            builder.setCategory(NotificationCompat.CATEGORY_MESSAGE);
            builder.setPriority(NotificationCompat.PRIORITY_MAX);
            return builder;
        };

        // active this below if you want to overriding standart notifications
         OSNotificationDisplayedResult d = displayNotification(overrideSettings);
        return false;
    }
}
```
I Knew i have to make sure all drawable consist of 4 version dpi (hdpi, mdpi, xhdpi, xxhdpi). I think thats okay since first time i installed OneSignal there was no problem, but after i change my targetversionSdk to 28 for next release and feature, crash drastically occur

**Steps to Reproduce Issue:**
After update application from playstore then open it then crash occurs

**Anything else:**

> Fatal Exception: android.app.RemoteServiceException: Bad notification posted from package mobile.android.tribun: Couldn't expand RemoteViews for: StatusBarNotification(pkg=mobile.android.tribun user=UserHandle{0} id=-1279033265 tag=null score=0: Notification(pri=0 icon=7f0800b4 contentView=mobile.android.tribun/0x1090069 vibrate=null sound=null defaults=0x0 flags=0x18 when=1560300626000 ledARGB=0x0 contentIntent=Y deleteIntent=Y contentTitle=100 contentText=129 tickerText=N kind=[null] 2 actions))
>        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1461)
>        at android.os.Handler.dispatchMessage(Handler.java:102)
>        at android.os.Looper.loop(Looper.java:136)
>        at android.app.ActivityThread.main(ActivityThread.java:5584)
>        at java.lang.reflect.Method.invokeNative(Method.java)
>        at java.lang.reflect.Method.invoke(Method.java:515)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
>        at dalvik.system.NativeStart.main(NativeStart.java)

  I have watched this issue [263](https://github.com/OneSignal/OneSignal-Android-SDK/issues/263) but, when i saw the reconcile only for Nougat version.

**Comment by rgomezp** [comment]
Hello,
I don't see onesignal in the stack trace. Could you please include the full log using a [pastebin](https://pastebin.com) link? Also, what happens if you change the targetversionSDK back to the previous?

**Comment by superdiazzz** [comment]
@rgomezp Please take a look [full-log](https://pastebin.com/T6pJM0D2)
Actually, i want to use android jetpack so i put all version in app.gradle to latest update. Like compileSdkVersion, buildToolsVersion, targetSdkVersion to 28 (previously on version 27). There was no change from NotificationExtenderService, yes i did not find this kind of crash before (version 27). But if i turn it back to 27 i got error building, because i put so many code after this changing

**Comment by jkasten2** [comment]
@superdiazzz I did a deeper dive on the "Bad notification" issue in https://github.com/OneSignal/OneSignal-Android-SDK/issues/263#issuecomment-348664720.

In your case though it is most likely an issue where your custom sound is not found on some devices.
```java
builder.setSound(defaultUriSound);
```
I would add some runtime checks to make sure it is available before making this call.

**Comment by superdiazzz** [comment]
@jkasten2 should i check if defaultUriSound is not null first?

**Comment by jkasten2** [comment]
yes, just incase it isn't found. Also may want to look into if `context.getResources().getIdentifier()` is able to resolve a non-zero value. If `getIdentifier()` returns `0` then the resource could not be found.
However I believe `RingtoneManager.getDefaultUri(RingtoneManager.TYPE_NOTIFICATION)` will just be the default notification sound which OneSignal defaults already. OneSignal uses `setDefaults(Notification.DEFAULT_SOUND)` so I don't believe you need this code.

However `setSound` won't work on Android Oreo 8.0 and newer devices. You have to create an Android Notification Category (AKA Notification Channel) and set the custom sound there. Same goes for `setPriority`.

This can be configured on the OneSignal dashboard.
https://documentation.onesignal.com/docs/android-notification-categories

Lastly the OneSignal SDK is already setting the following so you can remove them from your code to clean things up.
```java
// Set already by default by the OneSignal SDK.
builder.setContentTitle(notification.payload.title);
builder.setContentText(notification.payload.body);
builder.setAutoCancel(true);
builder.setTicker(notification.payload.body);

// Can set these via the OneSignal dashboard / REST API instead
builder.setSmallIcon(R.drawable.ic_notification);
builder.setPriority(NotificationCompat.PRIORITY_MAX);
``

**Comment by superdiazzz** [comment]
@jkasten2 Thank your for advise, this is super... i will try it, then make report later

**Comment by superdiazzz** [comment]
```
public class OneSignalExtenderService extends NotificationExtenderService {

    @Override
    protected boolean onNotificationProcessing(OSNotificationReceivedResult notification) {

        Timber.d("ONESIGNAL masuk receiver!");

        boolean focus = notification.isAppInFocus;

        Timber.d("ONESIGNAL focus %s", focus);

        OverrideSettings overrideSettings = new OverrideSettings();
        overrideSettings.extender = builder -> {

            Uri defaultUriSound = RingtoneManager.getDefaultUri(RingtoneManager.TYPE_NOTIFICATION);
            builder.setSmallIcon(R.drawable.ic_notification);
            builder.setBadgeIconType(NotificationCompat.BADGE_ICON_SMALL);
            builder.setContentTitle(notification.payload.title);
            builder.setContentText(notification.payload.body);
            builder.setAutoCancel(true);
            if(defaultUriSound != null){
                if(RingtoneManager.getRingtone(this, defaultUriSound) != null){
                    builder.setSound(defaultUriSound);
                }
            }
            builder.setTicker(notification.payload.body);
            builder.setCategory(NotificationCompat.CATEGORY_MESSAGE);
            builder.setPriority(NotificationCompat.PRIORITY_MAX);
            return builder;
        };

        // active this below if you want to overriding standart notifications
         OSNotificationDisplayedResult d = displayNotification(overrideSettings);
        return false;
    }
}
```
@jkasten2 I dunno if this snippet code is right but when i using this code, the error still occured. And still in the same devices (OS Kitkat)
![image](https://user-images.githubusercontent.com/10770867/59573064-4a484a80-90db-11e9-8313-aebeb768755a.png)

**Comment by superdiazzz** [comment]
I also have tried with this code, and trying to use setting config from API (backend). But the result still same, crash occured when received notification. But when i tested by dashboard, everything is okay.
```
public class OneSignalExtenderService extends NotificationExtenderService {

    @Override
    protected boolean onNotificationProcessing(OSNotificationReceivedResult notification) {

        Timber.d("ONESIGNAL masuk receiver!");

        boolean focus = notification.isAppInFocus;

        Timber.d("ONESIGNAL focus %s", focus);

        OverrideSettings overrideSettings = new OverrideSettings();
        overrideSettings.extender = builder -> {
            builder.setCategory(NotificationCompat.CATEGORY_MESSAGE);
            builder.setPriority(NotificationCompat.PRIORITY_MAX);
            return builder;
        };

        // active this below if you want to overriding standart notifications
         OSNotificationDisplayedResult d = displayNotification(overrideSettings);
        return false;
    }
}
```
After crash, whenever i open the apps it is going to crash again (after received notifications). So I can't use apps again, the only one things that i can solve this issue is to clear data then open again. So it's works but i loose my local data.

**Comment by rgomezp** [comment]
@superdiazzz ,
Thanks for your patience while we investigate

**Comment by superdiazzz** [comment]
Dear OneSignal Team, i found something good about my project. After i compare value betweet "sent by dashboard" and "by API server" there some difference. Like logo icon for Action Button. Then i push my team to including it inside request then everything is fine now. I think this is my suspend problem. thank you for your attention and your works guys, sorry if i did some mistake. 
this issue can be closed
