### ISSUE TITLE
Player changes ignored when provideUserConsent(false) is called too quickly

### ISSUE THREAD

**Issue by rgomezp** [OneSignal/OneSignal-Android-SDK#777]
Currently, any changes to a player don't propagate if `provideUserConsent(false)` is called too quickly afterward. When `OneSignal.provideUserConsent(false);` is called the OneSignal SDK stops sending any updates to onesignal.com, including any unsynced changes. 

See issues #565 and #647 for more details.

**Comment by aleksandra-majchrzak** [comment]
Is there any work in progress with this bug? I guess I can post `provideUserConsent` with delay, but this seems to be not a clean solution.

**Comment by Jeasmine** [comment]
Hey @aleksandra-majchrzak, we are working on improvements under [Beta major release](https://github.com/OneSignal/OneSignal-Android-SDK/tree/major_release_4.0.0) we will love to have feedback regarding this issue

**Comment by rgomezp** [comment]
This should now be resolved in version 4.0+
