### ISSUE TITLE
NotificationCompat.Extender is not used for notifications with grouping

### ISSUE THREAD

**Issue by kistitan** [OneSignal/OneSignal-Android-SDK#78]
In _showNotification_ method of _GenerateNotification_ class you use the _NotificationBuilder.extend()_ to add the extender, but if the group field is not empty you rather call the _createSummaryNotification()_ method that creates a new _NotificationBuilder_, and there you do not add the extender any more.

**Comment by jkasten2** [comment]
@kistitan Since the look of the summary notification would differ from the individual notifications it would need to have isn't own extender. This wasn't initially added to the `NotificationExtenderService` as we didn't want it to delay the feature.

Lets consolidate this with issue #68

Thanks.
