### ISSUE TITLE
Using NotificationExtenderService to start and stop alarm-like behavior

### ISSUE THREAD

**Issue by sunweiyang** [OneSignal/OneSignal-Android-SDK#783]
**Description:**
I'm trying to create an alarm-style push notification; in other words, I'm using a remote notification to trigger a notification on the app  with looping sound and looping vibration, and I wish for the sound and vibration to stop when the app is opened (either through tapping the app icon or through tapping the notification). 

1. I've been able to use NotificationExtenderService to start the sound and vibration, but I can't figure out how to stop it when the app returns to the foreground.
2. When the app is killed, an incoming notification causes the audio to play only for a brief time period (~0.2 seconds). How can this audio be made to last for the killed-app scenario?

**Environment**
* OneSignal SDK version 3.10.5
* Android targetSdkVersion 28

**Steps to Reproduce Issue:**
Here is my NotificationExtenderService:
```
public class OneSignalExtenderService extends NotificationExtenderService {
    @Override
    protected boolean onNotificationProcessing(OSNotificationReceivedResult receivedResult) {
        JSONObject additionalData = receivedResult.payload.additionalData;
        try {
            if (additionalData.has("command")) {
                String command = additionalData.getString("command");
                if (command.equals("alarm")) {
                    MediaPlayer mMediaPlayer = MediaPlayer.create(this, R.raw.alarm);
                    mMediaPlayer.setAudioStreamType(AudioManager.STREAM_MUSIC);
                    mMediaPlayer.setLooping(true);
                    mMediaPlayer.start();
                    Vibrator mVibrator = (Vibrator) getSystemService(Context.VIBRATOR_SERVICE);
                    long[] pattern = {0, 500, 1000};
                    mVibrator.vibrate(pattern, 0);
                }
            } else {
                ShortcutBadger.applyCount(getApplicationContext(), 1);
            }
        } catch (JSONException e) {
            Log.e("OneSignal", "onNotificationProcessing Failure: " + e.getMessage());
        }

        // Return true to stop the notification from displaying.
        return false;
    }
}
```

**Comment by mikechoch** [comment]
So I think you are creating a little more work for yourself here. We allow with our SDK to attach sound files and add custom vibration patterns. Here is the link to the documentation that can help you with this in the **Appearance** section:
[https://documentation.onesignal.com/reference#create-notification](url)

A good example is shown below using JSON and then you would simply place this in a JSONObject and pass it into `OneSignal.postNotification(JSONObject json, Callback callback)`
```
{
<img width="1126" alt="Screen Shot 2019-06-20 at 6 32 13 PM" src="https://user-images.githubusercontent.com/24537305/59891786-5bb77e00-938b-11e9-9ee8-afac9d656e9b.png">

  "app_id": "5eb5a37e-b458-11e3-ac11-000c2940e62c",
  "android_sound": "notification.wav",
  "contents": {"en": "English Message"}
}
```

In terms of the vibration, this can be done through the dashboard by creating a category shown in the link below:
[https://documentation.onesignal.com/docs/android-notification-categories](url)

Then using the channel id you can apply this category or set of settings in the Android json or from the dashboard.

**Comment by sunweiyang** [comment]
@mikechoch Thank you; however, when I was checking out the category editor, I didn't see options in the category editor to loop the sound resource and vibration pattern indefinitely (until the user opens the app). Can that be accomplished in category editor? Apologies if I missed something on that page.

**Comment by mikechoch** [comment]
Yes this can be done in the category filter, which is the easiest way to provide custom sound and vibration. Then you would simply attach the channel_id to the JSON of the notification or dashboard form.

**Comment by sunweiyang** [comment]
@mikechoch Good to know the scope of this SDK. I went ahead and created a singleton class (`Alarm.java`) that both my `MainActivity` and `NotificationExtenderService` can access (via . Posting it here so that others looking for the same alarm-type functionality can make use of it.

MainApplication.java:
```
public class MainApplication extends Application {
    public static Context mContext;
    ...
}
```

OneSignal extender service class (in my case, OneSignalExtenderService.java):
```
public class OneSignalExtenderService extends NotificationExtenderService {
    @Override
    protected boolean onNotificationProcessing(OSNotificationReceivedResult receivedResult) {
        JSONObject additionalData = receivedResult.payload.additionalData;
        try {
            if (additionalData.has("command")) {
                String command = additionalData.getString("command");
                if (command.equals("alarm")) {
                    Alarm.INSTANCE.start();
                }
            }
        } catch (JSONException e) {
            Log.e("OneSignal", "onNotificationProcessing Failure: " + e.getMessage());
        }
        return false;
    }
}
```

MainActivity.java:
```
public class MainActivity extends Activity {
    ...
    @Override
    public void onResume () {
        super.onResume();
        // Alarm should not be on if app is in foreground
        Alarm.INSTANCE.stop();
    }
    ...
}
```

Alarm.java:
```
package com.example;

import android.content.Context;
import android.media.AudioManager;
import android.media.MediaPlayer;
import android.os.Vibrator;

class Alarm {
    static final Alarm INSTANCE = new Alarm();
    private static MediaPlayer mMediaPlayer;
    private static Vibrator mVibrator;
    private static long[] vibratePattern = {0, 500, 1000};

    private Alarm() {
        instantiatePlayer();
        instantiateVibrator();
    }

    private void instantiatePlayer() {
        mMediaPlayer = MediaPlayer.create(MainApplication.mContext, R.raw.alarm);
        mMediaPlayer.setAudioStreamType(AudioManager.STREAM_MUSIC);
        mMediaPlayer.setLooping(true);
    }

    private void instantiateVibrator() {
        mVibrator = (Vibrator) MainApplication.mContext.getSystemService(Context.VIBRATOR_SERVICE);
    }

    void start() {
        mMediaPlayer.start();
        mVibrator.vibrate(vibratePattern, 0);
    }

    void stop() {
        if (mMediaPlayer.isPlaying()) {
            mMediaPlayer.stop();
            mMediaPlayer.release();
            mVibrator.cancel();
            instantiatePlayer();
            instantiateVibrator();
        }
    }

}
```
Closing this issue; thank you!

**Comment by mikechoch** [comment]
Glad I could help!
