### ISSUE TITLE
if user are connected in some networks the onse signal timezone is wrong

### ISSUE THREAD

**Issue by andresserranoglb** [OneSignal/OneSignal-Android-SDK#787]
**Description:**

we are getting a wrong timezone using the endpoint (https://onesignal.com/api/v1/players/{PlayerId}) Image 2. web service response.
in the dashboard details (Image 1), we have one user using the app in Uruguay but the timezone is from Colombia, so we have some logic to send the notification we check the timezone and calculate, so this person is getting the notification early 

<img width="1196" alt="Screen Shot 2019-06-28 at 5 51 09 PM" src="https://user-images.githubusercontent.com/25957176/60519183-a64cca80-9ca8-11e9-8729-40fe2bf0e362.png">

**Image 1**. One signal  Dashboard

<img width="694" alt="Screen Shot 2019-06-28 at 5 51 27 PM" src="https://user-images.githubusercontent.com/25957176/60519189-aa78e800-9ca8-11e9-9100-96b8a34d4215.png">

**Image 2**. Web service response

**Environment**

**Steps to Reproduce Issue:**

  1.Login whit one user in Colombia  and do logout 
  2. check the time zone using the endpoint (https://onesignal.com/api/v1/players/{PlayerId}) result: Colombia Time zone 
  3. Login whit the same user in Uruguay connected in a corporative  wifi 
  4. check the time zone using the endpoint (https://onesignal.com/api/v1/players/{PlayerId}) 
      **Result**: Colombia Time zone (Image 2.) **Expected**: Uruguay Time zone 

**Anything else:**

Note: we were checking and if we use an LTE or other networks the time zone works as expected, this only happens with some corporate wifi.

**Comment by rgomezp** [comment]
Howdy, 
The timezone is set by [checking the timezone on the device](https://developer.android.com/reference/java/util/TimeZone). Could you please check and confirm that the device shows a different timezone than the expected timezone?

**Comment by andresserranoglb** [comment]
Hi @rgomezp  we did it, we add a breakpoint on the method in the class OneSignal.java

private static int getTimeZoneOffset() {
      TimeZone timezone = Calendar.getInstance().getTimeZone();
      int offset = timezone.getRawOffset();
      
      if (timezone.inDaylightTime(new Date()))
          offset = offset + timezone.getDSTSavings();
      
      return offset / 1000;
   }

and returns the right time zone.

**Comment by rgomezp** [comment]
Howdy,
When you say "corporate wifi" could you be referring to a VPN?

**Comment by andresserranoglb** [comment]
:), no we were using VPN and works well, this only happen connected to corporate wifi

**Comment by rgomezp** [comment]
This is strange. You say that it is returning the right time zone in the breakpoint. Did you test this with the same device on the same network?

**Comment by rgomezp** [comment]
Closing due to no response
