### ISSUE TITLE
Access the OSNotificationPayload.notificationId in OneSignalNotificationOpenedHandler

### ISSUE THREAD

**Issue by drayan85** [OneSignal/OneSignal-Android-SDK#79]
I am trying build a activity feed for the push notification to our app to show the list of all user push notifications. In order show read/unread messages.

I am trying to access the notification id when user open the push notification to mark it as read but in the current OneSignal SDK, I can only access notification id from the extended class of NotificationExtenderService. 

I couldn't access from the implemented class of OneSignal.NotificationOpenedHandler.

Is there anyway i can access from OneSignal.NotificationOpenedHandler, may be i have missed out from the documentation ?

**Comment by jkasten2** [comment]
@drayan85 The [NotificationOpenedHandler](https://documentation.onesignal.com/docs/android-sdk-api#NotificationOpenedHandler) interface in the new 3.0 SDK passes a [OSNotificationOpenResult](https://documentation.onesignal.com/docs/android-sdk-api#OSNotificationOpenResult) instance which now contains a the OneSignal notification id. It can be accessed like this now.
```Java
class ExampleNotificationOpenedHandler implements OneSignal.NotificationOpenedHandler {
  @Override
  public void notificationOpened(OSNotificationOpenResult result) {
    Log.d("OneSignalDebug", "Notification with OneSignal id: " + result.notification.payload.notificationId);
  }
}
```

**Comment by drayan85** [comment]
@jkasten2 Thanks a lot.
