### ISSUE TITLE
NotificationExtenderService onNotificationProcessing result is ignored

### ISSUE THREAD

**Issue by drmms** [OneSignal/OneSignal-Android-SDK#806]
According to the documentation in https://documentation.onesignal.com/docs/service-extensions: 
>       // Return true to stop the notification from displaying.
But no matter what the returning value of NotificationExtenderService.onNotificationProcessing is, the notification is displayed anyway. 

My goal is to get some data from a OneSignal push notification, extending NotificationExtenderService, and not show anything to the user if certains conditions occur. But this doesn't seems to be possible. 

The only way I found was to 
((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).cancel(displayedResult.androidNotificationId);
but this is just a workaround. 

```
public class MarketingNotificationExtenderService extends NotificationExtenderService {
    @Override
    protected boolean onNotificationProcessing(OSNotificationReceivedResult notification) {
        OneSignalPayloadData payload = OneSignalPayloadData.create(this, notification);
        OverrideSettings overrideSettings = new OverrideSettings();
        if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.O) {
            overrideSettings.extender = new NotificationCompat.Extender() {
                @Override
                public NotificationCompat.Builder extend(NotificationCompat.Builder builder) {
                    Context c = MarketingNotificationExtenderService.this;
                    NotificationChannel channel = NotificationChannel.loadOrCreateMarketingChannel(c);
                    builder.setChannelId(channel.getId());
                    return builder;
                }
            };
        }
        OSNotificationDisplayedResult displayedResult = displayNotification(overrideSettings);
        boolean hideNotification = shouldHideNotification(...); // Some logic here
        Log.d("OneSignal","Hide notification " + hideNotification);
        return hideNotification; // I tried also to just return true;
    }
}

```
Using classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.2, 0.99.99]'
and 'com.onesignal:OneSignal:[3.10.0, 3.99.99]'

**Comment by rgomezp** [comment]
Howdy,
Thanks for your patience while we investigate

**Comment by jkasten2** [comment]
@drmms Since you are calling `displayNotification(overrideSettings);` in your code the notification is being displayed at that time, returning `true` after won't have an effect.
