### ISSUE TITLE
Google play services dependencies

### ISSUE THREAD

**Issue by leonardoxh** [OneSignal/OneSignal-Android-SDK#81]
Hi,

Looking into OneSignal SDK on the buildscript this two lines:

https://github.com/OneSignal/OneSignal-Android-SDK/blob/master/OneSignalSDK/onesignal/build.gradle#L38-L39

This lines compiles the Google play services 8.4.0 into the package, if the programmer don't specify a upper version of the play services gcm or play services location, or exclude them of the buildscript this librarys are packed into the application, because it's a compile dependency.

This dependency should be a <code>provided</code> dependency ? So in this way the dependency is valid only for compile time.

For example, on my project we not use the <code>play-services-location</code> dependency, so we remove this dependency with the exclude...

**Comment by jkasten2** [comment]
@leonardoxh They won't automatically be included in your project from `compile` less you set `transitive = true` globally on your project.

For example if you remove the following lines from the example project it will no longer get a Google registration id and there is be missing class errors in the logcat.
https://github.com/OneSignal/OneSignal-Android-SDK/blob/master/Examples/AndroidStudio/app/build.gradle#L37-L39

**Comment by leonardoxh** [comment]
Oh that's nice. Thanks
