### ISSUE TITLE
Send app for scanning?

### ISSUE THREAD

**Issue by emailsubjekt** [OneSignal/OneSignal-Android-SDK#813]
I have searched existing issues for an answer at https://goo.gl/K3KQNT, I have tried your common issues documentation at  https://goo.gl/DmJAj5, I have looked at your contributing guidleines. 
**Description:**

(your description here)

I am getting this warning from Google Play Protect when installing the app, 
https://ibb.co/kqBtY1b

It disappears right away and there's no time to read it just click really fast if you know what it says, I have managed to capture it and that's why I have an image of it as it doesn't happen on every install, just sometimes. Not only that, some of the people that have joined Alpha testing over google play have reported seeing a warning that the app might contain a virus, we had to calm them down telling them that it's a normal procedure to have that warning while in alpha phase but until this image I haven't really been able to trace down the problem. It obviously appears in the class ExampleApplication which I have made according to your instructions on how to parse an incoming notification when clicked. I have adjusted the reader inside to read the notification message and open the right activity within the app accordingly. Nothing else. Yet I'm getting this google play protect warning and some of the users are getting 'this app is a virus' warning and now I see it's because of one signal. Could you please contact google play protect team and tell them about this because it's really unacceptable for this to even happen. I am not even taking people's information and I have read here https://forums.coronalabs.com/topic/73957-onesignal-all-my-apps-removed-from-google-play-store-because-of-onesignal/ that you take all this information and that people have had apps removed from play-store because of similar issues. I'm appalled, please consult play protect ASAP and resolve this immediately! 

Otherwise, everything else is working great and I really have no issues to speak of but this left me dumbfounded in front of my employer, I had to think of a reason and said that play store alpha does that because it's alpha when in reality I had no clue what the hell I was talking about to finally see today that OneSignal is the cause of all this. Please resolve this asap, it's really important, really really important! 

**Environment**

Version 28 - min version 23 
In Gradle 
In DeafultConfig 
        manifestPlaceholders = [onesignal_app_id               : "##########",     
                                // Project number pulled from dashboard, local value is ignored.
                                onesignal_google_project_number: "REMOTE"]
######## - is a number-removed it for security reasons posting here 

  implementation 'com.onesignal:OneSignal:3.10.8'   
This is at the bottom 
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

This is top of the Gradle file 

//////////////////////////////////////////////////////////////////////////////////////////////////

buildscript {
    repositories {
        // ...
        google()
        maven { url 'https://plugins.gradle.org/m2/' }
        maven { url 'https://maven.google.com' }
        maven {
            url 'https://maven.fabric.io/public'
        }
    }
    dependencies {
        // ...
        classpath 'com.android.tools.build:gradle:3.4.2'
        classpath 'io.fabric.tools:gradle:1.29.0'
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.12.1'
    }
}
plugins {
    id 'com.onesignal.androidsdk.onesignal-gradle-plugin' version '0.7.0'
}
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

///////////////////////////////////////////////////////////////////////////////////

**Steps to Reproduce Issue:**

1. (your steps here)
2.
3.

I have added OneSignal SDK to the app, everything works great, users are sending and receiving notifications and on time, this is just a part of my gradle file, probably has nothing to do with all this

Under defaultConfig
   manifestPlaceholders = [onesignal_app_id               : "############",       
                                // Project number pulled from dashboard, local value is ignored.
                                onesignal_google_project_number: "REMOTE"]
 minSdkVersion 23
        targetSdkVersion 28
 multiDexEnabled true
resConfigs "en"

 dexOptions {
//        incremental true
        javaMaxHeapSize "4g"
        preDexLibraries true
        dexInProcess = true
    }

    debug {
            debuggable true
            minifyEnabled false
            shrinkResources false
  release {
            debuggable false
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
I'm using AndroidX with Firebase 
implementation 'androidx.appcompat:appcompat:1.0.2'

  implementation 'com.google.android.gms:play-services-auth:17.0.0'
implementation 'com.google.firebase:firebase-core:16.0.7'

**Anything else:**

(crash stacktraces, as well as any other information here)

I don't have a crash or a stacktrace, I'm not getting anything in either. It's not a crash and in stacktrace I'm not even getting a mention of 'onesignal', 'one-signal', or 'signal' when I do a search.

**Comment by emailsubjekt** [comment]
Now I've tried it without onesignal, only with google places and I get the same window. Maybe you guys are not at fault here, but why would I still be getting that error on a class made specifically for onesignal ??

**Comment by rgomezp** [comment]
Hi @emailsubjekt ,
This doesn't sound like a problem with our SDK. What do you mean the error is on a class made for onesignal specifically? Aren't you getting this regardless?

**Comment by emailsubjekt** [comment]
I have just seen it happen on my friends Samsung S9 for Spotify too. Might not be your problem then, however the class that you can see mentioned in the attached image above is the ExampleClass you provide in your sdk example to allow different activities or fragments to be open according to data sent in a notification that was clicked on. I can't confirm I'm getting this regardless because I can't decouple onesignal right now from my app, not only that I'm not getting it for other apps that I install with Android Studio.
