### ISSUE TITLE
Caused by java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by maliX0024** [OneSignal/OneSignal-Android-SDK#819]
Caused by java.lang.NoClassDefFoundError
com.onesignal.DraggableRelativeLayout$1
com.onesignal.DraggableRelativeLayout.createDragHelper (DraggableRelativeLayout.java:72)
com.onesignal.DraggableRelativeLayout.<init> (DraggableRelativeLayout.java:49)
com.onesignal.InAppMessageView.setUpDraggableLayout (InAppMessageView.java:311)
com.onesignal.InAppMessageView.access$500 (InAppMessageView.java:47)
com.onesignal.InAppMessageView$2.run (InAppMessageView.java:245)
android.os.Handler.handleCallback (Handler.java:739)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1199)

**Comment by jkasten2** [comment]
Closing to merge with #820
