### ISSUE TITLE
ERROR: Duplicate key file collection

### ISSUE THREAD

**Issue by rexi1r** [OneSignal/OneSignal-Android-SDK#823]
@gdeglin I got this error after upgrade Gradle wrapper to 5.5.1 and build tools to com.android.tools.build:gradle:3.6.0-alpha06

what can i do to solve this problem? 
because of another dependency those. need to be those version

**Comment by jkasten2** [comment]
@rexi1r Thanks for reporting the issue, however I am not able to reproduce a build error using that version of the AGP with OneSignal.
Please provide the following information so we can look into the issue further;
1. Please provide the fullstack trace and which task failed
   - Run `./gradlew app:build --stacktrace` from the terminal to do this.
2. Provide your `build.gradle` and your `app/build.gradle` files.

**Comment by rexi1r** [comment]
@jkasten2 
this is stacktrace file:
[stacktrace.txt](https://github.com/OneSignal/OneSignal-Android-SDK/files/3504285/stacktrace.txt)

app/build.gradle:
[build.gradle.txt](https://github.com/OneSignal/OneSignal-Android-SDK/files/3504286/build.gradle.txt)

onesignal/build.gradle:
[build.gradle.txt](https://github.com/OneSignal/OneSignal-Android-SDK/files/3504287/build.gradle.txt)

root/build.gradle:
[build.gradle.txt](https://github.com/OneSignal/OneSignal-Android-SDK/files/3504288/build.gradle.txt)

**Comment by jkasten2** [comment]
@rexi1r The project under the [OneSignalSDK](https://github.com/OneSignal/OneSignal-Android-SDK/tree/master/OneSignalSDK) folder is this repo was designed to develop the SDK it self. It contains a number of settings that you normally would not have in a production app.

I recommend using one of the example projects in the link below to avoid build issues.
https://github.com/OneSignal/OneSignal-Android-SDK/tree/master/Examples
