### ISSUE TITLE
Some Devices Not Subscribing At All and some Subscribing After a few minutes

### ISSUE THREAD

**Issue by AnkitS221** [OneSignal/OneSignal-Android-SDK#833]
I am having some troubles with subscribing to some devices. At first the problem was the date was not current through the logcats which i fixed,now i have distributed my app already.
In one of the devices i had to factory reset the settings which also worked.
But now since it being distributed I am unable to track those devices and what problems they are having for not getting subscribed.
The Device in which i had to factory reset had issues in Logcat like unable to fetch android parameters.
So what can be the problems which will lead to Onesignal not being subscribed and how to keep track of them.
I am using Ionic 3 and have initialised onesignal using following lines
 this.oneSignal.startInit('APP_id', '********');
 this.oneSignal.endInit();
    this.oneSignal.getIds().then(data => {
         this.authService.setDevice(JSON.stringify(data.userId));
  }

Now, here in the getids function I am saving the player id of device in locastorage which will complete my login process but with the device itself not being subscribed to onesignal database won't fetch me the playerid and hence the login process fails.
Please Help....Devices I have tested in are Samsung A9,Acer One 7 4G and lenovo tb 7504x
in the above devices the subscription takes place with some delay.

**Comment by Vietvantue** [comment]
I almost have the same issue. I can get Id but in OneSignal dashboard it says my device is unsubcribed.

**Comment by shah-nishant** [comment]
We are also facing the same issue. Even after reinstalling the app, OneSignal dashboard shows user is not subscribed to the push notification and notifications are not being delivered to such users

**Comment by rgomezp** [comment]
Howdy. We're looking into the issue. Thanks for your patience

**Comment by rgomezp** [comment]
This issue has been resolved. Cheers
