### ISSUE TITLE
OSSubscriptionObserver not invoked on userId changed

### ISSUE THREAD

**Issue by torgeiou** [OneSignal/OneSignal-Android-SDK#834]
**Description:**

It seems to me that OSSubscriptionObserver does not work as intended. I'm retrieving the player id and sending it to a rest api to be stored, but for some reason when using the OSSubscriptionObserver as described in the documentation it does not get invoked when userId is changed. It seems to work when the pushToken is changed, but I can get the player id from this code:
```kotlin
val status: OSPermissionSubscriptionState = OneSignal.getPermissionSubscriptionState()
var player_id = status.subscriptionStatus.userId
Log.i("debug", "playerid = ${player_id}")
```
And by using this to debug, I can see that the userId has been changed, but the the observer will not trigger on that change until I exit and kill the app and then start it up again.

**Environment**

android-sdk version 28 and app written in kotlin with the latests versions of OneSignal.
(depenency gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.4, 0.99.99] and 
implementation 'com.onesignal:OneSignal:[3.11.2, 3.99.99]')

**Steps to Reproduce Issue:**

```kotlin
class App : Application() {
    ...
    fun onCreate()
        ...
        OneSignal.startInit(this)
                .inFocusDisplaying(OneSignal.OSInFocusDisplayOption.Notification)
                .unsubscribeWhenNotificationsAreDisabled(true)
                .init()

        OneSignalObserver(this).onCreate()
```
And this is the observer class:
```kotlin
class OneSignalObserver(var context: Context?)  : OSSubscriptionObserver {

    fun onCreate() {
        OneSignal.addSubscriptionObserver(this)
    }


    override fun onOSSubscriptionChanged(stateChanges: OSSubscriptionStateChanges) {
        Log.i("Debug", "onOSSubscriptionChanged: $stateChanges")
        if (stateChanges.from.userId != stateChanges.to.userId) {

            // get player ID
            var player_id = stateChanges.to.userId
            var injector = Injector()
            var api = injector.provideApi()
            api.addOneSignalPlayerId(AppUtil.getHeaders(context), player_id)
                    .observeOn(AndroidSchedulers.mainThread())
                    .subscribeOn(App.instance?.defaultSubscribeScheduler())
                    .subscribeWith(LongObserver())

            // for testing
            var date: Date = Date()
            OneSignal.sendTag("onOSSubscriptionChanged last invoked", date.getTime().toString())
        }
    }


    private inner class LongObserver : DisposableObserver<Response<OneSignalResponse>>() {
        override fun onNext(t: Response<OneSignalResponse>) {
        }

        override fun onError(e: Throwable) {
            Timber.d(e.localizedMessage)

        }

        override fun onComplete() {

        }
    }
}
```

1. (your steps here)
2.
3.

**Anything else:**

(crash stacktraces, as well as any other information here)

This output shows that the player id was at some point changed, but the onOSSubscriptionChanged was not invoked when that happened.

```
I/Debug: onOSSubscriptionChanged: {"from":{"userId":null,"pushToken":null,"userSubscriptionSetting":false,"subscribed":false},"to":{"userId":null,"pushToken":null,"userSubscriptionSetting":true,"subscribed":false}}
2019-09-04 15:12:52.444 I/debug: playerid = null
2019-09-04 15:13:02.525 I/debug: playerid = 6db13282-0186-476f-808d-678a1c75c44f
```
 
It would help a lot if someone could update the code examples for this in kotlin. At least one kotlin example uses idsAvailable() that is deprecated.

**Comment by rgomezp** [comment]
Thanks for your patience while we investigate.

**Comment by rgomezp** [comment]
The player id should only really change if the player is deleted from the dashboard. In this scenario, it is expected that the new player id will only be generated once the app is reopened. Therefore, this is not really an issue. 

With regard to the kotlin code examples, I will make sure to make a note of that as a feature request. Cheers

**Comment by torgeiou** [comment]
> 

> In this scenario, it is expected that the new player id will only be generated once the app is reopened

Why is this expected? Why not generate the player id on the first launch? For our product this means we can't reach users that installs our apps and tries it out once and then are inactive of waits for notifications. Our primary reason for choosing OneSignal was to be able to reach these users.

**Comment by rgomezp** [comment]
> Why not generate the player id on the first launch?
That's what I'm saying. It will be regenerated once the app launches. But this doesn't really matter unless you are deleting users from the dashboard which I suspect you aren't doing on a large scale since it is very tedious to do.

> For our product this means we can't reach users that installs our apps and tries it out once and then are inactive of waits for notifications. 
As long as they don't unsubscribe, you should still be able to reach them.

I feel like there is something I'm not understanding. Perhaps you could try to rephrase your question or elucidate when it comes to your use case/implementation

**Comment by jkasten2** [comment]
@torgeiou It seems you are not keeping a reference to an instance of your `OneSignalObserver` class anywhere. When you call `OneSignal.addSubscriptionObserver` OneSignal only holds a weak reference so it will be dereferenced if you don't keep a reference to it anywhere else in your code.

I recommend adding a `private var` for  your `OneSignalObserver` instance to your `App` class so it doesn't get garbage collected.

**Comment by rgomezp** [comment]
Closing due to no response

**Comment by AlfredAndroidTedmob** [comment]
Hi.

We faced this issue in 10 Android applications so far (I work in a company), and our users were not happy about the Android version "not working" as compared to the iOS version (we are also waiting for the userId to be generated in order to send it to our server).
I just stumbled across this Github issue, and, well, at least I have a solution now.

**My use case below:**
I wrote a base project for the Android team at our company, and the way I coded to listen the OneSignal userId was meant to make it as modular and easy to use as possible:
```
inline val oneSignalUserIdSingle: Single<String>
    get() = Single.create<String> {
        val userId = OneSignal.getDeviceState()?.userId

        if (!userId.isNullOrEmpty()) {
            //shortcut
            it.onSuccess(userId)
        } else {
            val observer = object : OSSubscriptionObserver {
                override fun onOSSubscriptionChanged(stateChanges: OSSubscriptionStateChanges?) {
                    //TODO add timeout
                    if (stateChanges?.to?.userId != null) {
                        it.onSuccess(stateChanges.to?.userId.orEmpty())
                        OneSignal.removeSubscriptionObserver(this)
                    }
                }
            }
            OneSignal.addSubscriptionObserver(observer)
        }
    }
        .subscribeOn(AndroidSchedulers.mainThread())
```

This is an extension function using RxJava in order to chain an operation to get the userId before an api call. Example (some implementation details removed):
````
class LoginUseCase
@Inject constructor(
    private val api: RestApi,
) : UseCase<Unit, LoginUseCase.UserLoginInfo>() {

    override fun buildUseCaseObservable(params: UserLoginInfo): Observable<Unit> {
        return oneSignalUserIdSingle
            .observeOn(Schedulers.io())
            .flatMap {
                api.login(params.username, params.password)
                    .map { user ->
                        //...
                    }
            }
    }

    data class UserLoginInfo(val username: String, val password: String)
}
````

I think having to hold a strong reference to the observer is not intuitive, as it is only used in a very specific scope (in my code, only if the userId did not exist before); I just hope we don't accidentally remove the strong reference, and face the issue again.

I will have to find a way to write the inline function with a list of strong references for any observers added (with the proper removal of no longer needed references) not accessible by the developers.
