### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException at NotificationExtenderService.java line 112

### ISSUE THREAD

**Issue by DimaKoz** [OneSignal/OneSignal-Android-SDK#84]
Hi there.
I got a [crashlog](https://github.com/OneSignal/OneSignal-Android-SDK/files/405196/log2.txt).
I used a version 2.5.1 of OneSignal.
About devices:
<img width="1122" alt="screen shot 2016-08-07 at 0 42 43" src="https://cloud.githubusercontent.com/assets/3092276/17459221/47a5c7f8-5c40-11e6-8988-2e122c05470e.png">

**Comment by jkasten2** [comment]
@DimaKoz Thanks for the report, just fixed the rare crash in commit 9467856b7aa2d0cd7a4081ecc5da3c3ee50f41ba. It will go out in the next release.
