### ISSUE TITLE
Error on jitpack one signal plugin

### ISSUE THREAD

**Issue by kareemzok** [OneSignal/OneSignal-Android-SDK#843]
Hello,

Suddenly I m getting the following error

`ERROR: Could not GET 'https://jitpack.io/gradle/plugin/com/onesignal/onesignal-gradle-plugin/'. Received status code 522 from server: Origin Connection Time-out`

Also when I m trying to enter  https://jitpack.io/gradle/plugin/com/onesignal/onesignal-gradle-plugin/ I m getting the following:

```
Connection
There seems to be an issue connecting to our servers. Please try again in a few minutes.

```

Any advice, please

**Comment by MasaYanagida** [comment]
I've faced same problem😱

```
Could not GET 'https://jitpack.io/gradle/plugin/com/onesignal/onesignal-gradle-plugin/maven-metadata.xml'. Received status code 522 from server: Origin Connection Time-out
```

---
```
classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.4, 0.99.99]'
implementation 'com.onesignal:OneSignal:[3.11.2, 3.99.99]'
```

**Comment by MasaYanagida** [comment]
I'm not sure but resolved naturally in next day 🙏

**Comment by kareemzok** [comment]
Hey @MasaYanagida , please [check this issue](https://github.com/jitpack/jitpack.io/issues/3983) maybe it will help you solve the issue. I havent tried it yet but it might be helpful

**Comment by rgomezp** [comment]
Thanks @kareemzok

**Comment by MasaYanagida** [comment]
@kareemzok @rgomezp 
Thanks!!
