### ISSUE TITLE
Version Mismatch on maven-push gradle script

### ISSUE THREAD

**Issue by Chuckytuh** [OneSignal/OneSignal-Android-SDK#846]
As the title suggests, there's a mismatch on the maven-push.gradle file and the release version 3.11.4

https://github.com/OneSignal/OneSignal-Android-SDK/blob/849c4e26d90ab38fc8072ab8245b494e301ddd2f/OneSignalSDK/onesignal/maven-push.gradle#L27

**Comment by rgomezp** [comment]
This has been fixed in 3.11.4
