### ISSUE TITLE
Notifications coming up even after turning notifications off on some devices

### ISSUE THREAD

**Issue by Deeptola** [OneSignal/OneSignal-Android-SDK#85]
Issue is on phones with AndroidVersion:22

**Comment by jkasten2** [comment]
@Deeptola Can you check your device on the Users list on the OneSignal dashboard to see if it was marked as unsubscribed? Also note if your uninstall your app and reinstall it you may have a new OneSignal user / player id.

**Comment by jkasten2** [comment]
@Deeptola Any updates?

**Comment by jkasten2** [comment]
@Deeptola We haven't seen any other reports of this issue. Feel free to reopen this if you are able to reproduce or if you have any additional information.

**Comment by Deeptola** [comment]
@jkasten2 is there a possibility that there can be some issues on phones that are very obscure and unknown, coz all the users who have faced this issue are on these kind of phones. 
For example:
DeviceModel:Coolpad CP8676_I02 Coolpad
AndroidVersion:22
AppVersion:18406
DeviceHeight:640.0dp
DeviceWidth:360.0dp
Density:2.0

**Comment by jkasten2** [comment]
@Deeptola It is possible their is a bug in the ROM of the device. Are you disabling notifications with `OneSignal.setSubscription` or from Settings>Apps on the device?
