### ISSUE TITLE
Nullpointer at com.onesignal.OneSignal.startLocationUpdate + 865(OneSignal.java:865)

### ISSUE THREAD

**Issue by superdiazzz** [OneSignal/OneSignal-Android-SDK#851]
**Description:**
Hi OneSignal Team, i have crash reported from crashlytics that related with OneSignal Library.  i using onesignal with these specification

>  implementation('com.onesignal:OneSignal:3.11.2') {
>         exclude group: 'com.google.android.gms'
>     }

**Steps to Reproduce Issue:**
Under investigation

**Anything else:**
This what crashlytics said
> Caused by java.lang.NullPointerException
>        at com.onesignal.OneSignal.startLocationUpdate + 865(OneSignal.java:865)
>        at com.onesignal.OneSignal.startRegistrationOrOnSession + 846(OneSignal.java:846)
>        at com.onesignal.OneSignal.doSessionInit + 761(OneSignal.java:761)
>        at com.onesignal.OneSignal.onAppFocus + 1222(OneSignal.java:1222)
>        at com.onesignal.ActivityLifecycleHandler.handleFocus + 207(ActivityLifecycleHandler.java:207)
>        at com.onesignal.ActivityLifecycleHandler.onActivityResumed + 121(ActivityLifecycleHandler.java:121)
>        at com.onesignal.ActivityLifecycleListener.onActivityResumed + 78(ActivityLifecycleListener.java:78)
>        at android.app.Application.dispatchActivityResumed + 224(Application.java:224)
>        at android.app.Activity.onResume + 1124(Activity.java:1124)
>        at androidx.fragment.app.FragmentActivity.onResume + 456(FragmentActivity.java:456)
>        at android.app.Instrumentation.callActivityOnResume + 1210(Instrumentation.java:1210)
>        at android.app.Activity.performResume + 5468(Activity.java:5468)

**Comment by rgomezp** [comment]
This has been fixed in 3.11.3
