### ISSUE TITLE
Cant launch an Activity after Killing the app with com.onesignal.NotificationOpened.DEFAUL

### ISSUE THREAD

**Issue by RomainDev25** [OneSignal/OneSignal-Android-SDK#852]
[**Description:**]
Hello, I have not exactly the same problem, like this issue #779

When I kill application
Receive notification
Tap
Open Application
And open good activity

But, when I receive notification when app is open, reopen main activity
So I have add this 

`<meta-data android:name="com.onesignal.NotificationOpened.DEFAULT" android:value="DISABLE" />`

Now when app is open good activity is open
Kill app
Receive notification
Tap on it
App doesn't open

**Environment**
SDK OneSignal : 12.4

I don't try service background, but do you have any idea ?

Thanks

**Comment by RomainDev25** [comment]
Hello, I have try with Example application in this repo and I have the same problem.

Same thing
If app is killed, tap notification and open good activity
If app is open, don't open activity

Thanks

` private class ExampleNotificationOpenedHandler implements OneSignal.NotificationOpenedHandler {
      // This fires when a notification is opened by tapping on it.
      @Override
      public void notificationOpened(OSNotificationOpenResult result) {
         OSNotificationAction.ActionType actionType = result.action.type;
         JSONObject data = result.notification.payload.additionalData;
         String launchUrl = result.notification.payload.launchURL; // update docs launchUrl

         String customKey;
         String openURL = null;
         Object activityToLaunch = GreenActivity.class;

         Intent intent = new Intent(getApplicationContext(), (Class<?>) activityToLaunch);
         // intent.setFlags(Intent.FLAG_ACTIVITY_REORDER_TO_FRONT | Intent.FLAG_ACTIVITY_NEW_TASK);
         intent.setFlags(Intent.FLAG_ACTIVITY_REORDER_TO_FRONT | Intent.FLAG_ACTIVITY_NEW_TASK);
        
         startActivity(intent);

        
      }
   }`

**Comment by rgomezp** [comment]
Hello,
Unfortunately, I didn't understand your issue. Could you please try to rephrase it and format it a bit better? Thanks

**Comment by RomainDev25** [comment]
Hello, ok sorry for my english and my explains.

If I add this in manifest
`<meta-data android:name="com.onesignal.NotificationOpened.DEFAULT" android:value="DISABLE" />`

I have this issue 
1. I kill application
2. I send notification
3. I tap on notification
4. Application not start

If I dont add in manifest
If application is started or in focus Main Activity start again, not detail activity
Sometimes, detail activity open, but just one time
If application is killed, detail activity start everytime.
I has try with project in this repo and I have the same problem with two device android 6.0 and 8.1
It's more clear ?

Thank you very much.

**Comment by rgomezp** [comment]
@RomainDev25 ,
Take a look at these docs here: https://documentation.onesignal.com/docs/android-customizations#section-preventing-multiple-instances-of-the-same-activity

**Comment by RomainDev25** [comment]
Ok, I did not see this part of the documentation.
I will test it Thursday of this week.
Thank you. Romain

**Comment by guillaumeAgisHeetch** [comment]
Hey @rgomezp , I am still facing the issue with the same use case.

- Kill my app
- receive a notif
- Click on it to open a custom activity
-> It opens my app but the activity is blank

Here is the sample of my code  : 


`class MyNotificationOpenedHandler(private val context: Context) : OneSignal.NotificationOpenedHandler {

    // This fires when a notification is opened by tapping on it.
    override fun notificationOpened(result: OSNotificationOpenResult) {
        val actionType = result.action.type
        val data = result.notification.payload.additionalData

            val intent = Intent(context, HomepageActivity::class.java)
            intent.flags = Intent.FLAG_ACTIVITY_REORDER_TO_FRONT or Intent.FLAG_ACTIVITY_NEW_TASK
            context.startActivity(intent)
        } `

I have  in my manifest:
`<meta-data android:name="com.onesignal.NotificationOpened.DEFAULT" android:value="DISABLE" />`


HomepageActivity is in singleTop in the manifest.
HomepageActivity is open (onCreate) but the page is blank.
