### ISSUE TITLE
Could not resolve com.google.android.gms:play-services

### ISSUE THREAD

**Issue by kirilamenski** [OneSignal/OneSignal-Android-SDK#858]
I use onesignal 3.11.3 and recently [oss.sonatype.org](https://oss.sonatype.org) started to work intermittently and gradle can't build the project because:

```gradle 
Could not resolve com.google.android.gms:play-services-base:[15.0.0, 16.0.0).
    Required by:
        project :*** > com.onesignal:OneSignal:3.11.3
     > Failed to list versions for com.google.android.gms:play-services-base.
        > Unable to load Maven meta-data from https://oss.sonatype.org/content/repositories/snapshots/com/google/android/gms/play-services-base/maven-metadata.xml.
           > Could not get resource ‘https://oss.sonatype.org/content/repositories/snapshots/com/google/android/gms/play-services-base/maven-metadata.xml’.
              > Could not GET ‘https://oss.sonatype.org/content/repositories/snapshots/com/google/android/gms/play-services-base/maven-metadata.xml’.
                 > Read timed out
  > Could not resolve com.google.android.gms:play-services-base:[15.0.1,16.0.0).
    Required by:
        project :*** > com.google.android.gms:play-services-location:15.0.1
     > Skipped due to earlier error
  > Could not resolve com.google.android.gms:play-services-basement:[15.0.1,16.0.0).
    Required by:
        project :*** > com.google.android.gms:play-services-location:15.0.1
        project :*** > com.google.android.gms:play-services-places-placereport:15.0.1
     > Skipped due to earlier error
  > Could not resolve com.google.android.gms:play-services-tasks:[15.0.1,16.0.0).
    Required by:
        project :*** > com.google.android.gms:play-services-location:15.0.1
     > Skipped due to earlier error
```

Is it possible to make onesignal work independently of the remote repository? I tried to enable Gradle to work offline, but this does not resolve the error it still requires these libraries.

I would really appreciate your help. Thanks!

**Comment by jkasten2** [comment]
@kirilamenski The `OneSignal-Android-SDK` it self is found but some of its dependencies could not be found.

The issue is most likely related to the `OneSignal-Gradle-Plugin` note below.
https://github.com/OneSignal/OneSignal-Gradle-Plugin/issues/91

The `OneSignal-Gradle-Plugin` can be removed as a work around but then you will need to resolve any mismatch dependencies yourself.

If you can provide exact steps to reproduce the issue with a new project we can take another look at the issue. We haven't been able to reproduce the issue in the past

**Comment by kirilamenski** [comment]
@jkasten2 Thank you for the reply and for the link. I found the answer here  [in this post](https://github.com/OneSignal/OneSignal-Gradle-Plugin/issues/91#issuecomment-454369551). You just need to exclude gms from the library and add it yourself.

**Comment by jkasten2** [comment]
@kirilamenski Ah good find, I overlooked it. I'll update my post on the summary of the problem to include that work around https://github.com/OneSignal/OneSignal-Gradle-Plugin/issues/91#issuecomment-495409126
