### ISSUE TITLE
NotificationExtenderService - Add support for setDeleteIntent or add event for it

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-Android-SDK#86]
#### Current limitation

Calling `setDeleteIntent` currently has no effect when calling this from the `NotificationCompat.Extender`. This is overridden by the OneSignal SDK to ensure the summary notifications are shown correct, not restored after dismissing, and to maintain the correct badge count.
#### Implementation options
- Provide a new interface / abstract class or new method to `NotificationExtenderService` which will fire on a dismissed OneSignal notification.
- The OneSignal SDK maybe able to detect `setDeleteIntent` was called from the app developer's code and serialize it with [writePendingIntentOrNullToParcel](https://developer.android.com/reference/android/app/PendingIntent.html#writePendingIntentOrNullToParcel%28android.app.PendingIntent, android.os.Parcel%29) then de-serialize it with [readPendingIntentOrNullFromParcel](https://developer.android.com/reference/android/app/PendingIntent.html#readPendingIntentOrNullFromParcel%28android.os.Parcel%29). The recreated Intent can then be fired from the OneSignal's internally set DeleteIntent.
  - `Parcel` isn't designed to be saved to persistent storage so it may need to be serialized in a custom way or the `PendingIntent` may need to be serialized into something else.

**Comment by DennyWeinberg** [comment]
+1 to be able to pass pendingIntent while using NotificationCompat.Extender

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration
