### ISSUE TITLE
OneSignal with a TWA: how to do it?

### ISSUE THREAD

**Issue by SebastienTainon** [OneSignal/OneSignal-Android-SDK#868]
**Description:**

Trusted Web Activities (TWA) are a new way to create Android applications from websites. Google has written a guide about how to create a TWA: https://developers.google.com/web/updates/2019/02/using-twa

There is currently nothing in the OneSignal documentation about TWA: what is the best practice to handle notifications in a TWA?

Should we handle it like a PWA and don't include the Onesignal Android SDK (and use web push notifications) or should we integrate the SDK into the TWA to benefit from Android native notifications?

In this issue, the issue author tries to integrate the Onesignal Android SDK in a TWA but is stuck by a duplicate class problem: https://github.com/OneSignal/OneSignal-Android-SDK/issues/762

**Comment by rgomezp** [comment]
Thanks for your recommendation. We will consider adding this in the future

**Comment by rgomezp** [comment]
We will continue tracking this request internally

**Comment by pharidali** [comment]
implementation ('com.onesignal:OneSignal:3.12.7') {
        exclude group: "com.android.support", module: "customtabs"
    }

This will work :)

**Comment by Vegas10128** [comment]
> ```
>  implementation ('com.onesignal:OneSignal:3.12.7') {
>         exclude group: "com.android.support", module: "customtabs"
>     }
> ```
> 
> This will work :)

is this the only code we need to add to the gradle? or do we need to add the onesignal key as well?

**Comment by cp1797** [comment]
Hey! Would really appreciate some closure to this. I've got a TWA app as well and I've implemented OneSignal for Web Push at the moment. Is the above mentioned comment the right way to go for the Android implementation or are we better off using the Android SDK or wrapping it in Cordova?

**Comment by Vegas10128** [comment]
> ```
>  implementation ('com.onesignal:OneSignal:3.12.7') {
>         exclude group: "com.android.support", module: "customtabs"
>     }
> ```
> 
> This will work :)

No it does not, receive following error in android studio. 

"Manifest merger failed with multiple errors, see logs"

**Comment by jkasten2** [comment]
## Issue
The issue is OneSignal-Android-SDK 3.x.x uses the Android Support Library and `com.google.androidbrowserhelper:androidbrowserhelper` uses AndroidX / Jetpack. If you have a mix of these in your project you have to enable Jetifier.

To fix the build issue there are two options:

## Option 1 - Enable Jetifier
Open your project's `gradle.properties` and add the following two lines:
```
android.useAndroidX=true
android.enableJetifier=true
```

## Option 2 - Upgrade to OneSignal-Android-SDK 4.x.x 
Upgrade to OneSignal-Android-SDK 4.x.x which has been updated to use AndroidX / Jetpack. See the step-by-step migration guide to upgrade easily.
https://documentation.onesignal.com/docs/step-by-step-android-native-3x-to-400-upgrade-guide


## Testing
I have verified these options fix the build issue with Google's TWA example project:
https://github.com/GoogleChromeLabs/svgomg-twa

**Comment by mashwishi** [comment]
> ```
>  implementation ('com.onesignal:OneSignal:3.12.7') {
>         exclude group: "com.android.support", module: "customtabs"
>     }
> ```
> 
> This will work :)

`
Duplicate class android.support.customtabs.ICustomTabsCallback found in modules browser-1.0.0-runtime (androidx.browser:browser:1.0.0) and jetified-customtabs-e849e45c90-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:e849e45c90)
Duplicate class android.support.customtabs.ICustomTabsCallback$Stub found in modules browser-1.0.0-runtime (androidx.browser:browser:1.0.0) and jetified-customtabs-e849e45c90-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:e849e45c90)
Duplicate class android.support.customtabs.ICustomTabsCallback$Stub$Proxy found in modules browser-1.0.0-runtime (androidx.browser:browser:1.0.0) and jetified-customtabs-e849e45c90-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:e849e45c90)
Duplicate class android.support.customtabs.ICustomTabsService found in modules browser-1.0.0-runtime (androidx.browser:browser:1.0.0) and jetified-customtabs-e849e45c90-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:e849e45c90)
Duplicate class android.support.customtabs.ICustomTabsService$Stub found in modules browser-1.0.0-runtime (androidx.browser:browser:1.0.0) and jetified-customtabs-e849e45c90-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:e849e45c90)
Duplicate class android.support.customtabs.ICustomTabsService$Stub$Proxy found in modules browser-1.0.0-runtime (androidx.browser:browser:1.0.0) and jetified-customtabs-e849e45c90-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:e849e45c90)
Duplicate class android.support.customtabs.IPostMessageService found in modules browser-1.0.0-runtime (androidx.browser:browser:1.0.0) and jetified-customtabs-e849e45c90-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:e849e45c90)
Duplicate class android.support.customtabs.IPostMessageService$Stub found in modules browser-1.0.0-runtime (androidx.browser:browser:1.0.0) and jetified-customtabs-e849e45c90-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:e849e45c90)
Duplicate class android.support.customtabs.IPostMessageService$Stub$Proxy found in modules browser-1.0.0-runtime (androidx.browser:browser:1.0.0) and jetified-customtabs-e849e45c90-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:e849e45c90)
Duplicate class androidx.browser.customtabs.CustomTabsCallback found in modules browser-1.0.0-runtime (androidx.browser:browser:1.0.0) and jetified-customtabs-e849e45c90-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:e849e45c90)
Duplicate class androidx.browser.customtabs.CustomTabsClient found in modules browser-1.0.0-runtime (androidx.browser:browser:1.0.0) and jetified-customtabs-e849e45c90-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:e849e45c90)
Duplicate class androidx.browser.customtabs.CustomTabsClient$1 found in modules browser-1.0.0-runtime (androidx.browser:browser:1.0.0) and jetified-customtabs-e849e45c90-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:e849e45c90)
Duplicate class androidx.browser.customtabs.CustomTabsClient$2 found in modules browser-1.0.0-runtime (androidx.browser:browser:1.0.0) and jetified-customtabs-e849e45c90-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:e849e45c90)
Duplicate class androidx.browser.customtabs.CustomTabsClient$2$1 found in modules browser-1.0.0-runtime (androidx.browser:browser:1.0.0) and jetified-customtabs-e849e45c90-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:e849e45c90)
Duplicate class androidx.browser.customtabs.CustomTabsClient$2$2 found in modules browser-1.0.0-runtime (androidx.browser:browser:1.0.0) and jetified-customtabs-e849e45c90-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:e849e45c90)
Duplicate class androidx.browser.customtabs.CustomTabsClient$2$3 found in modules browser-1.0.0-runtime (androidx.browser:browser:1.0.0) and jetified-customtabs-e849e45c90-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:e849e45c90)
Duplicate class androidx.browser.customtabs.CustomTabsClient$2$4 found in modules browser-1.0.0-runtime (androidx.browser:browser:1.0.0) and jetified-customtabs-e849e45c90-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:e849e45c90)
Duplicate class androidx.browser.customtabs.CustomTabsClient$2$5 found in modules browser-1.0.0-runtime (androidx.browser:browser:1.0.0) and jetified-customtabs-e849e45c90-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:e849e45c90)
Duplicate class androidx.browser.customtabs.CustomTabsIntent found in modules browser-1.0.0-runtime (androidx.browser:browser:1.0.0) and jetified-customtabs-e849e45c90-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:e849e45c90)
Duplicate class androidx.browser.customtabs.CustomTabsIntent$Builder found in modules browser-1.0.0-runtime (androidx.browser:browser:1.0.0) and jetified-customtabs-e849e45c90-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:e849e45c90)
Duplicate class androidx.browser.customtabs.CustomTabsService found in modules browser-1.0.0-runtime (androidx.browser:browser:1.0.0) and jetified-customtabs-e849e45c90-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:e849e45c90)
Duplicate class androidx.browser.customtabs.CustomTabsService$1 found in modules browser-1.0.0-runtime (androidx.browser:browser:1.0.0) and jetified-customtabs-e849e45c90-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:e849e45c90)
Duplicate class androidx.browser.customtabs.CustomTabsService$Relation found in modules browser-1.0.0-runtime (androidx.browser:browser:1.0.0) and jetified-customtabs-e849e45c90-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:e849e45c90)
Duplicate class androidx.browser.customtabs.CustomTabsService$Result found in modules browser-1.0.0-runtime (androidx.browser:browser:1.0.0) and jetified-customtabs-e849e45c90-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:e849e45c90)
Duplicate class androidx.browser.customtabs.CustomTabsServiceConnection found in modules browser-1.0.0-runtime (androidx.browser:browser:1.0.0) and jetified-customtabs-e849e45c90-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:e849e45c90)
Duplicate class androidx.browser.customtabs.CustomTabsServiceConnection$1 found in modules browser-1.0.0-runtime (androidx.browser:browser:1.0.0) and jetified-customtabs-e849e45c90-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:e849e45c90)
Duplicate class androidx.browser.customtabs.CustomTabsSession found in modules browser-1.0.0-runtime (androidx.browser:browser:1.0.0) and jetified-customtabs-e849e45c90-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:e849e45c90)
Duplicate class androidx.browser.customtabs.CustomTabsSessionToken found in modules browser-1.0.0-runtime (androidx.browser:browser:1.0.0) and jetified-customtabs-e849e45c90-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:e849e45c90)
Duplicate class androidx.browser.customtabs.CustomTabsSessionToken$1 found in modules browser-1.0.0-runtime (androidx.browser:browser:1.0.0) and jetified-customtabs-e849e45c90-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:e849e45c90)
Duplicate class androidx.browser.customtabs.CustomTabsSessionToken$MockCallback found in modules browser-1.0.0-runtime (androidx.browser:browser:1.0.0) and jetified-customtabs-e849e45c90-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:e849e45c90)
Duplicate class androidx.browser.customtabs.PostMessageService found in modules browser-1.0.0-runtime (androidx.browser:browser:1.0.0) and jetified-customtabs-e849e45c90-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:e849e45c90)
Duplicate class androidx.browser.customtabs.PostMessageService$1 found in modules browser-1.0.0-runtime (androidx.browser:browser:1.0.0) and jetified-customtabs-e849e45c90-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:e849e45c90)
Duplicate class androidx.browser.customtabs.PostMessageServiceConnection found in modules browser-1.0.0-runtime (androidx.browser:browser:1.0.0) and jetified-customtabs-e849e45c90-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:e849e45c90)
Duplicate class androidx.browser.customtabs.TrustedWebUtils found in modules browser-1.0.0-runtime (androidx.browser:browser:1.0.0) and jetified-customtabs-e849e45c90-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:e849e45c90)
`

**Comment by jkasten2** [comment]
@mashwishi It looks like you are using `com.github.GoogleChrome.custom-tabs-client:customtabs` which is deprecated:
https://github.com/GoogleChrome/custom-tabs-client

It is recommend you switch to android-browser-helper:
https://github.com/GoogleChrome/android-browser-helper

**Comment by mashwishi** [comment]
> @mashwishi It looks like you are using `com.github.GoogleChrome.custom-tabs-client:customtabs` which is deprecated:
> https://github.com/GoogleChrome/custom-tabs-client
> 
> It is recommend you switch to android-browser-helper:
> https://github.com/GoogleChrome/android-browser-helper

I'm not sure how to set this up: https://github.com/GoogleChrome/android-browser-helper

**Comment by mashwishi** [comment]
The PWA to TWA needs Permission for Location and Push Notification (firebase and onesignal)

**Comment by mashwishi** [comment]
The deprecated version https://github.com/GoogleChrome/custom-tabs-client is easy to setup unlike the  `android-browser-helper` however I can't implement the onesignal but google/facebook login is working also location and push notification (firebase)
