### ISSUE TITLE
There is no Badge Count in my NotificationExtenderService

### ISSUE THREAD

**Issue by superdiazzz** [OneSignal/OneSignal-Android-SDK#869]
**Description:**
Although i received notifications in my device but there was no badge count displays

Here what i wrote in my NotificationExtenderService
```
public class OneSignalExtenderService extends NotificationExtenderService {

    @Override
    protected boolean onNotificationProcessing(OSNotificationReceivedResult notification) {

        //Timber.d("ONESIGNAL masuk receiver!");
        boolean focus = notification.isAppInFocus;

        Timber.d("ONESIGNAL focus %s", focus);

        OverrideSettings overrideSettings = new OverrideSettings();
        overrideSettings.extender = builder -> {
            builder.setBadgeIconType(NotificationCompat.BADGE_ICON_SMALL);
            builder.setCategory(NotificationCompat.CATEGORY_MESSAGE);
            builder.setPriority(NotificationCompat.PRIORITY_MAX);
            return builder;
        };

        // active this below if you want to overriding standart notifications
         OSNotificationDisplayedResult d = displayNotification(overrideSettings);
        return false;
    }
}
```
i am using this dependency
```
implementation('com.onesignal:OneSignal:3.11.3') {
        exclude group: 'com.google.android.gms'
    }

```
there is no badge in Samsung Galaxy S9 os 8
can someone give me some advise?

**Comment by rgomezp** [comment]
What exactly are you trying to do that the SDK doesn't do already?

**Comment by superdiazzz** [comment]
@rgomezp i want to display badge when my application received notification. In some devices it's shown badge but in some devices like Samsung Galaxy S9 os 8 and Vivo y17 os 9 there were no "badge count" although receive notifications

**Comment by jkasten2** [comment]
@superdiazzz We have tested the OneSignal SDK on a Samsung S7 with Android 8.0 (Oreo) and the badge does show. Please go to Setting > Notifications on the device and ensure "App icon badges" are enabled.

We don't have a Vivo device to test with but I recommend checking it isn't turned off in the settings as well.

This SDK uses the [ShortcutBadger](https://github.com/leolin310148/ShortcutBadger) library so OneSignal supports the same list of devices it notes, including Samsung and Vivo devices.

**Comment by rgomezp** [comment]
Closing due to no response
