### ISSUE TITLE
Get current badge count

### ISSUE THREAD

**Issue by Jaymassena** [OneSignal/OneSignal-Android-SDK#87]
Is there a way to retrieve the current badge icon count? It looks like there might be for other platforms but I couldn't find anything for Android. We use a notification drawer and show the badge count as an overlay on the toolbar icon controlling the drawer.

**Comment by jkasten2** [comment]
@Jaymassena There currently isn't a method to get this. When we complete #76 you can use this to get this value as the badge count matches the current number of notifications in the notification shade.

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration
