### ISSUE TITLE
can't get head-up notification

### ISSUE THREAD

**Issue by shahishasank** [OneSignal/OneSignal-Android-SDK#878]
**Description:**

I tried notification priority(high) form OS dashboard and also tried using NotificationExtenderService and setting NotificationCompat.Builder priority to high but nothing worked. Here's my service code

```
public class NotificationExtender extends NotificationExtenderService {
    @Override
    protected boolean onNotificationProcessing(OSNotificationReceivedResult receivedResult) {
        OverrideSettings overrideSettings = new OverrideSettings();
        overrideSettings.extender = new NotificationCompat.Extender() {
            @Override
            public NotificationCompat.Builder extend(NotificationCompat.Builder builder) {
                builder.setDefaults(Notification.DEFAULT_VIBRATE);
                builder.setPriority(Notification.PRIORITY_HIGH);
                return builder;
            }
        };

        OSNotificationDisplayedResult displayedResult = displayNotification(overrideSettings);
        Log.d("OneSignalExample", "Notification displayed with id: " + displayedResult.androidNotificationId);

        return true;
    }
}
```

Code in manifest file
`<service
            android:name="com.sarkaribank.Activities.NotificationExtender"
            android:permission="android.permission.BIND_JOB_SERVICE"
            android:exported="false">
            <intent-filter>
                <action android:name="com.onesignal.NotificationExtender" />
            </intent-filter>
        </service>`

I tried debugging and above code was working fine. But I'm not able to get heap-up notification.

**Environment**

Android SDK 3.0.1
OneSignal dependency 3.12.0

**Comment by jkasten2** [comment]
@shahishasank `builder.setPriority` will only work for Android 5 through Android 7.x devices to make the notification show as a heads up.

For Android 8 and newer you will need to create a Notification Category / Channel with a high priority to make it heads up. OneSignal's dashboard has this build in, see the documentation below.
https://documentation.onesignal.com/docs/android-notification-categories

Also note that OneSignal's Category logic will also apply those settings to pre-Android 8 devices so you don't need call `builder.setPriority` even for older devices.

**Comment by shahishasank** [comment]
thanks, it is solved now.. All I had to do is create a category from OS dashboard.
