### ISSUE TITLE
Accessing a view when the location notifications have been denied should not trigger a flicker

### ISSUE THREAD

**Issue by settlersxp** [OneSignal/OneSignal-Android-SDK#884]
**Description:**
In our current implementation we call the OneSignal method for accessing the location of the device. Before the user agrees to grant persmissions the standard OS popup is visible. In this popup the user can deny the permission and choses to never see them again. In this case, every time the user enters this view, a flicker happens. It would be great if this flicker would not happen. It looks like the permissions popup is called by OneSignal and the OS blocks the call.

**Environment**
Android 9.0

**Steps to Reproduce Issue:**
Implement OneSignal into a view
Call OneSignal.promptLocation();
On the device deny the permission for ever
Access the view again
Notice a flicker

**Comment by rgomezp** [comment]
Thanks for your patience while we attempt to reproduce

**Comment by mikechoch** [comment]
This was very easy to reproduce, thank you for finding and reporting this with detail. Expect a fix in the next release.

**Comment by mikechoch** [comment]
PR #920 will take care of this issue and is merged in now.
