### ISSUE TITLE
Buttons localization

### ISSUE THREAD

**Issue by Maykonn** [OneSignal/OneSignal-Android-SDK#89]
Is impossible to send localized buttons text in a notification.
Notification content accept localized texts:

```
{"en": "English Message", "es": "Spanish Message"}
```

So buttons must be localized too, something like this:

```
[{
    "id": "id1",
    "text": {
      "en": "English text",
      "es": "Spanish text"
    }
    "icon": "ic_menu_share"
}, {
    "id": "id2",
    "text": {
      "en": "English text",
      "es": "Spanish text"
    }
    "icon": "ic_menu_send"
}]
```

**Comment by DimaKoz** [comment]
I think you should use https://documentation.onesignal.com/docs/android-notification-customizations#background-data-and-notification-overriding

**Comment by jkasten2** [comment]
@Maykonn We don't have localization support for buttons at this time. You can however use @DimaKoz suggestion. You will need to put the buttons as additional data on  the payload and then use `addAction` on the builder to add your buttons.

Another way without any client side changes would be to create a Segment for each language on our dashboard and sent a notification for each.

**Comment by Maykonn** [comment]
In my case the better to do is send a notification for each player/device. 
This enhancement is important to be applied on server side restful API too, to send localized buttons to many players at same time(with just one request), in my domain one User can have many devices/players and each one in a different language.

**Comment by jkasten2** [comment]
@Maykonn Adding the buttons client side then would be the way to go for you. Replay if you need any more details on implementing this in your app.

**Comment by Maykonn** [comment]
@jkasten2 I can't implements on client side because the buttons text and action are dynamic, and I really can't add business rules on apps(to get this dynamic behaviour).

**Comment by jkasten2** [comment]
@Maykonn You can send the following in your POST request to OneSignal.
```JSON
"data": {
  "buttons": [{
    "id": "id1",
    "text": {
      "en": "English text",
      "es": "Spanish text"
    },
    "icon": "ic_menu_share"
  }, {
    "id": "id2",
    "text": {
      "en": "English text",
      "es": "Spanish text"
    },
    "icon": "ic_menu_send"
  }]
```

In your app's code you can then read the buttons as a `JSONArray`.
```Java
public class NotificationExtenderExample extends NotificationExtenderService {
   @Override
   protected boolean onNotificationProcessing(OSNotificationReceivedResult receivedResult) {
      OSNotificationPayload payload = receivedResult.payload;
      if (payload.additionalData.has("buttons")) {
         addLocalizedButtons(payload.additionalData.optJSONArray("buttons));
         return true;
      }
      return false;
   }

   private void addLocalizedButtons(final JSONArray buttons) {
      OverrideSettings overrideSettings = new OverrideSettings();
      overrideSettings.extender = new NotificationCompat.Extender() {
         @Override
         public NotificationCompat.Builder extend(NotificationCompat.Builder builder) {
           String lang = Locale.getDefault().getLanguage();
           for (int i = 0; i <  buttons.size(); i++) {
              JSONObject button = (JSONObject) buttons.get(i);
              // NOTE: Upate YourActivity here.
              Intent intent = new Intent(this, YourActivity.class);
              buttonIntent.setAction("" + i);
              PendingIntent buttonPIntent = PendingIntent.getActivity(this, 1, intent, PendingIntent.FLAG_UPDATE_CURRENT);
              String buttonText = button.optString("text").optString(lang, null);
              if (buttonText == null)
                buttonText = button.optString("text").optString("en");
              
              int buttonIcon = 0;
              // NOTE: Only checking for system icon resources.
              // Add your own code to check for your own drawables.
              if (button.has("icon"))
                 buttonIcon = drawable.class.getField(iconName).getInt(null);
              
              mBuilder.addAction(buttonIcon, buttonText, buttonPIntent);
           }
         }
      };

      OSNotificationDisplayedResult displayedResult = displayNotification(overrideSettings);
      Log.d("OneSignalExample", "Notification displayed with id: " + displayedResult.androidNotificationId);
   }
}
```

Note, the Java code is untested and you need to make changes where there is `NOTE` comments.

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration
