### ISSUE TITLE
Issue with WebView while using in-app message

### ISSUE THREAD

**Issue by nicktz9** [OneSignal/OneSignal-Android-SDK#901]
**Description:**
We got a lot of crashes while using in-app message. 
1.  `Fatal Exception: android.content.res.Resources$NotFoundException` issue on Android 5 
```
com.onesignal.OSWebView.<init> (OSWebView.java:10)
com.onesignal.WebViewManager.setupWebView (WebViewManager.java:285)
com.onesignal.WebViewManager.access$200 (WebViewManager.java:36)
com.onesignal.WebViewManager$3.run (WebViewManager.java:133)
```
2. Runtime exception on Android 8, 9
```
com.onesignal.WebViewManager.calculateHeightAndShowWebViewAfterNewActivity (WebViewManager.java:229)
com.onesignal.WebViewManager.available (WebViewManager.java:263)
com.onesignal.ActivityLifecycleHandler.setCurActivity (ActivityLifecycleHandler.java:93)
com.onesignal.ActivityLifecycleHandler.onActivityResumed (ActivityLifecycleHandler.java:119)
com.onesignal.ActivityLifecycleListener.onActivityResumed (ActivityLifecycleListener.java:78)
```

**Environment**
1. my gradle setup
```
 implementation('com.onesignal:OneSignal:3.12.3') {
        exclude group: 'com.google.android.gms', module: 'play-services-location'
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.firebase', module: 'firebase-iid'
        exclude group: 'com.google.firebase', module: 'firebase-messaging'
    }
```

**Steps to Reproduce Issue:**
1. We got a lot of crashes while using in-app message.

**Comment by rgomezp** [comment]
Howdy,
We're aware of this issue and are investigating. Thanks for your patience

**Comment by nuhin-startern** [comment]
WARNING: tile memory limits exceeded, some content may not draw
shows on any android 6 devices 
But upper devices in-app notification works fine.. 
Is there any limitation ???

**Comment by ksc91u** [comment]
please provide a new sdk so we can have a switch to turn this feature off on 6.0 devices.

**Comment by mikechoch** [comment]
Can we have more information or a more detailed stack trace. In version 3.12.3 line number 229 does not matches up with a `}`. This is not helpful and you may be referencing the wrong OneSignal SDK version. Please help us with more information so we can dig into this issue more.
