### ISSUE TITLE
Requires a placeholder substitution but no value for <onesignal_app_id> is provided

### ISSUE THREAD

**Issue by Secretbox1987** [OneSignal/OneSignal-Android-SDK#903]
I use 
plugins {
    id 'com.onesignal.androidsdk.onesignal-gradle-plugin' version '0.12.5'
}
and 
implementation 'com.onesignal:OneSignal:3.10.6'

when I delete
  manifestPlaceholders = [
                                    onesignal_app_id               : "xxx",
                                    onesignal_google_project_number: "xxx"
]
from build.gradle and begin to use
 OneSignal.init(
                        this,
                        "xxx",
                        "xxx",
                        NotificationOpenedHandler(this)
                )
                OneSignal.getCurrentOrNewInitBuilder().unsubscribeWhenNotificationsAreDisabled(true)
I recieve this issue:
requires a placeholder substitution but no value for <onesignal_app_id> is provided and
requires a placeholder substitution but no value for <onesignal_google_project_number> is provided
Help me fix it

**Comment by rgomezp** [comment]
Please follow our issue template
