### ISSUE TITLE
NullPointerException on OneSignalChromeTabAndroidFrame

### ISSUE THREAD

**Issue by Eric-github1024** [OneSignal/OneSignal-Android-SDK#916]
Description:
I have encountered a NullPointerException crash on the library.The crash happens since the 3.12.3 version.It will crash if the function doCreateOrNewSession receives  error code 400. It will update user id, and call the function OneSignalChromeTabAndroidFrame.setup(). But the OneSignal.remoteParams is null, so it will crash.
Reason:
The reason of the crash is the commit: Create new player if missing player_id on put.
Here is the link: https://github.com/OneSignal/OneSignal-Android-SDK/commit/a0a9cdc2cac463acc157dfb7deb8b25221f754b1.
Calling updateIdDependents(null) in function handlePlayerDeletedFromServer will cause the NullPointerException.
Please fix it, thank you.

Environment
I'm using the following version of the library: implementation 'com.onesignal:OneSignal:[3.11.2, 3.99.99]'
It is not related to the android version since it happens at least from android 6 up to android 9.

Anything else:
Crash stacktrace:
# OS_REST_FAILURE_CALLBACK(60384)
java.lang.NullPointerException
Attempt to read from field 'boolean com.onesignal.OneSignalRemoteParams$Params.enterprise' on a null object reference
 com.onesignal.OneSignalChromeTabAndroidFrame.setup(OneSignalChromeTabAndroidFrame.java:12)
 com.onesignal.OneSignal.updateUserIdDependents(OneSignal.java:2258)
com.onesignal.UserStatePushSynchronizer.updateIdDependents(UserStatePushSynchronizer.java:135) com.onesignal.UserStateSynchronizer.handlePlayerDeletedFromServer(UserStateSynchronizer.java:484)
 com.onesignal.UserStateSynchronizer.access$400(UserStateSynchronizer.java:22)
 com.onesignal.UserStateSynchronizer$4.onFailure(UserStateSynchronizer.java:297)
 com.onesignal.OneSignalRestClient$6.run(OneSignalRestClient.java:277)
 java.lang.Thread.run(Thread.java:818)

**Comment by trivalent** [comment]
Encountering the same issue
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'boolean com.onesignal.OneSignalRemoteParams$Params.enterprise' on a null object reference
       at com.onesignal.OneSignalChromeTabAndroidFrame.setup(OneSignalChromeTabAndroidFrame.java:12)
       at com.onesignal.OneSignal.updateUserIdDependents(OneSignal.java:2258)
       at com.onesignal.UserStatePushSynchronizer.updateIdDependents(UserStatePushSynchronizer.java:135)
       at com.onesignal.UserStateSynchronizer.handlePlayerDeletedFromServer(UserStateSynchronizer.java:484)
       at com.onesignal.UserStateSynchronizer.access$400(UserStateSynchronizer.java:22)
       at com.onesignal.UserStateSynchronizer$4.onFailure(UserStateSynchronizer.java:297)
       at com.onesignal.OneSignalRestClient$6.run(OneSignalRestClient.java:277)
       at java.lang.Thread.run(Thread.java:764)

**Comment by mikechoch** [comment]
PR #920 will take care of this issue and is merged in now.
