### ISSUE TITLE
It exclude_segments work with playerId in onesignal

### ISSUE THREAD

**Issue by Raden-Hor** [OneSignal/OneSignal-Android-SDK#918]
**Description:**

(your description here)

**Environment**

**Steps to Reproduce Issue:**

1. (your steps here)
2.
3.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by Raden-Hor** [comment]
I want to push notification to all user except me!

**Comment by mikechoch** [comment]
Need a little more detail. Are you using a public method, dashboard, or API?

**Comment by Raden-Hor** [comment]
Rest api

**Comment by rgomezp** [comment]
While we appreciate the suggestion, this is not something we plan to add in the near future. Thank you!
