### ISSUE TITLE
ANR executing service com.onesignal.SyncJobService

### ISSUE THREAD

**Issue by justanapp** [OneSignal/OneSignal-Android-SDK#926]
Hi! I'm getting these type of ANRs 

**executing service com.onesignal.SyncJobService**

and it seems that the background service is not active on some devices - may this is the cause?

"main" prio=5 tid=1 Blocked
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x76b6fb30 self=0x7855c15c00
  | sysTid=26012 nice=0 cgrp=default sched=0/0 handle=0x78dc401548
  | state=S schedstat=( 11169619936 1583206278 72266 ) utm=850 stm=266 core=1 HZ=100
  | stack=0x7fd6865000-0x7fd6867000 stackSize=8MB
  | held mutexes=
  at android.os.MessageQueue.next (MessageQueue.java:388)
- waiting to lock <0x0f5ec43c> (a android.os.MessageQueue) held by thread 26
  at android.os.Looper.loop (Looper.java:175)
  at android.app.ActivityThread.main (ActivityThread.java:7625)
  at java.lang.reflect.Method.invoke (Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:524)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:987)

**Comment by jkasten2** [comment]
@justanapp I don't see OneSignal in the stacktrace, can you post the full stacktrace from all threads? It seems the main thread is looked with thread 26 in your case which isn't posted here.

Is this something you can reproduce locally?

ANRs will show the process followed by the Java class that started the process. However this does not indicate what actually triggered the ANR.

**Comment by rgomezp** [comment]
Closing due to no response
