### ISSUE TITLE
Error:Execution failed for task ':app:processDebugManifest'. > Manifest merger failed with multiple errors, see logs 

### ISSUE THREAD

**Issue by EgyptianM** [OneSignal/OneSignal-Android-SDK#93]
Hi,
I'm getting this error when I try to include your SDK in my project 
I'm using : 

`compile 'com.onesignal:OneSignal:3.+@aar'`

Where can I send you the source code that produces the issue?

**Comment by jkasten2** [comment]
@EgyptianM Can you provide the full log here or to OneSignal support? You can send the .gradle and AndroidManifest.xml to support@onesignal.com

**Comment by EgyptianM** [comment]
OK thank you.

I'll send you the files as soon as I can.

For now including the jar file in libs folder solved the issue.

**Comment by jkasten2** [comment]
@EgyptianM Good to hear that worked for you. The merger issue would be specific to your project so including the files above them will be the only way we can reproduce it.

Feel free to attache them here if you can scrub any sensitive information from them.

**Comment by palashmandokhot** [comment]
how to solve Error: Manifest merger failed with multiple errors in android studio

**Comment by jkasten2** [comment]
@palashmandokhot If you are still seeing an issue can you attach the full error your are seeing?

**Comment by palashmandokhot** [comment]
do you know about java or javascript

**Comment by d-rahul** [comment]
Open application manifest(AndroidManifest.xml), click on the "Merged Manifest" tab next to the "Text" tab of the manifest file. You can view the error in the right column, try to solve the error and build again it will solve this error.
For error: [](https://readyandroid.wordpress.com/errorexecution-failed-for-task-appprocessdebugmanifest-manifest-merger-failed-with-multiple-errors-see-logs-android/)
For more check: [](https://readyandroid.wordpress.com/)
