### ISSUE TITLE
After the in-app message is displayed, it may close immediately.

### ISSUE THREAD

**Issue by yuji-yoshimura** [OneSignal/OneSignal-Android-SDK#950]
**Description:**

In-app message restored by screen transition in Activity is closed.

Transition from Activity A to Activity B.

1. In-app message is restored by `onResume ()` of Activity B.
2. In-app message is closed by `onStop ()` of Activity A.

However, it is only assumed that the restored in-app message has been closed by a non-user action. (Example: Splash screen)
 
**Environment**

- OneSignal:3.12.6
- Android target sdk version 28
- Android compile sdk version 28

**Steps to Reproduce Issue:**

1. Kill the app with the in-app message displayed.
2. Restart the app.
3. The in-app message is restored on the splash screen, but the in-app message closes when the splash screen ends.
4. Move between Activities.

**Anything else:**

- [pauseInAppMessages](https://documentation.onesignal.com/docs/android-native-sdk#section-pause-in-app-messages) could not pause restoring in-app messages.
- Also in #942, restoration of in-app messages could not be paused.

<img width="320" src="https://user-images.githubusercontent.com/56010948/74132709-71cfc280-4c2a-11ea-9816-5ce340c251ae.gif" />

**Comment by mikechoch** [comment]
Continue thread on #952
