### ISSUE TITLE
Security alert google play after update library

### ISSUE THREAD

**Issue by DaxeshV** [OneSignal/OneSignal-Android-SDK#970]
Security alert

Your app contains exposed Google Cloud Platform (GCP) API keys. Please see this Google Help Center article for details.

Vulnerable locations:

com.onesignal.PushRegistratorFCM->getApiKey
Affects APK version 1.

**Comment by rborn** [comment]
Duplicate https://github.com/OneSignal/OneSignal-Android-SDK/issues/966

**Comment by DaxeshV** [comment]
But still, issue not resolved. Now, what can I do?

**Comment by rborn** [comment]
you could try o manually change this file https://github.com/OneSignal/OneSignal-Android-SDK/blob/a3b21d30afe05bb7b14ca35234a6870eaf8205df/OneSignalSDK/onesignal/src/main/java/com/onesignal/PushRegistratorFCM.java#L47-L49

and set the key to an empty string

However is a warning, not an error so your app will go just fine to the store (just published one).

**Comment by DaxeshV** [comment]
I know its warning. but I have used one signal on my many client applications. but last few days many clients prompt me for a solution. now things go worst. we are waiting for a better solution but now time to move with firebase notification. so in future, we never face again this kind of security issue.

**Comment by jkasten2** [comment]
We are shooting for an SDK update later this week with a fix for this false positive security warning as well as a few other SDK improvements.

@DaxeshV To work around the issue for today if you need to remove this warning for your clients I recommend using using OneSignal 3.12.6 for the time being. OneSignal 3.12.7 is only required if you use com.google.firebase:firebase-messaging:20.1.0 or newer. By default OneSignal depends on com.google.firebase:firebase-messaging:[10.2.1, 17.3.99] so in most cases this should be fine.

Closing this as a duplicate of #966, please use it to follow up on this topic.
