### ISSUE TITLE
Crash in UserStatePushSynchronizer

### ISSUE THREAD

**Issue by raymondd222** [OneSignal/OneSignal-Android-SDK#972]
**Description:**
Crash seen in firebase

**Environment**
Android app with gradle, our gradle file has 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.12.6'

**Steps to Reproduce Issue:**
Unknown, we just see the crash show up in our firebase crash reporting service.

**Anything else:**

Crash with stack trace:
https://pastebin.com/raw/wW1FyTkd

**Comment by jkasten2** [comment]
@raymondd222 Thanks for the stacktrace. This points to a line that already has a null check so your crash is from an older version of the SDK;
https://github.com/OneSignal/OneSignal-Android-SDK/blob/3.12.7/OneSignalSDK/onesignal/src/main/java/com/onesignal/UserStatePushSynchronizer.java#L34

**Comment by raymondd222** [comment]
I updated to latest SDK and you are right, line 34 appears to be different now. However, the actual offending line still looks unprotected (line 41 in newest SDK):

                                JSONObject dependDiff = generateJsonDiff(currentUserState.syncValues.optJSONObject("tags"),

where the thing that is null is "currentUserState". I think this means even if I update the SDK the crashes will continue to happen.
