### ISSUE TITLE
Can't update to latest version

### ISSUE THREAD

**Issue by summonerriftofficial** [OneSignal/OneSignal-Android-SDK#979]
**Description:**
ERROR: Failed to resolve: com.onesignal:onesignal:3.12.7
Show in Project Structure dialog
Affected Modules: app

**Comment by mikechoch** [comment]
`3.12.7` is not the latest version, `3.13.0` is. Also are you trying to use a range in the `build.gradle`?

**Comment by jkasten2** [comment]
@summonerriftofficial Sorry for the confusion here. ` com.onesignal:onesignal:` should be ` com.onesignal:OneSignal:`
We have updated our documentation to correct this:
https://documentation.onesignal.com/docs/android-sdk-setup#section-setup

**Comment by summonerriftofficial** [comment]
@jkasten2 thank you the issue was with the documentation and thanks <3
