### ISSUE TITLE
3.13.0 Release For Unity SDK

### ISSUE THREAD

**Issue by asrakan** [OneSignal/OneSignal-Android-SDK#981]
Hello, could you guys update Unity SDK with 3.13.0 release. Current Unity SDK is giving "Addressed IllegalThreadStateException from OneSignal"

**Comment by jkasten2** [comment]
@asrakan For OneSignal Unity issues please uses the following repo:
https://github.com/OneSignal/OneSignal-Unity-SDK/issues
