### ISSUE TITLE
Could not HEAD 'https://plugins.gradle.org/m2/gradle/plugin/com/onesignal/onesignal-gradle-plugin/maven-metadata.xml'

### ISSUE THREAD

**Issue by yaronlevi** [OneSignal/OneSignal-Android-SDK#983]
Hi (-:

I hope you are feeling well these days.

We are using the React Native SDK. Last night we could run the project successfully. But suddenly we get the following error from Gradle:

`Could not resolve gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.10.0, 0.99.99].`

`Could not HEAD 'https://plugins.gradle.org/m2/gradle/plugin/com/onesignal/onesignal-gradle-plugin/maven-metadata.xml'. Received status code 530 from server`

Here is a screen capture:
<img width="1246" alt="Screen Shot 2020-04-05 at 10 57 39" src="https://user-images.githubusercontent.com/5398977/78469705-4a7a0b00-772c-11ea-8fbf-a4b758ccbc8b.png">

Any help on the issue would be much appreciated.

**Comment by jkasten2** [comment]
@yaronlevi The HTTP 530 error code isn't something I have seen before. Make sure you don't have any proxy, VPN, or other network settings that could be giving you a modified response. It is also possible gradle.org had some server problem during the time it tried to download the plugin.

If the issue persists make sure you can open the following URL in your browser and you can curl it from your terminal as well.
https://plugins.gradle.org/m2/gradle/plugin/com/onesignal/onesignal-gradle-plugin/maven-metadata.xml

**Comment by yaronlevi** [comment]
Thank You! It was resolved by itself
