### ISSUE TITLE
Use OneSignal with latest Firebase cloud messaging at the same time

### ISSUE THREAD

**Issue by mahdi-malv** [OneSignal/OneSignal-Android-SDK#984]
### Description:

New changes in `Firebase-Messaging` makes it dependent to **Firebase Installation SDK**.
Apps that initialize a `FirebaseApp` using **FirebaseOptions** must provide extra information (APIKey, AppId and ProjectId)

In the latest version of OneSignal it only knows about `SenderId` and `ServerKey`. As I saw in the source it passes an ApiKey of it's own, or requests for them. How does the library get these while I have not passed them?
**If something else is used, is it safe for my app**, or should I wait for the latest version that takes my info at the console?

### Environment

* OneSignal version 3.13.0
* Firebase-Messaging version 20.1.4

### Steps to Reproduce Issue:

1. Create an app
2. Add and setup `Firebase-messaging` and add the latest (20.1.4 at the time) to the project
3. Add onesignal (version 3.13.0 at the time)
4. Run the app (Works fine and no issues occur. But we expect `FIS_AUTH_ERROR`)

(crash stacktraces, as well as any other information here)

**Anything else**:

* App uses androidX artifact and latest version of Jetpack libararies

**Comment by rgomezp** [comment]
This is handled automatically and is safe for your app. Simply upgrade to the latest version. Enjoy!
