### ISSUE TITLE
Onesignal crash on boot completed

### ISSUE THREAD

**Issue by gbtt** [OneSignal/OneSignal-Android-SDK#99]
Hi,
on One Plus One with Android 4.4.4 OneSignal crashes.
The problem doesn't happen on other devices.
This is what i see in logcat:

````Java
E/AndroidRuntime: FATAL EXCEPTION: IntentService[NotificationExtenderService]
  Process: it.nameof.app, PID: 9249
  java.lang.NullPointerException
      at com.onesignal.NotificationExtenderService.processIntent(NotificationExtenderService.java:113)
      at com.onesignal.NotificationExtenderService.onHandleIntent(NotificationExtenderService.java:106)
      at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
      at android.os.Handler.dispatchMessage(Handler.java:102)
      at android.os.Looper.loop(Looper.java:136)
      at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by jkasten2** [comment]
@gbtt Thanks for the report, could you also include the version of the OneSignal SDK you are using?

**Comment by gbtt** [comment]
Hi, the version is 3.1.0

**Comment by gbtt** [comment]
I found how to reproduce this crash also on other devices.
I am using android.intent.action.BOOT_COMPLETED

How to reproduce it:
- Starts the smartphone without internet connection.

The error message is:

`09-01 14:53:51.286 8202-8202/it.nameof.app I/GMPM: App measurement is starting up, version: 8487
09-01 14:53:51.286 8202-8202/it.nameof.app I/GMPM: To enable debug logging run: adb shell setprop log.tag.GMPM VERBOSE
09-01 14:53:51.302 8202-8202/it.nameof.app E/GMPM: GoogleService failed to initialize, status: 10, Missing an expected resource: 'R.string.google_app_id' for initializing Google services.  Possible causes are missing google-services.json or com.google.gms.google-services gradle plugin.
09-01 14:53:51.302 8202-8202/it.nameof.app E/GMPM: Scheduler not set. Not logging error/warn.
09-01 14:53:51.370 8202-8202/it.nameof.app I/HwCust: Constructor found for class android.app.HwCustAlarmManagerImpl
09-01 14:53:51.370 8202-8202/it.nameof.app D/HwCust: Create obj success use class android.app.HwCustAlarmManagerImpl
09-01 14:53:51.398 8202-8311/it.nameof.app E/GMPM: Uploading is not possible. App measurement disabled
09-01 14:53:51.463 8202-8202/it.nameof.app D/debug: User:ec1e9052-[...]
09-01 14:53:51.463 8202-8202/it.nameof.app D/debug: registrationId:APA91b[...]
09-01 14:53:51.492 8202-8327/it.nameof.app E/AndroidRuntime: FATAL EXCEPTION: IntentService[NotificationExtenderService]
                                                                  Process: it.nameof.app, PID: 8202
                                                                  java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
                                                                      at com.onesignal.NotificationExtenderService.processIntent(NotificationExtenderService.java:113)
                                                                      at com.onesignal.NotificationExtenderService.onHandleIntent(NotificationExtenderService.java:106)
                                                                      at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:150)
                                                                      at android.os.HandlerThread.run(HandlerThread.java:61)`

**Comment by jkasten2** [comment]
@gbtt Just tested this on LGE LGL15G Android 4.4.2 and an LG G2 Android 5.0.2 with any issues. Notifications were restored after a reboot without any crashes in the logcat.

Can you try reproducing the issue with our example project?

This crash is most likely the same as #84 but it was fixed in 3.0.1 of the SDK.

Thanks.

**Comment by gbtt** [comment]
Hi, I tried with your example project and I get the same problem.
I upload the package [here](https://drive.google.com/open?id=0BxYN5UgjufTvLURheHNVRnBCNFE), and [here](https://drive.google.com/open?id=0BxYN5UgjufTvYjA4NDR0NjdxUVk) you can find a screenshot of logcat. You have to wait some time to get the error.

Thanks for your support.

**Comment by jkasten2** [comment]
@gbtt Thanks for the project, I'll give it a try. Did you send any specific notifications before rebooting? Or were they just simply ones with just a message body set?

**Comment by gbtt** [comment]
Hi, I sent simply notifications with just a message body

Ok, i will send the logcat also to support. Fyi it's the same of the screenshot.
Thanks

**Comment by jkasten2** [comment]
@gbtt The full logcat will be useful to see if the device is somehow running out of memory and causing the process to restart multiple times.

**Comment by gbtt** [comment]
@jkasten2 hi, I sent the email with the full logcat.

**Comment by jkasten2** [comment]
@gbtt Thanks for the full log. The logcat showed the process isn't restarted. I have added a null check for this in commit 6db772665cde6f76a744c1614ff3323bb5f7e133
