### ISSUE TITLE
In-App Notifications proguard issue

### ISSUE THREAD

**Issue by rohankandwal** [OneSignal/OneSignal-Android-SDK#991]
**Description:**
In-App notification popup not appearing for release build with proguard configurations. However, push notifications appear for release builds. 

Notifications are appearing fine for debug builds.

**Environment**

Android SDK - 28
com.onesignal:OneSignal:[3.13.0, 3.99.99]
```
buildscript {
  repositories {
    maven { url 'https://plugins.gradle.org/m2/'}
  }
  dependencies {
    classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.12.6'
  }
}

apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

repositories {
  maven { url 'https://maven.google.com' }
}
```

**Steps to Reproduce Issue:**

1. Create a release APK with proguard, minification & shrinkResources enabled.
2. Install the release build on device and create a new In-App popup
3. Popup appears on debug build, but not on release build.

**Anything else:**
No special proguard settings added for InApp popups or Push notifications added.

**Comment by jkasten2** [comment]
@rohankandwal How is `proguardFiles` defined in your `app/build.gradle`? If you have custom file please share that here.

This is the default for Android Studio projects uses `proguard-android.txt` which isn't in the project but part of the Android SDK itself. These rules should be safe to use with OneSignal.
```gradle
 proguardFiles getDefaultProguardFile('proguard-android.txt')
```

Can you look for any errors or warnings in your logcat? I would suspect that there is something in there with more details on why the In-App Message did not show.

**Comment by rohankandwal** [comment]
I have a custom proguard file. 

`-optimizations !code/simplification/arithmetic,!code/simplification/cast,!field/*,!class/merging/*
-optimizationpasses 5
-allowaccessmodification
-dontpreverify

-dontusemixedcaseclassnames
-dontskipnonpubliclibraryclasses
-verbose

-keepattributes *Annotation*
-keep public class com.google.vending.licensing.ILicensingService
-keep public class com.android.vending.licensing.ILicensingService
-keepattributes SourceFile,LineNumberTable

-keepclasseswithmembernames class * {
    native <methods>;
}
-keep class androidx.appcompat.widget.** { *; }

-keepclassmembers public class * extends android.view.View {
   void set*(***);
   *** get*();
}

-keepclassmembers class * extends android.app.Activity {
   public void *(android.view.View);
}
-assumenosideeffects class android.util.Log {
    public static *** d(...);
    public static *** v(...);
}

-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}

-keep class * implements android.os.Parcelable {
  public static final android.os.Parcelable$Creator *;
}

-keep class com.google.android.gms.** { *; }
-dontwarn com.google.android.gms.**


-keep class saschpe.android.** { *; }
-dontwarn saschpe.android.**

-keepclassmembers class **.R$* {
    public static <fields>;
}
-keep class org.apache.http.** { *; }
-dontwarn org.apache.http.**
-dontnote android.net.http.*
-dontnote org.apache.commons.codec.**
-dontnote org.apache.http.**
-dontwarn android.support.**
-dontwarn com.squareup.picasso.**
-dontwarn com.squareup.okhttp.**
-dontwarn com.google.android.gms.**
-dontwarn org.xbill.DNS.spi.**
-keepclasseswithmembernames class * {
    native <methods>;
}

-keepattributes Signature

-keepattributes *Annotation*


-keep class com.google.gson.examples.android.model.** { *; }

-keep class * implements com.google.gson.TypeAdapterFactory
-keep class * implements com.google.gson.JsonSerializer
-keep class * implements com.google.gson.JsonDeserializer

 -keep class co.sosmethod.mobile.data.** { *; }
 -keep class co.sosmethod.mobile.di.** { *; }

-keep class com.google.** { *; }
-dontwarn com.google.**

-keep class com.gson.**{
*;
}
-keep class sun.misc.Unsafe {
*;
}
-keepattributes Signature
-keepattributes *Annotation*
-keepattributes InnerClasses

-keep public class android.net.http.SslError
-keep public class android.webkit.WebViewClient

-keep class org.apache.http.** { *; }

-dontwarn android.webkit.WebView
-dontwarn android.net.http.SslError
-dontwarn android.webkit.WebViewClient

-dontwarn org.apache.http.**
-dontwarn android.net.**

-keep class com.crashlytics.** { *; }
-dontwarn com.crashlytics.**
-keepattributes SourceFile,LineNumberTable,*Annotation*
-keep class com.crashlytics.android.**

 -keepattributes *Annotation*
 -keepattributes SourceFile,LineNumberTable
 -keep class com.crashlytics.** { *; }
 -dontwarn com.crashlytics.**


-keep public class * implements com.bumptech.glide.module.GlideModule
-keep public enum com.bumptech.glide.load.resource.bitmap.ImageHeaderParser$** {
  **[] $VALUES;
  public *;
}

-dontnote retrofit2.Platform
-dontwarn retrofit2.Platform$Java8
-keepattributes Signature
-keepattributes Exceptions

-keep class okio.** { *; }
-dontwarn okio.**

-keepattributes Signature
-keepattributes Annotation
-keep class okhttp3.** { *; }
-keep interface okhttp3.** { *; }
-dontwarn okhttp3.**


-keep public class * implements butterknife.Unbinder { public <init>(**, android.view.View); }

-keep class butterknife.*
-keepclasseswithmembernames class * { @butterknife.* <methods>; }
-keepclasseswithmembernames class * { @butterknife.* <fields>; }

-keep class com.google.android.gms.maps.** { *; }
-keep interface com.google.android.gms.maps.* { *; }

-dontwarn retrofit2.**
-keep class retrofit2.** { *; }
-keepattributes Signature
-keepattributes Exceptions

-keepclasseswithmembers class * {
    @retrofit2.http.* <methods>;
}

-keepattributes InnerClasses
-dontoptimize
-dontwarn InnerClasses
-keepattributes EnclosingMethod

-dontwarn com.google.errorprone.annotations.**

-keepattributes *Annotation*
-keepclassmembers class ** {
    @org.greenrobot.eventbus.Subscribe <methods>;
}
-keep enum org.greenrobot.eventbus.ThreadMode { *; }

-keepclasseswithmembernames class * {
native <methods>;
}
-keep class androidx.renderscript.** { *; }

-dontwarn com.airbnb.lottie.**
-keep class com.airbnb.lottie.** {*;}

-keep class com.appsee.** { *; }
-dontwarn com.appsee.**
-keep class android.support.** { *; }
-keep interface android.support.** { *; }
-keep class androidx.** { *; }
-keep interface androidx.** { *; }
-keepattributes SourceFile,LineNumberTable

-dontwarn io.branch.**

-keepclasseswithmembernames class * {
    native <methods>;
}

-keep class android.support.v8.renderscript.** { *; }

-dontwarn carbon.BR
-dontwarn carbon.internal**
-dontwarn java.lang.invoke**

-dontwarn android.databinding.**
-keep class android.databinding.** { *; }

-dontwarn com.sendbird.android.shadow.**

-dontwarn com.android.installreferre
-dontwarn com.appsflyer.**
-keep class com.appsflyer.** { *; }

-keep class android.support.v4.view.MenuCompat
-keep class android.support.v4.content.WakefulBroadcastReceiver
-keep class android.support.v4.app.NotificationManagerCompat
-keep class android.support.v4.app.JobIntentService
-keep class com.google.firebase.messaging.FirebaseMessaging`

**Comment by rgomezp** [comment]
Howdy,
Thanks for your patience while we investigate. If you are able to get logs somehow, we would appreciate you sharing them so we can expedite this issue.

**Comment by rohankandwal** [comment]
@rgomezp Since it is a release build, unable to get any info. Added following to proguard file and it is working for release build.

`-keep class com.onesignal.** { *; }`

**Comment by rgomezp** [comment]
Great! Let us know if you have any other questions
